cplusplus/draft

source/declarations.tex
=> [dcl.stc,dcl.type.cv] Avoid redundancy when specifying 'mutable'.

source/declarations.tex
[[namespace.def]/1](http://eel.is/c++draft/basic.namespace#namespace.def-1) states: 
> Every namespace-definition shall appear in the global scope or in a namespace scope
This is redundant, as global scope is a namespace. This could confuse readers to think that these are two separate things, when they in-fact are not. 
Proposed change is to remove "in the global scope".
=> [namespace.def]/1 Remove redundant statement

source/expressions.tex
type violations in function calls.
Fixes #2482.
=> [expr.call,expr.reinterpret.cast] Adjust cross-references for

source/strings.tex
Moved down constexpr iterator requirement with the other iterator requirements, and moved up the invalidation requirements alongside the complexity requirements as both apply as generally.
=> [string.view.template][string.view.iterators] Move requirements to a more appropriate place

source/declarations.tex, source/templates.tex
explicit specializations and explicit instantiations
to [temp.spec] and its subsections.
Fixes #2188.
=> [dcl.dcl,temp.spec] Move normative statements on restrictions for

source/declarations.tex
Require implementations to reserve storage of both proper size and aligment in an object definition. Previously, this sentence requires only storage of proper size be reserved.
Additionally, specified that space is only reserved for object definitions, as it does not make sense to reserve space for a function definition.
Rationale for being editorial: if implementations are not required to reserve storage of proper alignment, accessing any variable is then possibly-UB due to lifetime failing to begin ([basic.life]/1). This is obviously not the intent of the Committee.
=> [dcl.dcl]/11 Storage from object definitions has proper alignment

source/concepts.tex
Since lookup is only performed when at least one argument has class or enumeration type, template argument deduction can never succeed for the poisin pill overload with two parameters of reference-to-array type; it can be struck with no normative impact.
=> [concept.swappable] Strike array poison pill swap overload

source/algorithms.tex, source/atomics.tex, source/basic.tex, source/classes.tex, source/compatibility.tex, source/concepts.tex, source/containers.tex, source/declarations.tex, source/diagnostics.tex, source/expressions.tex, source/future.tex, source/iostreams.tex, source/iterators.tex, source/lex.tex, source/lib-intro.tex, source/locales.tex, source/macros.tex, source/numerics.tex, source/overloading.tex, source/preprocessor.tex, source/ranges.tex, source/regex.tex, source/strings.tex, source/styles.tex, source/support.tex, source/tables.tex, source/templates.tex, source/threads.tex, source/time.tex, source/utilities.tex
Fixes #2674.
Please squash when applying.
=> [std] Show stable labels for tables.

source/expressions.tex
Also remove the undefined term 'constant' and
instead add a note pointing to [expr.const].
Fixes #2671.
=> [expr.sizeof,expr.alignof,expr.unary.noexcept] Clarify value category.

source/basic.tex
Currently the cross references to 9.2.3.[1245] are not in numerical order, which just looks odd:
>  These methods of constructing types can be applied recursively; restrictions are mentioned in 9.2.3.1, 9.2.3.4, 9.2.3.5, and 9.2.3.2.
It seems like [9.2.3.3 [dcl.mptr]](https://wg21.link/dcl.mptr#3) also mentions a restriction:
>  A pointer to member shall not point to a static member of a class (11.3.8), a member with reference type, or “_cv_ `void`”.
Should [dcl.mptr] be added to the list of refs in [basic.compound] p2?
=> [basic.compound] Replace four refs with a single one to [dcl.meaning]

source/basic.tex, source/statements.tex
=> [stmt.stmt,basic.scope.block] Remove normative redundancy.

source/overloading.tex
Standardizes existing practice. All of GCC, Clang, MSVC, ICC in pedantic mode already behave as if all of these changes were made.
Evidence for the above: 
no method cv-qualifier: https://godbolt.org/z/C0AcCi
both method cv-qualifiers: https://godbolt.org/z/-zy4GY
const pointer: https://godbolt.org/z/EVQ781
volatile pointer: https://godbolt.org/z/tePbKG
const volatile pointer: https://godbolt.org/z/f-g1Ge
reference to const pointer: https://godbolt.org/z/uXEp-J
reference to volatile pointer: https://godbolt.org/z/l2KEs9
reference to const volatile pointer: https://godbolt.org/z/5Mhijc
Other justification for the first two (in document order) changes: it is unlikely to be Committee intent to permit surrogate calls only on conversion functions with exactly one cv-qualifier.
=> [over.call.object] Fix surrogate calls with regards to cv-qualifiers

source/ranges.tex
...to avoid confusion with the concept `Semiregular`. Update the uses in [range.single.view, range.filter.view,range.transform.view], and add a reference to [range.single.view] which now precedes [range.semi.wrap] since the "range factories" were pulled out into a separate subclause before the "range adaptors."
=> [range.semi.wrap] Rename "semiregular" to "semiregular-box"

source/statements.tex
Fixes #2781.
Partially addresses #1730.
=> [stmt.return.coroutine] Move one level up to avoid hanging paragraphs.

source/expressions.tex
=> [expr.add] Avoid x[i] syntax when defining pointer arithmetic.

source/expressions.tex
Also cover the missed case of a prvalue qualified-id.
Fixes #2919.
=> [expr.unary.op] Use bullets to clarify the address-of operator.

source/lex.tex
where it is obvious that 'basic source character set'
is meant.
Fixes #2857.
=> [lex] Fix stray uses of 'source character set'

source/ranges.tex
=> [range.split.outer] Convert trailing cross-reference to prefix style.

source/declarations.tex
Group examples with the corresponding normative statements.
Clarify the meaning of 'array type'.
Use 'declarator-id' instead of 'identifier'.
Fixes #2175.
=> [dcl.array] Rework description.

source/ranges.tex
=> [range.prim.size] Clarify by adding 'respectively'.

source/expressions.tex
=> [expr.unary.op] Modernize wording for obtaining a pointer.

source/expressions.tex
While "shall evaluate to a strictly positive value" is not wrong,
"shall be greater than zero" is easier and is used in [dcl.array] and
[dcl.init.aggr] to describe the same rule.
As a side note, I was surprized that negative bounds are not actually
banned by these "shall be greater than zero". It is now banned by a
narrowing conversion involved in a "converted constant expression of
type std::size_t" since approval of N3323(https://github.com/cplusplus/draft/commit/390dd7193de3d03e58e46d56216ff095f910f758#diff-baa06f0d56d1de4d541e8b3fca69df74).
Now these "shall be greater than zero" actually ban only zero.
But I think changing them to "shall not be zero" is not good (can be
more confusing).
=> [expr.new] Harmonize rules of constant array bounds > 0

source/algorithms.tex, source/containers.tex, source/future.tex, source/iostreams.tex, source/iterators.tex, source/lib-intro.tex, source/locales.tex, source/numerics.tex, source/regex.tex, source/strings.tex, source/support.tex, source/threads.tex, source/time.tex, source/utilities.tex
...instead of "satisfy".
Partially addresses #1263.
=> Library-wide: Use "meet" for non-concept type requirements

source/ranges.tex
Resolves #2880.
Note that I'm once again stretching "editorial" to avoid burning LWG time. The existing specification is obviously incorrect - it would result in either an ill-formed program or stack overflow - but the fix is not quite as obviously correct. As always, feel free to call this non-editorial and I'll file an LWG issue instead.
=> [range.filter.sentinel] Correct typo in constructor Effects

source/templates.tex
Update 'qualified-concept-name' (the previous incarnation of 'type-constraint') reference to 'type-constraint' in [temp.over.link]p6.
=> [Concepts] Remove qualified-concept-name reference

source/expressions.tex
=> [expr.reinterpret.cast] Properly capitalize full-sentence bullets.

source/expressions.tex
=> [expr.prim.req] Fix cross-reference for substituting into constraints.

source/basic.tex, source/classes.tex, source/declarations.tex, source/expressions.tex, source/preprocessor.tex, source/support.tex
P1510R0 Core Language Working Group "tentatively ready" Issues for the July, 2019 (Cologne) meeting
Fixes #2980.
Notes:
*CWG1839: This issue was in tentatively ready status so was added, but it is not in P1510R0, so was reverted in a Fixup.
*CWG1839: FYI - wording changed since proposal was written.
*CWG2300: Poor wording in change to 1st bullet of [basic.def.odr] p12:
We "considered" "the definition of *a* closure type" to "*consist* of the sequence of tokens of the corresponding /lambda-expression/" ??
*CWG2366: In [expr.const] p2, what is "the initialization full-expression" ??
*CWG2406: In [dcl.attr.fallthrough]p3, how can an iteration statement contain a
fallthrough statement?
=> Motions 2019 07 cwg 1

source/expressions.tex, source/future.tex
=> P1161R3 Deprecate uses of the comma operator in subscripting expressions

source/declarations.tex, source/expressions.tex, source/preprocessor.tex
[expr.const] Add missing "an" before "indeterminate value".
Fixes #2982
=> P1331R2 Permitting trivial default initialization in constexpr contexts

source/basic.tex, source/classes.tex, source/declarations.tex, source/expressions.tex, source/templates.tex
=> P0848R3 Conditionally Trivial Special Member Functions

source/basic.tex, source/classes.tex, source/declarations.tex, source/preprocessor.tex
=>  P1099R5 Using enum

source/classes.tex, source/compatibility.tex, source/overloading.tex
Definition of 'usable function' not added: it will be added by CWG
motion 6 (P1186R3) instead.
Fixes #2988
=> P1630R1 Spaceship needs a tune-up

source/basic.tex, source/modules.tex, source/preprocessor.tex
=> P1811R0 Relaxing redefinition restrictions for re-exportation robustness

source/declarations.tex, source/expressions.tex, source/overloading.tex
=> P0388R4 Permit conversions to arrays of unknown bound

source/declarations.tex
=> P1771R1 [[nodiscard]] for constructors

source/declarations.tex, source/overloading.tex, source/preprocessor.tex, source/templates.tex
- fixed one f' / f1' vs. f1' / f2' confusion in the example
Fixes #3001.
=> P1814R0 Class template argument deduction for alias template

source/classes.tex, source/compatibility.tex
- P0527R1 Implicitly move from rvalue references in return statements
- P1155R3 More implicit moves
Fixes #3002.
=> P1825R0 Merged wording for P0527R1 and P1155R3

source/algorithms.tex, source/concepts.tex, source/containers.tex, source/iostreams.tex, source/iterators.tex, source/lib-intro.tex, source/ranges.tex, source/time.tex, source/utilities.tex
P1724R0 C++ Standard Library Issues to be moved in Cologne)
Fixes #3005.
Notes:
LWG3185: Added constexpr to uninitialized_construct_using_allocator as a Fixup (since P0784 was accepted).
=> Motions 2019 07 lwg 1

source/support.tex, source/time.tex
- Also adjusted the class synopsis in [time.cal.wd.overview].
- Replaced "else" with "otherwise".
Fixes #3014.
=> P1466R3 Miscellaneous minor fixes for chrono

source/iostreams.tex
Fixes #3018.
Notes:
* Wording says:
"Add a conditional noexcept specification to swap with see below:"
but "see below" is not used in the wording for this swap member.
=> P0408R7 Efficient Access to basic_stringbuf ’s Buffer

source/compatibility.tex, source/future.tex, source/iostreams.tex, source/support.tex
- omitted rationalizing comments in synopsis
Fixes #3019.
=> P1423R3 char8_t backward compatibility remediation

source/lib-intro.tex, source/modules.tex
Fixes #3020.
Note: In [module.unit] I did not \grammarterm "identifier" in "reserved identifier" since "reserved identifier" is a term.
=> P1502R1 Standard library header units for C++20

source/support.tex, source/utilities.tex
[func.require]pa Added "requirements".
[func.bind.bind]p3 Added "of" in "invocation of".
[func.bind.bind]p11 Did not italicise "target argument" since it's not a definition or grammar term.  (Note that target argument is never defined).
Fixes #3025.
=> P1065R2 Constexpr INVOKE

source/iterators.tex
=> P1207R4 Movability of Single-pass Iterators

source/ranges.tex
Fixes #3028.
I wanted this pull request to just contain the patch against P1035R7, but that apparently failed.
=> P1638R1 basic_istream_view::iterator should not be copyable

source/containers.tex, source/support.tex
[vector.special] Could not apply the change to this section;
the section no longer exists, and its itemdecl for swap has been removed.
Fixes #3030.
=> P1004R2 Making std::vector constexpr

source/strings.tex, source/support.tex
[string.find]: Added \indexlibrarymember references to the variations of find* described via the placeholder F.
Fixes #3031.
=> P0980R1 Making std::string constexpr

source/algorithms.tex, source/basic.tex, source/lib-intro.tex, source/numerics.tex, source/support.tex, source/threads.tex
- Capitalization in subclause headings.
- Changed "determination" to "evaluated" in [thread.condvarany.interruptwait] p9.
Fixes #3032
=> P0660R10 Stop Token and Joining Thread

source/utilities.tex
Fixes #3035
- Adjusted parenthesis in is_layout_compatible requirements.
- Adjusted requirements in tables to use "shall".
- Moved punctuation outside quote marks in comments in example.
- Declared variable templates at the appropriate place in synopsis.
=> P0466R5 Layout-compatibility and Pointer-interconvertibility Traits

source/lib-intro.tex, source/support.tex
- Changed stable name to [support.srcloc].
- Added cross-references.
- Changed "description" environment showing result values to a table
Fixes #3036.
=> P1208R6 Adopt source_location for C++20

source/algorithms.tex, source/concepts.tex, source/containers.tex, source/expressions.tex, source/iterators.tex, source/lib-intro.tex, source/numerics.tex, source/ranges.tex, source/strings.tex, source/support.tex, source/threads.tex, source/time.tex, source/utilities.tex
=> P1754R1 Rename concepts to standard_case for C++20

source/strings.tex
=> [char.traits.specializations.char8.t] Align member typedefs.

source/support.tex
For consistency with the rest of the document.
=> [cmp.alg] Use regular apostrophes instead of fancy Unicode quotation marks.

source/compatibility.tex
See http://lists.isocpp.org/core/2019/08/6987.php .
=> [diff.cpp17.class] Add example where P0527R1 silently changes semantics.

source/compatibility.tex
=> [diff.cpp17.class] 'injected-class-name' is not a grammar non-terminal.

source/utilities.tex
with "temporary" in the definition of `forward_as_tuple`
=> [tuple] Use "objects" instead of "variables"

source/algorithms.tex
This was lost when changing Returns: to Effects: for P0896R4. The
paper included this change, but it was lost when applying it.
=> [is.sorted] Add missing "return" and semi-colon

source/expressions.tex
This looks like a copy-paste from previous operators (`sizeof`, `alignof`), which actually return `size_t`.
(See 8eff9b95)
=> [expr.unary.noexcept] Delete irrelevant copy-paste from previous section

source/numerics.tex
We have a bogus entry at the very start of the index of library names:
No other UDLs have such an entry in the index of library names (they just have a sub-entry under "literal" in the main index).
=> [complex.literals] Remove bogus index entry

source/basic.tex
under CWG2256, regardless of triviality of the destructor.
Fixes #2953.
=> [basic.life] Lifetime of class objects is treated uniformly

source/time.tex
Also refer to the table number instead of 'the table below'.
Fixes #2935.
=> [time.parse] Fix description of %Ex and %EX parse flags.

source/lib-intro.tex
Also add periods at the end of sentences.
Fixes #2945.
=> [res.on.functions] Properly capitalize full-sentence bullets.

source/expressions.tex
After CWG2051, a cv-decomposition can also be a no-op.
Fixes #2940.
=> [conv.qual] Fix example for cv-decomposition.

source/utilities.tex
=> [meta.trans.other] Use hyphens, not underscores, for meta-functions.

source/basic.tex, source/classes.tex, source/compatibility.tex, source/declarations.tex, source/expressions.tex, source/iterators.tex, source/modules.tex, source/overloading.tex, source/preprocessor.tex, source/ranges.tex, source/support.tex, source/threads.tex, source/utilities.tex
Mostly trivial changes made while reviewing.  No attempt is made to distinguish errors in motion application from errors in the motions (or merely nearby).
If the [expr.const]/5 changes are too much, the change to the bullets can certainly be omitted; the change before them is more important as it removes a redundancy.
=> Editing committee editing

source/atomics.tex
Fix an editorial issue that resulted from an incorrect merge.  In the
description of atomic_ref::notify_one and atomic_ref::notify_all in
[atomics.ref.operations] p25 and p27, N4830 has "Expects" in both of
those paragraphs.  But the paper that was merged in, P1643R1
( http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1643r1.html )
has "Effects".  "Effects" is correct, and it matches notify_one and
notify_all in the four other atomics-related classes.
=> Change Expects to Effects for atomic_ref::notify_{one,all}

source/utilities.tex
This is the only use of `\index` in the document.
=> [format.context] Use \indextext, not \index.

source/containers.tex
We already fixed the other specializations in #2679
=> [span.syn] Fix inconsistent class key in tuple_size/tuple_element

source/basic.tex
=> [basic.stc.dynamic.safety] Avoid undefined term 'dynamic object'.

source/classes.tex
typo fix for [[class.spaceship]/1.4](http://eel.is/c++draft/class.compare#class.spaceship-1.4)
=> [class.spaceship] equal to equivalent

source/concepts.tex
The terms "signed integral types" and "unsigned integral types" are not
defined in [basic.fundamental] The notes are trying to talk about
signed/unsigned *integer* types. `char` and `bool` are not signed or
unsigned *integer* types, but they certainly are *integral* types, and
so they model one of `signed_integral` or `unsigned_integral`.
=> [concepts.arithmetic] fix notes that use undefined terms

source/algorithms.tex, source/atomics.tex, source/basic.tex, source/classes.tex, source/containers.tex, source/declarations.tex, source/diagnostics.tex, source/exceptions.tex, source/expressions.tex, source/future.tex, source/intro.tex, source/iostreams.tex, source/iterators.tex, source/layout.tex, source/lex.tex, source/lib-intro.tex, source/locales.tex, source/macros.tex, source/numerics.tex, source/overloading.tex, source/preprocessor.tex, source/ranges.tex, source/regex.tex, source/statements.tex, source/strings.tex, source/support.tex, source/templates.tex, source/threads.tex, source/time.tex, source/utilities.tex
=> [std] Move \pnum and library element markers to a line of their own.

source/regex.tex
basic_regex::assign uses template parameters `class string_traits' and
`class A' while similar places use `class ST' and `class SA'.
=> [re.regex] assign editorial cleanup.

source/containers.tex
Misapplication in 019baa941945c1c8529fcaa0288ed5e98944f7a4.
Also restore the edit "." -> ", and".
Fixes #3257.
=> [list.ops] Fix misapplication of P1463R1, "!=" should be "==".

source/iostreams.tex, source/support.tex, source/threads.tex, source/utilities.tex, tools/check.sh
=> [lib] Remove parameter names from deleted special member functions.

source/containers.tex
"Returns: Equivalent to:" is not a library wording form, but an obvious misspelling of "Effects: Equivalent to:".
(Oddly enough, para 4 had the same error in P0122R5, but it was fixed in R6.)
=> [span.iterators] Fix typo in paragraph 5

source/numerics.tex
chi_squared_distribution's default constructor has delegating constructor with argument of integer literal `1`. But its type supposed to be the floating point types. Other distributions use floating literals in similar cases. So the suggested change.
=> change chi_squared_distribution's integer literal to floating literal

source/iterators.tex
Or add a section like `\rSec3[move.sent.ops.conv]{Conversion}` ?
=> [move.sent.ops] Add missing description of move_sentinel::base

source/basic.tex, source/classes.tex, source/declarations.tex, source/expressions.tex
=> [std] Harmonize cross-references for explicit casts.

source/expressions.tex, source/numerics.tex, source/time.tex
=> [std] Hyphenate floating-point and avoid 'floating'.

source/compatibility.tex, source/expressions.tex, source/lex.tex
=> [std] Rename 'floating literal' to 'floating-point literal'.

source/basic.tex, source/classes.tex, source/concepts.tex, source/declarations.tex, source/expressions.tex, source/iterators.tex, source/overloading.tex, source/ranges.tex, source/support.tex, source/templates.tex, source/utilities.tex
=> [std] Use consistent margins for codeblocks.

source/templates.tex
=> [temp.names] Remove misleading note.

source/compatibility.tex
[diff.char16] says `char16_t` and `char_32t` 
> ...do not appear as *macro* names...
[diff.wchar.t] says `wchar_t` 
> ...does not appear as a *type* name...
It would be nice to make these consistent if there is no reason for the difference. I thought there might not be because I saw at least one implementation in which `char16_t` and `char_32t` are `typedef`s rather than macros.
=> [diff.library] Consistency for wide char types

source/intro.tex
It seems this footnote is supposed to point at [intro.abstract] which describes how the implementation's documentations also defines implementation-defined behavior; In the same way that the footnote in [intro.abstract] points into [intro.compliance] where it says that the documentation also includes things which are listed there.
=> [intro.compliance] Fix reference in footnote

source/macros.tex, source/regex.tex
Currently, the regular expression grammar rules in [re.grammar] are formatted with crude codeblocks:
In the ECMA standard [itself](https://web.archive.org/web/20111103184035/http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-262%20edition%205.1%2C%20June%202011.pdf), rules are typeset like this:
So as an experiment, I tried mimicking that typesetting. Result:
Personally, I think it looks nicer than the crude codeblocks, and matching the upstream ECMAScript re grammar typesetting more closely is a nice bonus. What do you think? :)
(Incidentally, this also benefits cxxdraft-htmlgen, because it reduces the amount of non-C++ code in codeblocks.)
=> [re.grammar] Improve grammar typesetting.

source/basic.tex, source/templates.tex
from its original location in [temp] p3.
Fixes #3195.
=> [basic.def] Move rule on template definition here

source/threads.tex
=> [thread.latch] Subordinate [latch.syn] and [thread.latch.class]

source/declarations.tex
CWG2389 Agreement of deduced and explicitly-specified variable types
Fixes #2979.
=> [dcl.spec.auto] Add example to show variable redeclaration with 'auto'.

source/regex.tex
Fixes the consistency of several arguments in operator= and assign
and the constructor:
basic_regex from unnamed, that, e -> e
basic_string from p -> s
const charT* from ptr, p -> p
flag_type from unnamed -> f
initializer_list<charT> from unnamed -> il
These changes are in both [re.regex] and [re.regex.assign].
Moves the [re.regex.assign] LaTex reference in [re.regex] before the
operator= overloads to match the [re.regex.assign] section.
There is one more inconsistency [re.regex] declares:
basic_regex& assign(const charT* p, size_t len, flag_type f);
[re.regex.assign] declares:
basic_regex& assign(const charT* p, size_t len,
flag_type f = regex_constants::ECMAScript);
Since this is not an editorial issue I'll file an LWG issue.
=> Several editorial fixes in [re.regex].

source/basic.tex
=> [class.temporary] Fix typo in example.

source/expressions.tex
Reason for being editorial: It is probably not the committee's intent to require all programs to use "an id-expression that denotes an immediate function".
=> [expr.prim.id] Fix immediate function id-expression requirement

source/classes.tex
When I read "finds a usable function" in P1186r3, I wondered whether we should check this at lookup or viability time. However, "usable function" is really more precisely defined for the _ overall result_ of overload resolution.  I think we should just stick to that phrasing.
=> Avoid confusion between lookup and overall overload resolution

source/templates.tex
An alias declaration contains no type-id, its a defining-type-id.
=> Change type-id to defining-type-id [temp.alias] p4

source/classes.tex
Fixes #3117.
Additionally avoid duplication of name "a".
=> [class.copy.elision] Fix the contradiction introduced by CWG 2278

source/expressions.tex
Function types that can only be used for member functions
(because they have cv-qualifiers or a ref-qualifier)
cannot appear as a typeid operand.
Fixes #3260.
=> [expr.typeid] Add note highlighting prohibition of bad function types.

source/atomics.tex
for a more conventional and meaningful order.
Fixes #3172.
=> [atomics] Reorder members of atomic, atomic_ref, atomic_flag

source/expressions.tex
which is an undefined term. Instead, use 'full-expression
of the initialization'.
Fixes #3156.
=> [expr.const] Excise 'initialization full-expression'

source/atomics.tex
We use ".ops" quite a bit to mean "operations". Let's rename that before it's too late.
This section is new since C++17, thus no entry in xrefdelta is required.
=> [atomics.ref.ops] Rename stable label from .operations

source/basic.tex
=> [basic.def.odr] Replace misleading 'for which' with 'where'.

source/compatibility.tex, source/support.tex, tools/check.sh
- Avoid hanging paragraph.
- Rename label [source_location.syn] to [source.location.syn].
- Add automated check for clean labels.
- Separate header synopsis from class synopsis.
Fixes #3140.
=> [support.srcloc] Canonicalize presentation.

source/macros.tex, source/utilities.tex
Fixes #3051.
Partially addresses #3096.
=> [utilities] Index _t typedefs and _v variable templates.

source/classes.tex
when describing implicit definitions of defaulted
special member functions.  Instead, use plain 'are'.
Partially addresses #3234.
=> [class.mem] Avoid 'shall have been defined'

source/containers.tex, source/threads.tex, source/utilities.tex, tools/check.sh
Prevent future transgressions with an automated check.
=> [lib] Use macro \notdef for undefined entities.

source/overloading.tex
=> [over.match.funcs] Remove bullet for single-item bulleted list.

source/declarations.tex, source/expressions.tex, source/templates.tex
Harmonize the phrasing in [expr.prim.req.compound],
[dcl.type.auto.deduct], [temp], and [temp.param].
Fixes #2477.
=> [std] Consistently use 'immediately-declared constraint'.

source/expressions.tex
b7ac955  removed the use of this template<int> struct X, but not its declaration
=> [expr.const] drop unused declaration from integral constant expression example

source/expressions.tex
=> [basic.lval] Adjust cross-reference in the note.

source/concepts.tex, source/iterators.tex
It injects garbage into the PDF bookmarks.
=> [lib] Do not use macro \libconcept in headings.

source/classes.tex, source/declarations.tex, source/exceptions.tex, source/overloading.tex
instead of 'comparison operator function', and
define the term in [over.binary].
Fixes #3284.
=> [std] Consistently use 'comparison function'

source/algorithms.tex
Which I suspect happened during incorporation of P0896R4.
=> [set.symmetric.difference] Strike duplicated sentence from para 2

source/iterators.tex
The term defined in [basic.fundamental] is _extended integer type_.
=> [iterator.concept.winc] fix "extended integral type"

source/basic.tex
Without the introductory sentence that was deleted by that commit, we need to say explicitly that we are talking about a declaration _in a class_.
See also discussion on https://github.com/cplusplus/draft/pull/1137.
=> [basic.scope.class] Reinstate a qualification that was lost in 0e26279b88c3b8b0a09babdeec8418d383f07419.

source/classes.tex
The wording in [[class.mem]](http://eel.is/c++draft/class.mem) was changed to a note by CWG2404. It is now specified (rather than described) in [[class.mem]](http://eel.is/c++draft/expr.rel).
=> [class.access] Allocation order of data members is described in [expr.rel]

source/statements.tex
[[stmt.dcl] p3 sentence 2](http://eel.is/c++draft/stmt.dcl#3.sentence-2) says: 
> A program that jumps from a point where a variable with automatic storage duration is not in scope to a point where it is in scope is ill-formed unless the variable has vacuous initialization ([[dcl.init]](http://eel.is/c++draft/dcl.init)).
https://github.com/cplusplus/draft/commit/f3a6b2e671efdee5bacb74a5ea01d4bfb1900d3e kept the crosslink when they removed the reference to *initializer* and added vacuous initialization. Vacuous initialization is defined in [[basic.life]](http://eel.is/c++draft/basic.life).
=>  [stmt.dcl] Vacuous initialization is defined in [basic.life]

source/basic.tex
Fixes NB GB 032 (C++20 CD)
Fixes cplusplus/nbballot#31
=> [basic.lookup.argdep] Add missing namespace qualification in example.

source/expressions.tex
Fixes NB JP 045 (C++20 CD)
Fixes cplusplus/nbballot#44
=> [expr.type] Fix typo when using 'reference-related'.

source/modules.tex
Fixes NB GB 089 (C++20 CD)
Fixes cplusplus/nbballot#88.
=> [module.reach] Clearly separate translation units in example.

source/templates.tex
Non-type template parameters of non-reference non-class type are
prvalues, thus the usual reference initialization rules
create a temporary.
Fixes NB US099 (C++20 CD)
Fixes #cplusplus/nbballot#98.
=> [temp.param] Strike redundant normative sentence.

source/support.tex
Fixes NB JP 177 (C++20 CD)
Fixes cplusplus/nbballot#175-
=> [cmp.alg] Fix typo for 'ISO/IEC/IEEE 60559'.

source/time.tex
Fixes cplusplus/nbballot#337.
Fixes cplusplus/nbballot#335.
Fixes cplusplus/nbballot#336.
Do not squash; each commit addresses a separate NB comment.
=> [time.cal.month.members] Remove nested-name-specifier from declarations.

source/iostreams.tex
Fixes cplusplus/nbballot#344.
Fixes cplusplus/nbballot#345.
Fixes cplusplus/nbballot#346.
The default template arguments were shown for the declarations in &lt;iosfwd>, thus this seems to be an editorial fix.
While we can't repeat default template arguments in C++, be consistent with the existing specification practice for the other iostreams classes.
Do not squash the commits; each addresses an individual NB comment.
=> [syncstream] Add default template parameters for basic_syncbuf and basic_osyncstream

source/compatibility.tex
Fixes NB JP 373 (C++20 CD)
Fixes cplusplus/nbballot#369.
=> [diff.cpp17.lex] Add cross-references for 'requires' keyword.

source/basic.tex, source/modules.tex, source/preprocessor.tex
That is, rename [module.global] to [module.global.frag]
and [cpp.glob.frag] to [cpp.global.frag].
Fixes NB US 088 (C++20 CD)
Fixes cplusplus/nbballot#087
=> [module.global,cpp.glob.frag] Rename labels to ...global.frag.

source/expressions.tex
of the template parameter object.
Fixes NB US 047 (C++20 CD)
Fixes cplusplus/nbballot#46.
=> [expr.prim.id.unqual] Excise redundant special case for the type

source/basic.tex, source/intro.tex, source/statements.tex, source/threads.tex
Also clean up index entries to differentiate
'to block' from 'compound statement'.
Fixes NB US 021 (C++20 CD)
Fixes cplusplus/nbballot#21
=> [defns.block.stmt] Add definition of block as a compound statement.

source/compatibility.tex, source/lib-intro.tex
when defining reserved namespace names.
Fixes NB GB 078 (C++20 CD)
Fixes cplusplus/nbballot#77
=> [namespace.future,diff.cpp14.library] Properly refer to grammar 'digit'

source/classes.tex
This improves consistency with other such phrases.
Fixes late comment CH 02.
Fixes cplusplus/nbballot#376
=> [class.copy.assign] Remove semicolon in 'of the form' phrase.

source/basic.tex
That's not a big deal, but still.
=> [basic.types]/2 replace macro constant with constexpr variable

source/threads.tex
Minor issue, my parser failed to parse the jthread codeblock because the std namespace is not closed.
=> [thread.jthread.class] Namespace not closed

source/utilities.tex
...as is the typical library style.
=> [specialized.destroy] add whitespace around binary operator

source/containers.tex, source/lib-intro.tex, source/macros.tex
Also adjust a few hyphenation hints where needed.
Fixes NB GB 155 (C++20 CD)
Fixes #3387.
Fixes cplusplus/nbballot#153.
=> [macros, structure.specifications] Rename "Expects:"/"Ensures:" to "Preconditions:"/"Postconditions:"

source/expressions.tex
I can't find other uses of `\term` for single-letter variables/placeholders; most places appear to use math-mode variables instead.
=> [expr.sizeof] Replace inappropriate \term{n} with $n$.

source/declarations.tex, source/expressions.tex, source/templates.tex
=> Motions 2019 11 cwg 1: P1969R0 Core Language Working Group "ready" Issues

source/algorithms.tex, source/basic.tex, source/classes.tex, source/declarations.tex, source/expressions.tex, source/overloading.tex, source/statements.tex, source/templates.tex
Fixes #3395.
Fixes #2664.
Issues:
* CWG2419:
In [expr.add]/bullet 4.2, and, after applying CWG2419, in [numeric.ops.midpoint]/p5 and [expr.rel]/p4, we have the wording:
"a pointer to a hypothetical array element n"
This reads like n is the hypothetical array element, but n is the size of the array.
Can we reword this?
* CWG2433: FYI, wording changed after Davis Herring's change "[basic.def.odr] Clean up new bullets"
=> Motions 2019 11 cwg 2: P1968R0 Core Language Working Group "tentatively ready" Issues

source/basic.tex, source/declarations.tex, source/expressions.tex, source/intro.tex, source/modules.tex, source/overloading.tex, source/preprocessor.tex, source/statements.tex, source/templates.tex
Fixes #3396.
Fixes cplusplus/nbballot#7.
Fixes cplusplus/nbballot#41.
Fixes cplusplus/nbballot#19.
Fixes cplusplus/nbballot#20.
Fixes cplusplus/nbballot#37.
Fixes cplusplus/nbballot#43.
Fixes cplusplus/nbballot#51.
Fixes cplusplus/nbballot#52.
Fixes cplusplus/nbballot#64.
Fixes cplusplus/nbballot#78.
Fixes cplusplus/nbballot#86.
Fixes cplusplus/nbballot#110.
Fixes cplusplus/nbballot#131.
Fixes cplusplus/nbballot#363.
Fixes cplusplus/nbballot#374.
Issues:
* GB079 - fyi, Section [module.global] is now [module.global.frag]
* US111 - Comments in example use the wording "<expr> constraints" as a subject - should this be "the constraints on <expr>"?
=> Motions 2019 11 cwg 3: P1971R0 Core Language Changes for NB Comments

source/expressions.tex
Related to NB US 056 (C++20 CD)
Fixes #3398.
See also cplusplus/nbballot#55.
=> P1975R0 Fixing the wording of parenthesized aggregate-initialization

source/basic.tex
Fixes NB US 082 (C++20 CD)
Fixes #3399 
Fixes cplusplus/nbballot#81
Fixes cplusplus/papers#624
=> P1874R1 Dynamic Initialization Order of Non-Local Variables in Modules

papers/nxxxx.md, source/classes.tex, source/preprocessor.tex, source/templates.tex
Fixes #3401.
Also fixes NB US 092, US 093, US 100, US 102, US 114 (C++20 CD).
Fixes cplusplus/nbballot#91
Fixes cplusplus/nbballot#92
Fixes cplusplus/nbballot#99
Fixes cplusplus/nbballot#101
Fixes cplusplus/nbballot#113
Fixes cplusplus/papers#653
=>  P1907R1 Inconsistencies with non-type template parameters

source/expressions.tex, source/overloading.tex, source/templates.tex
Also fixes NB CA 096, US 095
Fixes #3403 
Fixes cplusplus/nbballot#95
Fixes cplusplus/nbballot#94
=> P1980R0 CA096: Declaration matching for non-dependent requires-clauses

source/algorithms.tex, source/concepts.tex, source/containers.tex, source/iostreams.tex, source/iterators.tex, source/ranges.tex, source/support.tex, source/time.tex, source/utilities.tex
Fixes #3404.
Issues:
* From LWG3149:
** "immediate context" is used but never defined. It is used in reference to variables, expressions, and stand-alone as ``immediate context'', yet there is only a definition for "immediate function context".
** What is an unrelated context? E.g. LWG3149 adds this in [concept.defaultconstructible]:
"Access checking is performed as if in a context unrelated to \tcode{T}."
* LWG3272 adds this wording to [time.parse]/p1:
"In the following paragraphs, let is denote an object of type basic_istream<charT, traits>, where charT and traits are template parameters in that context.".
What context?
Fixes cplusplus/nbballot#164
Fixes cplusplus/nbballot#257
Fixes cplusplus/nbballot#293
=> Motions 2019 11 lwg 1: P1917R0 C++ Standard Library Issues to be moved in Belfast

source/lib-intro.tex
Fixes #3405.
Also fixes NB RU 009, FI 010, US 158, US 159, GB 160, and
PL 161 (C++20 CD).
Fixes cplusplus/nbballot#9
Fixes cplusplus/nbballot#10
Fixes cplusplus/nbballot#156
Fixes cplusplus/nbballot#157
Fixes cplusplus/nbballot#158
Fixes cplusplus/nbballot#159
Fixes cplusplus/papers#609
=> P1855R0 Make <compare> freestanding

source/containers.tex, source/macros.tex
Fixes #3406.
Also fixes NB US 235, US 236, PL 237, and US 238 (C++20 CD).
Fixes cplusplus/nbballot#232
Fixes cplusplus/nbballot#233
Fixes cplusplus/nbballot#234
Fixes cplusplus/papers#467
=> P1690R1 Refinement Proposal for P0919 Heterogeneous lookup for unordered containers

source/containers.tex
Fixes #3407.
Fixes cplusplus/nbballot#236.
Fixes cplusplus/nbballot#241.
Fixes cplusplus/nbballot#244.
Fixes cplusplus/papers#622
Also fixes NB FR 240, US 245, and PL 248 (C++20 CD).
=> P1872R0 span should have size_type, not index_type

source/lib-intro.tex
Also fixes NB DE 165 and LWG3239
Fixes #3408
Fixes cplusplus/nbballot#163
Relates to #3110
=> P1965R0 Blanket Wording for Specifying "Hidden Friends"

source/lib-intro.tex, source/support.tex, source/utilities.tex
Also fixes NB US 176, US 220 (C++20 CD)
Fixes #3411
Fixes cplusplus/nbballot#174
Fixes cplusplus/nbballot#217
=> P1961R0 Harmonizing the definitions of total order for pointers

source/algorithms.tex, source/iterators.tex
Instructions to change section names were ignored; the shorter section
names are preferable, and the inclusion of 'iterator.' seems sufficient
to indicate that we're talking about indirect reading and writing.
Fixes #3412.
Fixes cplusplus/nbballot#259.
Fixes cplusplus/nbballot#260.
Fixes cplusplus/nbballot#264.
Fixes cplusplus/papers#628
Also fixes NB US 263, US 264, US 268 (C++20 CD), and LWG3279.
=> P1878R1 Constraining Readable Types

source/iterators.tex
Fixes #3413.
Fixes cplusplus/nbballot#253.
Fixes cplusplus/papers#621
Also fixes NB US 257 (C++20 CD).
=> P1871R1 Concept traits should be named after concepts

papers/nxxxx.md, source/ranges.tex
Fixes #3414.
Fixes cplusplus/nbballot#273
Partially addresses cplusplus/nbballot#249
Partially addresses cplusplus/nbballot#266
Fixes cplusplus/nbballot#277
=> P1456R1 Move-only views

source/strings.tex
Renamed constructor parameters in description to match those in class
definition.
Fixes #3415.
Fixes cplusplus/nbballot#229
Partially addresses cplusplus/nbballot#268
Partially addresses cplusplus/nbballot#284
Fixes cplusplus/papers#184
=> P1391R4 Range constructor for std::string_view

source/containers.tex
P1394R4 Range constructor for std::span
Converted run-on sentences in bulleted lists to
one sentence per bullet.
Fixes NB US 233, US 246, PL 251 (C++20 CD).
Fixes #3416.
Fixes cplusplus/nbballot#230
Fixes cplusplus/nbballot#242
Fixes cplusplus/nbballot#247
Partially addresses cplusplus/nbballot#268
Partially addresses cplusplus/nbballot#284
=> P1394R4 Range constructor for std::span

papers/nxxxx.md, source/containers.tex, source/ranges.tex, source/strings.tex
Fixes #3418. 
Issues with paper:
* [range.access.begin]/p1 adds "Given a subexpression E and an lvalue t that denotes the same object as E", but E is a subexpression, not an object.
Same for [range.access.end]/p1, [range.access.rbegin]/p1, and [range.access.rend]/p1.
* [range.range] range-impl is removed but is still referenced in p2 and p3.
Other editorial issues:
* cv-unqualified or \cv-unqualified?
The spec is inconsistent in its representation of cv-unqualified v. /cv/-unqualified.
* When to use \deflibconcept?
Some concept definitions in the library use \deflibconcept, others don't.
Also fix inconsistencies in the of \defexposconcept for \expos concepts.    
* The library is inconsistent in its use of \exposconcept v. \tcode{\placeholder
Fixes cplusplus/papers#620
Fixes …
=> Motions 2019 11 lwg 16: P1870R1 forwarding-range<T> is too subtle

source/threads.tex
NB US 365 (C++20 CD):
P1865R1 Add max() to latch and barrier
Fixes #3419.
Fixes cplusplus/papers#617
Fixes cplusplus/nbballot#361
=> LWG Motion 17: P1865R1 Add max() to latch and barrier

source/atomics.tex, source/future.tex, source/support.tex
Fixes #3422.
Issues:
* [depr.atomics] Check my use of sections - it wasn't clear to me which and when to repeat sections prefixed with "depr.".  Please check my use of sections.
Fixes cplusplus/papers#276
Fixes cplusplus/nbballot#6
Fixes cplusplus/nbballot#18
Fixes cplusplus/nbballot#347
Fixes cplusplus/nbballot#349
=> Motions 2019 11 lwg 20: P0883R2 Fixing Atomic Initialization

source/basic.tex, source/classes.tex, source/expressions.tex, source/iterators.tex, source/overloading.tex, source/support.tex
Fixes #3423.
Fixes cplusplus/nbballot#168.
Fixes cplusplus/nbballot#171.
Issues:
* wrt my editorial commit "[temp.param] Reword types in bulleted list for consistency", the spec is inconsistent wrt "function pointer" v. "function pointer type" - which should be used?
=> P1959R0 Remove std::weak_equality and std::strong_equality

source/utilities.tex
Fixes #3424.
Fixes cplusplus/nbballot#223
Fixes cplusplus/papers#641
=> P1892R1 Extended locale-specific presentation specifiers for std::format

source/locales.tex
Fixes #3429.
Fixes cplusplus/papers#486.
=> P1720R2 Mandating the Standard Library: Clause 28 - Localization library

source/numerics.tex
Leftover \pnum after remarks were removed in https://github.com/cplusplus/draft/commit/3ae74f0c84e0196734600f5ec581a2fb72ea390a
=> [complex.ops] Remove empty paragraph.

source/templates.tex
[[temp.local] p6](http://eel.is/c++draft/temp#local-6.sentence-1) says:
> A *template-parameter* shall not be redeclared within its scope (including nested scopes).
Using the provided example:
```
template<class T, int i> class Y {
int T;                                // error: template-parameter redeclared
[...]
};
```
The template-parameter here is not being redeclared (thats a declaration of a member), its name is. Declarations by definition introduce names.
=> [temp.local] Change "template-parameter" to "name of a template parameter"

source/future.tex, source/iostreams.tex, source/numerics.tex, source/utilities.tex
for constructors; this effect is implied by the
core language.  Only simple phrases are removed;
more complex sentence structures are left unchanged.
Partially addresses #3506.
=> [lib] Remove 'Constructs an object of type ...' phrases

source/declarations.tex
The phrase 'the function-body encloses X' is also used
in [dcl.constexpr].
Fixes #3376
=> [dcl.fct.def.coroutine] Use 'encloses' instead of imprecise 'contains'.

source/utilities.tex
[lib.types.movedfrom] already specifies that moved-from
objects are left in a valid but unspecified state.
Fixes #3362
=> [any.cons,any.assign] Remove redundant postcondition for moves.

source/templates.tex
Deduction guides apply only to class templates, so their
descriptions should be located in close proximity.
Fixes #3498.
=> [temp.deduct.guide] Move into [temp.class].

source/templates.tex
Also move concept-name here, both from [temp.pre].
Fixes #3378
=> [temp.concept] Move grammar non-terminal concept-definition here.

source/future.tex, source/utilities.tex
We left the index entry for `rel_ops` behind when P0768 moved the specification into Annex D.
=> [depr.relops] Move index entry here from [utility.syn]

source/expressions.tex, source/intro.tex
Add cross-linking between the places that introduce accesses and the
definition of the term, and add a note explaining that we only ever
access objects of scalar type.
=> [defns.access] Clarify definition of "access".

source/utilities.tex
=> [format.arg] Fix parameter type for basic_format_arg constructor.

source/basic.tex
Periods of construction and destruction are not referred to as phases anywhere else.
=> [basic.life] Use idiomatic wording.

source/iostreams.tex, source/numerics.tex
Do not refer to the inherited member in a derived class.
Fixes #3306.
=> [numerics,input.output] Consistently use ios_base::failure.

source/time.tex, source/utilities.tex
In these places we aren't saying "it's UB if it throws"; we're literally specifying the behavior of a library function as "it does not throw, we promise."
=> Replace "shall not throw" with "does not throw" when it describes library behavior

source/time.tex
The subclause describes functions beyond
duration_cast and time_point_cast.
Fixes #3298.
=> [time.duration.cast,time.point.cast] Rename subclause to 'Conversions'.

source/lex.tex
=> Lex.charset fixes

source/classes.tex, source/declarations.tex, source/macros.tex, source/regex.tex, source/std.tex
=> [std] Switch grammar to  \sffamily \itshape

source/ranges.tex
P1035 used `R` for such template parameters, introducing inconsistency. We could either restore consistency this way, or rename the `V`s to `R` once the converting constuctors of the other adaptors are removed, as I understand will happen.
=> [ranges.syn, range.adaptors] Name view template parameter V for consistency

source/declarations.tex, source/expressions.tex, source/templates.tex
from [temp.pre].
Also move the definition of 'immediately-declared
constraint' and fix all cross-references.
Fixes #3516
=> [temp.param] Move grammar non-terminal 'type-constraint' here

source/support.tex
of the source_location constructors and copy assignment
operators.
Fixes #3170.
=> [support.srcloc.class] Highlight unspecified properties

source/iterators.tex
The exposition-only concept _`indirectly-readable-impl`_ relies on
`ranges::iter_move`, but the text was missing the `ranges::` qualifier.
This commit adds it, as the intention is to use `ranges::iter_move`, not
`std::iter_move`.
cc @jwakely @CaseyCarter @ericniebler @timsong-cpp
=> qualifies indirectly-readable-impl's use of iter_move

source/classes.tex
=> [class.derived,class.member.lookup] Reference figures in running text.

source/time.tex
Today, the synopsis contains the following:
```
// [time.traits], customization traits
template<class Rep> struct treat_as_floating_point;
template<class Rep> struct duration_values;
template<class Rep>
inline constexpr bool treat_as_floating_point_v = treat_as_floating_point<Rep>::value;
template<class T> struct is_clock;
template<class T> inline constexpr bool is_clock_v = is_clock<T>::value;
```
The variable template for `is_clock` (`is_clock_v`) is right after `is_clock`, but for some reason `duration_values` is currently in between `treat_as_floating_point` and `treat_as_floating_point_v`. This editorial change just moves `treat_as_floating_point_v` to be directly after `treat_as_floating_point`.
=> [time.syn] Move `treat_as_floating_point_v` to be right after `treat_as_floating_point` in the `<chrono>` synopsis.

source/basic.tex, source/expressions.tex, source/lex.tex, source/preprocessor.tex, source/threads.tex, source/utilities.tex
Fixes #2110.
No visible difference (apart from a different page number for `__TIME__` in the index).
=> [std] Harmonize index entries for list items

source/containers.tex, source/diagnostics.tex, source/iostreams.tex, source/iterators.tex, source/lib-intro.tex, source/support.tex, source/utilities.tex, tools/check.sh
This was missed earlier due to a typo in the check script,
which is also fixed.
=> [lib] Put \constraints on a line of its own.

source/algorithms.tex, source/lib-intro.tex, tools/check.sh
Also extend the check script to flag missing \pnum in
library descriptions.
Limit the checking to library clauses other than [library].
=> [alg.partitions] Add missing \pnum.

source/overloading.tex
Per the normative wording, excluded functions are not candidates; don't suggest they are candidates by describing them as not being viable.
=> [over.match.funcs] Correct comment in example.

source/atomics.tex, source/basic.tex
=> [basic.atomics] Use math mode for memory model placeholders.

source/iostreams.tex, source/numerics.tex, source/strings.tex
=> [lib] Consistently use ios_base::failbit and ios_base::badbit.

source/ranges.tex, tools/check.sh
Also augment the check script accordingly.
Indented codeblock markers cause undesirable empty vertical space.
Fixes #3568.
=> [ranges] Do not indent \begin/end{codeblock}.

source/locales.tex
=> [locale.codecvt] Do not claim that 'Unicode' is a character encoding.

source/utilities.tex
=> [format.arg] Move 'otherwise' to the start of the bullets.

source/threads.tex
=> [thread.lock.unique.locking] Fix typo in try_lock_for.

source/overloading.tex
=> [over.built] Avoid confusing term 'promoted arithmetic type'.

source/iostreams.tex
=> [stringbuf] Use phrases from [bitmask.types].

source/expressions.tex
=> [expr.call] Clarify result of function call vs. return operand.

source/support.tex
The applicable rules have changed in response to
NB RU 007, US 042 (C++20 CD).
Fixes #3613.
=> [ptr.launder] Fix note and example for std::launder.

source/expressions.tex
as defined in [intro.execution] as an abbreviation
for value computations and side effects.
Fixes #3380.
=> [expr.compound] Use sequencing on expressions

source/templates.tex
=> [temp.type,temp.over.link] Define and use 'same template-id'.

source/threads.tex
P1869R1 Rename condition_variable_any interruptible wait methods
reordered the parameters of the wait_until function, but
neglected to adjust the 'Equivalent to' code for wait_for.
Fixes #3550.
=> [thread.condvarany.intwait] Fix invocation of wait_until.

source/classes.tex
=> [class.static.data] Cleanup description for local/unnamed classes.

source/classes.tex
=> [class.this] Member functions are not cv-qualified. 

source/intro.tex
...after application of P1971R0.
=> [defns.signature] functions never have trailing requires-clauses

source/basic.tex, source/classes.tex, source/compatibility.tex, source/declarations.tex, source/exceptions.tex, source/expressions.tex, source/future.tex, source/modules.tex, source/overloading.tex, source/preprocessor.tex, source/statements.tex, source/templates.tex, source/utilities.tex
=> [std] Harmonize comments indicating errors.

source/preprocessor.tex
where they fit more naturally, omitting some of the
now-redundant introductory phrases.
Fixes #3544
=> [cpp.replace] Distribute examples from [cpp.scope]

source/templates.tex
*Specialization* is the second most common term that is defined and used in [temp]. The definition in [temp.spec] p4 should be italicized to make it a proper definition. Also, the phrase " function, or class member that is [...] explicitly specialized" is incorrect: templates are explicitly specialized, not classes, functions etc (in some cases non-templates too, but rarely).
Additionally, a *specialization* of a alias template (such as the use here: http://eel.is/c++draft/temp.alias#2) is meaningless for non-class types. Consider the following:
```
template<typename T>
using A = int;
```
A specialization is a class, function, variable, or class member. The type denoted (if you could even say that, since its replaced) by the simple-template-id `A<void>` is none of these.
=> [temp.spec] Make "specialization" a proper definition & adjust definition.

source/basic.tex
=> [basic.scope.pdecl] Fix example of self-referential initialization.

source/basic.tex, source/templates.tex, tools/check.sh
Also fix existing offenders.
Induced by #3574.
=> [std] Enforce comment alignment in 'codeblocktu' environments.

source/declarations.tex, source/expressions.tex
involving non-static member functions.
Fixes #3607.
=> [dcl.fct,expr.ref] Fix description of class member access expressions

source/basic.tex, source/declarations.tex, source/expressions.tex, source/overloading.tex, source/templates.tex
Define the term in [basic.lookup] and use it throughout.
Avoid the term 'set of overloaded functions', because it
is ambiguous with the declaration view in [over.load].
(An overload set might contain functions from different
scopes that cannot be overloaded per [over.load].)
Fixes #3297.
=> [std] Consistently use 'overload set'.

source/concepts.tex, source/iterators.tex, source/ranges.tex, source/support.tex
Affects: [cmp.alg], [concept.convertibleto], [concept.swappable], [concept.boolean], [concept.equalitycomparable], [concept.stricttotallyordered], [iterator.cust.move], [iterator.cust.swap], and many subclauses of [ranges]
Fixes #3136.
=> Library-wide: don't use "for some" to mean "for an arbitrary"

source/ranges.tex
...per the direction of #3300. This PR consists of three commits:
* A commit that renames _`make-unsigned-like`_ to _`to-unsigned-like`_
* A commit that changes _`make-unsigned-like-t`_  from an exposition-only macro (invoked with parentheses) into an exposition-only alias template ("invoked" with angle brackets)
* A commit that corrects "For an object `x` of type `X`, `to-unsigned-like(x)` is..." to "For an expression `x`".
I believe the change from `()` to `<>` in the second commit makes the occurrences of _`make-unsigned-like-t`_ read better in the text - as well as increasing the intentional similarity with `make_unsigned_t<meow>` - but this change doesn't appear to have been discussed in the editorial meeting.
=> Cleanup make-unsigned-like

source/templates.tex
I noticed this example had a syntax error.
=> [temp.constr.normal] Extraneous parentheses on concept use

source/classes.tex
Seems to be a missing \tcode there. Also, the "(possibly cv-qualified)" preceding `void` should be changed to _cv_ for consistency.
=> [class.conv.fct] Add \tcode to void

source/templates.tex
We're substituting V& for U in the mapping $\tcode{T} \mapsto \tcode{U*}$, meaning T attempts to map to V&* (not T&*, which is a confusing notation in a context where T is another thing).
=> [temp.constr.normal] Confusing identifier used in explanation

source/ranges.tex
The description of basic_istream_view::iterator::operator*() refers to a
nonexistent data member value_ of basic_istream_view instead of the data
member object_.
=> [range.istream.iterator] Fix typo

source/ranges.tex
In [range.join.sentinel], we were referring to the nonexistent data member `parent_` instead of `parent`.
In [range.split.view], there was an invalid `const` qualifier in the signature for `split_view::inner-iterator::operator++()`.
=> [range.join.sentinel], [range.split.view] fix typos

source/basic.tex
The rules about integer range limits imply (in a roundabout fashion)
that increasing rank implies increasing width, so this is a
clarification that makes this implication explicit.
=> [conv.rank] Change "size" to "width" in conversion rank relation

source/diagnostics.tex, source/support.tex, source/utilities.tex
Moves the definition and specification of class compare_three_way from
[cmp, 17.11] to [comparisons, 20.14.7].
This is a partial response to NB GB 175 (C++20 CD).
Fixes cplusplus/nbballot#173.
=> [cmp, comparisons] Move description of compare_three_way.

.travis.yml, README.rst, source/Makefile, tools/check.sh
Remove all build methods other than `latexmk`. Make checking for out-of-date `.pdf` figures actually work and move it to `check.sh`. Simplify Travis CI to only run the single remaining sensible build configuration.
=> Simplify build process for the standard draft

source/basic.tex, source/declarations.tex, source/intro.tex, source/lex.tex, source/modules.tex, source/templates.tex
Fixes NB US028, US033, US041, CA104, CA107, US115, and US117 (C++20 CD).
Fixes #3685.
Also fixes cplusplus/nbballot#27.
Also fixes cplusplus/nbballot#32.
Also fixes cplusplus/nbballot#40.
Also fixes cplusplus/nbballot#103.
Also fixes cplusplus/nbballot#106.
Also fixes cplusplus/nbballot#114.
Also fixes cplusplus/nbballot#116.
=> CWG Poll 1: P2103R0 (Core Language Changes for NB Comments at the February, 2020 (Prague) meeting

source/classes.tex, source/declarations.tex
Also fixes NB US 090 (C++20 CD).
Fixes #3686.
Fixes cplusplus/papers#530.
Fixes cplusplus/nbballot#89.
=> CWG Poll 2: P1779R3 ABI isolation for member functions

source/basic.tex, source/compatibility.tex, source/lex.tex, source/modules.tex, source/preprocessor.tex
Fixes #3687.
Fixes cplusplus/papers#611.
Fixes cplusplus/nbballot#25.
Fixes cplusplus/nbballot#120.
Fixes cplusplus/nbballot#124.
Fixes cplusplus/nbballot#125.
Fixes cplusplus/nbballot#126.
Fixes cplusplus/nbballot#127.
Fixes cplusplus/nbballot#135.
Fixes cplusplus/nbballot#136.
Fixes cplusplus/nbballot#137.
Fixes cplusplus/nbballot#138.
Fixes cplusplus/nbballot#139.
Notes/issues/questions:
* [lex.pptoken]/p4 Note says: "None have any observable spelling." What is this saying?
* [diff.cpp17.basic] "The editor should consider a different section of annex C to move this to." Where to?
* [basic.link] FYI, the grammar for private-module-fragment moved to [module.private.frag].
* FYI, section [cpp.global.frag] is now [cpp.glob.frag].
* FYI, section [module.global] is now  [module.global.frag].
=> CWG Poll 3: P1857R3 Modules Dependency Discovery

source/compatibility.tex, source/declarations.tex, source/utilities.tex
Also fixes NB US 212 (C++20 CD) and LWG3228.
Fixes #3689.
Fixes cplusplus/nbballot#209.
Fixes cplusplus/papers#692.
=> CWG Poll 5: P1957R2 Converting from T* to bool should be considered narrowing

source/declarations.tex, source/expressions.tex
Also fixes NB US 064 (C++20 CD) and CWG2436.
Fixes #3691.
Fixes cplusplus/nbballot#63
=> CWG Poll 7: P2107R0 Core Issue 2436: US064 Copy semantics of coroutine parameters

source/basic.tex, source/declarations.tex, source/expressions.tex, source/future.tex, source/modules.tex, source/templates.tex
Also fixes NB US 035, US 133, and US 134 (C++20 CD).
Fixes #3698.
Fixes cplusplus/papers#586.
Fixes cplusplus/nbballot#34.
Fixes cplusplus/nbballot#132.
Fixes cplusplus/nbballot#133.
=> CWG Poll 14: P1815R2 Translation-unit-local entities

source/classes.tex, source/declarations.tex, source/exceptions.tex, source/expressions.tex, source/modules.tex, source/overloading.tex, source/support.tex
[class.compare.default] Added "was" to "no overload resolution performed".
Fixes #3700. 
Fixes cplusplus/papers#739.
Notes/Issues:
* [everywhere] Please check my \defns and \indextexts - I wasn't sure how I should specify them.
* [class.compare.default] We just say "operator@" not "operator@ function".  We're also inconsistent in whether we encode is as "operator \tcode{@}" v. "\tcode{operator@}".
* [class.compare.default] We usually say "defaulted comparison operator function" instead of "defaulted comparison function".
* [class.compare.default] In the last 2 bullets of the new paragraph after p2, the "for" at the end of each bullet is hard to parse correctly: "
** for an operator<=> whose return type is auto or for an operator==, for a comparison between an element of the expanded list …
=> CWG Poll 16: P2002R1 Defaulted comparison specification cleanups

source/classes.tex
Fixes #3701.
**Based on motions-2020-02-cwg-16** in order to resolve conflicts which would otherwise arise when trying to merge.
=> CWG Poll 17: P2085R0 Consistent defaulted comparisons

source/declarations.tex
Fixes #3702.
Fixes cplusplus/papers#654.
=> CWG Poll 18: P1908R1 Reserving attribute namespaces for future use

source/algorithms.tex, source/back.tex, source/concepts.tex, source/containers.tex, source/diagnostics.tex, source/intro.tex, source/iostreams.tex, source/iterators.tex, source/lib-intro.tex, source/ranges.tex, source/regex.tex, source/strings.tex, source/support.tex, source/threads.tex, source/time.tex, source/utilities.tex
Fixes #3704.
Notes/issues:
* LWG3281 not applied; text was removed by LWG3282
Fixes cplusplus/papers#781.
Fixes cplusplus/nbballot#298.
Fixes cplusplus/nbballot#258.
Fixes cplusplus/nbballot#154.
Fixes cplusplus/nbballot#300.
Fixes cplusplus/nbballot#283.
Fixes cplusplus/nbballot#282.
Fixes cplusplus/nbballot#214.
Fixes cplusplus/nbballot#215.
Fixes cplusplus/nbballot#216.
Fixes cplusplus/nbballot#290.
Fixes cplusplus/nbballot#160.
Fixes cplusplus/nbballot#161.
Fixes cplusplus/nbballot#329.
Fixes cplusplus/nbballot#330.
Fixes cplusplus/nbballot#331.
Fixes cplusplus/nbballot#340.
Fixes cplusplus/nbballot#243.
Fixes cplusplus/nbballot#210.
Fixes cplusplus/nbballot#295.
Fixes cplusplus/nbballot#176.
Fixes cplusplus/nbballot#299.
Fixes cplusplus/nbballot#278.
Fixes cplusplus/nbballot#222. …
=> LWG Poll 2: P2051R0 C++ Standard Library Issues to be moved in Prague

source/algorithms.tex, source/concepts.tex, source/containers.tex, source/future.tex, source/iostreams.tex, source/iterators.tex, source/lib-intro.tex, source/numerics.tex, source/preprocessor.tex, source/ranges.tex, source/strings.tex, source/support.tex, source/threads.tex, source/time.tex, source/utilities.tex
Notes/issues:
* This was **based on branch motions-2020-02-lwg-2** in order to resolve conflicts which would otherwise arise.
* LWG3247 not applied; conflicts with wording in LWG3299 (contacted lwgchair)
* LWG3269 [time.parse]/p3 Fixed wording in list of constraints by adding "has" before "value is".
* LWG3334 What about function declarations which are still in synopsis [syncstream.osyncstream.overview]?
* LWG1203 I don't see that the modified operators were ever declared in class basic_istream - why is that?  Note also that the referenced text was modified by other issues.
* LWG3314 Wording in [time.duration.io] conflicts with that of LWG3317; applied anyway.
** Edit issue: \impldef may need work; Latex can't handle my attempts at:
```
\impldef{whether \tcode{\placeholder{units_suffix}} …
```
=> LWG Poll 3: P2117R0 C++ Standard Library Issues Resolved Directly In Prague

source/ranges.tex
Also fixes NB GB 301, US 296, US 292, US 291, US 283 (C++20 CD), and LWG3278.
Fixes #3709.
Fixes cplusplus/papers#713.
Fixes cplusplus/nbballot#297.
Fixes cplusplus/nbballot#292.
Fixes cplusplus/nbballot#288.
Fixes cplusplus/nbballot#287.
Fixes cplusplus/nbballot#279.
=> LWG Poll 7: P1983R0 Wording for GB301, US296, US292, US291, and US283

source/time.tex
Also fixes NB DE 345 (C++20 CD).
Fixes #3710.
Fixes cplusplus/papers#711.
Fixes cplusplus/nbballot#341.
=> LWG Poll 8: P1981R0 Rename leap to leap_second

source/lib-intro.tex
Also fixes NB US 298, US 300 (C++20 CD) and LWG3345.
Fixes #3712.
Fixes cplusplus/nbballot#294.
Fixes cplusplus/nbballot#296.
=> LWG Poll 10: P2101R0 'Models' subsumes 'satisfies' (Wording for US298 and US300)

source/ranges.tex
Also fixes LWG3386.
Fixes #3715.
Fixes cplusplus/papers#717.
Notes/Issues:
* [range.elements.sentinel] Should \exposid{Base} be \exposid{base-t} as it is in [range.elements.iterator]?  We're inconsistent wrt Base v. base-t elsewhere as well.  There are also other differences between sentinel and iterator, like "other" and "base() const" (no ref) - I assume these are intentional?
=> LWG Poll 13: P1994R1 elements_view needs its own sentinel

source/intro.tex, source/utilities.tex
Fixes #3716.
Fixes cplusplus/papers#618.
Fixes cplusplus/nbballot#225.
=> LWG Poll 14: P1868R2 🦄 width: clarifying units of width and precision in std::format

source/numerics.tex, source/support.tex
Also fixes NB PL 326, US 327, GB 332, US 328, and GB 331 (C++20 CD).
Fixes #3717. 
Fixes cplusplus/papers#733.
Fixes cplusplus/nbballot#322.
Fixes cplusplus/nbballot#323.
Fixes cplusplus/nbballot#328.
Fixes cplusplus/nbballot#324.
Fixes cplusplus/nbballot#327.
=> LWG Poll 15: P1956R1 On the names of low-level bit manipulation functions

source/containers.tex, source/support.tex
Also fixes NB PL 250  (C++20 CD).
[span.sub] p3 and p6: Add explicit return types to account for
constructor being explicit now.
[span.objectrep] p1 and p3: Move extent of return type into a remark.
Add explicit return type to account for explicit constructor.
Fixes #3718
Fixes cplusplus/papers#707
Fixes cplusplus/nbballot#246
=> LWG Poll 16: P1976R2 Fixed-size span construction from dynamic range

source/algorithms.tex, source/concepts.tex, source/lib-intro.tex, source/macros.tex, source/support.tex
Also fixes NB US 198, US 195, US 196 and GB 197 (C++20 CD).
Fixes #3719. 
Fixes cplusplus/papers#698.
Fixes cplusplus/nbballot#196.
Fixes cplusplus/nbballot#193.
Fixes cplusplus/nbballot#194.
Fixes cplusplus/nbballot#195.
Notes/Issues:
* [concept.booleantestable]/p1 What are "conventional semantics"?
=> LWG Poll 17: P1964R2 Wording for boolean-testable

source/support.tex, source/utilities.tex
Also fixes NB DE 208 (C++20 CD).
Fixes #3721. 
Fixes cplusplus/papers#259.
Fixes cplusplus/nbballot#206.
=> LWG Poll 19: P0586R2 Safe integral comparisons

source/atomics.tex, source/future.tex, source/utilities.tex
Also fixes NB CZ 004, CA 210, and US 211 (C++20 CD).
- atomic_init was already deprecated, with and without volatile
Fixes #3722 .
Fixes cplusplus/papers#589.
Fixes cplusplus/nbballot#4
Fixes cplusplus/nbballot#208.
=> LWG Poll 20: P1831R1 Deprecating volatile: library

source/algorithms.tex, source/concepts.tex
Also fixes NB FR 305, US 318, and US 307 (C++20 CD).
Fixes #3724. 
Fixes cplusplus/papers#152
Fixes cplusplus/nbballot#301.
Fixes cplusplus/nbballot#314.
Fixes cplusplus/nbballot#303.
Notes:
* [alg.foreach] FYI: the referenced "Remarks:" is paragraph p27 (after the 2nd `for_each_n` declaration).
=> LWG Poll 22: P1243R4 Rangify New Algorithms

source/ranges.tex
Since backslashes are so rare in normal typography, I could just check all of them in the N4849 PDF.
Nothing to do with Said Özcan.
=> Add missing @s

source/basic.tex, source/classes.tex, source/compatibility.tex, source/declarations.tex, source/exceptions.tex, source/expressions.tex, source/iostreams.tex, source/lib-intro.tex, source/support.tex
"Automatic object" is not a term defined by the standard. Replacing all mentions of it with "object with automatic storage duration" resolves the issue.
=> Strike mentions of undefined term "automatic object"

source/templates.tex
The [resolution for CA378](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1971r0.html) used the term "templated function", but it is unclear what exactly this means (the intent is known, so I believe this is sufficiently editorial). This should be changed to "templated entity that is a function or function template" as is used in [[dcl.dcl]](http://eel.is/c++draft/dcl.dcl#dcl.spec.auto-12).
I didn't change the comment in the example to use this wording since it seems to be a little "extra" for a comment, but that can be changed too if deemed sufficiently important.
=> [dcl.decl] Change "templated function" to instead use "templated entity"

source/basic.tex, source/declarations.tex, source/exceptions.tex, source/expressions.tex
=> [std] Use $E$ as expression placeholder.

source/expressions.tex
[[expr.comma] p1 sentence 5](http://eel.is/c++draft/expr.comma#1.sentence-5) says:
> If the right operand is a temporary expression, the result is a temporary expression.
This is incorrect as no such grammar term exists, and if interpreted as meaning "xvalue", redundant.
=> [expr.comma] Remove "temporary expression"

source/exceptions.tex
=> [except.spec] Avoid reference to undeclared identifier in example.

source/basic.tex
=> [basic.fundamental] Clarify that in C, padding bits may cause traps.

source/expressions.tex
[expr.prim.req] uses grammarterm <em><code>requirement</code></em> in paragraph 5, but normal font in paragraph 6. Term "requirement" is never defined in this clause, but it has a different meaning in the library.
=> Use "requirement" in grammar font in expr.prim.req

source/declarations.tex
The definition of value-initialize in [dcl.init]/8 always causes me trouble because I have to recheck that the first two subbullets exhaustively cover all class types. I think with sub-bullets this becomes both more explicit and less wordy (since we don't have to repeat the condition of the first bullet).
=> Sub-bullets for value-initialization.

source/classes.tex
The intent of [CWG 727](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#727) was to allow explicit specializations to be declared in any scope that the primary template can be declared in, particularly class scope. Quote [[temp.expl.spec] p3](http://eel.is/c++draft/temp.expl.spec#3):
> An explicit specialization may be declared in any scope in which the corresponding primary template may be defined.
While this wording was changed, it seems like the grammar for member-declaration was neglected, meaning that declaring an explicit specialization in class scope is not syntactically valid.
(note that _explicit-specialization_ isn't a form of _template-declaration_, as the _template-parameter-list_ of _template-head_ cannot be empty)
=> [class.mem] Explicit specializations within classes

source/lib-intro.tex
This footnote seemed like it was trying to exhaustively list all types imported from the C stdlib, but it was incomplete. Most notably, it was missing the types from `<stdint.h>`. Removing rather than fixing since the list is of questionable value and would be likely to become stale again.
=> [extern.types] strike footnote listing C stdlib types

source/basic.tex, source/classes.tex, source/declarations.tex, source/overloading.tex, source/templates.tex
There are a lot of inconsistencies in how we specify cv-qualifiers in the text, so I went through and fixed most of the more offending examples. Most of the changes involved replacing "possibly cv-qualified" where *cv* could be used, however there were a few other things I went ahead and fixed:
- The "house style" is to say "possibly cv-qualified", but there are two occurrences of "optionally cv-qualified". One was changed to use *cv*, the other was changed to the correct phrasing.
- [[dcl.init] p 17 sub 6.2.2](http://eel.is/c++draft/dcl.init#17.6.2.2) Introduces the named type `A`, but doesn't reference it again.
- [[over.match.copy]](http://eel.is/c++draft/over.match.copy) had a type with described as "reference to possibly cv-qualified `T`". Quite obvious what's wrong there.
A couple …
=> Consistent cv-qualification notation

source/compatibility.tex
The specialization of iterator_traits for pointers 'T*' in C++20 is now
constrained by 'is_object_v<T>' and so no longer applies to pointers
to function, or to void.
=> [diff.cpp17.iterators] Added compatibility note on iterator_traits

source/concepts.tex, source/iterators.tex
=> [concept.swappable,iterator.cust] Fix phrasing 'with no diagnostic required'

source/atomics.tex, source/compatibility.tex, source/lib-intro.tex, source/support.tex
Resolves #3794.
Index entries before/after:
---
---
=> [atomics.nonmembers,diff.cpp17.dcl.dcl,library,version.syn] Replace non-code "C++" with "\Cpp{}"

source/atomics.tex
The index for the primary atomic template was split across
two entries, atomic and atomic<T>.  Reconciled into one.
A couple of operations for atomic smart pointers are
specificed in the primary template, but were missing the
cross-reference into that specification, which is supplied
in the same way for all the other atomic specializations.
=> [atomic] Minor corrections to atomic index

source/expressions.tex
The problem and fix here is obvious.
=> [expr.sizeof] Incorrect use of \term

source/time.tex
I can't tell what the perceived problem behind the `FIXME` was; I'd welcome feedback; @AlisdairM?
=> [time.format] Add/fix region-index entry for "format"

source/ranges.tex
Which is the only remaining CPO not so fixed by #3752.
=> [range.prim.cdata] Properly ranges::-qualify cdata

source/iterators.tex
What should be a defaulted default constructor is instead an ill-formed defaulted non-default constructor. This appears to be copy pasta from the original merge of P0896R4 in e85af9533ab6ab0f0b101ac61fc01ba47c406503.
=> [front.insert.iterator] Correct mis-incorporation of P0896R4

source/locales.tex, source/regex.tex, source/support.tex, source/utilities.tex
These are conventionally wrapped in `\tcode{}`
=> [lib] Format true/false in code font conventionally

source/algorithms.tex, source/concepts.tex, source/containers.tex, source/expressions.tex, source/iterators.tex, source/numerics.tex, source/overloading.tex, source/ranges.tex, source/support.tex, source/templates.tex, source/threads.tex, source/time.tex, source/utilities.tex
This substantially improves the index of library concepts.
Fixes #3494.
=> [std] Mark all concepts with \libconcept or \exposconcept

source/compatibility.tex, source/lex.tex, source/time.tex
=> [lex.icon,lex.fcon] Rework description to avoid redundancies.

source/preprocessor.tex
Lowercase `__cplusplus` had properly been sorted relative to uppercase `__DATE__`,
..., `__VA_OPT__`, but the other lowercase terms `__cpp_`* and `__has_`* had wrongly
been sorted after all the uppercase ones.
Instead of special-casing `__cplusplus`, special-case the uppercase terms.
=> In the index, properly sort terms starting with two underscores

source/expressions.tex
According to the definitions, objects don't have members, and member subobjects don't have names. The standard is somewhat unclear on how the member subobjects of an object of class type relate to the non-static data members of the class. This change helps clarify that there is a member subobject associated with each non-static data member.
=> [expr.ref] clarify access of non-static data members

source/utilities.tex
=> [allocator.members] Replace SIZE_MAX with numeric_limits<size_t>::max()

source/utilities.tex
Add index entries for the inplace constructuction tag types
and values, as they exist only in the header synopsis.
=> [utility.syn] Index in-place construction types

source/classes.tex
The cross-reference for "linkage of the namespace of which it is a member" is useful for determining the linkage if the namespace is known; however, there was no cross-reference to assist with determining the namespace.
A cross-reference to [namespace.memdef] is added.
=> [class.friend] Add cross-reference for the namespace of the friend

source/atomics.tex
There is a consistent ordering of declarations for members
of std::atomc specializations, other than for the atomic
smart pointers.  This patch reorders the declarations to
follow that convention.
=> [atomic] Apply conventional order to members of atomic smart pointers

source/basic.tex
[[basic.type.qualifier] p2](http://eel.is/c++draft/basic.type.qualifier#2.sentence-2) and [[basic.type.qualifier] p6](http://eel.is/c++draft/basic.type.qualifier#6.sentence-1) are made reduntand by [[dcl.array] p5](http://eel.is/c++draft/dcl.array#5). 
Removing [basic.type.qualifier] p2 sentence 2, adjusting the first sentence to acknowledge what is stated in p6, and turning [basic.type.qualifier] p6 sentence 1 into a note resolves this.
In addition to this, [[basic.type.qualifier] p3](http://eel.is/c++draft/basic.type.qualifier#3) should be turned into a note, as it has no normative effects.
=> [basic.type.qualifier] Remove redundant wording

source/classes.tex
[[class.base.init] p17](http://eel.is/c++draft/class.base.init#17) uses `\term` to define *polymorphic behavior* within a note. This definition is not used outside of notes, and terms should not be defined in notes anyways.
=> Remove definition in note

source/time.tex
This is a typographical error in the PR of [LWG3294](https://cplusplus.github.io/LWG/issue3294). Clearly<sup>1</sup> `remove_cvref_t` is meant.
cc @HowardHinnant @tomaszkam
<sup>1</sup> For some definition of "clearly".
=> [time.zone.zonedtime.overview] Fix typo

source/ranges.tex
This restores references to the 'current' placeholder.
Fixes #3848
=> [range.split.outer], [range.split.inner] Fix misuses of current_

source/basic.tex, source/support.tex
=> [basic,support] Correctly use 'startup' and 'start of program'

source/compatibility.tex, source/config.tex, source/lib-intro.tex, source/support.tex, source/xrefdelta.tex
=> [support] Renamed from [language.support].

source/overloading.tex
=> [over.oper] Make statement about non-overloadable operators a note.

source/future.tex, source/lib-intro.tex, source/xrefdelta.tex
=> [res.on.requires] Move description of 'Requires' element to Annex D

source/containers.tex
because it also covers the size_type constructor of span.
Fixes #3778.
=> [span.deduct] Rename template parameter 'End' to 'EndOrSize'

source/classes.tex, source/overloading.tex
[[class.copy.ctor] p10](http://eel.is/c++draft/class.copy.ctor#10) and [[class.copy.assign] p7](http://eel.is/c++draft/class.copy.assign#7) both redundantly specify that defaulted move special member functions that are defined as deleted are ignored by overload resolution. This is already specified in [[over.match.funcs] p8](http://eel.is/c++draft/over.match.funcs#8), so turning the others into notes would be good. Also, [[over.match.funcs] p8](http://eel.is/c++draft/over.match.funcs#8) refers to "special functions", this is incorrect terminology and has been changed to "special member functions"
=> [class] [over] Redundant specification of ignoring move special members

source/utilities.tex
As the enum class 'pointer_safety' is defined only in the header synopsis
for <memory>, it had escaped indexing.  This adds the missing entries.
=> [memory.syn] Index the pointer_safety enum class

source/atomics.tex, source/future.tex
Since the application of P0439R0, the library wording has been partially
updated to use the new scoped enumaration values whenever memory order
constants are required, and partially retains use of the inline
constants supplied for back compatibility.
This patch conistently uses the memory_order::enumerators, retaining
the old name only for their declaration, the index, and for Annex C
wording on C++17 compatibility, which /should/ use the old spelling.
=> [atomics] Consistent use of enum class memory_order

source/support.tex
[LWG2950](https://wg21.link/LWG2950) has the correct edit but 61babcd dropped the `b =` part.
(Also, now that core has fixed this part of the rules in [CWG2338](https://wg21.link/CWG2338), we can editorially drop the `static_cast<unsigned char>`, but that's separate.)
Fixes #3862.
=> [support.types.byteops] Fix misapplication of LWG2950

source/ranges.tex
=> [range.access] Introduce 'reified object' to simplify the descriptions.

source/classes.tex
=> [class.mfct] consteval member functions are also inline.

source/compatibility.tex, source/declarations.tex, source/expressions.tex, source/lex.tex, source/lib-intro.tex, source/limits.tex, source/locales.tex, source/overloading.tex, source/preprocessor.tex, source/strings.tex, source/templates.tex
Also use the grammar non-terminals character-literal and
string-literal throughout the standard.
Fixes #3636.
=> [lex.ccon,lex.string] Remove redundant repetition of the grammar.

source/support.tex
These casts are redundant after [CWG2338](https://wg21.link/CWG2338).
=> [support.types.byteops] remove redundant static_cast to unsigned char

tools/check.sh
Augment the check script to detect non-ASCII character in the LaTeX source, which may appear due to copy/paste from PDF.
=> [check] Flag non-ASCII characters in source

source/basic.tex, source/expressions.tex
The definition of *null pointer value" was moved to [basic.compound], however, multiple cross-references still refer to [conv.ptr].
=> [basic], [expr] Fix incorrect cross-references to [conv.ptr] for null pointer values

source/lib-intro.tex
Fixes #3202. 
The requirement tables need a wholesale overhaul, so this is just shaving off the tip of the iceberg.
=> [allocator.requirements] Fix punctuation in tables.

source/algorithms.tex
Define `comp` and `proj` for the overloads with no such parameters and spell out the meaning of the handwavy "is no greater than" and "is less than".
=> [alg.clamp] Reword for clarity

source/iostreams.tex
Also fix grammar in [istream], [istream.extractors] and
[ostream.inserters] to refer to "*the* error state", and use "is set in"
when talking about a bitmask element being set in a value of a bitmask
type.
Fixes #3333
=> [ostream] Fix poor grammar to be consistent with [istream]

source/concepts.tex, source/containers.tex, source/iostreams.tex, source/iterators.tex, source/ranges.tex, source/statements.tex
For my review of LWG 7&ndash;19 except 11 and 18.  (Many of those have no changes.)  Only the last commit is supposed to affect meaning at all, and that to supply information needed to interpret its template argument deduction (in text that doesn't really do anything anyway).
=> More review changes

source/future.tex, source/macros.tex
Now that Mandating is complete, we can prevent accidentally using `\requires` by relegating the macro itself to Annex D (in a form of meta-deprecation).
=> Disable \requires

source/front.tex, source/preface.tex
The general text was provided by the ISO CS. A list of incorporated
technical specifications was derived from N4824. A list of technical
changes since C++17 was derived from P2131R0.
Fixes #3668.
=> Add Foreword

source/declarations.tex, source/expressions.tex, source/future.tex
[dcl.fct] uses `\term{cv}` for a placeholder cv-qualifier as opposed to the usual `\cv{}`, this fixes that.
Additionally, the wording for "Deprecating volatile" uses `\tcode{volatile}`-qualified, as opposed to the defined term _volatile-qualified_ from [basic.type.qualifier]. This is also addressed.
=> More cv-qualification fixes

source/declarations.tex
Should be `\grammarterm{template-parameter}{s}`, not `\grammarterm{template-parameters}`
=> [dcl.fct] Fix incorrectly pluralized grammar terms

source/templates.tex
Super tiny fix. LaTeX doesn't hyphenate this, so we don't need it.
=> [temp.class.spec] Remove unused hyphenation point

source/declarations.tex
On a somewhat related note, it might be time to just remove [[class.this]](http://eel.is/c++draft/class.this). It only has 3 normative sentences, the first 2 being redundant by [expr.prim.this] and the third by [over.match.funcs].
=> [dcl.fct.def] Fix incorrect cross-ref referring to "this"

source/expressions.tex
`dynamic_cast` here would be the correct terminology, we generally adhere to that everywhere else.
Also, I moved *throw-expression* to its own item, since it can either:
- throw an exception
- rethrow an exception
- call `std::terminate`
Thus never being eligible to be evaluated in a constant expression. Putting it in the same item as `dynamic_cast` and `typeid` along with "[...] that would throw an exception" only serves to confuse the reader.
=> [expr.const] Change "dynamic cast" to "dynamic_cast" and move throw-expression to its own item

source/iterators.tex
Three commits with related changes:
* Change the declaration of `move_iterator`'s non-member `operator+` in [iterator.synopsis] to agree with the redeclaration in [move.iter.nonmember] which was changed by P0896R4.
* Fix the formatting of the declaration of `move_iterator`'s non-member `operator-` in [iterator.synopsis], and harmonize the formatting of the redeclaration in [move.iter.nonmember].
* Use `iter_difference_t` in the declaration of `reverse_iterator`'s non-member `operator+` to harmonize with the style of `move_iterator`.
=> [iterator.synopsis] Cleanups

source/algorithms.tex
...which were accidentally ommitted from 31a1a94d. Note that this doesn't alter the semantics of the overload in `std`: `comp`'s type `Compare` is required to be a function object (and therefore not a pointer-to-member for which `invoke` would be significant) by [alg.sorting]/2.
=> [alg.clamp] Add missing calls to invoke

source/strings.tex
While technically correct, comparing pointers against nullptr is usually preferred to comparing them against the null pointer costant 0. Moreover, it seems more consistent to compare against nullptr, since the default value of the pointer idx is actually declared as nullptr in the synopsis.
=> [string.conversions] Replaced comparisons of a pointer against 0 with comparision against nullptr

source/future.tex
The typo was introduced in commit bbb46260d5dd0bb8b561cc74f929ac9a982629a9
while applying P0883R2 Fixing Atomic Initialization.
Fixes #3947.
=> [depr.atomics] Fix <atomic> header name.

source/iterators.tex
=> [iterator.concepts.general] Remove synthesizeable operator!= in example.

source/overloading.tex
We don't capitalize it anywhere else when used in the context
=> [over.ics.ref] Remove erroneous capitalization of Conversion

source/utilities.tex
...suggesting that elsewhere where we say only "object type" we intend to admit non-C++ object types.
=> [meta.trans.other] "C++ object type" is overprecise

source/styles.tex
texlive 2020 uses version 1.8d
=> Allow 'listings' package v1.8d

source/classes.tex
[CWG2404](bb641cba40211374d8b2dd3472f42274de662761) demoted this paragraph to a note, but didn't include a reference to _why_ the ordering of non-static data member addresses was still defined.
Credit to [aschepler on StackOverflow](https://stackoverflow.com/a/61590855/166389) for the reference.
=> Reference the normative text for data member order

source/concepts.tex
modify customization point to customization point object when referring to ranges::swap
=> modify customization point to customization point object #1

source/iterators.tex
Modified the title of [iterator.cust] to 'customizatin point objects' since it talks about customization point objects. Modified the reference to it in [iterator.synopsis] too.
=> fixing customization point references #3

source/ranges.tex
changed customization point to customization point object when talking about ranges::data
=> Fixing customization point references #2

source/iterators.tex
renaming [common.iter.cust] to match [counted.iter.cust] for consistency reasons
=> renaming [common.iter.cust]

source/basic.tex
"trivially-copyable" is space-separated in the rest of the standard
(this occurrence originated in  611f4c675e2160463cb1fbf71ab87bd67c9102eb and is the only such spelling in the entire commit history)
=> [class.temporary] space-separate trivially copyable

source/threads.tex
=> [thread.syn] Don't mandate including <initializer_list> when including <thread>

source/containers.tex
Per [Specification-Style-Guidelines/describing-function-calls](https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines#describing-function-calls).
=> [container.requirements.general] Don't use 'f()' to refer to non-nullary function.

source/lib-intro.tex, source/xrefdelta.tex
The latter consisted of a single sentence that is
best integrated into the place where the Preconditions:
element is introduced.
Also fixes LWG3168.
=> [structure.specifications] Integrate [res.on.expects].

source/basic.tex
In all other places in this sub-clause we use the canonical forms of type names as described in [dcl.type.simple]. We should do so here as well.
=> [basic.fundamental] Use canonical types in Table 12

source/containers.tex
=> [container.requirements] Improve index entries for contiguous and reversible containers.

source/classes.tex
This index entry seems useless because how would one even know to look for "X(X&)" in the index, given that the name X is arbitrary? :)
=> [special] Remove index entry for 'X(X&)'.

source/expressions.tex
I overlooked these in https://github.com/cplusplus/draft/pull/1501.
=> [expr.new] Use repeated \indextext for index redirects with multiple targets.

source/utilities.tex
The space is visible in the PDF.
=> [allocator.members] Remove stray whitespace.

source/algorithms.tex
Defines `last2` and `pred` for the overloads in `std` with no parameters by those names so the remainder of the specification need not exhaustively describe each case.
=> [alg.is.permutation] Rephrase to simplify

source/grammar.tex, source/regex.tex, source/statements.tex
This is already done everywhere else in the document as far as I can tell.
No visible difference in the PDF.
(Incidentally, this change makes life easier for cxxdraft-htmlgen.)
=> [stmt.pre, re.grammar, gram] Use a separate bnf environment for each nonterminal.

source/regex.tex
=> [re.grammar] Don't use monospace for ordinary text.

source/lib-intro.tex
The space shows up in the PDF.
=> [tab:cpp17.moveassignable] Remove superfluous space.

source/iostreams.tex
I think LaTeX is interpreting the periods as sentence full stops, causing it to apply sentence-spacing by default. `\ ` forces an interword space.
=> [fs.class.path] Ensure interword spacing inside sentence.

source/expressions.tex
```c++
struct S { int i; } s;
auto fp = reinterpret_cast<float*>(&s); // the value of `fp` is  "pointer to s"
reinterpret_cast<float*>(reinterpret_cast<int*>(fp));
// converting to `int*` and back to `float*` does NOT yield the original pointer value,
// because the value became "pointer to s.i" when casting to `int*`.
```
@hubert-reinterpretcast
=> [expr.reinterpret.cast] Fix a note

source/iostreams.tex
Missing editorial changes in [this commit](https://github.com/cplusplus/draft/pull/3749/commits/ffb23d0521af5a8795fc051d2915858d00518d41).
=> [istream.syn][ostream.syn] update synopses according to LWG1203

source/algorithms.tex, source/atomics.tex, source/containers.tex, source/iostreams.tex, source/locales.tex, source/numerics.tex, source/ranges.tex, source/regex.tex, source/strings.tex, source/support.tex, source/threads.tex, source/time.tex, source/utilities.tex
Partially addresses #3677
(There are 6 remaining mis-orderings that need more attention.)
=> [lib] Canonicalize order of library descriptive elements.

source/lex.tex
This change has no visible effect on the PDF, but:
- it makes the LaTeX source a little bit simpler
- it makes the use of `\placeholder` inside a string literal consistent with e.g.
https://github.com/cplusplus/draft/blob/de443df351fdecd010633fbadde0d793d0005616/source/declarations.tex#L5972
- it makes things easier for cxxdraft-htmlgen (I admit this is my main motivation).
=> [lex.ext] Simplify use of \placeholder.

source/lex.tex
No visible difference in the PDF.
=> [lex.ccon] Remove redundant nested \tcode.

source/numerics.tex
Many nouns appear in this sentence before "it", _none_ of which is the proper antecedent.
=> [mask.array.assign] Replace "it" with its antecedent

source/numerics.tex
We don't refer to an instance of a specialization of `mask_array` as a "mask object" elsewhere, but we do use the phrase "`mask_array` object" which is consistent with library-wide style.
=> [mask.array.comp.assign] Clarify "mask object"

source/ranges.tex
With thanks to @johelegp for catching me exacerbating the problem in https://github.com/cplusplus/LWG/pull/332.
=> [ranges.syn] Properly capitalize "Clause"

source/algorithms.tex, source/utilities.tex
... for consistency with the renaming of the concept `sentinel` to `sentinel_for` from P1754R1.
Fixes #4050.
=> [memory.syn,specialized.algorithms] Append "-for" to exposition-only concept "no-throw-sentinel"

source/expressions.tex
=> [expr.cond] drop redundant subclause (CWG 2316)

source/threads.tex
Resolves https://github.com/cplusplus/draft/issues/4114.
Remove reference to nonexistent variable "cv" in the new cv interruptible waits.
Presumably this was copied from a reference implementation that built on top of another cv type wherein "cv" was a member variable.
=> [thread.condvarany.intwait] remove reference to nonexistent "cv" variable

source/ranges.tex
=> [range.utility.helpers] Move template argument out of \libconcept.

source/ranges.tex
... to agree with the declaration in [range.transform.view] as modified by [LWG-3325](https://cplusplus.github.io/LWG/issue3325). The resolution of this LWG issue failed to direct the Editor to also change the declaration in [ranges.syn].
=> [ranges.syn] Fix declaration of transform_view

source/utilities.tex
by moving the declarations of w/format_context and
w/format_args to the front.
=> [format.syn] Avoid forward references

source/atomics.tex
Same as for [tab:atomic.types.int.comp]: https://github.com/cplusplus/draft/blob/76ce4297dbe18794331174a281f3bf786d77de41/source/atomics.tex#L2210-L2218
=> [tab:atomic.types.pointer.comp] Fix column captions.

source/algorithms.tex, source/containers.tex, source/iostreams.tex, source/iterators.tex, source/locales.tex, source/numerics.tex, source/threads.tex, source/time.tex
=> [lib] Fix uses of "clause"

source/expressions.tex
not the whole `. template` or `-> template`.
=> [expr.post] Only keyword template is optional

source/compatibility.tex
These names, as well as operators for std::byte, are part of <cstddef>.
Fixes #4144.
=> [diff.mods.to.declarations] Also mention 'byte' and 'to_integer.

source/classes.tex
Index the two paragraphs that actually specify the rules for 'final'
and 'override' virt-specifiers applied to functions.
I chose to index these specifiers using the 'keyword' macro rather
than try to set up a separate indextext entry to ensure:
1) the index points to the right page if ever the paragraph splits
across pages
2) the form is consistent with every othert index entry for these
two contextual keywords, which are all created by 'keyword'
Visually confirmed that the text renders in the same monospace
font as the previous 'tcode' entry.
=> [class.virtual] index semantics of final and override

source/atomics.tex, source/containers.tex, source/diagnostics.tex, source/iostreams.tex, source/lib-intro.tex, source/preprocessor.tex, source/regex.tex, source/time.tex
- Only a dozen or so tables are affected.
- Effect:
- The miniscule amount that the content below the affected tables is raised by is too small to cause reflow anywhere.
=> [std] Remove superfluous final \rowsep or \hline in tables.

source/macros.tex
Such links were pointing to immediately after the clause
or annex title, not to immediately before them. The issue
was introduced with commit beb88157cc49f76677fc467db8ec4a523dbc41d0.
Fixes NB JP 014 and JP 015 (C++20 DIS)
Fixes cplusplus/nbballot#390
Fixes cplusplus/nbballot#391
=> [macros] Fix PDF links to clauses and annexes

source/exceptions.tex
Fixes NB JP 013 (C++20 DIS)
Fixes cplusplus/nbballot#389
=> [except.uncaught] Remove parentheses when not invoking a function

tools/check.sh
A "hanging paragraph" per the ISO Directives, Part 2,
is a subclause that directly contains text as well as
subordinate subclauses.  Those are not allowed.
Partially addresses cplusplus/nbballot#394
We might not want to apply this to the C++20 branch at all, since no further maintenance happens here, but instead rebase this onto the master branch.
=> [check] Detect hanging paragraphs.

source/algorithms.tex, source/atomics.tex, source/compatibility.tex, source/declarations.tex, source/diagnostics.tex, source/iterators.tex, source/lib-intro.tex, source/locales.tex, source/numerics.tex, source/overloading.tex, source/ranges.tex, source/regex.tex, source/strings.tex, source/support.tex, source/templates.tex, source/threads.tex, source/time.tex, source/utilities.tex
These typically mean the parent subclause now. Mechanically:
"this subclause" became "\ref{parent}".
"This subclause" became "Subclause \ref{parent}", because it doesn't
look great to start a sentennce with a subclause number.
... with some manual fixups for cases where that didn't work out well.
=> Replace "this subclause" with an explicit reference in all formerly-hanging paragraphs

source/back.tex, source/intro.tex, source/xrefdelta.tex
Integrate trademark acknowledgements into [intro.refs].
Add base works to the bibliography.
Fixes cplusplus/nbballot#399
=> [intro.ack] Dissolve subclause.

source/preface.tex
Fix some minor discrepancies between our Foreword and the text provided by ISO/CS, and reduce the list of changes a bit.
Fixes cplusplus/nbballot#388.
=> Adjust Foreword based on comments from ISO/CS

source/future.tex, source/iterators.tex, source/locales.tex, source/numerics.tex, source/support.tex, source/xrefdelta.tex
[ISO/CS comment 018 on the C++20 DIS](https://github.com/cplusplus/nbballot/issues/394) requests that we avoid subclauses with no siblings.
Merging this to master will address #3525.
Fixes cplusplus/nbballot#394
=> Fix solitary subclauses

tools/check.sh
According to the ISO Directives, Part 2, each subclause
is required to have at least one sibling.
Partially addresses #3525 and cplusplus/nbballot#394
=> [check] Detect subclauses without siblings.

source/atomics.tex
Fixes cplusplus/nbballot#386
Was fixed on main branch with commit e674373e2515868ca17b24157f30515fad62b8e6 #4001
=> [atomics.types.operations] Fix typo in exposition-only code

source/utilities.tex
Fixes NB JP 005 and JP 006 (C++20 DIS)
Fixes cplusplus/nbballot#381
Fixes cplusplus/nbballot#382
=> [variant.helper] Use 'struct' for variant_size and variant_alternative

source/utilities.tex
Fixes NB JP 008 (C++20 DIS)
Fixes cplusplus/nbballot#384
=> [mem.res.syn] Add default template argument for polymorphic_allocator

source/utilities.tex
Fixes NB JP 009
Fixes cplusplus/nbballot#385
=> [mem.poly.allocator.mem] Fix syntax for variadic template declaration

source/intro.tex
=> [intro.refs] Fix clause reference to ISO/IEC 9899.

source/future.tex, source/intro.tex
This is the most recent version of ISO/IEC 10646 that
specifies the encoding form UCS-2.
Fixes cplusplus/nbballot#401
=> [intro.refs] Update from ISO/IEC 10646-1:1993 to ISO/IEC 10646:2003.

source/back.tex, source/basic.tex, source/intro.tex, source/time.tex
ISO/IEC/IEEE 60559:2011 and UAX#29 are not normative
requirements of C++ and thus were moved to the bibliography.
For ISO 8601:2004, highlighted its normative impact on
time formatting.
Move the footnote about the Unicode trademark to the
new first mention of the term in [intro.memory].
Fixes ISO/CS 002 (C++20 DIS)
Fixes cplusplus/nbballot#378
=> [intro.refs,time.format] Fix normative references.

source/intro.tex
=> [intro.defs] Remove cross-references to main part

source/algorithms.tex, source/containers.tex, source/expressions.tex, source/future.tex, source/intro.tex, source/iostreams.tex, source/iterators.tex, source/layout.tex, source/lex.tex, source/locales.tex, source/macros.tex, source/ranges.tex, source/tables.tex, source/time.tex, source/utilities.tex, tools/check.sh
Number notes and examples, make them one point smaller, and move them to (un-numbered) paragraphs of their own.
Partially addresses ISO/CS 016 (C++20 DIS).
Fixes https://github.com/cplusplus/nbballot/issues/398.
=> [everywhere] Follow ISO rules for the presentation of notes and examples

source/containers.tex, tools/check.sh
Also prevent future occurrences by updating check.sh
Clone of #3983 for the C++20 DIS.
Fixes #3982
=> C++20 [vector.capacity] Remove duplicate \pnum

source/threads.tex
This was accidentally introduced while applying
LWG3330 Include <compare> from most library headers.
Clone of #3991 for C++20 DIS.
Fixes #3988
=> C++20 [thread.syn] Do not mandate including <initializer_list> when including <thread>

source/ranges.tex
This is a clone of #4009 to apply to the C++20 DIS.
=> C++20 [range.single.view] Add missing requires-clause to \itemdecl

source/compatibility.tex, source/future.tex, source/preprocessor.tex, source/support.tex, source/utilities.tex
As far as ISO is concerned, there is only one International Standard for
C++, and in any case, we don't mean the document here, we mean the
language in the abstract and don't care whether that's an ISO standard
or not. Refer to "revisions of C++" instead of revisions of particular
ISO documents.
Partially addresses ISO/CS 016 (C++20 DIS).
=> [everywhere] Stop talking about C++ International Standards.

source/declarations.tex
The invocation of final_suspend is guaranteed to be non-throwing,
thus final_suspend in the example needs to be declared 'noexcept'.
Fixes #4200
=> [dcl.fct.def.coroutine] Add missing 'noexcept' for final_suspend.

source/expressions.tex
=> [expr.const] Disambiguate 'it' by introducing the name V.

source/expressions.tex
=> [expr.const] Add cross-reference for 'constant initialization'.

source/modules.tex
I think this is the intent of that sentence. Another possible reading, and the one my rewording attempts to prevent, is that because it doesn't say that no other TUs may be reachable, any TU may be, and it is just giving an example of a specific likely case of incidental reachability. But if that is the intent, then we probably shouldn't have it in normative text.
There is an existing issue in the wording (#3502) in that http://eel.is/c++draft/module#import-10 defines "has an interface dependency" as a relationship between two TUs, but this uses it as a relationship between "point with the program" and a TU. This makes it ambiguous about whether TU imported later in a file may be reachable at an earlier point. I am not trying to resolve that ambiguity with this change.
=> [module.reach] Clarify that only TUs with an interface dependency may be incidentally reachable

source/classes.tex
These shouldn't be `\tcode`, as these are defined terms (a function can be a _virtual function_ ora  _pure virtual function_)
=> [class.dtor] Remove incorrect uses of virtual as a keyword

source/expressions.tex
Having an example after a comma mid-sentence is _horrible_ (I had to read this several times to realize that it wasn't a sentence fragment).
=> [expr.comma] Remove mid-sentence example

source/basic.tex
=> [intro.object] Say "member subobject" instead of "data member"

source/expressions.tex
The term "local entity" can be used here now that structured bindings
can be captured (after P1091R3 and P1381R1).
=> [expr.prim.lambda.capture] Use the term "local entity".

source/statements.tex
The Example immediately after the wording makes me strongly suspect that the wording should've looked like this.
https://timsong-cpp.github.io/cppwp/n4659/basic.lval#def:result_object
=> [stmt.return] Improve CWG2426 wording

source/macros.tex
Use upright font for : in Preconditions: and friends.
=> [everywhere] Reduce width of space after Note: and Example:.

source/overloading.tex
=> [over.literal] Mark use of a reserved identifier with 'error'.

source/expressions.tex
=> [conv.qual] Fix punctuation in bulleted list.

source/ranges.tex
Is `ranges​::​empty(E)` in the text here not `E`?
>Given a subexpression ranges​::​empty(E) with type T, let t be an lvalue that denotes the reified object for E.
- [24.3.11 ranges​::​empty [range.prim.empty] - eel.is](http://eel.is/c++draft/range.access#range.prim.empty-2.sentence-1)
=> [range.prim.empty] Fix expression specification

source/declarations.tex
This doesn't follow our usual convention
=> [dcl.init.ref] Remove "type" from "reference to type T"

source/atomics.tex, source/basic.tex, source/intro.tex, source/lib-intro.tex, source/preprocessor.tex
=> [std] Improve index for 'freestanding/hosted implementation'.

source/templates.tex
[[temp.pre]/10](http://eel.is/c++draft/temp.pre#10):
"""
A definition of a function template ... shall be reachable from the end of every definition domain ([basic.def.odr]) in which it is implicitly instantiated ([temp.inst]) unless the corresponding specialization is **explicitly instantiated** ([temp.explicit]) in some translation unit; no diagnostic is required.
"""
So, implicit instantiation (or explicit specialization) won't make the example well-formed.
=> [temp.over] Fix example

source/classes.tex
=> [class.virtual] Fix example with constrained non-templated function

source/classes.tex
[[class.union.anon] p1](http://eel.is/c++draft/class.union.anon#1) already specifies that a declaration of a union with declarators isn't an anonymous union, so p3 can be turned into a note. Additionally, objects of pointer type are objects, so "pointers" in p3 can be removed.
=> [class.union.anon] Turn redundant wording into a note

source/support.tex
=> [cmp.categories.pre] Remove unused enumerators

source/concepts.tex
with 'the library Clauses'.
Fixes #3980.
=> [concepts.equality] Replace spurious 'this document'

source/iostreams.tex, source/utilities.tex, source/xrefdelta.tex
There should only be one subclause called "normative
references".
Fixes #4176
=> [fs.norm.ref] Dissolve subclause.

source/containers.tex
Remove mention of "assignment", which is not specified here.
Fixes #4193
=> [vector.cons] Fix subclause heading.

source/algorithms.tex, source/atomics.tex, source/basic.tex, source/classes.tex, source/containers.tex, source/declarations.tex, source/expressions.tex, source/future.tex, source/intro.tex, source/iostreams.tex, source/iterators.tex, source/lib-intro.tex, source/numerics.tex, source/overloading.tex, source/preprocessor.tex, source/ranges.tex, source/regex.tex, source/strings.tex, source/support.tex, source/templates.tex, source/threads.tex, source/time.tex, source/utilities.tex
This pull request contains all the changes on `master` but not on `c++20` that I think we might want to take for the IS. This aims to exclude changes that:
* that got too close to looking like a normative change (excluding misapplied motions), or
* that are trivial or unimportant or a wording cleanup (excluding changes that only affect the index or formatting fixes), or
* that doesn't affect the produced document.
=> Pull a bunch of changes from master onto the C++20 branch

source/atomics.tex, source/containers.tex, source/diagnostics.tex, source/iostreams.tex, source/iterators.tex, source/lex.tex, source/lib-intro.tex, source/preprocessor.tex, source/ranges.tex, source/regex.tex, source/time.tex, source/utilities.tex
These are changes that either have no effect but decrease the diff between branches, or that are improvements to the overall quality of the final document.
Please discuss.
See https://github.com/cplusplus/draft/pull/4220#issuecomment-697047187 for a list of candidate commits.
=> Further cherry-picks for the c++20 branch

source/iostreams.tex
Initially, 75bea3cfb49cd07fb267d46b22aa0a5d40dc6735 moved a footnote into a new "recommended practice" paragraph. Later, cb07613ed7c6cfa19a5ce024a5a8ed1c6d9bf869 added the same "recommended practice" into the middle of the paragraph that originally contained the footnote.
Initial edit: https://github.com/cplusplus/draft/commit/75bea3cfb49cd07fb267d46b22aa0a5d40dc6735#diff-8d76c9854d3e844d443d7516819ba062
Bogus duplication: https://github.com/cplusplus/draft/commit/cb07613ed7c6cfa19a5ce024a5a8ed1c6d9bf869#diff-8d76c9854d3e844d443d7516819ba062
=> [iostream.objects.overview] Delete duplicate paragraph.

source/preface.tex
It does not seem helpful to link into the mention of a header in the
foreword, esp. since these links would use the Roman frontmatter page numbers.
=> [foreword] Exclude mentions of library headers from the index.

source/intro.tex, source/limits.tex
This change also promotes Annex B [implimits] to a "normative" annex. The existing wording in the annex is already normative in character.
=> [intro.compliance.general, implimits] Cite Annex B normatively.

source/classes.tex
With the new note style, notes should no longer appear in the middle of a sentence.
Fixes #4236.
=> [class.mem.general] Move note to the end of the list item.

source/iostreams.tex, source/lib-intro.tex, source/macros.tex, source/time.tex, source/utilities.tex
Partially addresses #4228.
This should also be applied to master.
=> [std] Introduce tailnote environment to avoid empty lines in tables.

source/containers.tex, source/lib-intro.tex, source/regex.tex, source/utilities.tex, tools/check.sh
Also add an automated check.
Partially addresses #4228 
Must be applied to "master" as well.
=> [std] Use tailnote and tailexample to avoid empty space in tables.

source/ranges.tex
The nested name is an exposition-only name and needs to be formatted accordingly.
=> [ranges] Index "split_view::{outer,inner}-iterator" correctly.

source/time.tex
=> [time.clock.utc.overview] Move explicit line break in example.

source/basic.tex, source/compatibility.tex, source/expressions.tex, source/future.tex, source/intro.tex, source/iterators.tex, source/lex.tex, source/ranges.tex, source/statements.tex
=> Page breaks (tkoeppe)

source/algorithms.tex, source/atomics.tex, source/iostreams.tex, source/locales.tex, source/regex.tex, source/threads.tex, source/time.tex
=> Page breaks (jmaurer)

source/containers.tex, source/locales.tex, source/time.tex
Build fix:
* 30353134 [tab:container.alloc.req] Indent clauses to fix the build.
Optional fixes:
* 727aff3e [locale.codecvt] Use 2 space indentation (but leave inconsistent indentation for parameters in synopsis as is).
* 6ab88976 [time.clock.cast.fn] Use 2 space indentation in the constraints for clock_cast.
=> C++20 tweaks

source/expressions.tex
It is still needed for the naming-local-entity-in-lambda case.
=> [expr.prim.id.unqual] Restore "Otherwise"

source/iostreams.tex
=> [iomanip.syn] Use 'unspecified' instead of type meta-variables.

source/ranges.tex
We clearly meant for this to cover cv-unqualified `subrange`s of that form too.
=> [range.reverse.overview] Use \cv{} instead of "cv-qualified"

source/expressions.tex
=> [expr.prim.paren] Replace "value" with "result"

source/intro.tex, source/regex.tex, source/xrefdelta.tex
Also rephrase the regular expression definitions to fit
the ISO-mandate style.
Fixes #4283
=> [intro.defs] Integrate [re.def].

source/expressions.tex
=> [expr.unary.op] Use 'negative', not 'negation'.

source/algorithms.tex, source/atomics.tex, source/basic.tex, source/classes.tex, source/concepts.tex, source/containers.tex, source/declarations.tex, source/expressions.tex, source/future.tex, source/intro.tex, source/iostreams.tex, source/iterators.tex, source/lex.tex, source/lib-intro.tex, source/locales.tex, source/macros.tex, source/modules.tex, source/numerics.tex, source/overloading.tex, source/preprocessor.tex, source/regex.tex, source/statements.tex, source/strings.tex, source/support.tex, source/templates.tex, source/threads.tex, source/time.tex, source/utilities.tex, tools/check.sh
Create a "footnoteenv" environment for footnotes.
This allows to clearly separate them in the LaTeX source, enabling automatic checking for normative words such as "shall" or "may" inside them.
[temp.constr.order] has an example each inside two footnotes that now gets formatted differently.
We should get rid of that for unrelated reasons (bad rendering with the new separate-paragraph examples).
With this compensated, this patch has no visible differences in "appearance" mode except for footnote 12 (different hyphenation) and footnote 256 (slight differences in spacing/kerning, it seems).
=> footnote environment

source/declarations.tex
=> [dcl.array] Clarify that arrays do not have extra padding.

source/ranges.tex
There is a `ranges::` qualifier missing here.
=> Fix missing `ranges::` qualifier in example

source/back.tex, source/latexmkrc, source/std.tex
This doesn't consume a \write stream per index.
The disadvantage is that it needs the `-shell-escape` option for pdflatex to split up the single index file.
We can now easily add a separate index of exposition-only library names.
"diffpdf" says the before/after PDFs are the same.
=> [index] Use LaTeX package 'imakeidx' to allow for more indices.

source/basic.tex
[[basic.types] p5 sentence 3](http://eel.is/c++draft/basic.types#5.sentence-3) is made redundant by [[basic.def] p5](http://eel.is/c++draft/basic.def#5). This changes the former into a note and adds a cross-ref to [basic.def].
=> [basic.types] Change redundant normative wording into note

source/declarations.tex
[[dcl.init] p17.4](http://eel.is/c++draft/dcl.init#17.4) and [[dcl.init] p11](http://eel.is/c++draft/dcl.init#11) both specify when value-initialization is performed. This can just be specified in p17.4, since it describes the semantics of initializers. The note in p11 is also moved to p17.4.
While on the topic, both of the aforementioned paragraphs only specify initialization of an object with `()`, but not a reference, and [dcl.init.ref] does not handle this case either. 
One way to resolve this would be:
- Strike p9 (or turn it into a note)
- Add an item to the definitions of value/default-initialization saying "If `T` is a reference type, the program is ill-formed"
- Change p17.4 to "If the initializer is `()`, value-initialization is performed", and move it above p17.2
In addition to …
=> [dcl.init] Remove redundant specification of when value-initialization occurs

source/classes.tex
The intent in [P0091R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0091r3.html) is pretty clear (emphasis mine):
> Deduction guides must name a class template and must be introduced within the same semantic scope of the class template, but **they do not becomes members of that scope (i.e if that scope is a class)**.
=> [class.mem] Deduction guides do not declare new members

source/declarations.tex
We usually say "parenthesized *expression-list*", there is no need to use a code block to specify this.
=> [dcl.spec.auto] Denoise wording for when placeholders can deduce from an initializer

source/expressions.tex
=> [expr.spaceship] Clarify treatment of pointers.

source/classes.tex
All of the normative wording here is redundant: the overloading rule is specified in [over.load], the _cv-qualifier-seq_ rule in [dcl.fct], and the virtual rule in [dcl.fct.spec]. 
I added the trailing _requires-clause_ rule for overloading, and also changed "shall" to "cannot" since it shouldn't be used within informative wording.
It seems that we ran out of normative wording in this sub clause with this change, so perhaps more drastic measures should be taken (eventually).
=> [class.static.mfct] Strike redundant normative wording

source/templates.tex
Non-template functions are never virtual by inheritance. 
This also includes a small drive-by fix to an example.
=> [temp.mem] Change "virtual" to "declared virtual"

source/basic.tex, source/expressions.tex
no need to mention them separately
=> [basic.lval] bit-fields are objects

source/templates.tex
As discussed on the reflector, CWG2303 causes shadowing of a base class
when attempting deduction in the case where the type is a base of
another successful base class.  This patch adds an example that
clarifies that intent.
=> Add additional example to CWG2303 example to clarify meaning.

source/lex.tex, source/locales.tex, source/preprocessor.tex, source/time.tex
Do not use 'white space' or 'white-space'.
Fixes #4196
=> [everywhere] Consistently use 'whitespace'.

source/utilities.tex
that refers to participation in overload resolution.
Fixes #4266
=> [declval] Indent example and fix phrasing in example

source/atomics.tex, source/containers.tex, source/expressions.tex, source/future.tex, source/iostreams.tex, source/iterators.tex, source/macros.tex, source/overloading.tex, source/ranges.tex, source/templates.tex, source/threads.tex, source/time.tex, source/utilities.tex
Together, these two changes fix #4097.
No visible difference outside of the index.
=> [std] Remove unnecessary bracketing in \tcode and retire \dcr

source/statements.tex
Those are placeholders for expressions.
Fixes #4285
=> [stmt.ranged] Align font for begin-expr and end-expr.

source/exceptions.tex, source/support.tex, source/threads.tex, source/utilities.tex
instead of saying 'is called'.
Also add cross-references to [except.terminate].
Also use 'exits via an exception' consistently.
Fixes #3079.
=> [std] Harmonize phrasing 'terminate is invoked'

source/iostreams.tex
`swap`'s parameter is `rhs`; there is no `s` here. (This appears to have been copy-pasted from `[string.swap]` where the parameter is named `s`.)
=> [stringbuf.assign] Fix typo.

source/strings.tex
=> [strings] Replace 'could' and 'might'

source/iterators.tex
=> [iterators] Replace 'could' and 'might'

source/ranges.tex
=> [ranges] Replace 'could' and 'might'

source/numerics.tex
=> [numerics] Replace 'could' and 'might'

source/locales.tex
=> [localization] Replace 'could' and 'might'

source/algorithms.tex, source/std.tex
=> [algorithms] Replace 'could' and 'might'

source/threads.tex
=> [thread] Replace 'could' and 'might'

source/time.tex
=> [time] Replace 'could' and 'might'

source/compatibility.tex
=> [diff] Replace 'could' and 'might'

source/diagnostics.tex
=> [diagnostics] Replace 'could' and 'might'

source/lib-intro.tex
=> [library] Replace 'could' and 'might'

source/preprocessor.tex
=> [cpp] Replace 'could' and 'might'

source/exceptions.tex
=> [except] Replace 'could' and 'might'

source/statements.tex
=> [stmt.stmt] Replace 'could' and 'might'

source/iostreams.tex
=> [input.output] Replace 'could' and 'might'

source/concepts.tex
=> [concepts] Replace 'could' and 'might'

source/utilities.tex
=> [utilities] Replace 'could' and 'might'

source/atomics.tex
=> [atomics] Replace 'could' and 'might'

source/future.tex
=> [depr] Replace 'could' and 'might'

source/support.tex
=> [support] Replace 'could' and 'might'

source/templates.tex
=> [temp] Replace 'could' and 'might'

source/overloading.tex
=> [over] Replace 'could' and 'might'

source/classes.tex
=> [class] Replace 'could' and 'might'

source/declarations.tex
=> [dcl.dcl] Replace 'could' and 'might'

source/basic.tex
=> [basic] Replace 'could' and 'might'

source/expressions.tex
=> [expr] Replace 'could' and 'might'

source/lex.tex
=> [lex] Replace 'could' and 'might'

source/basic.tex, source/classes.tex, source/declarations.tex, source/exceptions.tex, source/expressions.tex, source/lex.tex, source/overloading.tex, source/preprocessor.tex, source/statements.tex, source/templates.tex
These changes editorially remove the words "could" and "might".
Please review this change carefully with the following goals:
* Flag anything that seems even remotely non-editorial, e.g. even if the explanation provided by a Note becomes less useful or (more) misleading.
* Also flag anything that could conceivably be worded better by a wider review.
I would like all remaining instances of "could" and "might" to be reviewed by CWG/LWG, so please don't hold back on rejecting anything at this point.
=> Replace "could" and "might", Clauses 1-15.

source/algorithms.tex, source/atomics.tex, source/concepts.tex, source/containers.tex, source/iostreams.tex, source/iterators.tex, source/lib-intro.tex, source/locales.tex, source/numerics.tex, source/ranges.tex, source/regex.tex, source/std.tex, source/strings.tex, source/support.tex, source/threads.tex, source/time.tex, source/utilities.tex
These changes editorially remove the words "could" and "might".
Please review this change carefully with the following goals:
Flag anything that seems even remotely non-editorial, e.g. even if the explanation provided by a Note becomes less useful or (more) misleading.
Also flag anything that could conceivably be worded better by a wider review.
I would like all remaining instances of "could" and "might" to be reviewed by CWG/LWG, so please don't hold back on rejecting anything at this point.
=> Replace "could" and "might", Clauses 16-32.

source/macros.tex
=> [macros] Add "\exposidnc", like \exposid without italic correction

source/declarations.tex, source/statements.tex, source/templates.tex
Fixes #4322
Questions/comments:
* CWG2312 It looks like there's a space after the "e" in "e.mi".  I tried both `\tcode{\exposid{e}.$\tcode{m}_i$}` and `$\tcode{\exposid{e}.m}_i$` with the same results.  Is this space a problem? If so, how to fix?
=> CWG Poll 1: P2238R0 Core Language Working Group "tentatively ready" Issues

source/classes.tex, source/declarations.tex, source/lex.tex, source/preprocessor.tex, source/templates.tex, source/xrefdelta.tex
Fixes #4324
Fixes cplusplus/papers#825
=> CWG Poll 3: P2096R2 Generalized wording for partial specializations

source/lex.tex
Fixes CWG411, CWG1656, and CWG2333.
- Shorten string literal examples by removing the indefinite article.
- Move footnotes from inside character literals table to notes.
Fixes #4325
Fixes cplusplus/papers#760
=> CWG Poll 4: P2029R4 Numeric and universal character escapes in character and string literals

source/basic.tex, source/classes.tex, source/declarations.tex, source/expressions.tex, source/templates.tex
This PR contains the changes I made when I attempted to rebase the Motion-5 branch onto the previous four motions and previous editorial changes.
@burblebee, @jensmaurer, @opensdh : could you kindly review the technical changes here?
=> Rebase Motion 5

source/templates.tex
As requested by @tkoeppe, with the additional movement of "The template parameters of a template…" to follow the movement of "The template argument list of a primary template is…" by #4326.  The first change is written informally as befits a note.
=> Address partial specialization merge conflicts

source/basic.tex, source/classes.tex, source/compatibility.tex, source/concepts.tex, source/declarations.tex, source/exceptions.tex, source/expressions.tex, source/future.tex, source/intro.tex, source/lex.tex, source/modules.tex, source/overloading.tex, source/preprocessor.tex, source/statements.tex, source/templates.tex, source/xrefdelta.tex
Fixes #4326
Fixes cplusplus/papers#533
This is a rebase of #4379, which we retain as-is in order to preserve the comments.
=> Rebased version of CWG Poll 5: P1787R6 Declarations and where to find them

source/algorithms.tex, source/atomics.tex, source/concepts.tex, source/containers.tex, source/future.tex, source/iostreams.tex, source/iterators.tex, source/lib-intro.tex, source/ranges.tex, source/strings.tex, source/support.tex, source/threads.tex, source/utilities.tex
Fixes #4327
Fixes cplusplus/papers#936
Questions/comments on wording:
* LWG2820 Should the xrefs be *after* the new paragraphs?
* LWG3419 FYI, the referenced wording was changed by e5455e3b to replace 'may', addressing ISO/CS 017 (C++20 DIS).
* LWG3265 Fixed by LWG3435.
Could not apply due to wording conflicts:
* LWG3368 Conflicts with wording changed by P2091R0.
Could not apply because wording is for a TS:
* LWG3414 [networking.ts] service_already_exists has no usable constructors
* Note, LWG3443 and LWG3413 apply to TSes also but were explicitly excluded in the motion.
=> LWG Poll 3: P2236R0 Standard Library Ready and Tentatively Ready issues

source/strings.tex, source/support.tex
Fixes #4328 
Fixes cplusplus/papers#457
=> LWG Poll 4: P1679R3 string contains function

source/lib-intro.tex, source/support.tex, source/utilities.tex
- Added some articles as required by the English language.
- Removed [stacktrace.def] subheading to avoid confusion with 'Terms and Definitions' clause.
- Turned a note with 'should' into 'Recommended practice'.
Fixes #4329 
Fixes cplusplus/papers#119
=> LWG Poll 5: P0881R7 A Proposal to add stacktrace library

source/intro.tex, source/iostreams.tex, source/lib-intro.tex
Fixes #4330 
Fixes cplusplus/papers#931
=> LWG Poll 6: P2227R0 Update normative reference to POSIX

source/support.tex, source/utilities.tex
Fixes #4331 
Fixes cplusplus/papers#308
=> LWG Poll 7: P1048R1 A proposal for a type trait to detect scoped enumerations

source/atomics.tex, source/compatibility.tex, source/future.tex, source/lib-intro.tex, source/support.tex
Fixes #4332 
Fixes cplusplus/papers#365
=> LWG Poll 8: P0943R6 Support C atomics in C++

source/atomics.tex
=> [atomics.syn] Move macro definitions to the global namespace.

source/expressions.tex
[expr.type.conv]/2 states that:
> Otherwise, if the type is `cv void` and the initializer is `()` or `{}` [...], the expression is a prvalue of the specified type that performs no initialization.
This is unnecessarily indirect. As per Richard Smith in a [clang bug report](https://bugs.llvm.org/show_bug.cgi?id=48331#c1):
> See [expr.type]p2:
>
> "If a prvalue initially has the type “cv T”, where T is a cv-unqualified non-class, non-array type, the type of the expression is adjusted to T prior to any further analysis."
The specification can be made clearer by changing the reference to "the specified type" to explicit state that the type is void without any semantic impact, and as such is an editorial change.
=> [expr.type.conv] Remove unnecessary indirection of "specified type" when the resulting type will always be unqualified void

source/compatibility.tex
=> [diff.cpp03.temp] 'export' was resurrected for modules.

source/time.tex
The years::rep type could be a signed integer wider than int.
=> [time.cal.year.nonmembers] Avoid narrowing conversion

source/time.tex
The returns specification for `gps_clock::to_utc` says `gps_time` instead of `utc_time`, probably a copy-paste typo from p3. The original proposal, [P0355R7](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0355r7.html), also says `gps_time`, but the intent seems obvious, and the status quo doesn't compile.
=>  [time.clock.gps.members]/2 return type typo

source/atomics.tex, source/basic.tex, source/expressions.tex, source/iostreams.tex, source/overloading.tex, source/statements.tex, source/strings.tex, source/support.tex, source/templates.tex, tools/check.sh
Also add an automated check.
Fixes #4400
=> [std] Move punctuation to before the footnote marker.

source/declarations.tex
The definition of the term was removed by
P1787R6 Declarations and where to find them.
Fixes #4413
=> [dcl.constexpr] Remove use of 'identifier label'.

source/iostreams.tex
You don't call rdbuf() to get to the streambuf, this type is the streambuf.
=> [syncstream.syncbuf.cons] Remove bogus rdbuf() calls

source/classes.tex
=> [class.access.base] Clarify 'direct member' for access checks.

source/locales.tex
Also add two missing periods and remove one instance
of superfluous whitespace.
=> [localization] Reformat LaTeX source code.

source/overloading.tex
the word "can" seems to have been accidentally dropped when applying P1787R6
=> [over.match.conv]: added missing "can"

source/expressions.tex
The comment that a class template specialization is required can be taken as meaning that more is required than the validity of the _template-id_ (which is all that the requirement really checks).
=> [expr.prim.req.type] Clarify example comment re: validity of name only

source/containers.tex, source/iostreams.tex, source/threads.tex
=> [lib] Ensure non-member swap is declared in the header synopsis only

source/concepts.tex
=> [concepts.equality] Turn 'e.g.' into a proper example.

source/overloading.tex
The note in [over.built] uses "hidden" to describe how built-in candidates are removed from consideration; however, this is not hiding in the sense of name lookup. This PR removes the bad terminology and also corrects the note to defer to the normative text regarding the conditions upon user-written candidates that suppress built-in candidates.
=> [over.built] Correct note re: "hiding" to match over.match.oper/3

source/iostreams.tex, source/iterators.tex, source/strings.tex, source/utilities.tex
https://wg21.link/[stringbuf.assign]#5 doesn't use a code block. Is that OK?
=> [lib] Change 'expression inside noexcept' to 'exception specification'

source/utilities.tex
P1614R2 changed the name to 'lexicographical_compare_three_way'.
Supersedes #4473
=> [stacktrace.basic.cmp] Update 'lexicographical_compare_3way'

source/utilities.tex
It was specified as 'see below', pointing nowhere.
Use 'decltype(auto)', congruent with the Effects item.
http://lists.isocpp.org/lib/2021/02/18545.php
=> [format.arg] Fix return type of visit_format_arg

README.rst
`texlive-latexextra` depends on `texlive-core` which now includes `latexmk`.
=> Update Getting Started on Arch Linux

source/statements.tex
Using "contained" in some, but not all cases of decomposing the grammar is inconsistent and not helpful.
Fixes #4468
=> [stmt.pre] Excise undefined term 'contained'

source/declarations.tex
Block-scope externs are in view here, but those are not
block variables, because their target scope is an
enclosing namespace scope.
Fixes #4478
=> [dcl.init.general] Fix misapplied term 'block variable'

source/iostreams.tex, source/locales.tex, source/strings.tex, source/time.tex
Using the elaborated-type-specifier implies that this type
is declared in namespace 'std', which might not be true.
Fixes #4338
=> [lib] Use 'tm', not 'struct tm'

source/containers.tex
This is a first step towards dissolving the container requirements tables. This step is clearly editorial.
=> [container.requirements] Use bulleted lists to introduce identifiers

source/basic.tex, source/expressions.tex, source/lib-intro.tex, source/ranges.tex, source/statements.tex, source/templates.tex
Change all occuances of '){' to ') {'. This was noticed due to the
differences in [bitmask.types].
=> [Editorial] Add whitespace.

source/containers.tex
In this vicinity I also noticed:
- The copy-constructor and assignment-operators for both flavors of `vector` give the rhs argument the name "`x`", which seems a bit silly; it _could_ go unnamed if we wanted.
- `vector<bool>`'s move-constructor is not declared `noexcept`. This was deliberate; I don't really know why, though. [N4258](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4258.pdf) made `vector<T>`'s move-ctor noexcept, and says briefly at the bottom: "No change in vector<bool>" (no rationale).
- The sequence containers and `set` declare constructors taking `initializer_list<T>`, whereas the maps and `unordered_{multi,}set` declare constructors taking `initializer_list<value_type>`. (This is almost entirely consistent with the hypothesis that for simplicity we use `T` …
=> [vector.bool] Remove an extra close-paren.

source/ranges.tex
...so it doesn't appear in the rendered text.
=> [range.iota.iterator,range.iota.sentinel] Fix markup around \libconcept

source/ranges.tex
Tab characters were accidently added in LWG3482 and merged into master as part of 2020-11 LWG Motion 3.
=> [range.drop.view] Fix tabs inserted as part of LWG3482

source/iterators.tex, source/ranges.tex, source/support.tex, source/utilities.tex
These fixes from branch motions-2019-07-lwg-11 were lost in the new branch motions-2019-07-lwg-11-rs.  The 2nd commit in this PR encodes additional but unconventional uses of concept names with \libconcept, but more work may still be needed - see related inline comments in PR #3149.
Update 2/25/21: Most of the changes in the original patch had already been fixed in master since this PR was created.  The rebased branch has been updated to include the few changes that remain in master.
=> Lost changes to P1754R1 (LWG Motion 11)

source/preprocessor.tex
=> [cpp.import] Clarify header units as the source of macro definitions.

source/time.tex
The comparison operators for `leap_second` are all specified as being `constexpr` in [[time.zone.leap.nonmembers]](http://eel.is/c++draft/time.zone.leap.nonmembers), but this specifier is missing in the corresponding section of [[time.syn]](http://eel.is/c++draft/time.syn). Although the current wording matches [P0355R7](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0355r7.html), I think this could qualify as an editorial issue. It's internally inconsistent and the intent seems clear, especially because these functions just call the corresponding `time_point` overrides, which are `constexpr` in both places. I'm happy to submit an LWG issue, however, if you feel differently.
=> [time.syn] add constexpr to leap_second comparisons

source/expressions.tex
Fixes #4505
Fixes cplusplus/papers#938
=> P1102R2 Down with ()!

source/iterators.tex, source/ranges.tex
Fixes #4507
Fixes cplusplus/papers#951
=> P2259R1 Repairing input range adaptors and counted_iterator

source/support.tex, source/utilities.tex
Also fixes LWG3052.
- Introduced new type meta-variable FV_i to handle overfull lines.
Fixes #4509
Fixes cplusplus/papers#873
=> P2162R2 Inheriting from std::variant

source/threads.tex
[thread.req.lockable.general] Use "or" instead of "and" (a lock can't be both
a shared lock and a shared lock).
[thread.req.lockable.shared][thread.req.lockable.shared.timed] Fix punctuation
to be consistent.
Fixes #4510.
Fixes cplusplus/papers#871
Issues/Questions:
*[thread.req.lockable.shared.timed]p2 uses "has not been acquired" while [thread.req.lockable.shared]p2 uses "shall not have been acquired".  I believe these two should use the same wording. Which is correct?
=> LWG Poll 5: P2160R1 Locks lock lockables

tools/check-source.sh
even before a closing }, to improve compatibility
with BSD-based implementations.
=> [check] Terminate sed commands with semicolons

source/ranges.tex
These constraints redundantly repeat the constraints from the template we're partially specializing for. This isn't incorrect, but it is unnecessary, adds opportunities for editorial errors, and is inconsistent with how other partial specializations of templates for constrained types are specified.
EDIT: To be perfectly clear, removing these constraints has no normative effect. One cannot so much as form the template-id `meow<T, U>` if `T` and `U` don't satisfy the constraints of `meow`. So if a partial specialization matches the pattern `meow<T, U>`, we know a priori that the constraints of `meow` are satisfied by `T` and `U`. The only possible results of duplicating the constraints are that an implementation may waste compiletime rechecking them, and WG21 will waste time keeping them in …
=> [ranges.syn] Don't constrain specializations of enable_borrowed_range

source/ranges.tex
=> [range.split.outer] Clarify scope of exposition-only 'current'

source/templates.tex
With modules, 'declared before' no longer makes sense.
Fixes #4479
=> [temp.expl.spec] Use 'reachable from', not 'declared before'

source/algorithms.tex, source/concepts.tex, source/iterators.tex, source/lib-intro.tex, source/ranges.tex, source/support.tex, source/utilities.tex
Resolves #4383.
No visible diff outside the index according to diffpdf.
Remaining question: Should these be dropped?
```
support.tex:\indexlibraryglobal{three_way_comparable}%
support.tex:\indexlibraryglobal{three_way_comparable_with}%
```
=> [lib] Index all uses of public concepts

source/utilities.tex
Unlike `description` and `source_file`, this function does not return a string.
This appears to be a mistake made when [P0881R7](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p0881r7.html) was applied.
=> [stacktrace.entry.query] Fix description of `source_line`

source/declarations.tex, source/expressions.tex
An array element type is constrained by [dcl.array]/4:
> U is called the array element type; this type shall not be a placeholder type ([dcl.spec.auto]), a reference type, a function type, an array of unknown bound, or cv void.
=> [expr.call] [dcl.fct] Move return type requiremens

source/declarations.tex
Group discussion of simple-declaration and
move other kinds of declarations to the end.
Fixes #338
=> [dcl.pre] Reorder paragraphs

source/classes.tex, source/declarations.tex
The definition of "deleted definition" in [dcl.fct.def.delete] is not written in the form of a definition and neither is the definition of "deleted function". Most problematically, these definitions encompass only the syntactic case of explicitly deleting a function but the terms are used where semantic deletedness is meant.
Applying the syntactic interpretation of the definition could lead to the conclusion that the following is ill-formed:
```cpp
struct A { ~A() = delete; };
struct B {
A a;
virtual ~B() = default;
};
struct C : B { virtual ~C() = delete; };
```
This patch changes the definitions to cover semantic deletion.
**Drafting notes:**
- It appears that uses of "deleted definition" in the text is usually refer to physical definitions (but not necessarily to explicit deletions).
- …
=> [dcl.fct.def.delete] Make terms cover semantic deletedness

source/ranges.tex
... to avoid confusion about what it means for a name that is not present to denote a type.
=> [range.split.inner] Clarify paragraph 1

source/utilities.tex
During writing P2351 I noticed missing to_underlying in library index.
=> missing to_underlying in index

source/lex.tex, source/locales.tex, source/preprocessor.tex
The wording refer to the set of whitespaces characters
as "whitespace", white-space" or "white space"
Unify by using "whitespace" consistently.
This doesn't address that we use "whitespace" and "whitespace characacters" inconsistently.
=> Spell "whitespace" consistently

source/basic.tex
The last sentence looks just wrong: the type of the expression doesn't affect the value of the objects.
The second to last sentence doesn't look normative, it looks like a typical implementation strategy description.
Fixes #2308
=> [intro.object]/1 Turn non-normative wording into a Note; remove incorrect wording.

source/ranges.tex
The primary templates tuple_size and tuple_element
are partially specialized, and should be declared
before doing so.
Fixes #4572
=> [ranges.syn] Add primary templates for tuple-like protocol

source/exceptions.tex
CWG1774 clarified that partially-constructed objects may not be of
automatic storage duration. CWG2256 re-introduced that false
claim.
Fixes #4548
=> [except.ctor] Remove false claim about automatic objects

source/lex.tex
I think syntactic construct `string-literal` couldn't be modified, unlike its resulting object.
=> [lex.string] Replace string-literal with a string literal object in a note

source/compatibility.tex, source/containers.tex, source/xrefdelta.tex
This makes the labels consistent.
Fixes #4302
=> [forward.list] Rename stable label from [forwardlist]

source/utilities.tex
While I use both terms — data members and member variables — I don't think "member variable" is a defined term in the Standard.
=> [tuple.elem] Replace "member variables" with "data members"

source/expressions.tex
`static_cast` from `base*` to `derived*` only handles the case where the `base` is a base class subobject of a `derived`, not when `base` is a member subobject. This brings the pointer wording in line with the reference wording:
> If the object of type “cv1 B” is actually a base class subobject of an object of type D, the result refers to the enclosing object of type D.
=> [expr.static.cast] static_cast of pointer to derived class only handles base class subobjects

source/numerics.tex
The `e()` mod 2<sup>32</sup> operation is a no-op, because `e.max()` < 2<sup>32</sup>.
When I raised this on the LWG reflector @CaseyCarter agreed that this is the case. We should simplify the spec by removing the noise.
=> [rand.eng.sub] drop no-op modulo operation

source/expressions.tex
The previous names 'cv-combined' and 'cv-decomposition' are
no longer adequate since a qualification conversion can now
convert to an array of unknown bounds.
Fixes #3088
=> [expr] Use 'qualification-combined' and 'qualification-decomposition'.

source/time.tex
=> [time.clock.cast.sys],[time.clock.cast.utc] Use Duration2 for clarity.

source/expressions.tex
=> [expr.await] Clarify rethrowing exceptions from await-suspend

source/declarations.tex
Do not claim that a designated-initializer-list or
an initializer-list is an initializer list.
Fixes #4571
=> [dcl.init.aggr] An initializer list is brace-enclosed

source/declarations.tex
Highlight 'innermost enclosing' namespace, and remove
unneeded mechanism of inserting a using-directive.
Fixes #4556
=> [namespace.def.general] Clarify inline namespaces

source/ranges.tex
We need at least one element in the initializer list to actually have a type in order for deduction to work.
Examples 2 and 3 are also broken for other reasons, but those will be addressed via an LWG issue.
=> [range.elements.overview] Correct example

source/ranges.tex
=> [ranges] Rename 'not-same-as' to 'different-from'.

source/expressions.tex
A local entity is not any entity that is local, so add
cross-references for clarification.
http://lists.isocpp.org/core/2021/06/11071.php
=> [expr] Add cross-references for 'local entity'.

source/basic.tex, source/classes.tex, source/declarations.tex, source/expressions.tex, source/overloading.tex
Fixes #4631 
Fixes #4612
Partially addresses #3262
=> P2386R0 Core Language Working Group "ready" Issues for the June, 2021 meeting

source/back.tex, source/compatibility.tex, source/intro.tex, source/lex.tex, source/std.tex, source/uax31.tex
Fixes  #4634
Fixes cplusplus/papers#688
=> P1949R7 C++ Identifier Syntax using Unicode Standard Annex 31

source/declarations.tex
Also fixes CWG1914.
Fixes #4635
Fixes cplusplus/papers#864
=> P2156R1 Allow Duplicate Attributes

source/lex.tex
Fixes  #4637
Fixes cplusplus/papers#925
=> P2223R2 Trimming whitespaces before line splicing

source/classes.tex, source/expressions.tex
Fixes #4638
Fixes cplusplus/papers#600
=> P1847R4 Make declaration order layout mandated

source/algorithms.tex, source/containers.tex, source/iostreams.tex, source/iterators.tex, source/lib-intro.tex, source/numerics.tex, source/ranges.tex, source/strings.tex, source/time.tex, source/utilities.tex, source/xrefdelta.tex
Fixes #4640
Fixes #1793
Fixes #4221
=> P2385R0 C++ Standard Library Issues to be moved in Virtual Plenary, June 2021

source/containers.tex
Fixes #4645
Fixes cplusplus/papers#381
=> P1518R2 Stop overconstraining allocators in container deduction guides

source/algorithms.tex, source/support.tex
Fixes #4647
Fixes cplusplus/papers#442
=> P1659R3 starts_with and ends_with

source/strings.tex
Fixes #4649
Fixes cplusplus/papers#714
=> P1989R2 Range constructor for std::string_view 2: Constrain Harder

source/support.tex, source/utilities.tex
Also fixes LWG2690.
Fixes #4650
Fixes cplusplus/papers#851
=> P2136R3 invoke_r

source/support.tex, source/utilities.tex
Fixes  #4652
Fixes cplusplus/papers#933
=> P2231R1 Missing constexpr in std::optional and std::variant

source/compatibility.tex, source/support.tex, source/utilities.tex
- Avoid redundantly presenting the definition of basic-format-string
in the header synopsis.
- Do not italicize basic-format-string's private exposition-only member,
consistent with similar situations.
Fixes #4653
Fixes cplusplus/papers#919
=> P2216R3 std::format improvements

source/lib-intro.tex, source/ranges.tex
Also fixes LWG3509 and LWG3510.
Fixes #4654
Fixes cplusplus/papers#974
=> P2281R1 Clarifying range adaptor objects

source/ranges.tex
Also fixes LWG3524.
Fixes #4658
Fixes cplusplus/papers#1042
=> P2367R0 Remove misuses of list-initialization from Clause 24

source/ranges.tex
During reflector discussion of [LWG3563](https://wg21.link/LWG3563), LWG expressed a preference for examples to use the `views::meow` objects whenever applicable, instead of `meow_view`s directly.
=> [ranges] Use views::meow in examples instead of meow_view

source/expressions.tex
Here's the entry being redirected to:
https://github.com/cplusplus/draft/blob/fb3bea889899c5ea5c0f70b12fc72129f7d1692a/source/expressions.tex#L552
=> [conv.general] Fix index redirect for contextual conversion to bool.

source/ranges.tex
This is consistent with the typo fixes for ranges::size done in
aa9c660a835540117123617a13b0ba1ab6dd801e as part of #3752.
=> [range.prim.data] Use ranges::begin(t) not ranges::begin(E)

source/utilities.tex
Fixes occurrences noted in #4680
=> [format.syn] Remove extraneous commas in vformat_to declarations

source/basic.tex
This clarifies and centralizes the definition and
also avoids the undefined term 'local variable'.
Fixes #4567
=> [basic.stc.static] Rephrase the definition of 'static storage duration'

source/strings.tex
There is no reason to declare a deleted function constexpr.
=> [basic.string.general], [string.view.template.general] remove constexpr

source/basic.tex
It is unclear why having pointers to `T` is a precondition, since it doesn't seem that these pointers are used normatively.
Not sure should I write «For any distinct objects», «For two distinct objects» or «For any two distinct objects».
=> [basic.types.general] Do not mention pointers

source/ranges.tex
With the adoption of P1989, string_view is constructible from
subrange, we can use that to provide a good example of
string splitting.
=> Better string splitting example

source/declarations.tex
This changes "These declarations" to "The declarations above" inn example so it's clear which declarations we're talking about.
=> [dcl.fct] Clarify which declarations we're talking about in example.

source/declarations.tex
=> [dcl.type.auto.deduct] Clarify initializer for placeholder type deduction.

source/iterators.tex
It was previously not explicitly stated that input iterators would
actually be incremented (which invalidates copies). The new wording is
more explicit about how the distance is measured, and in doing so
calls out more explicitly that input iterators are indeed incremented.
Fixes #2807.
Fixes #2813.
This is an alternative approach to #2813, as suggested by @jensmaurer in the comments.
@jwakely, @CaseyCarter, I'd welcome your review on this!
=> [iterator.operations, range.iter.op.distance] Reword "get to".

source/utilities.tex
=> [format] Use \exposid{,nc} for format-arg-store, not \placeholder

source/declarations.tex
The [current note](http://eel.is/c++draft/dcl.dcl#dcl.pre-12.note-1) on *nodeclspec-function-declarations* is a little lacking when it comes to providing useful information as to why the outlined restriction exists. This clarifies it.
=> [dcl.dcl] Improve note regarding nodeclspec-function-declarations

source/concepts.tex, source/iterators.tex
Or
> [concept.booleantestable,reverse.iter.elem,common.iter.nav] Remove space between `requires` and parameter list
=> [lib] Remove space between `requires` and parameter list

source/ranges.tex
=> [range.split.iterator] Fix formatting of the 'Effects' clause

source/expressions.tex
and clarify ambiguous antecedent for 'its'.
Fixes #4746
=> [expr.delete] Replace 'denote' with 'pointed to'

source/ranges.tex
Based on empirical evidence, the existing wording is too subtle, so this adds a note to make the implication more obvious.
=> [range.nonprop.cache] Clarify that emplace-deref does not require materialization of the result of *i before the initialization

source/utilities.tex
The definition of 'common initial sequence' in [class.mem] only applies
to standard-layout struct types, which excludes unions. There is no
reason to define is_corresponding_member in terms of standard-layout
types (which includes unions and scalars and arrays of such types) when
the common initial sequence is only meaningful for standard-layout
structs.
=> [meta.member] Clarify is_corresponding_member semantics

source/atomics.tex, source/basic.tex, source/classes.tex, source/compatibility.tex, source/declarations.tex, source/iostreams.tex, source/strings.tex, source/support.tex, source/utilities.tex
The former includes names introduced by alias-declarations,
the latter (arguably) does not.
Fixes #4401
=> [std] Use grammar typedef-name instead of 'typedef name'.

source/numerics.tex
=> [cmath.syn] Add 'lerp' to list of differences vs. C

source/iostreams.tex
Also remove ill-formed default template arguments in the definition
of sentry and spell out the return type of arithmetic inserters and
extractors.
=> [iostream.format] Use the injected-class-name throughout

source/support.tex
=> [coroutine.handle.export.import] Add missing space after _cv_

source/utilities.tex
Duplicate declaration of `sp1`. Change it to `sp2` just as that in example 1 above.
=> [forward] Fix typo in example 2 in paragraph 6

source/basic.tex, source/classes.tex, source/expressions.tex, source/iterators.tex, source/modules.tex, source/numerics.tex, source/templates.tex, source/threads.tex, tools/check-source.sh
Also add an automated check.
(No visual diff in the resulting PDF.)
=> [std] Replace vestigial parenthesized \ref with \iref

source/strings.tex
Use constexpr and an explicit conversion to size_type,
for consistency with basic_string_view.
Requested by http://lists.isocpp.org/lib-ext/2021/09/19813.php
=> [basic.string.general] Fix basic_string::npos

.github/workflows/check.yml
because Ubuntu 20.04 can otherwise no longer install ghostscript,
which is needed for LaTeX.
=> [actions] Update dependencies cache before installing

source/intro.tex
This is similar to #3192,
but recognizes that the sibling subclause
should be the destination of the reference,
which covers
conditionally-supported constructs and
locale-specific characteristics.
=> [intro.abstract] Reference the sibling subclause

source/basic.tex
All these references are for terms defined in the subclause.
=> [basic] Reference [basic.types.general] where appropriate

source/declarations.tex
"The placeholder type" gives the wrong impression that we're talking about the case from the previous paragraph. We're not; this is parallel to the previous paragraph so should use parallel wording.
=> [dcl.spec.auto.general] The placeholder type -> A placeholder type

source/declarations.tex
Is [dcl.init.general] p7 really supposed to be all one paragraph, with bullet numbers continuing between two separate lists, or should there be a `\pnum` after each list? Or just after the first list, giving two paragraphs?
=> [dcl.init.general] break p7 into three paragraphs

source/basic.tex
=> [conv.rank] Avoid hinting that 'bool' be a standard integer type.

source/expressions.tex
=> [expr.typeid] Require class type to be complete

source/iostreams.tex
"are only be provided" is not a valid english verb phrase. I'm not sure if the intent was "are only provided" or "are only to be provided", but I think the first more closely adheres to our style of making existential statements about library implementations.
=> [fstream.syn] Fix grammar

source/declarations.tex
=> [dcl.init.aggr] Insert paragraph break to avoid bad \item numbering

source/classes.tex
Those do not have a (grammatical) mem-initializer-list,
yet they ignore default member initializers.
Fixes #4916
=> [class.base.init] Clarify implicitly-defined copy/move constructors

source/statements.tex
They necessarily have automatic storage duration.
Fixes #4741
=> [stmt.dcl] Clarify 'active' variables

source/declarations.tex
when the properties of the expression are still relevant.
Fixes #4753
=> [dcl.init.ref] Avoid 'value of the expression'

source/expressions.tex
Also move the relevant text to after the syntactic constraints.
Fixes #4752.
=> [expr.new] Clarify result type and value category

source/algorithms.tex, source/utilities.tex
to 'nothrow-', for consistency with nothrow_constructible
Fixes #4101
=> [lib] Rename exposition-only 'no-throw-' concepts

source/classes.tex, source/compatibility.tex, source/declarations.tex, source/expressions.tex, source/overloading.tex, source/statements.tex
No visual diff, except for (intentional) additional index entries.
=> [std] Use \keyword for coroutine keywords

source/utilities.tex
and remove superfluous std:: qualification.
Fixes #4948
=> [tuple.apply] Move exposition-only functions to namespace std

source/expressions.tex
The semicolon is missing from the 'struct' definition, add it.
=> Add trailing semicolon to the example in expr.prim.id.general p5

source/declarations.tex, source/expressions.tex, source/preprocessor.tex
Fixes #4963
Fixes cplusplus/papers#941
=> P2242R3  Non-literal variables (and labels and gotos) in constexpr functions

source/basic.tex, source/classes.tex, source/declarations.tex, source/expressions.tex, source/overloading.tex, source/preprocessor.tex, source/templates.tex
Fixes  #4964
Fixes cplusplus/papers#115
=> P0847R7 Deducing this

source/preprocessor.tex
Fixes #4965
Fixes cplusplus/papers#1000
=> P2316R2 Consistent character literal encoding

source/compatibility.tex, source/expressions.tex, source/future.tex, source/overloading.tex, source/preprocessor.tex, source/xrefdelta.tex
Fixes #4970
Fixes cplusplus/papers#845
=> P2128R6 Multidimensional subscript operator

source/basic.tex, source/compatibility.tex, source/expressions.tex, source/intro.tex, source/iostreams.tex, source/lex.tex, source/lib-intro.tex, source/locales.tex, source/preprocessor.tex, source/time.tex
Fixes #4971
Fixes cplusplus/papers#998
=> P2314R4 Character sets and encodings

source/declarations.tex, source/expressions.tex, source/ranges.tex, source/threads.tex
Fixes #4979
Fixes cplusplus/papers#293
=> P0849R8 auto(x): decay-copy in the language

source/iostreams.tex
Moved to [ostream.inserters.arithmetic] and renamed the parameter
from 'val' to 'p' for consistency with the 'const void*' overload.
Fixes #4981
Fixes cplusplus/papers#320
=> P1147R1 Printing volatile Pointers

source/iterators.tex
Every other place (including the itemdecl for these overloads) uses `Iterator` directly.
=> [move.iterator] Use the template parameter directly in declaration of base()

source/declarations.tex, source/expressions.tex
Fixes #4745.
See #5015 for discussion and suggestions.
=> [expr.type.conv] Move description of 'auto' deduction to [dcl.type.auto.deduct]

source/lib-intro.tex
It does not make sense to attempt to qualify class members
with a nested-name-specifier consisting of namespace-names.
Fixes #1793.
=> [contents,fs.req.namespace] Qualify only namespace-scope names LWG2818

source/lex.tex, source/macros.tex, source/strings.tex, source/uax31.tex, source/utilities.tex, tools/check-source.sh
Fixes #5032
The presentation of Unicode character names is ... hurting the eye. Using \textsc improves the situation:
Before:
After:
We could also consider using fixed-width font for the "U+nnnn" part, but maybe it is better to limit fixed-width font to C++-level things, which "U+nnnn" most definitely is not.
@tkoeppe, I'd appreciate your opinion here.
=> [lex] Use \textsc for Unicode character names

source/algorithms.tex, source/numerics.tex, tools/check-source.sh
and augment the automatic checks to flag literal 'ISO C'.
=> [alg.c.library,c.math.fpclass,cmath.syn] Use \xrefc macro

source/utilities.tex
=> [smartptr] Rework subclause nesting

source/declarations.tex
=> [dcl.typedef] Add explanation for lookup failure in example

source/iostreams.tex, source/xrefdelta.tex
=> [input.output] Fix headings of 'assign and swap' subclauses

source/basic.tex, source/classes.tex, source/compatibility.tex, source/declarations.tex, source/expressions.tex, source/lex.tex, source/lib-intro.tex, source/overloading.tex, source/templates.tex
In contrast to errors, which use a colon, an OK comment
is not followed by any unique reason why the code is
well-formed, but by a subjective highlighting of a fact.
=> [std] Replace 'OK:' in code comments with 'OK,'

source/atomics.tex, tools/check-source.sh
and augment the autmatic checks accordingly.
=> [stdatomic.h.syn] Fix missing \expos

source/locales.tex
We introduce POSIX as an alias for ISO/IEC 9945, and we use 'POSIX'
everywhere else.
=> [locale.time.get] Replace 'ISO/IEC 9945' with 'POSIX'

source/expressions.tex, source/intro.tex
```c++
struct S { int i; } s;
auto u = (unsigned&)s; // accesses s, which is an object of class type
```
So the Notes are not accurate enough.
=> [defns.access] [basic.lval] Clarify what and how can be accessed

source/strings.tex
=> [c.mb.wcs] mbrtoc8 stores code units, not characters

source/utilities.tex
LWG3539 has the following resolution
template<class Out, class... Args>
Out format_to(Out out, string_view fmt, const Args&... args);
template<class Out, class... Args>
Out format_to(Out out, wstring_view fmt, const Args&... args);
-8- Effects: Equivalent to:
using context = basic_format_context<Out, decltype(fmt)::value_type>;
return vformat_to(<add>std::move(</add>out<add>)</add>, fmt, make_format_args<context>(args...));
template<class Out, class... Args>
Out format_to(Out out, const locale& loc, string_view fmt, const Args&... args);
template<class Out, class... Args>
Out format_to(Out out, const locale& loc, wstring_view fmt, const Args&... args);
-9- Effects: Equivalent to:
using context = basic_format_context<Out, decltype(fmt)::value_type>;
return …
=> Fixes misapplied resolution of LWG3539

source/utilities.tex
which is an undefined term.
Fixes #5034
=> [func.wrap.func.general,func.wrap.move.class] Remove 'first-class' object

source/basic.tex
If "to end the program" is merely describing what `std::exit` does, it's redundant; if it is read as expressing purpose or intent, it's incorrect - whether a program has UB cannot depend on the programmer's intent.
=> [basic.start.main] remove redundant phrase

source/containers.tex
=> [associative.reqmts.general] Fix typo: 'kx', not 'rx'

source/declarations.tex, source/ranges.tex
Also introduce a label 'term.array.type' in [dcl.array}.
Fixes #5146
=> [range.access] Fix cross-references for 'array'

source/future.tex, source/utilities.tex
LWG3170 deprecated `allocator::is_always_equal`. We moved it to Annex D, but left this index entry behind.
=> [depr.default.allocator] Index allocator::is_always_equal here

source/regex.tex, source/utilities.tex
=> Avoid "compiler"

source/utilities.tex
Pointer to member has no function call expression (only pointer to member expression has). `call_args` should mean the args passed to the call wrapper.
=> [func.memfn] Correct target object by fixing typo

source/classes.tex, source/expressions.tex, source/templates.tex, tools/check-output.sh
Also adds a check. This essentially flags typos inside `\grammarterm`.
=> [std] Fix bad \grammarterms

source/time.tex
=> [chrono.syn] Use nested namespace definitions for clarity

source/exceptions.tex
=> [except.throw,except.handle] Move lvalue specification for copies

source/utilities.tex
=> [meta.rel] Avoid undefined term 'void types'

source/classes.tex
Initialization is fully specified in [dcl.init],
so turn the list of default-initialization cases
into a note and shorten it appropriately.
Fixes #4019
=> [class.default.ctor] Fix sloppy wording.

source/classes.tex, source/statements.tex
Highlight that constructors and destructors do not have a
return type and thus a return statement within a constructor
or destructor cannot have an operand.
Supersedes #3647
=> [stmt.return,class.{ctor,dtor}] Clarify no return operand

source/templates.tex
The wording at [temp.param]/15 says:
> A template-parameter shall not be given default arguments by two
> different declarations if one is reachable from the other.
But it is conflicted with [basic.def.odr]/13:
> There can be more than one definition of a
> ...
> 	default template argument
> ...
> in a program provided that each definition appears in a different
> translation unit and the definitions satisfy the [same-meaning
> criteria of the ODR].
[temp.param] should be deleted otherwise we couldn't modularize a real
project. 
Here is an reduced example:
```C++
// templ.h
template<class T = int> class X{}
// foo.cppm
module;
#include "templ.h"
export module foo;
// decls to make 'X' not discard.
//bar.cpp
import foo;
#include "templ.h"
```
The example above here should be able to be …
=> [temp.param] Delete outdated wording at p15

source/compatibility.tex
Also annotate the 'void' and 'int' keywords.
Partially addresses #3908.
=> [diff.stmt] Properly refer to function return types

source/atomics.tex
This should refer to the shared_ptr subclause, not its parent.
=> [util.smartptr.atomic.general] Fix xref

source/basic.tex, source/classes.tex
=> Move [class.free]

source/classes.tex
=> [class.mem.general] Add cross-reference for 'layout-compatible type'

source/statements.tex
=> [stmt.return] Clarify flowing off the end of a function

source/containers.tex, source/diagnostics.tex, source/lib-intro.tex, source/macros.tex, source/regex.tex, source/strings.tex
We've wanted to get rid of the huge requirement tables since ages. Here's a specific suggestion, converting [re.req] as a guinea pig. Note that this is a fairly mechanical conversion, avoiding larger rephrasing.
Fixes #120.
Fixes #4785
Partially addresses #1571.
=> Dismantle requirements table in [re.req] and [container.requirements]

source/declarations.tex, source/expressions.tex
Fixes #5258
Fixes cplusplus/papers#882
=> P2173R1 Attributes on lambda-expressions

source/atomics.tex, source/containers.tex, source/diagnostics.tex, source/iostreams.tex, source/iterators.tex, source/ranges.tex, source/strings.tex, source/support.tex, source/utilities.tex
=> P2531R0 C++ Standard Library Issues

source/lib-intro.tex, source/support.tex, source/utilities.tex
- Introduce "General" subclauses to avoid hanging paragraphs.
- Introduce "Returns: *this" to avoid duplication.
Fixes #5261 
Fixes cplusplus/papers#254
=> P0323R12 std::expected

source/expressions.tex, source/intro.tex, source/lib-intro.tex, source/numerics.tex, source/support.tex
Fixes #5262 
Fixes cplusplus/papers#104
=> P0533R9 constexpr for <cmath> and <cstdlib>

source/containers.tex, source/ranges.tex, source/strings.tex, source/support.tex
- Fix misnamed constructor in [multiset.cons]
- Fix garbled constructor in [stack,defn]
- Fix bad pack expansion "std::forward<Args...>(args)..."
Fixes #5264
Fixes cplusplus/papers#145
=> P1206R7 Conversions from ranges to containers

source/future.tex, source/utilities.tex
- Replace 'shall be' with 'is'.
Fixes #5265
Fixes cplusplus/papers#197
=> P1413R3 Deprecate std::aligned_storage and std::aligned_union

source/support.tex, source/utilities.tex
Fixes #5266
Fixes cplusplus/papers#949
=> P2255R2 A type trait to detect reference binding to temporary

source/support.tex, source/utilities.tex
- Fix position of 'constexpr' operator<=>(nullptr_t)
Fixes #5267
Fixes cplusplus/papers#961
=> P2273R3 Making std::unique_ptr constexpr

source/ranges.tex, source/support.tex, source/utilities.tex, source/xrefdelta.tex
Fixes  #5268
Fixes cplusplus/papers#1060
=> P2387R3 Pipe support for user-defined range adaptors

source/algorithms.tex, source/support.tex
Fixes #5269
Fixes cplusplus/papers#1106
=> P2440R1 ranges::iota, ranges::shift_left, and ranges::shift_right

source/ranges.tex, source/support.tex
- Fix return type in description of chunk_view::inner-iterator::operator++.
Fixes #5271
Fixes cplusplus/papers#1108
=> P2442R1 Windowing range adaptors: views::chunk and views::slide

source/ranges.tex, source/support.tex
Fixes #5272
Fixes cplusplus/papers#1109
=> P2443R1 views::chunk_by

source/containers.tex, source/iostreams.tex, source/numerics.tex, source/ranges.tex, source/strings.tex, source/utilities.tex, tools/check-source.sh
Also fix the ineffective check script by rewriting the
check in straightforward awk.
=> [lib] Add missing \pnum before descriptive elements

source/modules.tex
Although we could infer the declaration should refer to 'exported declaration' from the context in the previous paragraph, they are two paragraphs and split by a relatively long example. So I am confused at the first sight. I think it would be helpful to add the adjective.
=> [module.interface] Add adjective 'exported' to dangling prons

source/ranges.tex
=> [range.slide.iterator] Remove `@` in `\tcode`

source/templates.tex
Situations in the Note are not examples for the last list bullet exclusively (e.g. the first situation is an example for the next to the last normative bullet)
=> [temp.res] Move a note outside itemize environment

source/lib-intro.tex
Also switch footnote to note.
Partially addresses #5240
=> [derivation] Remove 'basic integral type' from footnote

source/compatibility.tex
Also annotate the 'void' keyword.
Partially addresses #3908.
=> [diff.expr] Replace 'will' with present tense

source/ranges.tex, source/utilities.tex
and 'term.simple.call.wrapper' and refer to them.
@languagelawyer , what do you think?
=> [func.require] Introduce labels 'term.perfect.forwarding.call.wrapper'

source/atomics.tex, source/basic.tex, source/classes.tex, source/concepts.tex, source/containers.tex, source/declarations.tex, source/expressions.tex, source/lib-intro.tex, source/numerics.tex, source/strings.tex, source/templates.tex, source/utilities.tex
For ease of review, these are all separate commits.
Feel free to squash on merge.
Fixes #4630
=> Introduce term.* labels for [basic.types.general] terms

source/support.tex
`std::priority_queue` is defined in `<queue>`.
The "Feature test macros" section in [P1206R7 Conversions from ranges to containers](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1206r7.pdf) does say that the macro `__cpp_lib_containers_ranges` is present in `<priority_queue>`, but I guess it's an error rather than a proposal to add this header.
=> [version.syn] Remove mention of nonexistent header `<priority_queue>`

source/utilities.tex
The description was confusing objects and types.
Fixes #518
=> [allocator.adaptor.members] Fix select_on_container_copy_construction

source/threads.tex
Missed update with commit d74c2170a9f4c928519461d7742293af2d141852.
See #5313
=> [thread] Rename to 'Concurrency support library'

source/macros.tex
=> [macros] Use math font for ranges

source/ranges.tex
=> [range.chunk.outer.value] Fix unformatted dereference operator

source/ranges.tex
Also, I strongly doubt that this should be a `constexpr` function, if so I'd be happy to add an LWG (if that can't be as an edit fixed) for it.
=> [range.utility.conv.general] Add missing template parameter to container_inserter

source/iostreams.tex
=> [span.streams] Move non-member swaps to header synopsis

source/algorithms.tex
=> [alg.min.max] Consistently specify `ranges::minmax_element` with `ranges::minmax_element_result`

source/diagnostics.tex
LWG3330 added #include <compare> to all header files
where a three-way comparison operator was declared,
but missed this one.
Fixes #5373
=> [stacktrace.syn] Add '#include <compare>'

source/lib-intro.tex
Requirements for some member types in [allocator.requirements.general] are specified with `typename`, but the following are currently not:
- `X::propagate_on_container_copy_assignment`
- `X::propagate_on_container_move_assignment`
- `X::propagate_on_container_swap`
- `X::is_always_equal`
=> [allocator.requirements.general] Specify all member types with `typename`

source/future.tex
=> [depr.tuple],[depr.variant] Use struct class-key consistently

source/expressions.tex
=> [expr.prim.lambda.general] Clarify deduced lambda return type

source/ranges.tex
Currently `<ranges>` has two formats for the description of print messages, one is
`// prints: 1 2 3 4 5 6 7 8 9`
The other is
`// prints \tcode{1 2 3 4 5 6 7 8 9}
`
This pull request converts all the first form to the second form, that is, omits the colon after `prints`, and then outputs the message in code format.
It also fixes incorrect formatting of `The above prints:` in [[range.join.with.overview]](https://timsong-cpp.github.io/cppwp/range.join.with.overview)[[range.chunk.overview]](https://timsong-cpp.github.io/cppwp/range.chunk.overview), [[range.chunk.by.overview]](https://timsong-cpp.github.io/cppwp/range.chunk.by.overview).
=> [range.adaptors] Make the prints message format consistent

source/utilities.tex
Some minor improvements to the `std::unexpected` spec.
This is the TOC before:
And after:
In the second image every "Class template foo" under 22.8 is at the same level, without the pointless "Unexpected objects" subclause, and without two "General" subclauses for one simple class template.
The other commit just reorders the `std::unexpected` synopsis to match the order of the detailed descriptions, and the order of corresponding constructors in the `std::expected` and `std::expected<cv void, E>` synopses and details descriptions.
=> [expected.unexpected] Rearrange std::unexpected

source/ranges.tex
Just an unnecessary semicolon after a function definition ostensibly at namespace scope.
=> [range.utility.conv.general] Strike extraneous semicolon

source/lex.tex
Correct "apostrohpe" to "apostrophe".
Fixes #5410
=> Fix the typo for "apostrohpe"

source/utilities.tex
In [[expected.object.general]](https://timsong-cpp.github.io/cppwp/expected.object.general), the function is defined as
`constexpr const E& error() const &;`
However in [[expected.object.obs]](https://timsong-cpp.github.io/cppwp/expected.object.obs), it is defined as
`constexpr const E& error() const & noexcept;`
So let me assume it's just that the author of the paper forgot to add `noexcept`.
=> [expected.object.general] Add missing noexcept for expected::error()

source/iterators.tex
There is a note in this section
> The expression *i is indirectly required to be valid via the exposition-only dereferenceable concept
This makes sense before P1878R1. But after P1878R1, the expression `*i`
is "directly" required in the requires clause. So this note is no longer
valid.
The change that adds `*i` in the require clause is here
https://github.com/cplusplus/draft/commit/333b6eb8c147fce1a9ddcd905ee3bb1a09b91e30#diff-0043c904d3e034a77b44feeddf18719e63e646d55db1c564f2a5defe7330c9eaR1213
=> [iterator.concept.readable] remove obsolete Note

source/numerics.tex
=> [cons.slice] Add copy constructor for 'slice' to synopsis

source/overloading.tex
=> [over.match.best.general] Fix typo in example

source/ranges.tex
This is the follow up of [pull/5333](https://github.com/cplusplus/draft/pull/5333), and I think the authors agree that the missing `constexpr` is not intended, it's more like a bug in the paper.
=> [range.utility.conv.general] Add missing constexpr for container-inserter

source/ranges.tex
I think this is a reasonable simplification and also makes it consistent with `end()`.
=> [range.join.view] Simplify `range_reference_t<V>` to `InnerRng`

source/utilities.tex
.... as is conventional in library wording.
=> [expected.object.ctor] Use the injected class name to refer to the current instantiation

source/ranges.tex
This is a follow-up of #5498, which removes redundant `// exposition only` comment in the `{itemdecl}` section of `join_view​::​iterator::satisfy`, `split_view::find-next`, and `elements_view​::​iterator::get-element`.
=> [ranges] Remove redundant `// exposition only` comments in itemdecl section

source/utilities.tex
See https://eel.is/c++draft/tuple#cnstr-15.sentence-2.
=> [tuple.cnstr] Remove bad escaping in codeblock

source/containers.tex
This makes this consistent with the rest of [[containers]](https://eel.is/c++draft/containers) since we are not under the `ranges` namespace.
=> [sequence.reqmts] Add `ranges` namespace qualifier for `range` concept

source/ranges.tex
In [[ranges.syn]](https://eel.is/c++draft/ranges.syn), only the template list of `take_view` has no name, so I added it for consistency.
=> [range.take.overview]  Correct punctuation for `take_view` overview

source/ranges.tex
which is consistent with other examples.
=> [range.join.with.overview, range.split.overview] use fully-qualified name

source/lex.tex
Fixes #5571
Fixes cplusplus/papers#1036
=> P2362R3 Remove non-encodable wide character literals and multicharacter wide character literals

source/classes.tex, source/declarations.tex, source/preprocessor.tex
Fixes #5574
Fixes cplusplus/papers#1119
=> P2448R2 Relaxing some constexpr restrictions

source/lex.tex, source/preprocessor.tex
Fixes  #5576
Fixes cplusplus/papers#798
=> P2071R2 Named universal character escapes

source/expressions.tex
Fixes #5578
Fixes cplusplus/papers#973
=> P2280R4 Using unknown pointers and references in constant expressions

source/back.tex, source/basic.tex, source/declarations.tex, source/expressions.tex, source/intro.tex, source/iostreams.tex, source/lex.tex, source/lib-intro.tex, source/numerics.tex, source/overloading.tex, source/preprocessor.tex, source/support.tex, source/threads.tex, source/utilities.tex, source/xrefdelta.tex
Fixes #5579
Fixes cplusplus/papers#227
=> P1467R9 Extended floating-point types and standard names

source/declarations.tex, source/expressions.tex
Fixes #5582
Fixes cplusplus/papers#529
=> P1774R8 Portable assumptions

source/algorithms.tex, source/containers.tex, source/future.tex, source/iostreams.tex, source/iterators.tex, source/lib-intro.tex, source/memory.tex, source/ranges.tex, source/regex.tex, source/strings.tex, source/threads.tex, source/utilities.tex, source/xrefdelta.tex
Fixes #5588
Fixes cplusplus/papers#1281
=> [2022-07 LWG Motion 1] P2618R0 C++ Standard Library Issues

source/containers.tex, source/lib-intro.tex, source/support.tex
- Rephrase "may" in notes
Fixes #5589
Fixes cplusplus/papers#96
=> P0009R18 mdspan

source/containers.tex, source/lib-intro.tex, source/support.tex
- Replaced "may" with "can" in notes.
- Replace && in constraints with prose "and" to avoid overfull \hbox
Fixes #5593 
Fixes cplusplus/papers#101
=> P0429R9 A Standard flat_map

source/algorithms.tex, source/support.tex
Fixes #5595
Fixes cplusplus/papers#149
=> P1223R5 find_last

source/containers.tex, source/ranges.tex, source/support.tex, source/utilities.tex
Fixes #5599
The 2nd part of this (replacing all usages of tuple-or-pair by tuple in the range clause) should be applied after P2374R4 #5605 as per the Editor's note at end of P2165R4.
=> P2165R4 Compatibility between tuple and tuple-like objects

source/containers.tex, source/support.tex, source/utilities.tex
Fixes #5601
The paper adds examples which contain non-ascii characters.  I wasn't able to figure out how to add these examples and needed to delete them in order to fix the build.
=> P2286R8 Formatting Ranges

source/algorithms.tex, source/support.tex
Fixes #5604
Fixes cplusplus/papers#1004
=> P2322R6 ranges::fold

source/compatibility.tex, source/concepts.tex, source/support.tex
Fixes #5607
Fixes cplusplus/papers#1074
=> P2404R3 Move-only types for equality_comparable_with, totally_ordered_with, and three_way_comparable_with

source/algorithms.tex, source/regex.tex, source/support.tex
Fixes #5608
Fixes cplusplus/papers#1078
=> P2408R5 Ranges iterators as inputs to non-Ranges algorithms

source/time.tex
Fixes #5610
Fixes cplusplus/papers#1093
=> P2419R2 Clarify handling of encodings in localized formatting of chrono types
