cplusplus/draft

source/algorithms.tex
source/utilities.tex

Also fixes NB GB 315 and NB GB 316.
Fixes #3725 .
Fixes cplusplus/nbballot#311.
Fixes cplusplus/nbballot#312.
Open issues:
- Changes contingent on D1243R4 not applied (for_each_n_result).

LWG Poll 23: P2106R0 Alternative wording for GB315 and GB316

---

source/containers.tex
source/future.tex
source/utilities.tex

Also fixes LWG3212.
Fixes #3727.

LWG Poll 25: P2116R0 Remove tuple-like protocol support from fixed-extent span

---

source/ranges.tex

Also fixes NB DE 269 (C++20 CD).
Fixes #3728.
Fixes cplusplus/papers#703.
Fixes cplusplus/nbballot#265.

LWG Poll 26: P1970R2 Consistency for size() functions: Add ranges::ssize

---

source/basic.tex

Improvements inspired by a comment from @hubert-reinterpretcast on #3782.

Fixes for 2020-02 CWG Poll 1

---

source/classes.tex
source/expressions.tex
source/numerics.tex

A few tiny changes in case they're wanted right away.

Cross-reference fixes

---

source/basic.tex

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cplusplus/draft/3669)

[basic.pre] Improve consistency in list

---

source/overloading.tex

[over.oper] Clarify handling of individual operators.

---

source/algorithms.tex

Missed edits from application of P1878R1 (2019-11 LWG Motion 9).

[algorithms] Rename concept 'writable' to 'indirectly_writable'.

---

source/algorithms.tex

[algorithms.general] Add [specialized.algorithms] to summary table.

---

source/future.tex

[depr.conversions] Rename snake_case template parameters to CamelCase.

---

source/lib-intro.tex

[contents] Some standard library functions are not defined.

---

source/modules.tex

[module.interface] Remove redundant bullet for exported declaration.

---

source/future.tex

[depr.atomics] Use enum class memory_order

---

README.rst

Update Getting Started on Debian-based Systems

---

source/future.tex

Add examples to [depr.volatile]

---

source/algorithms.tex

[alg.replace] Clarify which value gets assigned depending on E.

---

source/preprocessor.tex
source/utilities.tex

Fixes very minor errors in applying P1857R3 and P1460R1.
@zygoloid: please review.

Motion corrections

---

source/support.tex

...of `__cpp_lib_bind_front` and `__cpp_lib_bit_cast`.

[version.syn] Fix mis-ordering

---

source/basic.tex
source/declarations.tex
source/modules.tex
source/preprocessor.tex
source/templates.tex

Changes to normative text (that are editorial unless I've misunderstood the wording), mostly resulting from DIS review.
@zygoloid: please review and/or delegate.

Normative cleanup

---

source/modules.tex

Remove impossible _private-module-fragment_ case.

Simplify reachability definition

---

source/basic.tex

For a defect faithfully copied from my own P1815R2 (oops).
@zygoloid: If you care about one word...

One more review fix

---

source/exceptions.tex

Pretty obvious what can be improved here :)

[except.handle] Simplify void pointer cv-qualification

---

source/future.tex

[depr.strstream] Fix typography for NTBS in index.

---

source/atomics.tex

[atomics.types.operations] Fix note typo

---

source/ranges.tex

Noticed while looking at http://wg21.link/LWG3428.

[range.single.view] Add missing requires-clause to spec

---

source/containers.tex
tools/check.sh

Also prevent future occurrences by updating check.sh
Fixes #3982

[vector.capacity] Remove duplicate \pnum

---

source/algorithms.tex

So that https://github.com/cplusplus/draft/issues/2661#issue-405939401 continues to be the truth.

[algorithms.general] Add [algorithms.results] to summary table

---

source/algorithms.tex

Same as on these earlier lines:
https://github.com/cplusplus/draft/blob/dab72a1f433264d22989a2b6a07b700a305b6042/source/algorithms.tex#L4262-L4263
Diff:

[alg.copy] Typeset variable consistently.

---

source/strings.tex

[string.syn] Index basic_string typedefs.

---

source/ranges.tex

[range.drop.view] Fix italics for exposition-only members.

---

source/algorithms.tex

There's also http://wg21.link/LWG3467, which will add another occurrence.

[numeric.ops.gcd,numeric.ops.lcm] Say "other than cv bool" as done elsewhere

---

source/ranges.tex

[range.elements.iterator] Add missing 'friend' for operator-.

---

source/expressions.tex
source/intro.tex
source/lib-intro.tex
source/macros.tex
source/std.tex

Partially addresses cplusplus/nbballot#392

Various small edits for CS016

---

source/future.tex
source/iterators.tex
source/locales.tex
source/numerics.tex
source/support.tex

Merge of #4178 to master.
Fixes #3525.

Fix solitary subclauses

---

source/utilities.tex

Fixes NB JP 007 (C++20 DIS)
Fixes cplusplus/nbballot#383

[util.smartptr.shared.cast] Add hyphen for 'well-formed'.

---

source/intro.tex

Fixes NB JP 003 (C++20 DIS)
Fixes cplusplus/nbballot#379

[defns.undefined] Move cross-reference to [expr.const]

---

source/intro.tex

[intro.defs] Refer to undated ISO/IEC 2382 for the terminology.

---

source/intro.tex

including Annex D.
Partially addresses cplusplus/nbballot#392

[intro.compliance.general] Properly reference normative clauses

---

source/ranges.tex

... to agree with [range.iota.view] as modified by LWG3292.

[ranges.syn] Update iota_view constraints

---

source/basic.tex

C++20 [basic.link] Add word missing from P1815R2

---

source/classes.tex

[class.derived] Clean up cross-references.

---

source/threads.tex

[thread.mutex.requirements] Harmonize wording for try_lock.

---

source/basic.tex

Shall is idiomatic for normative requirements.

[basic.def.odr] Change "is required" to "shall"

---

source/classes.tex
source/declarations.tex
source/iostreams.tex
source/time.tex
tools/check.sh

[std] Remove cross-references to the very same subclause

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/iostreams.tex
source/lib-intro.tex
source/templates.tex
source/threads.tex

No visible changes outside the index.

[std] Use \defnadj to improve/add many index entries.

---

source/statements.tex

[stmt.block] Rephrase introductory sentence.

---

source/iterators.tex

[iterator.cpp17] Index old-style iterator requirements.

---

source/ranges.tex
source/utilities.tex

Fix index entries for CPOs

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/containers.tex
source/exceptions.tex
source/expressions.tex
source/grammar.tex
source/iostreams.tex
source/iterators.tex
source/locales.tex
source/overloading.tex
source/statements.tex
source/templates.tex
source/threads.tex

Partially addresses cplusplus/nbballot#393

Fix modal verb "must"

---

source/algorithms.tex
source/atomics.tex
source/basic.tex
source/iterators.tex
source/overloading.tex
source/strings.tex
source/utilities.tex

@jwakely, @CaseyCarter your input is most welcome. See also https://github.com/cplusplus/draft/pull/4220#issuecomment-697047187 for a complete list of candidate commits.

Yet more cherry-picks for c++20

---

source/classes.tex
source/containers.tex
source/declarations.tex
source/expressions.tex
source/lib-intro.tex
source/preprocessor.tex
source/strings.tex
source/support.tex
source/templates.tex
source/utilities.tex

Page breaks (burblebee)

---

source/basic.tex

[intro.races] Harmonize index entry for "visible side effect(s)".

---

source/locales.tex

[locale.codecvt.virtuals] Add missing pnum

---

source/iostreams.tex

[tab:filebuf.open.modes] Consistently order table rows.

---

source/containers.tex

[tab:container.assoc.req] Add missing 'Effects'

---

source/algorithms.tex

[specialized.algorithms] Fold away unnecessary compound-statements.

---

source/std.tex

Do not claim the document is an "International Standard";
it is just a Working Draft.
Fixes #2367

[std] Fix PDF title and subject.

---

source/classes.tex

[class.union.anon] Remove duplicate normative wording.

---

source/containers.tex

[tab:container.hash.req] Capitalize start of sentence.

---

source/macros.tex
source/numerics.tex
source/regex.tex

Remove library names from general index

---

source/time.tex

year_month_weekday ctor : fix object name

---

source/iostreams.tex

... as is the common library style.

[stringbuf.cons] Insert space after comma

---

source/containers.tex

[containers] Replace 'could' and 'might'

---

source/declarations.tex
source/lex.tex
source/preprocessor.tex
source/statements.tex
source/templates.tex

Fixes #4323 
Fixes cplusplus/papers#1

CWG Poll 2: P0330R8 Literal Suffix for (signed) size_t

---

source/utilities.tex

[util.smartptr.weak] Remove declarations already in [memory.syn]

---

source/classes.tex
source/threads.tex

Fix list item punctuation

---

source/statements.tex

[stmt.return] Remove unhelpful example.

---

source/cover-wd.tex
source/std.tex

@hsutter, @zygoloid: Your approval would be most welcome.

[std, cover-wd] Update editor

---

source/utilities.tex

[stacktrace.entry.overview] Italicize 'implementation-defined' in code block

---

source/basic.tex

[basic.lookup.qual.general] Add \tcode around N::B<0>

---

source/algorithms.tex

[specialized.algorithms] Align requires-clause with return type

---

source/utilities.tex

[stacktrace.syn] Add header index entry for <stacktrace>.

---

source/declarations.tex
source/overloading.tex

Remove some \textit

---

source/iostreams.tex

As decided in #2656
Partially addresses #2512

[fs.op.funcs] Qualify declarator-id with sub-namespace.

---

source/threads.tex

[thread.condition.general] Fix style of quotation marks

---

source/ranges.tex

[ranges] Improve concept index

---

source/iostreams.tex
source/time.tex
source/utilities.tex

[lib] Use 'specialization' instead of 'instance'

---

source/ranges.tex

Completes https://github.com/cplusplus/draft/commit/ae15dd1b9116975f9f6d71955802536551d95d59.

[range.iota.iterator,range.iota.sentinel] Complete iota_view's requires-clause

---

source/containers.tex
source/iostreams.tex
source/threads.tex

[index] Add missing implementation-defined types

---

source/lib-intro.tex

[library.general] Adjust order according to recent clause reorganizations.

---

source/ranges.tex

[range.dangling] Split up overly long sentence.

---

.github/workflows/check.yml

Addresses #4529 partially and https://github.com/cplusplus/draft/issues/4529#issuecomment-786786718 completely.

ci: split make and check steps

---

.github/workflows/check.yml
tools/check-output.sh
tools/check-source.sh

Also improve the visibility of error messages.
Resolves #4529

[check] Split github action into two stages (source, output)

---

source/basic.tex

CWG Poll 2: CWG2470 Multiple array objects providing storage for one object

---

source/threads.tex
source/time.tex

Fixes #4508
Fixes cplusplus/papers#913

P2212R2 Relax Requirements for time_point::clock

---

source/support.tex
source/utilities.tex

Fixes #4512 
Fixes cplusplus/papers#460

P1682R2 std::to_underlying for enumerations

---

source/basic.tex

[conv.rank] Avoid 'shall' for plain descriptions.

---

source/iostreams.tex

[floatfield.manip] Rephrase note about ios_base::hex

---

source/utilities.tex

[unord.hash] Remove redundant wording

---

source/support.tex

[cmp.alg] Clarify ill-formed CPO invocations are SFINAE-friendly

---

source/expressions.tex

[expr.unary.general] Fix misaligned grammar.

---

source/ranges.tex

[ranges] Improve library index for views

---

source/utilities.tex

[format.context] Rephrase recommended practice

---

source/utilities.tex

Fixes for bitset function declarations

---

source/basic.tex
source/intro.tex

[index] Fix entry for 'program execution'

---

source/intro.tex

[defns.well.formed] Fix definition of 'well-formed'

---

source/basic.tex

Fixes #4463 
@opensdh, please have a look.

[basic.lookup.unqual] Add examples for conversion-function-ids

---

source/iostreams.tex
source/locales.tex
source/numerics.tex
source/regex.tex
source/threads.tex
source/utilities.tex
tools/check-source.sh
tools/element-order.awk

Check for misordered library elements

---

source/declarations.tex
source/exceptions.tex
source/statements.tex

Also fixes CWG2320.
Fixes #4636
Fixes cplusplus/papers#188

P1401R5 Narrowing contextual conversions to bool

---

source/compatibility.tex
source/lex.tex

Fixes #4639
Fixes cplusplus/papers#905

P2201R1 Mixed string literal concatenation

---

source/iostreams.tex
source/lib-intro.tex
source/support.tex

Fixes  #4643
Fixes cplusplus/papers#103
Fixes  #4622

P0448R4 A strstream replacement using span<charT> as buffer

---

source/containers.tex
source/support.tex

Fixes #4644
Fixes cplusplus/papers#204

P1425R4 Iterators pair constructors for stack and queue

---

source/lib-intro.tex
source/support.tex
source/utilities.tex

Fixes #4646
Fixes cplusplus/papers#401

P0401R6 Providing size feedback in the Allocator interface

---

source/utilities.tex

Fixes #4648
Fixes cplusplus/papers#689

P1951R1 Default Arguments for pair's Forwarding Constructor

---

source/ranges.tex

Fixes  #4655
Fixes cplusplus/papers#1008

P2328R1 join_view should join all views of ranges

---

source/containers.tex
source/iterators.tex
source/ranges.tex
source/support.tex
source/xrefdelta.tex

Also fixes LWG3479.
Fixes  #4656
Fixes cplusplus/papers#1007

P2325R3 Views should not be required to be default constructible

---

source/ranges.tex
source/xrefdelta.tex

Also fixes LWG3478.
Fixes #4657
Fixes cplusplus/papers#912

P2210R2 Superior String Splitting

---

source/iostreams.tex

[fs.path.native.obs] Remove bogus note.

---

source/basic.tex

[basic.fundamental] Redirect some index entries.

---

source/classes.tex

[class.pre] Fix incorrect comment in example

---

source/expressions.tex

[expr.rel] Clarify function pointer comparisons

---

source/basic.tex

[basic.start.dynamic] Clarify note about templated variables

---

source/utilities.tex

[allocator.uses.construction] Add missing closing parentheses

---

source/time.tex

[time.clock.cast.sys,time.clock.cast.utc] Shorten introdution of Duration2

---

source/numerics.tex

[bit.count] Add missing paragraph number

---

source/expressions.tex

[expr.static.cast] Admit integral promotion for cast to enumeration type

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/lib-intro.tex
source/overloading.tex
source/templates.tex

[std] Harmonize 'reference binds to an expression' phrasing

---

source/lib-intro.tex

[allocator.requirements.general] Fix typo in table's note

---

source/basic.tex

[basic.types.general] Fix comment in example

---

source/strings.tex
source/support.tex
source/utilities.tex

[impldef] Add missing index entries

---

source/basic.tex

Fixes #4812 
@opensdh, please have a look.

[basic.lookup.unqual] Clarify 'unqualified name'

---

source/expressions.tex

[expr.ass] Clarify type of assignment-expression

---

source/utilities.tex

[optional] Replace bool(x) with x.has_value()

---

source/expressions.tex

[expr.delete] Clarify constraints on non-array delete

---

source/expressions.tex

http://lists.isocpp.org/core/2021/08/11368.php

[expr.delete] Clarify treatment of arrays of classes

---

source/classes.tex

[class.copy.elision] Fix comment in example

---

source/expressions.tex

The preceding paragraph already introduces the
"otherwise" branch for the runtime check whose
algorithm is explain in this paragraph.

[expr.dynamic.cast] Remove apparent condition

---

source/statements.tex

Fixes #4968
Fixes cplusplus/papers#1034

P2360R0 Extend init-statement to allow alias-declaration

---

source/expressions.tex

Fixes #4969
Fixes cplusplus/papers#766

P2036R3 Change scope of lambda trailing-return-type

---

source/support.tex
source/utilities.tex

Fixes #4977
Fixes cplusplus/papers#400
Partially addresses #4960

P0288R9 move_only_function

---

source/utilities.tex

Fixes #4986
Fixes cplusplus/papers#987

P2301R1 Add a pmr alias for std::stacktrace

---

source/utilities.tex

Fixes #4990
Fixes cplusplus/papers#1071

P2401R0 Add a conditional noexcept specification to std::exchange

---

source/support.tex

Turn it into a "recommended practice" section.
Fixes #4958

[support.types.layout] Avoid implementation guidance in a note

---

.github/workflows/check.yml

I was hoping find the "Error" bug, but that wasn't successful.
Posted https://github.com/github/feedback/discussions/7381

[check] Cosmetics

---

source/intro.tex

See https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor218
for the current state.

[defs] Update introduction to match ISO Directives

---

source/intro.tex

[intro.refs] Update dated reference to previous POSIX standard

---

source/basic.tex
source/declarations.tex

Avoid implementation guidance in notes

---

source/lex.tex

Unicode naming cleanups

---

source/macros.tex

[index] Index keywords as '<keyword>, keyword' for differentiation

---

source/utilities.tex

Looks like missing editorial fixes in #5024.

[pairs.pair] Add missing `_v`

---

source/containers.tex
source/macros.tex

[container.requirements] Improve indexing of members described in requirements

---

source/expressions.tex

consistent with the specification of other -seq non-terminals.

[expr.prim.req.general] Change requirement-seq to right-recursive

---

source/containers.tex

[associative.reqmts.general] Fix confusing local use of 'r'

---

source/templates.tex

[temp.res.general] Clarify binding of names

---

source/declarations.tex

[dcl.meaning.general] Clarify correspondence for block-scope friends

---

source/atomics.tex

[util.smartptr.atomic] Add cross-reference to <memory> header

---

source/locales.tex

[locale.ctype.virtuals] Clarify do_widen parameter

---

source/compatibility.tex

[diff] Annotate keywords

---

source/ranges.tex

[range.req.general] Remove incorrect normative duplication for 'view'

---

source/preprocessor.tex

Fixes #5259 
Fixes cplusplus/papers#1149

P2493R0 Missing feature test macros for C++20 core papers

---

source/support.tex
source/utilities.tex

Fixes #5263
Fixes cplusplus/papers#275

P0627R6 Function to mark unreachable code

---

source/ranges.tex
source/support.tex

Fixes #5270
Fixes cplusplus/papers#1107

P2441R2 views::join_with

---

source/lex.tex

[lex.name] Rephrase note to avoid upper/lower-case

---

source/iterators.tex

This fixes a bad merge between P2393R1 Cleaning up integer-class types
and P2321R2 zip.
Fixes #5251.

[iterator.concept.winc] Remove duplicate paragraph

---

source/templates.tex

[temp.local] Fix type-name interpretation of injected-class-name

---

source/containers.tex

Fixes probable oversights in P2416.

[container.gen.reqmts] Eliminate "Value:"

---

source/expressions.tex

[expr] Cleanup for 'discarded-value expression'

---

source/atomics.tex

[atomics] Harmonize references to atomics operations tables

---

source/basic.tex
source/classes.tex
source/expressions.tex
source/intro.tex
source/support.tex
source/templates.tex
source/utilities.tex
source/xrefdelta.tex
tools/check-output.sh
tools/check-source.sh

[std] Replace hyphen with period in labels

---

source/utilities.tex

[unique.ptr.single] Rephrase destruction

---

source/basic.tex
source/ranges.tex
source/utilities.tex
tools/check-source.sh

spacing of ref-qualifiers

---

source/compatibility.tex

[diff.cpp20.library] Add subclause, highlighting new headers

---

source/iostreams.tex

[spanbuf] Fix template name in subclause heading

---

source/memory.tex

[memory.syn] Add missing closing bracket for attribute

---

source/strings.tex

Fixes #4039
@jwakely , please have a look.

[string.view.deduct] Move to immediately after [string.view.cons]

---

source/ranges.tex

[range.transform.iterator] Add some missing \exposid

---

source/algorithms.tex
source/iostreams.tex
source/threads.tex

Fixes #5430
Fixes #5434
Fixes #5437
Relates to #5428

Minor fixes related to issue 5428

---

source/iostreams.tex

[syncstream.osyncstream.cons] Fix use of parameter name

---

source/threads.tex

[thread.sema.cnt] Add missing parentheses on function call expression

---

source/classes.tex

Invalidated by #4667
https://lists.isocpp.org/std-discussion/2022/04/1599.php

[class.access] Remove dangling Note

---

source/meta.tex

... for `ratio_add`, `ratio_subtract`, `ratio_multiply`, and `ratio_divide`.

[ratio.arithmetic] Add missing index entries

---

source/algorithms.tex
source/containers.tex
source/iterators.tex
source/memory.tex
source/meta.tex
source/ranges.tex
source/strings.tex
source/utilities.tex

Typo and formatting fixes

---

source/classes.tex

[class.prop] Clarify definition of implicit-lifetime class

---

source/iterators.tex

[istreambuf.iterator.general] Add \ref for proxy

---

source/classes.tex
source/declarations.tex
source/overloading.tex

Fixes #5567
Fixes cplusplus/papers#1284

[2022-07 CWG Motion 2] P2622R0 Core Issues 2507 and 2586

---

source/modules.tex
source/overloading.tex

Fixes #5568
Fixes cplusplus/papers#1127

P2468R2 The Equality Operator You Are Looking For

---

source/expressions.tex
source/future.tex

Fixes #5569
Fixes cplusplus/papers#1023

P2327R1 De-deprecating volatile compound operations

---

source/preprocessor.tex

Fixes #5570
Fixes cplusplus/papers#1103

P2437R1 Support for #warning

---

source/statements.tex

Fixes #5572
Fixes cplusplus/papers#1006

P2324R2 Labels at the end of compound statements (C compatibility)

---

source/lex.tex

Fixes #5573
Fixes cplusplus/papers#983

P2290R3 Delimited escape sequences

---

source/classes.tex
source/compatibility.tex
source/declarations.tex
source/expressions.tex
source/preprocessor.tex

Fixes #5575
Fixes cplusplus/papers#968

P2266R3 Simpler implicit move

---

source/expressions.tex
source/overloading.tex
source/preprocessor.tex
source/threads.tex
source/utilities.tex

Fixes #5577
Fixes cplusplus/papers#1022
Note: slight editing overlap with LWG3617

P1169R4 static operator()

---

source/compatibility.tex
source/lex.tex

Fixes #5583
Fixes cplusplus/papers#985

P2295R6 Support for UTF-8 as a portable source file encoding

---

source/compatibility.tex
source/declarations.tex
source/preprocessor.tex

Fixes #5584
Fixes cplusplus/papers#1171

P2513R3 char8_t Compatibility and Portability Fix

---

source/basic.tex
source/lib-intro.tex

Fixes #5585
Fixes cplusplus/papers#1122

P2460R2 Relax requirements on wchar_t to match existing practices

---

source/basic.tex
source/expressions.tex

Fixes #5586
Fixes cplusplus/papers#1274

P2579R0 Mitigation strategies for P2036 "Changing scope for lambda trailing-return-type"

---

source/ranges.tex
source/support.tex

Fixes #5597
Fixes cplusplus/papers#647

P1899R3 stride_view

---

source/containers.tex
source/iterators.tex
source/ranges.tex
source/support.tex

Fixes #5600
Fixes cplusplus/papers#971

P2278R4 cbegin should always return a constant iterator

---

source/algorithms.tex
source/support.tex

Fixes #5603 
Fixes cplusplus/papers#988

P2302R4 std::ranges::contains

---

source/macros.tex
source/ranges.tex
source/support.tex

Fixes #5605
Fixes cplusplus/papers#1044

P2374R4 views::cartesian_product

---

source/support.tex
source/utilities.tex

Fixes #5609
Fixes cplusplus/papers#1087

P2417R2 A more constexpr bitset

---

source/compatibility.tex
source/strings.tex

Fixes #5611
Fixes cplusplus/papers#1104

P2438R2 std::string::substr() &&

---

source/iostreams.tex
source/support.tex

Fixes #5615
Fixes cplusplus/papers#1138

P2467R1 Support exclusive mode for fstreams

---

source/ranges.tex
source/support.tex

Fixes #5616
Fixes cplusplus/papers#1155

P2474R2 views::repeat

---

source/strings.tex

Fixes #5618
Fixes cplusplus/papers#1158

P2499R0 string_view range constructor should be explicit

---

source/iostreams.tex
source/utilities.tex

Fixes #5620
Fixes cplusplus/papers#1163

P2508R1 Expose std::basic-format-string<charT, Args...>

---

source/utilities.tex

Fixes #5621
Fixes cplusplus/papers#1175

P2517R1 Add a conditional noexcept specification to std::apply

---

source/iterators.tex
source/support.tex

Fixes #5622 
Fixes cplusplus/papers#1176

P2520R0 move_iterator<T*> should be a random access iterator

---

source/utilities.tex

Fixes #5623
Fixes cplusplus/papers#1209

P2549R1 std::unexpected<E> should have error() as member accessor

---

source/utilities.tex

Resolves
https://github.com/cplusplus/draft/pull/5700#discussion_r937166231.

[format.formattable] Fix spacing of _requires-expression_

---

source/templates.tex

[temp.inst] Clarify referent of 'declaration'

---

source/compatibility.tex

C compatibility fixes

---

source/support.tex

[cmp.categories] Replace 'operator admits' phrasing.

---

source/lib-intro.tex

[allocator.requirements.general] Simplify `SimpleAllocator` with some new styles

---

source/threads.tex

[thread.lock.unique.locking] Fix function call expressions

---

source/diagnostics.tex
source/threads.tex
tools/check-source.sh

Also augment check script
Fixes #5466

[stacktrace.basic.nonmem] Add missing \pnum before \recommended

---

source/ranges.tex

[range.as.rvalue.view] Fix curly brace format

---

source/ranges.tex

Make it consistent with the synopsis.

[range.as.const.view] Fix constrain order

---

source/algorithms.tex
source/iostreams.tex
source/locales.tex
source/numerics.tex
source/time.tex

More typo and formatting fixes

---

source/ranges.tex

[ranges.elementsof] Fix template format

---

source/containers.tex
source/iterators.tex
source/memory.tex
source/numerics.tex
source/ranges.tex
source/strings.tex
source/utilities.tex

Fix various library typos and style issues from #5428

---

source/containers.tex

[flat.set.modifiers] Remove stray 'return' in Effects clause

---

source/basic.tex
source/expressions.tex
source/iostreams.tex
source/macros.tex
source/ranges.tex
source/regex.tex
source/templates.tex
source/utilities.tex
tools/check-source.sh

Fix and use \logop

---

source/utilities.tex

[expected.object.assign] Add missing 'Returns: *this'

---

tools/check-source.sh

We have a check script, let's use it.

[check] Add check for \^ and recommend \caret

---

source/basic.tex
source/lex.tex

use "named by" in place of "appear as" for odr-using a variable

---

source/basic.tex

[basic.life] Add cross-reference for union member lifetime

---

source/diagnostics.tex

[diagnostics] Remove 'shall', use 'recommended practice'

---

source/utilities.tex

[func.bind.isplace] Add cross-reference to [func.bind.place]

---

source/containers.tex

[vector.bool.pspc] Index vector<bool>::reference

---

source/overloading.tex

[over.best.ics.general] Split long paragraph

---

source/expressions.tex

[expr.add] Use better example

---

source/utilities.tex

[func.bind] Index 10 placeholders

---

source/threads.tex

[thread.thread.this] Clarify this_thread::get_id

---

source/ranges.tex
tools/check-source.sh

Also add automated checks.
Fixes #5832

[ranges] Indexing fixes for iterator and sentinel classes

---

source/classes.tex

The example relates to the note which relates to the p4's first sentence.

[class.union.general] Attach example to its note

---

source/threads.tex

This resolves NB comment [GB-129](https://github.com/cplusplus/nbballot/issues/438).

[atomics] Replace integral and floating-point placeholders

---

source/declarations.tex

[motions-2022-11-cwg-2] P2709R0 ready issue 2635

---

source/expressions.tex
source/future.tex

Fixes #5960.
Fixes cplusplus/nbballot#488

[Motions 2022 11 cwg 5] Issue 2654 (Un-deprecation of compound volatile assignments) from P2710R0

---

source/overloading.tex
source/preprocessor.tex

P2589R1 static operator[]
Fixes #5962.
Fixes cplusplus/nbballot#460
Fixes cplusplus/papers#1247

2022-11 CWG Motion 7

---

source/declarations.tex
source/expressions.tex
source/preprocessor.tex

P2564R3 consteval needs to propagate up
Fixes #5964.
Fixes cplusplus/nbballot#467
Fixes cplusplus/papers#1223

2022-11 CWG Motion 9

---

source/basic.tex
source/compatibility.tex
source/statements.tex

P2718R0 Wording for P2644R1 Fix for Range-based for Loop
Fixes #5967.
Fixes cplusplus/papers#1316
Fixes cplusplus/nbballot#471

2022-11 CWG Motion 12

---

source/containers.tex
source/diagnostics.tex
source/iostreams.tex
source/lib-intro.tex
source/memory.tex
source/meta.tex
source/ranges.tex
source/threads.tex
source/utilities.tex
source/xrefdelta.tex

Fixes #5969.
Fixes cplusplus/papers#1393

[Motions 2022 11 lwg 8] P2704R0 C++ Standard Library Immediate Issues

---

source/iostreams.tex
source/strings.tex
source/utilities.tex

Fixes #5973.
Fixes https://github.com/cplusplus/papers/issues/342.

[Motions 2022 11 lwg 12] P1264R2 Revising the wording of stream input operations

---

source/support.tex
source/utilities.tex

Fixes #5974.
Fixes cplusplus/nbballot#511
Fixes cplusplus/nbballot#510
Fixes cplusplus/nbballot#433
Fixes cplusplus/nbballot#413
Fixes cplusplus/papers#1161

[Motions 2022 11 lwg 13] P2505R5 Monadic Functions for std::expected

---

source/utilities.tex

[optional.ctor], [expected.object.ctor] Add converts-from-any-cvref

---

source/classes.tex
source/lex.tex

[CWG 2] P2796R0 issues 2674 and 2691

---

source/basic.tex

Fixes NB US 8-036 (C++23 CD).
Fixes #6090.
Fixes cplusplus/papers#1477
Fixes cplusplus/nbballot#480

[CWG 9] P2788R0: Linkage for modular constants

---

source/algorithms.tex
source/compatibility.tex
source/containers.tex
source/iostreams.tex
source/iterators.tex
source/locales.tex
source/memory.tex
source/meta.tex
source/numerics.tex
source/ranges.tex
source/regex.tex
source/strings.tex
source/support.tex
source/time.tex
source/utilities.tex

Fixes #6092.
Fixes cplusplus/papers#1478
Fixes cplusplus/nbballot#534

[LWG  2] P2789R0 Ready and Tentatively Ready issues

---

source/ranges.tex
source/regex.tex

Fixes NB US 61-126 (C++23 CD).
Fixes #6095.
Fixes cplusplus/nbballot#539

[LWG 5] P2770R0 Stashing stashing iterators for proper flattening

---

source/ranges.tex
source/support.tex

Fixes NB FR 14-021, US 48-108 (C++23 CD).
Fixes #6096.
Fixes cplusplus/papers#875
Fixes cplusplus/nbballot#525
Fixes cplusplus/nbballot#416

[LWG 6] P2164R9 views::enumerate

---

source/iterators.tex
source/support.tex

Fixes NB US 39-099 (C++23 CD).
Fixes #6098.
Fixes cplusplus/papers#1271
Fixes cplusplus/nbballot#516

[LWG 8] P2609R3 Relaxing Ranges Just A Smidge

---

source/ranges.tex

Fixes #6107
Fixes cplusplus/papers#1457
Fixes cplusplus/nbballot#529

[LWG 17] P2787R1 pmr::generator - Promise Types are not Values

---

source/compatibility.tex
source/support.tex
source/threads.tex

Fixes #6109 
Fixes cplusplus/papers#1246 
Fixes cplusplus/nbballot#541
Fixes cplusplus/nbballot#468

P2588R3 barrier's phase completion guarantees

---

source/containers.tex

Fixes #6110 
Fixes cplusplus/papers#1448

[LWG 20] P2763R1 layout_stride static extents default constructor fix

---

source/iostreams.tex

[tab:iostreams.summary] Add missing header in summary table

---

.github/workflows/check.yml

Update the `actions/upload-artifact` action to version 3.

tools: update action in GitHub workflow

---

source/preprocessor.tex

Fixes cplusplus/CWG#281
As agreed there, this is editorial.

[cpp.predefined] Add __cpp_auto_cast

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/exceptions.tex
source/expressions.tex
source/lex.tex
source/modules.tex
source/overloading.tex
source/templates.tex

Fixes #6276
Fixes cplusplus/papers#1465
Fixes cplusplus/papers#1467
Fixes cplusplus/CWG#237
Fixes cplusplus/CWG#278
Fixes cplusplus/CWG#279
Fixes cplusplus/CWG#280
Fixes cplusplus/CWG#291
Fixes cplusplus/CWG#292
Fixes cplusplus/CWG#293
Fixes cplusplus/CWG#294
Fixes cplusplus/CWG#296
Fixes cplusplus/CWG#297
Fixes cplusplus/CWG#300
Fixes cplusplus/CWG#301

[Motions 2023 06 cwg 1] P2922R0 Core Language Working Group "ready" Issues

---

source/lex.tex
source/preprocessor.tex

Original title: UB? In my lexer?
- Added a cross-reference.
Fixes #6277
Fixes cplusplus/papers#1283

P2621R2 Undefined behavior in the lexer

---

source/declarations.tex
source/lex.tex
source/overloading.tex

Fixes #6279
Fixes cplusplus/papers#1035

P2361R6 Unevaluated strings

---

source/expressions.tex
source/preprocessor.tex

Fixes #6281
Fixes cplusplus/papers#1431

P2738R1 constexpr cast from void*: towards constexpr type-erasure

---

source/support.tex
source/utilities.tex

Fixes #6288
Fixes cplusplus/papers#1454

P2497R0 Testing for success or failure of <charconv> functions

---

source/algorithms.tex
source/support.tex

Fixes #6291
Fixes cplusplus/papers#1222

P2562R1 constexpr Stable Sorting

---

source/iostreams.tex
source/support.tex

Fixes #6295
Fixes cplusplus/papers#1190

P2495R3 Interfacing stringstreams with string_view

---

source/future.tex
source/support.tex
source/utilities.tex

Fixes #6307.
Notes/questions:
* Is there any order to the sections in [depr]?

[LWG motion 21] P2637R3 Member visit

---

source/numerics.tex
source/support.tex

Fixes #6311.
Fixes cplusplus/papers#168

[LWG motion 25] P1383R2 More constexpr for cmath and complex

---

source/meta.tex
source/support.tex

Fixes #6312.
Fixes cplusplus/papers#1427

[LWG Motion 26] P2734R0 Adding the new 2022 SI prefixes

---

source/support.tex
source/utilities.tex

Fixes #6313.
Fixes cplusplus/papers#1275

[LWG motion 27] P2548R6 copyable_function

---

source/containers.tex
source/lib-intro.tex
source/support.tex

Fixes #6315.
Fixes cplusplus/papers#1293

[LWG 29] P2630R4 submdspan

---

source/expressions.tex

Fixes #6268.
No changes to normative wording.

[expr.add] Clarify note on pointer subtraction

---

source/basic.tex

[basic.def.odr] Restructure requirements in p14-p15

---

source/utilities.tex

[func.wrap.ref.class] change deduction guide to match its detailed specifications

---

source/compatibility.tex

Fixes https://github.com/cplusplus/draft/issues/5544 (in part).

[diff.cpp20.utilities] Hyphenate bit-fields

---

source/numerics.tex

[rand.device] Remove stray \textit.

---

source/threads.tex

[atomics] Reword preconditions on memory_order values in a positive form

---

source/containers.tex

For consistency with:
https://github.com/cplusplus/draft/blob/9a0b5d767ed6ef038adc129856c0c0623f552abe/source/containers.tex#L21883-L21884
and
https://github.com/cplusplus/draft/blob/9a0b5d767ed6ef038adc129856c0c0623f552abe/source/containers.tex#L22048-L22049

[mdspan.submdspan.extents] Format equations as math.

---

source/lib-intro.tex

[tab:headers.cpp] Add <hazard_pointer>

---

source/strings.tex

[string.cons] Remove erroneous paragraph break

---

source/intro.tex

Fixes ISO/CS 004 (C++23 DIS).
Fixes cplusplus/nbballot#546

[intro.refs] Fix title of ISO/IEC 9899:2018

---

source/std.tex

Fixes NB ** 029 (C++23 DIS).
Fixes cplusplus/nbballot#571

[annex] Fix table numbering in annexes

---

source/lex.tex

Fixes ISO/CS 030 (C++23 DIS).
Fixes cplusplus/nbballot#572

[lex.name] Add cross-reference to Annex E

---

source/intro.tex

Fixes ISO/CS 018 (C++23 DIS).
Fixes cplusplus/nbballot#560

[defns.component] Remove unwarranted italics

---

source/memory.tex

Fixes NB JP 025 (C++23 DIS).
Fixes cplusplus/nbballot#567

[util.smartptr.shared.cmp] Fix missing right parenthesis

---

source/memory.tex

Fixes NB JP 024 (C++23 DIS).
Fixes cplusplus/nbballot#566

[unique.ptr.runtime.modifiers] Fix placement of 'constexpr'

---

source/expressions.tex

Fixes NB JP 023 (C++23 DIS).
Fixes cplusplus/nbballot#565

[expr.const] Amend comments in example

---

source/expressions.tex

Fixes NB JP 021 (C++23 DIS).
Fixes cplusplus/nbballot#563

[expr.prim.lambda.general] Add example for parsing ambiguity

---

source/intro.tex

Fixes ISO/CS 034 (C++23 DIS).
Fixes cplusplus/nbballot#576

[intro.scope] Clarify 'they'

---

source/basic.tex
source/classes.tex
source/concepts.tex
source/declarations.tex
source/expressions.tex
source/iostreams.tex
source/lex.tex
source/locales.tex
source/modules.tex
source/support.tex
source/templates.tex
source/time.tex
source/utilities.tex
tools/check-source.sh

Notes with requirements

---

source/intro.tex
source/xrefdelta.tex

Fixes cplusplus/nbballot#553
Fixes cplusplus/nbballot#558

DIS **-011: remove unused definitions

---

source/meta.tex

Fixes ISO/CS 001 (C++23 DIS).
Fixes cplusplus/nbballot#543

[type.traits] Add references to tables

---

source/intro.tex
source/lib-intro.tex
source/regex.tex

[intro.refs] Move nicknames for standards to relevant subclauses

---

source/compatibility.tex

Fixes https://github.com/cplusplus/draft/issues/5544 (in part).

[diff.dcl] Replace `field initializers` with `member initializers`

---

source/intro.tex

[defns.character.container] Improve note

---

source/iterators.tex

Fixes #6537.
Not sure whether the clarification can be done editorially.

[iterator.requirements.general] Clarify non-forward iterator

---

source/iterators.tex

[forward.iterators] Consistently use Cpp17 requirements

---

source/iostreams.tex

The template argument 'Allocator' was missing.

Added missing template argument

---

source/ranges.tex

[range.cartesian.view] Remove unused template parameter

---

source/intro.tex

We changed the grammar non-terminal font to sans-serif, so we should update the description.

[syntax] Change "italic" to "italic, sans-serif"

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/exceptions.tex
source/expressions.tex
source/lex.tex
source/modules.tex
source/overloading.tex
source/statements.tex
source/templates.tex

Fixes #6655.
Notes:
* CWG1038 is fixed by CWG2725
* CWG1698 is fixed by CWG2747
Fixes cplusplus/CWG#320
Fixes cplusplus/CWG#22
Fixes cplusplus/CWG#33
Fixes cplusplus/CWG#54
Fixes cplusplus/CWG#63
Fixes cplusplus/CWG#69
Fixes cplusplus/CWG#143
Fixes cplusplus/CWG#325
Fixes cplusplus/CWG#348
Fixes cplusplus/CWG#349
Fixes cplusplus/CWG#356
Fixes cplusplus/CWG#354
Fixes cplusplus/CWG#358
Fixes cplusplus/CWG#355
Fixes cplusplus/CWG#391
Fixes cplusplus/CWG#410
Fixes cplusplus/CWG#436
Fixes cplusplus/CWG#420
Fixes cplusplus/CWG#198
Fixes cplusplus/papers#1585

[Motions 2023 11 cwg 1] P3046R0 Core Language Working Group "ready" Issues

---

source/declarations.tex
source/templates.tex

Fixes #6656
Fixes cplusplus/papers#1469

[Motions 2023 11 cwg 2] P2308R1 Template parameter initialization

---

source/compatibility.tex
source/expressions.tex
source/future.tex
source/xrefdelta.tex

Fixes #6658 
Fixes cplusplus/papers#1554

[Motions 2023 11 cwg 4] P2864R2 Remove deprecated arithmetic conversions

---

source/compatibility.tex
source/lib-intro.tex
source/support.tex
source/utilities.tex

Fixes #6662.
Fixes cplusplus/papers#1207

[LWG motion 4] P2546R5 Debugging Support

---

source/iostreams.tex
source/utilities.tex

Fixes #6663.
Fixes cplusplus/papers#1578

[LWG 5] P2905R2 Runtime format strings

---

source/support.tex
source/utilities.tex

Fixes #6664.
Fixes cplusplus/papers#1598

[LWG 6] P2918R2 Runtime format strings II

---

source/containers.tex
source/support.tex

Fixes #6668.
Fixes cplusplus/papers#1501
Note: 2nd commit is Part 2 of [LWG 16] P2833R2 for #6703.

[LWG 10] P2821R5 span.at()

---

source/compatibility.tex
source/future.tex
source/lib-intro.tex
source/xrefdelta.tex

Fixes #6671
Fixes cplusplus/papers#1527

[LWG 13] P2871R3 Remove deprecated <codecvt> header

---

source/basic.tex

[basic.scope.pdecl] 6.4.2-2, example 2
[basic.types.general] 6.8.1-6, example 3

[basic.scope.pdecl], [basic.types.general] Remove unnecessary whitespace

---

source/iostreams.tex

[stringbuf.cons] 31.8.2.2-4 & 31.8.2.2-7

[stringbuf.cons] Rename const Allocator &a to const Allocator& a

---

source/basic.tex

[basic.def] Replace . with ,

---

source/lib-intro.tex

[zombie.names] Fix punctuation

---

source/support.tex

[numeric.special] Fix indentation

---

source/containers.tex

[container.alloc.reqmts] End note with .

---

source/classes.tex

[class.mem.general] 11.4.1-21.2 note 9
[class.mfct.non.static] 11.4.3-3 note 2

[class.mem.general,class.mfct.non.static] End note with .

---

source/iterators.tex

[iterator.concept.winc] 25.3.4.4-15 implementaton -> implementation

[iterator.concept.winc] Fix typo

---

source/templates.tex

[temp.constr.order] Move index entry to correct paragraph

---

source/threads.tex

Fixes https://github.com/cplusplus/draft/issues/6775

[semaphore.syn] add binary_semaphore to index

---

source/utilities.tex

Cherry-picked from https://github.com/cplusplus/draft/pull/6111

[format.syn] Remove obsolete index entry

---

source/back.tex

Update link to secure connection

---

source/support.tex

[coroutine.traits.primary] Index `coroutine_traits`

---

source/iostreams.tex

Fixes #6878.
Fixes cplusplus/papers#1794

[LWG motion 7] P3142R0 Printing Blank Lines with println

---

source/ranges.tex
source/support.tex

Fixes #6881.
Fixes cplusplus/papers#1204

[LWG motion 10] P2542R8 views::concat

---

source/strings.tex
source/support.tex

Fixes #6882 
Fixes cplusplus/papers#1249

P2591R5 Concatenation of strings and string views

---

source/containers.tex
source/support.tex

Fixes #6887
Fixes cplusplus/papers#1308

P2642R6 Padded mdspan layouts

---

source/lib-intro.tex

This table is sorted numerically by clause number

[tab:headers.cpp.fs] Move debugging library to correct position

---

source/containers.tex

[mdspan.layout.leftpad.obs] Remove extra \item

---

source/containers.tex

[mdspan.layout.rightpad.obs] Line break between \expects and \returns

---

source/tables.tex

Add hypertarget before table captions

---

source/declarations.tex
source/locales.tex

Fix punctuation details

---

source/limits.tex

[implimits] Rephrase introductory sentence for list of quantities

---

source/declarations.tex
source/expressions.tex

[CWG motion 2 2024-06] issues 2819, 2858, and 2876 in P3345R0 (Core Language Working Group "ready" Issues)

---

source/containers.tex
source/support.tex

Fixes #7086
Fixes cplusplus/papers#1743

[LWG motion 3 2024-06] P2389R2 dextents Index Type Parameter

---

source/xrefdelta.tex

- P2300 is miswritten as P3400
- P2875 is missing a revision number

Fix some issues in comments of xrefdelta.tex

---

source/statements.tex

[stmt.ambig] Make references more precise

---

source/time.tex

Analogous to https://github.com/cplusplus/draft/blob/decb06cd28ca5187444092ddebbb6845cae878c6/source/utilities.tex#L3068

[time.traits.specializations] Fix index entry for common_type specialization

---

source/containers.tex

[deque, forward.list, list, vector] Fix instances of "FooInsertable into *this"

---

source/algorithms.tex

It's not clear which conditions correspond to each overload.
Let me know if you'd prefer this to be done as an LWG issue.

[alg.search] Replace "the following corresponding conditions"

---

source/exec.tex

which aligns with the original paper.

[exec.fwd.env] Add \tcode for true

---

source/text.tex

[locale.codecvt.virtuals] Fix garbled sentence

---

source/iterators.tex

[reverse.iter.cons] Removed redundant wording

---

source/utilities.tex

[refwrap.invoke] Place period at end

---

source/classes.tex
source/declarations.tex
source/expressions.tex
source/lex.tex
source/preprocessor.tex
source/statements.tex

P3340R0 A Consistent Grammar For Sequences
Fixes https://github.com/cplusplus/draft/issues/7406
Fixes https://github.com/cplusplus/papers/issues/2003

P3340R0 A Consistent Grammar For Sequences

---

source/expressions.tex
source/preprocessor.tex
source/support.tex

Fixes https://github.com/cplusplus/draft/issues/7408
Fixes https://github.com/cplusplus/papers/issues/1754

P3068R6 Allowing exception throwing in constant-evaluation

---

source/threads.tex

Fixes #7425
Also fixes cplusplus/papers#1985
Also fixes cplusplus/papers#1891

P3323R1 cv-qualified types in atomic and atomic_ref

---

source/containers.tex

[inplace.vector.overview] Replace residual use of 'trivial type'

---

source/algorithms.tex

For consistency with the rest of the clause.

[alg.lex.comparison], [specialized.algorithms] Remove extraneous whitespace

---

source/iostreams.tex

Analog 11 "an NTBS" and 3 "an NTMBS" in this draft.

[filebuf.members,fs.path.req] Fix indefinite article

---

source/text.tex

- Fix indentation
- Insert space around & for consistency
- Insert space around | for consistency

[facet.num.get.virtuals] Minor formatting fixes

---

source/exec.tex

[exec.getcomplsigs] Add missing LaTeX escaping of braces

---

source/exec.tex

[exec.snd.expos] Move write-env paragraph into itemdescr

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/expressions.tex
source/modules.tex

Fixes #7651 
Also fixes cplusplus/CWG#628
Also fixes cplusplus/CWG#654

[2025-02 CWG 1] P3638R0 Core Language Working Group "ready" Issues

---

source/numerics.tex
source/support.tex

Fixes #7671 
Also fixes https://github.com/cplusplus/papers/issues/1330

[2025-02 LWG Motion 12] P2663R7 Interleaved complex values support in std::simd

---

source/basic.tex
source/lex.tex

Creates a new index entry for the act of linking a program.

[lex.phases][basic.link] Index linking

---

source/containers.tex

This is consistent with other places.

[list.ops] Fix format for N

---

source/compatibility.tex
source/lex.tex
source/uax31.tex

Index XID_Start and XID_Continue

[lex.name][diff.cpp20.lex][uaxid.def] Index Unicode properties

---

source/declarations.tex

[dcl.contract.func] added missing \br after precondition-specifier

---

source/diagnostics.tex

[assertions.assert] Add ISO C reference for standard error stream

---

source/basic.tex

[class.temporary] Define "temporary object"

---

source/ranges.tex

[ranges.*][range.*][coro.generator] Add missing library indexes. Fixes #8015.

---

source/basic.tex
source/meta.tex

Closes #7935.
Also closes https://github.com/cplusplus/papers/issues/1764.

P3096R12 Function Parameter Reflection in Reflection for C++26

---

source/numerics.tex

P3480R6 std::simd is a range
Fixes https://github.com/cplusplus/draft/issues/7948.

LWG Motion 11

---

source/meta.tex

Fixes NB US 94-201 (C++26 CD).
Fixes cplusplus/nbballot#770

[meta.reflection.names] Fix formatting for 'N'

---

source/meta.tex

Fixes NB US 92-199 (C++26 CD).
Fixes cplusplus/nbballot#768

[meta.reflection.operators] Fix table formatting

---

source/templates.tex

Fixes NB US 51-095 (C++26 CD).
Fixes cplusplus/nbballot#672

[temp.variadic] Add separate bullet for annotation-list

---

source/classes.tex

Fixes NB CA-083 (C++26 CD).
Fixes cplusplus/nbballot#659

[class.pre] Adjust phrasing around 'identifer'

---

source/meta.tex

Fixes NB US 111-174 (C++26 CD).
Fixes cplusplus/nbballot#992

[meta.reflection.extract] Apply code font to "U"

---

source/meta.tex

Fixes NB US 108-169 (C++26 CD).
Fixes cplusplus/nbballot#987

[meta.reflection.layout] Remove incorrect 'of'

---

source/exec.tex

Fixes NB US 217-359 (C++26 CD).
Fixes cplusplus/nbballot#934

[exec.getcomplsigs] Fix indentation of paragraph
