cplusplus/draft

- source/expressions.tex
N4296 5.3.3 [expr.sizeof] says
>The sizeof operator shall not be applied to an expression that has function or incomplete type, to an enumeration type whose underlying type is not fixed before all its enumerators have been declared, to the parenthesized name of such types, or to a glvalue that designates a bit-field.
Now that "an enumeration type whose underlying type is not fixed before all its enumerators have been declared" is considered as an incomplete type (7.2[dcl.enum]p6), `to an enumeration type whose underlying type is not fixed before all its enumerators have been declared` become redundant.
> [expr.sizeof] redundant wording

- source/iostreams.tex
`flush()` "behaves as an unformatted output function", but the link is to [ostream.formatted.reqmts]. It should link to [ostream.unformatted] like others in the same section. (Originally reported as #438.)
> Fix link in basic_ostream::flush() description

- source/threads.tex
From stl@
Too trivial for a library issue IMO.
> [thread.lock.shared.cons] fix typos

- source/exceptions.tex
Pull request for updating the list of situations in which std::terminate() is called to include condition variables.
> Adding a bullet to [except.terminate] for condition variables

- source/containers.tex
Addresses Issue #400
This part of the clean-up changes only whitespace
* inserted before commas: `foo<A,B>` becomes `foo<A, B>`
* removed after namespace braces
* improved indentation consistency (e.g. in the groupings with `erase` and `swap`)
* removed some extraneous linebreaks for things that fit well on one line (mostly in the member function declarations that lead the descriptions)
> Consistency cleanups in [containers]: Whitespace

- source/threads.tex
Makes the formatting of DECAY_COPY consistent as all-caps/italic/code.
> Fix formatting of DECAY_COPY

- source/containers.tex
Addresses Issue #400
This part of the clean-up changes whitespace and ordering of members in the synopses.
Specifically:
* Add linebreak in `swap(priority_queue&)` as requested in the previous PR
* Add missing spaces after commas as requested in the previous PR
* Align `equal_range` members consistently
* Order `empty`, `size`, `max_size` members consistently in that order, and move "iterators" above "capacity" consistently.
> Consistency cleanups in [containers] (cf. Issue #400): Ordering, whitespace

- source/strings.tex
Two unrelated fixes:
* spacing around an `\indextext`.
* line breaking in a table caption, which fixes the corresponding entry in the List of Tables.
> Typographic fixes in [strings]

- source/containers.tex
N4140 23.6.4.4 [priqueue.special] says `template <class T, class Container, Compare>`. It should say `template <class T, class Container, class Compare>`.
> [priqueue.special] fix typo

- source/algorithms.tex
Make the note for both two conditions, not for just the latter of two, as the note says "Under these conditions...".
This changes numbering of the items in the note from "(4.2.1) ..." to "(4.3) ...".
> [algorithms] Fix for a note for conditions of strict-weak-ordering

- source/support.tex
97e974390f5de39244b9178a27b729ae6bb5ce6c removed the wrong signatures, this puts them back and removes the ones actually removed by LWG 2458
> [support.dynamic] LWG2458 remove correct signatures

- source/basic.tex
- source/containers.tex
- source/intro.tex
- source/templates.tex
Consistency is better than inconsistency, and the general consensus on the editorial list was to hyphenate one-definition to clarify ambiguity.
> Unify the spelling of one-definition rule to be consistent.

- source/basic.tex
cv-unqualified is not a grammar term in this context, similar to other uses in the same paragraph.
> Fix misuse of cv-unqualified as a grammar term

- source/utilities.tex
> [tuple.assign] Fix typo

- source/utilities.tex
Looks like this one was overlooked when `decay_t` (and the other `_t` helpers) were introduced.
> Change "typename decay<F>::type" to "decay_t<F>"

- source/declarators.tex
This rewording removes the subjective emphasis "very" from the normative text.
> [dcl.init.ref] Replace normative note with actual note.

- source/containers.tex
In #357 @tkoeppe suggested this change. It would be more consistent with the rest of Clause 23, although it makes 23.3.1 [sequences.general] a rather weedy subclause.
> [sequences.general] Promote header synopses to rSec2

- source/lib-intro.tex
`\idxcode` is necessary for correct collation of text with fancy formatting.
(Without this change, the index entry for "specifier, friend" is broken.)
> [library] Fix index entry

- source/locales.tex
There is no "bold italic teletype" font. This produces a LaTeX warning and a font replacement.
The next best thing is "bold slanted teletype", which this change introduces.
> [localization] Change bold-slanted font, removes warning

- source/iterators.tex
- source/locales.tex
See also issues #319 and #326 and PRs #553 and #350.
Before:
After:
The above is the *only* diffpdf diff caused by this PR.
> [iterators, locales] Apply \placeholder macro

- source/lib-intro.tex
- source/utilities.tex
No diffpdf diff.
Note that I'm not touching any of the `\tcode{\textit{INVOKE}}` instances.
@zygoloid, @jwakely: maybe you can also take a look at  [character.seq]/(1.3) for use of placeholders and italics and macros.
> [lib-intro, utilities] Apply \placeholder macro

- source/utilities.tex
This note should be talking about the callable object being wrapped, i.e., f, rather than its "target", which makes no sense for arbitrary callable objects. This seems to be a copy/paste error from the very similar note in the copy constructor's description a few paragraphs above.
> [func.wrap.func.con] Fix error in note

- source/algorithms.tex
As allowed in 25.1 [algorithms.general] p12, to express the same things
as same.
For is_permutation, it is really bad because last1 - first1 is used in the previous line.
Others are just for consistency.
> [algorithms] Uniform notation of distance(first, last) to (last - first)

- source/atomics.tex
`inttypes.h` is not the primary header that defines `int_least8_t` etc. That's `cstdint`. The only new thing `inttypes.h` adds is `idivmax_t`, but we don't have an atomic version of that.
> [atomics] Reword table headers, removing mention of "inttypes.h"

- source/algorithms.tex
- source/macros.tex
The usual typographic convention is to have a space after (but not before) a comma. This change inserts a comma into the `\range` macro to print ranges as `[a, b)` rather than the current `[a,b)`.
This has about 90 pdfdiffs, all looking like improvements.
> [macros] Add space into \range, reflow [alg.transform]

- source/algorithms.tex
Here are some example screenshots from diffpdf (new on the left, old on the right):
> [algorithms] Improve typographic consistency of complexity expressions

- source/compatibility.tex
Add `NULL <cstdio>` and reflow Table 149 to maintain alphabetical order (for issue #586)
> [diff.library] add missing NULL <cstdio> to Table 149

- source/iostreams.tex
This addresses #596 by removing the uppercase X from the SCN* rows of Table 134
> [c.files] cinttypes synopsis refers to SCNX* macros which do not exist

- source/support.tex
There seems to be a typo in the application of LWG2111 to the WP.
> [terminate] Fix typo "terminate_handleri"

- source/regex.tex
while looking at LWG issue #2589, I noticed that L2554 says "`match_results` shall satisfy the ...".
In general, we use "shall" to place requirements on user code, not on library code.
Change to just say "satisfies", rather than "shall satisfy"
> Remove incorrect "shall"

- source/regex.tex
Currently, `basic_regex::operator=` is defined in terms of assign. This is different from what `basic_string` (and possibly others) do.
Swap the descriptions so that `assign` is now defined in terms of `operator=`. No functional change to either is intended.
> Swap effects of `basic_regex::operator=` and `assign`

- tools/grambase.tex
Last year, I submitted some changes to grammar.tex to fix some index entries, but I did not realize that grammar.tex is a file generated by tools/makegram.
This patch makes the same changes in tools/grambase.tex, so that grammar.tex corresponds once more to the output of tools/makegram.
> Re-synchronize generated grammar.tex with grambase.tex.

- source/numerics.tex
> Clarify the return value range of log(x)

- source/iostreams.tex
[string.streams] and [file.streams] follow very similar structure (an introduction followed by streambuf, input stream, output stream and bidirectional stream class templates) but are nested entirely differently. Under [fstreams] we have an entirely flat hierarchy where the definition of `basic_streambuf` is at the same level as its own members.
This change makes [file.streams] consistent with [string.streams] by promoting [filebuf], [ifstream], [ofstream] and [fstream] to `rSec2`.
Also promote [c.files] to `rSec1`, I don't think `<cstdint>` should be nested underneath the sub-clause for `basic_fstreambuf` and `basic_fstream` etc.
> [file.streams] Change sub-clauses to rSec2, similar to [string.streams]

- source/compatibility.tex
It is always legal in C++ to declare new types in a sizeof expression or cast expression, but you can't *define* a new type in an expression.
> [diff.expr] replace "declare" with "define"

- source/classes.tex
- source/declarations.tex
- source/declarators.tex
- source/derived.tex
- source/exceptions.tex
- source/expressions.tex
- source/grammar.tex
- source/intro.tex
- source/lex.tex
- source/overloading.tex
- source/preprocessor.tex
- source/special.tex
- source/statements.tex
- source/templates.tex
* occurrences of "\opt \terminal{" apparently always require "\opt{}" to not eat
the intervening space (despite the \xspace in the definition of \opt)
* cleaned up two occurrences of "\opt\ " (in
noptr-abstract-pack-declarator \terminal{[} constant-expression\opt\ \terminal{]} attribute-specifier-seq\opt\br
in declarators.tex and grammar.tex) to consistenly use "\opt{}" instead
* cleaned up two occurrences of "\opt{}" (in
pp-tokens\opt{} new-line
in grammar.tex and preprocessor.tex) that did not need the "{}"
> Typographic fixes, spacing after \opt

- source/iostreams.tex
- source/numerics.tex
- source/regex.tex
- source/utilities.tex
- Fix index entry for `basic_istream::operator>>`.
- Use `basic_istream` instead of `istream`.
- Use `operator\sh[lr]` instead of `operator(<<|>>)`.
- Add `class-name!function-name` entry in addition to `function-name!class-name`.
> Refine "Index of library names" for operator<< and operator>>

- source/intro.tex
- source/lib-intro.tex
- source/macros.tex
- source/std.tex
Angle brackets look better than less-than/greater-than operators when used to typeset parentheticals.
> Use textual angle brackets rather than relational operators

- source/atomics.tex
- source/macros.tex
> [macros, atomic] Align placeholders

- source/declarations.tex
[dcl.type.cv]/6 reads
> If an attempt is made to refer to an object defined with a volatile-qualified type through the use of a glvalue with a non-volatile-qualified type, the program behavior is undefined.
This is probably meant to use the idiomatic phrase "the behavior is undefined".
> [dcl.type.cv]/6 "program behavior" vs "behavior"

- source/expressions.tex
Array bounds now use "converted constant expressions of type std::size_t", not integral constant expressions.
> [expr.const] adjust note

- source/statements.tex
Changed identifier label into a definition; it is used by the resolution to CWG 2163.
> Making identifier label into a definition.

- source/classes.tex
1.8 defines member subobject and has an x-ref to 9.2, but 9.2 never mentions what a member subobject is. This note clarifies what is normatively stated elsewhere.
> Adding a note about what a member subobject is

- source/lib-intro.tex
It seems that this `\tcode{false}. \exitexample` is wrongly copied from the pevious section, i.e. 17.3.27 [defns.valid].
I also removed the full stop, because most definitions in section 1.3 [intro.defs] and 17.3 [deﬁnitions] do not use full stop ([defns.well.formed] and [defns.referenceable] being the only two exceptions).
> [defns.const.subexpr] Remove superfluous words

- source/support.tex
Remove the use of "field" from [support.types] p4 "The result of applying the offsetof macro to a field that is a static data member or a function member is undefined.", because
- the Standard does not define the term, or
- the usual meaning of "field" in OPP does not include member functions but this sentence says "a field that is **a static data member or a function member**".
> [support.types] Remove "field", which is not a defined term in C++

- source/utilities.tex
Add missing `\tcode` in [unique.ptr.runtime.ctor]/2.2.
> [unique.ptr.runtime.ctor] Fix format

- source/basic.tex
- source/declarations.tex
- source/expressions.tex
"one's complement" is inconsistent with the C standard.
"1's complement" and "2's complement" are also inconsistent.
FYI, I found that there was a lengthy discussion on Wikipedia at 2011
about "one's complement". The C++ standard was mentioned as a notable
use of "one's complement". There seems no consensus in the discussion,
but the main article has been settled as "ones' complement" for years
since then.
https://en.wikipedia.org/wiki/Ones'_complement
https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Computer_science/Archive_10#Ones.27_complement_or_one.27s_complement.3F
For me, a quote from "Art of Computer Programming, Volume 2" by
Donald E. Knuth is convincing.
https://books.google.com/books?id=Zu-HAwAAQBAJ&pg=PT343
> ... A two's complement number is complemented with respect …
> Uniform "ones' complement" and "two's complement"

- source/macros.tex
No PDF diffs
This change allows the `\Cpp` macro to be used in PDF bookmarks once again following PR #579.
> [macros] Make \Cpp work in PDF bookmarks again

- source/utilities.tex
> [utilities] Add some hyphenation hints for long inline expressions

- source/compatibility.tex
Change for `&&` in [diff.cpp03.expr] should refer to [expr.log.and] rather than [expr.log.or].
> Fix wrong reference

- source/declarations.tex
Please always check that your source code uses only basic characters:
grep -P -n "[\x80-\xFF]" *.tex
> [dcl.attr] Fix wrong source encoding

- source/lib-intro.tex
The defintions introduced in clauses 1.3 and 17.3 are
ordered alphabetically, other than the trailing
definition for 'constant subexpression', that I am
guessing was added at a later date.  This change
simply moves it into the correctly sorted place in
the sequence.
> [defns.const.subexpr] Place defintition in alphabetical order

- source/declarators.tex
The example is modified from the old example, which used the name `B`; the constructor name should be `base2` here.
> [dcl.init.aggr] Fix an example in extended init.

- source/compatibility.tex
This change was clearly introduced in C++17, at the same meeting
as removing the meaning of the register keyword.  I can see no
Core issue tied to this removal being resolved as a DR against
14 or earlier.
I have confirmed that paper p0002r1 applied this to the C++17
annex, but was listed as a change in annex D rather than clause
5 - the latter change seeming the consistent editorial policy
for removed Core features, so retained.
> Move removal of bool++ from C++14 compatibility annex to C++17 annex

- source/classes.tex
The fact that local classes shall not have static data members is already stated in [class.local]/4 with the exact same wording.
> Remove redundant constraint in [class.static.data]

- source/algorithms.tex
- source/atomics.tex
- source/containers.tex
- source/diagnostics.tex
- source/future.tex
- source/iostreams.tex
- source/lib-intro.tex
- source/locales.tex
- source/macros.tex
- source/numerics.tex
- source/regex.tex
- source/strings.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
This is a single commit extracted from PR #238 which seems abandoned. This commit had been deemed useful, so I copied it and rebased it so it can be applied.
No PDF diffs.
> Replaced \note with \remark and \notes with \remarks.

- source/numerics.tex
The `T init` overload for `inclusive_scan` is missing a template parameter `class T`. Also fixed the `<numeric>` synopsis in [numeric.ops.overview].
> [inclusive.scan] Add missing template parameter.

- source/preprocessor.tex
function-like and object-like were being defined as grammar terms when they are not, and this is confusing with the term of art definitions in p10.
> [cpp.replace] Remove a bogus grammar term

- source/utilities.tex
This change consolidates some of the sprawl occurring in clause 20,
by moving the integer sequence utilities, which are part of the \<utility>
header, adjacent to the rest of the \<utility> documentation, between
the main \<utility> doc and pair, while retaining the pair doc as a
separate subsection adjacent to \<tuple>.
Considered making the integer sequences a subsection nested in 2.2,
but decided that it must have been pulled out into its own separate
sub-clause for a reason.
> [intseq] consolidate <utility> docs

- source/utilities.tex
The preferred style since C++14 is to use the _t alias
rather than the trait::type formulation for transformation
traits.  As a second fix, the types in the common_type
instantiation are, in turn, dependant types so require a
leading typename keyword.  I double-checked elsewhere and
we are consistent to use typename where requrired inside
other expressions, even though it is frequently omitted
when the named type is used within the surrounding
English text.
> [unique.ptr.special] prefer use of common_type_t

- source/utilities.tex
Prefer to use the _t alias to the old trait::type formulation
when specifying the place-holder name for defining
tuple_element of a cv-qualified type.  This neatly sidesteps
the question of whether there is a missing typename in the
subsequent usage, or whether that would be implied in the
use of the place-holder.
> [tuple.helper] prefer to use tuple_element_t

- source/locales.tex
In [locale.ctype.members], the returns clause for locale::narrow refers
to "high". For correct binding, the corresponding parameter should be
named as such.
> Add name "high" to locale::narrow in [category.ctype]

- source/containers.tex
Deque introduces itself in terms of vector, to describe the idea of
random access iterators.  This is perhaps more confusing that simply
directing the reader to the clause for random access iterators.  For
C++17 we introduce the category of contiguous iterators for vector,
array, and string, and we do not want to confuse the reader into bad
assumptions.  Meanwhile, the notion of iterators is much more widely
understood than in 1998, so pointing directly to the appropriate
clause is more likely to help the reader than a potentially misleading analogy.
> [deque.overview] deque should not reference vector

- source/utilities.tex
Fix the font for the use of INVOKE in the two new additions
to table 54, is_callable and is_nothrow_callable.  Considered
adding a new \invoke command and applying that consistently,
but decided I am not a LaTeX hacker yet, and took the easy
way out.
> [meta.rel] Fix for for INVOKE in table 54

- source/lib-intro.tex
Two move operations for the allocators refer to `a` or `a1`, though the code uses `u`.  Fix the description to match the code.
Also, change the phrase "equals" to "is equal to", which matches other uses in the standard (see [unique.ptr]/4.1 for an example).
> Fix incorrect variable references

- source/compatibility.tex
CWG1560: Gratuitous lvalue-to-rvalue conversion in
conditional-expression with throw-expression operand
http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1560
The change had been made between C++11 and C++14.
> [diff.cpp11] Supply a compatibility note for CWG1560

- source/utilities.tex
This patch addresses https://github.com/cplusplus/draft/issues/544.
Update all use of 'void' in type traits tables to use the codified
form \tcode{void}.  There was one use of the phrase "void types"
that I deliberately chose to not touch.
A second issue I stumbled over in this edit was inconsistent use
of cv-qualified vs. \cv-qualfied.  The latter seemed preferable,
so I applied that formatting consistently through this file for
all uses of cv-qualified that were not otherwise participating
in mark-up.
> [meta.unary.prop] Consistent formatting for 'void'

- source/algorithms.tex
MeowIterator is not a named requirement, so reworded as "shall satisfy
the requirements of a meow iterator", consistent with the wording in
[algorithm.general]/5. Added cross-references to [meow.iterators], and
to [iterator.requirements.general] for "writable".
Partially addresses #697 and #696.
> [alg.random.sample] reword and add cross-reference

- source/algorithms.tex
- source/numerics.tex
Add cross-references to [iterator.requirements.general] for "writable"
for [alg.replace], [alg.fill], [alg.partitions], [partial.sum] and
[adjacent.difference].
Fixes #697.
> [algorithms] [numeric.ops] Crossref "writable"

- source/iostreams.tex
There's no way `os << put_money(...)` could be a formatted *input* function; presumably a formatted *output* function is meant. Also add cross reference to [ostream.formatted.reqmts].
> [ext.manip] fix typo in put_money description

- source/utilities.tex
Currently p6 appears in the same line as p5.
> [util.smartptr.enab] make p6 appear in its own line

- source/containers.tex
- source/future.tex
- source/iostreams.tex
- source/iterators.tex
- source/locales.tex
- source/numerics.tex
- source/regex.tex
- source/strings.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
This set of changes replace (almost) all use of 'typedef' in the library with a type alias instead:
typedef Original NewName;   ->    using NewName = Original;
Attention was paid to retaining table-like formatting where present, which is worth reviewing in case I made idiosyncratic choices.
Clause 20 has NOT been applied, as that clause is churning a bit at the moment, and I don't want a conflict there to hold up a this review.  The most likely conflict is my own pull request:
https://github.com/cplusplus/draft/pull/683
I will happily rebase and complete the work once that branch lands (or is deferred again until this branch completes)
A second set of changes that should follow are to update the text that refers to typedefs to perhaps use a term more consistent with the type alias syntax …
> [18-30] Replace typedefs with alias

- source/utilities.tex
This patch simply moves the scoped allocator clause to
be adjacent to the other memory and allocator clauses
for a more consistent sub-organization of clause 20.
The patch looks pretty awful thanks to the diff
algorithm treating it a lot of interspersed edits,
where in fact is way a single cut/paste for the
bulk of the test (plus a second one-liner for the
clause 20 table of contents).
> [allocator.adaptor] consolidate memory utilities

- source/utilities.tex
The index entry for 'operator<' of the 'duration' class template is
associated with an unknown 'idxl' type, instead of 'duration'.
> [time.duration.comparisons] Fix index entry for duration operator<

- source/strings.tex
The first issue is that operator<< does not group in the index with
other definitions for operator<<, which use an index key of
operator\shl.
The second issue is that operator<< was the only operator indexed
under the 'basic_string_view' key, where the precedent fro basic_string
and other types is that the free-function operators are still indexed
under their respective class entry.
> [string.view.comparison] Fix index for basic_string_view operators

- source/compatibility.tex
> [compatibility] Add compatibility notices for pp-number

- source/containers.tex
- source/iostreams.tex
- source/iterators.tex
- source/locales.tex
- source/strings.tex
- source/support.tex
- source/utilities.tex
Several old index entries use '\tcode' to force a code
font on their sub-entry.  This is no longer necessary,
as the LaTeX scripts produce the correct font for an
'\idxcode' entry.  However, using '\tcode' inconsistently
will produce duplicate entries, and entries that do not
sort correctly.  This change set consistently applies
'\idxcode' in preference to '\tcode' to eliminate the
redundant and mis-sorted entries.
Note that this change-set does NOT change '\tcode'
entries for constructors, as those are handled separely
by https://github.com/cplusplus/draft/pull/740
> [18-27] Remove tcode from index entries

- source/support.tex
Simple typo where the index (but not the main text) refers to <stdarg.h> as <staarg.h>.
> [support.runtime] Fix name of stdarg.h in index

- source/containers.tex
- source/diagnostics.tex
- source/future.tex
- source/iostreams.tex
- source/iterators.tex
- source/numerics.tex
- source/regex.tex
- source/support.tex
- source/utilities.tex
The preferred way to list constructors in the index is under the
non-code font term 'constructor', but many classes retain old
text that lists the constructor under the class name as the same
class name, in a code font.  Worse, there are quite a few classes
that have fallen into a hybrid approach, with both listings, which
can be confusing. This change-set should catch every constructor
indexed in the old style and consistently transform it to the new.
One additional fix is that allocator_traits mis-indexed the static
member functions 'construct' and 'destroy' as the plain-text
constructor and destructor.  This patch correctly indexes them as
their correct name, in a code-font.
> [18-28] Fix index entry for constructors

- source/support.tex
This adjusts the index entries for `bad_cast::what` and `bad_exception::what` to be nested consistently with `bad_alloc::what` and `bad_array_new_length::what`
> [bad.cast], [bad.exception] nest index entries consistently

- source/numerics.tex
This applies the fix supplied in editorial issue https://github.com/cplusplus/draft/issues/160
Confirmed with both LWG Chair and Project Editor that it is reasonable
to fix this example editorially, rather than via LWG issues process.
> [valarray.sub] Fix error in example code

- source/expressions.tex
- source/support.tex
- source/utilities.tex
Appply a simple, consistent pattern to the index entries, including
th index of implementation defined behaviors, for the library types
that derive from std::exception.
In some cases this means adding entries, in others removing extra
nested implementation-defined entries that are redundant since the
addition of the index of implementatio defined behaviors.
A few cross-references were added or corrected as part of this
process.
Further work to make the presentation and specification of these
types probably requires LWG issues.  In particular, bad_any_cast
is woefully underspecified.
> [18,20] Consistent indexing of simple exception types

- source/classes.tex
- source/declarations.tex
There's a spurious definition of layout-compatible hiding in dcl.enum when it really lives in basic.types.
> [dcl.enum] This is not where layout-compatible is defined

- source/iterators.tex
N4296 24.5.1.2/2 says
>Additionally, Iterator shall meet the requirements of a Random Access Iterator (24.2.7) if any of the members operator+ (24.5.1.3.8), operator- (24.5.1.3.10), operator+= (24.5.1.3.9), operator-= (24.5.1.3.11), operator \[] (24.5.1.3.12), or the global operators operator< (24.5.1.3.14), operator> (24.5.1.3.16), operator <= (24.5.1.3.18), operator>= (24.5.1.3.17), operator- (24.5.1.3.19) or operator+ (24.5.1.3.20) are referenced in a way that requires instantiation (14.7.1).
The operator<, operator>, operator <=, etc mentioned here do not live in the global namespace, but the current wording can be read as implying so.
> [reverse.iter.requirements] Avoid saying 'global operators'

- source/future.tex
- source/iostreams.tex
- source/support.tex
- source/utilities.tex
This patch makes consistent use of the 'override' contextual
keyword for every member function (other than destructors)
that overrides a virtual function in one of its base classes.
In general, this came down to one of three cases:
1) the 'what' function for an exception class
2) the allocation functions of a memory resource
3) the implementation methods of a stream buffer.
As far as I can tell, all other virtual function declarations
in the standard library are intended as customization points
for users, and are not overriden in the standard itself.
This pull request addresses https://github.com/cplusplus/draft/issues/751
> [18-20,27] Prefer to use 'override' where appropriate

- source/macros.tex
This aids collation for situations where the index entry contains underscores. The `underscore` package changes the underscore command (`\_`) to do something fairly complex (e.g. adding a hyphenation hint), which isn't easy to index.
No visual diffs.
> [macros] Replace cooked underscore with raw version

- source/declarations.tex
We use a leading article for many other sections, and this implements the common style advice to not start a sentence or heading with a symbol.
> [dcl.spec.auto] Add 'The' to heading

- source/numerics.tex
The index currently lists the named member-functions of valarray as
if they were free functions - this adds the corresponding entry under
the valarray listing in the index, alongside the existing entries for
the many operator functions. It also fixes the entry for "size()".
> [valarray.members] Fix up index entries for named valarray member functions

- source/iostreams.tex
- source/strings.tex
- source/utilities.tex
> [input.output,strings,utilities] Don't format informative 'see below' as code

- source/containers.tex
- source/diagnostics.tex
- source/numerics.tex
- source/utilities.tex
The library clauses have started to make inconsistent use of the _v
variable templates for traits, in preferene to directly querying
trait::value.  This change set applies that change consistently over
all existing wording, where there is a choice of which form might
be used.  It does not make any changes where the _v variable is not
aviable, or is being defined in terms of the corresponding ::value.
This may want a second pass by someone better able to pay attention
to desirable line-breaking.
> [19-26] Consistent use of _v

- source/grammar.tex
- source/macros.tex
- tools/grambase.tex
This avoids having one environment depend on another, which makes extraction impossible.
> [macros,gram] Simplify definition of non-copying grammar environments

- source/utilities.tex
The *unordered* associative containers do not use default_*order*.
> [func.default.traits] remove crossref to [unord]

- source/lex.tex
> Make universal-character-name \grammarterm'd

- source/iostreams.tex
Some work remains to properly index all of the free (namespace scope) functions.
Will review other clauses later, especially those clauses with lots of additions for C++17.
> [clause 27] Index all member functions in clause 27

- source/support.tex
Fix a couple of mis-indexed operators, and add index entries
for a few missing functions, most notably the new launder
function.
> [support] clean up index for clause 18

- source/iostreams.tex
Remove the second "method" in "The method of conversion method is unspecified."
> [path.type.cvt] remove redundant word

- source/compatibility.tex
Though Annex C is informative, it's better to keep the terminology similar to normative text, which is easier to refer.
> [diff.basic] Fix format and inexact wording

- source/diagnostics.tex
The only issues that turned up are missing '%' continuations
at the end of around half of the index entry lines.  This
patch consistently cleans that up, so that every index entry
terminates in a '%', but it is not clear that this has any
effect on the final rendering, and the patch could safely be
rejected.  The primary benefit is consistency, should we ever
want to write some follow-up tooling to analyze index entries.
Audit confirmed that every \begin{itemdecl} is indexed, and the
index entry matches the declared name(s).
> [diagnostics] audit index entries for clause 19

- source/declarators.tex
I suppose this was omitted when applying [P0135R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0135r1.html), as it's present in the paper.
> Add back function lvalues to [dcl.init.ref]/5.2.1.2

- source/lib-intro.tex
...in table 14 should be `<memory_resource>`.
> [Editorial] Typo <memory_resorce>

- source/support.tex
The new hardware interference constants are introduced
above the definition of their semantics with a codeblock,
rather than an itemdecl, macro.  Prefer the latter for
consistently introducing names that are about to be defined,
as this will simply auditing the text in the future, e.g.,
when trying to reivew that every itemdecl has a corresponding
library index entry.
> [hardware.interference] prefer itemdecl to codeblock

- source/atomics.tex
- source/containers.tex
- source/diagnostics.tex
- source/iostreams.tex
- source/iterators.tex
- source/locales.tex
- source/macros.tex
- source/numerics.tex
- source/regex.tex
- source/strings.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
The new command `\indexlibrarymember{C}{mem}` creates an entry `C!mem` and another entry `mem!C` in the index of library names. This makes it easier to always create both entries consistently.
Thanks to @AlisdairM for the idea and the prototype.
> Use new macro \indexlibrarymember to simplify the library index

- source/declarators.tex
`T1` and `T2` didn't have code formatting.
> Fix formatting in [dcl.init.ref]/4.2

- source/declarators.tex
- source/expressions.tex
- source/lib-intro.tex
- source/macros.tex
- source/preprocessor.tex
- source/utilities.tex
This involves modifying the `\indeximpldef` macro to strip out the bare arguments from a selection of commands that we use inside index entries, and using the bare text to create the collation key. Complex index commands need to use the new `\impldefplain` commands.
> [impldef] Collate index correctly

- source/utilities.tex
This constexpr specifier is present in the `<optional>` synopsis, but omitted from the detailed specification in [optional.object.observe]. (I understand I'm stretching the definition of "editorial" here. Please let me know if the editors feel this change is substantive, and I'll file a defect report with LWG.)
> Add constexpr to optional::value_or(U&&) &&

- source/templates.tex
Avoiding the line wrap results in reflow that affects 13 pages. The first two pages of diffs: ![diffs](http://eel.is/longlinediffs.jpg)
> [temp.deduct.call] Avoid line wrap in long comment.

- source/iostreams.tex
> [path.generic.obs] Escape backslash in string literal in example.

- source/diagnostics.tex
- source/iterators.tex
- source/numerics.tex
- source/strings.tex
- source/support.tex
- source/utilities.tex
* fix outright errors, indexing the wrong name
* fix errors of omission: every itemdecl is now indexed
* consistent ordering of indexlibrarymember{identifier}{class-name}
* escape newlines everywhere
* indexhdr entry for all headers
> Review of library index entries

- source/regex.tex
These two newlines are visible in the pdf as awkward whitespace.
I also tried a larger patch which removed trailing newlines and spliced adjacent codeblocks as well, but that seemed to have no visible effect.
> [re.traits] Remove excessive newlines from codeblocks.

- source/declarations.tex
- source/future.tex
(Of the two changes, only the change in [depr.ostream.members] has a visible effect.)
> [dcl.attr.deprecated, depr.ostream.members] Fix trailing whitespace in \tcode.

- source/utilities.tex
There is another use of "but not a union type" in this section, which will be captured in an LWG issue resolution (http://cplusplus.github.io/LWG/lwg-active.html#2358) in Chicago.
> [meta.unary.cat] Use core term non-union class type

- source/templates.tex
In this section, paragraphs 7, 8 and 9 are nested /inside/ paragraph 6 (they are part of the second item of the enumeration in paragraph 6). As far as I know, this is the only instance of nested paragraphs in the document.
LaTeX seems to allows this, and so technically there is no problem, but in my HTML conversion of the draft (http://eel.is/c++draft), this curiosity is very hard to deal with, to the point where I've resorted to branching the document and moving the paragraphs outside of the enumeration.
So this is a pull request for the odd chance that you guys either want to support the HTML version, and/or agree with me that nesting paragraphs inside eachother is a very dubious construct of limited value to begin with, to be avoided in any case. :)
Cheers!
> [temp.deduct.call] Don't nest paragraphs inside eachother.

- source/containers.tex
No visual difference in the PDF, but only because the line in question happens to wrap at the same place thanks to the narrowness of the table column. :)
> [associative.reqmts] Add missing line break.

- source/numerics.tex
There's nothing special about the math; mathematicians have long termed these functions as "special functions".  Because C++ also uses "special functions" as a different term of art (referring to copy c'tors, d'tors, etc.), we disambiguate by prefixing "mathematical".
> g/special math functions/s//mathematical special functions/

- source/threads.tex
(Note how the parameter type /is/ specified correctly in the synopsis at the start of the section.)
> [thread.thread.id] Consistently use an lvalue reference for operator<<'s first parameter.

- source/std.tex
(No visual difference in PDF.)
> Remove imports for unused packages: verbatim, fixme, and booktabs.

- source/lib-intro.tex
During all the discussion of overloading on language linkage with regards to the C library, we never noticed that `at_exit` and `at_quick_exit` are also overloaded.
@zygoloid, @jwakely: Is this simple change to the synopsis sufficient? Unlike for `qsort` and `bsearch`, I didn't mark these synopses entries up specially, because we actually specify these functions directly rather than by reference.
> [cstdlib.syn] Add missing extern-C/C++ overloads for at_exit, at_quick_exit

- source/future.tex
This review handles several topic related to the index of library names:
apply indexlibrarymember for all member functions other than constructors/destructors
consistent ordering of indexlibrarymember{identifier}{class-name}
every index macro has a trailing % to avoid accidental whitespace
ensure headers are indexed with synopsis
ensure every itemdecl has a library index entry
index all of the adaptable function typedef-names
> [depr] Reviewed index for Anndex D

- source/containers.tex
- source/iostreams.tex
- source/strings.tex
- source/threads.tex
- source/utilities.tex
in [string::compare] and [any.modifiers].
Also fix a missing `\tcode` in [variant.assign] discovered on the way.
> Remove redundant `this->` in library specification

- source/utilities.tex
Remove redundant <T> when passing an optional<T> parameter to a construtor or other member function.  The class definition is already correct, so this is just making the function specifications consistent with their original declarations.
> [optional.object.ctor] remove redundant <T>

- source/lex.tex
Add a cross-reference on the reversion of universal characters in raw string
literals, as it is far from clear that [lex.pptoken] is the place to look
for this rule, which is not spelled out clearly in the phase1/phase2 rules.
Remove a confusing pair of parentheses as it was not clear if the intent
was to make the parenthetical a note, which we have a better way to render,
or normative.  Given the requirement that universal characters behave
consistently, this seems normative, rather than a note.
Index raw string literals, which appear to be entirely lacking from the
main index.
> [lex.phases] Index and xref raw string literels

- source/support.tex
This paragraph is currently identical to the one in [new.delete.single], and should refer to the operator delete[] functions that this section deals with.
> [new.delete.array] Add missing [].

- source/future.tex
- source/support.tex
This change moves the deprecated declarations in the <exception>
header to Annex D, in a manner consistent with the library pattern
of fully specifying deprecated components and names in the deprecation
annex.
Then apply consistent wording across the library parts of the annex
describing how non-deprecated headers introduce the deprecated extensions.
Finally, ensure that the deprecated extensions to standard headers are
indexed as part of that standard header.
> [depr, exception.syn] Consistently move deprecated decls to Annex D

- source/threads.tex
This review handles several topic related to the index of library names:
apply indexlibrarymember for all member functions other than constructors/destructors
consistent ordering of indexlibrarymember{identifier}{class-name}
every index macro has a trailing % to avoid accidental whitespace
ensure headers are indexed with synopsis
ensure every itemdecl has a library index entry
index every class definition
> [thread] Index review clause 30

- source/containers.tex
> [container.node] Move sub-clause to after [sequence.reqmts]

- source/utilities.tex
Revise presentation of all functors in clauses 20.14.(5-8) to use a
formal Returns: clause, consistent with the conventions laid out in
clause 17, rather than ad-hoc presentation lacking any of the
recognised markers.
This turned into a substantial re-render.  In order to break up a
wall of code with occasional normative text, I have introduced a
subsection for each class.  Under each new subsection, I collect
the primary class template and the 'diamond' specialization, which
were previously separated by the intervening classes.
I believe these changes are strictly editorial, but please let me
know soon if you would rather see a CD ballot comment before
accepting an editorial change of this scale.
> [function.objects] Use formal Returns: clause for std functors

- source/declarations.tex
- source/overloading.tex
Ensure all index references to name hiding use the same whitespace character.
> [index] consistent indexing of name hiding

- source/declarations.tex
The main index for type specifiers was split in two, due to
alternate spellings as 'type specifier' and 'type~specifier'.
Consistently use the latter, as it was the dominant form.
> [dcl.type.simple] consistent indexing of type specifiers

- source/utilities.tex
Addresses parts of issue #916.
> [time.duration.nonmember] Add missing \tcode

- source/preprocessor.tex
On the point of redundancy: please correct me if I'm wrong, but my understanding is that /all/ the requirements in the C++ standard only apply to implementations compiling C++ translation units, in which case spelling it out in this instance seems unnecessary. :)
> [cpp.predefined] Make description for __cplusplus non-redundant and consistent with rest.

- source/lib-intro.tex
> [extern.names] Use \tcode when referring to namespace std.

- source/classes.tex
- source/derived.tex
- source/special.tex
Other places already use a space instead of a tilde, and this distinction currently results in two separate index key nodes.
> [class, class.derived, special] Write space in 'access control' consistently in index keys.

- source/expressions.tex
Only visual difference is that this removes the stray indentation at the start of the paragraph.
> [expr.reinterpret.cast] Fix indentation artifact by adding missing % after \indextext.

- source/basic.tex
- source/declarators.tex
- source/statements.tex
Btw, you may notice the inconsistency in whether parentheses are used after "see". That happens in a couple other places in the document as well, and I'll submit a separate patch for that.
> [basic, stmt, dcl.dcl] Move surrounding punctuation out of \grammarterm arguments.

- source/algorithms.tex
- source/basic.tex
- source/classes.tex
Nowhere else does the document use parentheses when "see" is written explicitly.
> [basic, class.this, algorithms] Remove parentheses after "see".

- source/statements.tex
The original note has become obsolete with f40f23d2c9b8de9eeeb781c4e7b90d056750535f.
> [stmt.iter] Remove superfluous and incorrect note

- source/intro.tex
The original example is wrong.
> [syntax] Use a different example

- source/containers.tex
In the table most types are defined as `X::key_type`, `X::value_type` etc., apart from `mapped_type`, which I assume is a typo.
> [associative.reqmts] Fully qualify 'mapped_type'

- source/basic.tex
- source/declarations.tex
- source/special.tex
- source/templates.tex
This removes the precedent of ".c" extension and makes the comments in this example consistent with the comments used in the example in [basic.def.odr]6.6. Also, vast majority of comments use a space after //. This commit adds the space to the few comments that don't.
> [temp.over.link] replace "file" with "translation unit", add space after //

- source/utilities.tex
> Editorial: execpol.vec was renamed to unsequenced

- source/intro.tex
- source/lib-intro.tex
Move the definitions of block and unblock to the clause 1
definitions subclause, rather than the library definitions
subclause, as the memory model relies on these terms.
> NB GB-29 (C++17 CD): [intro.defs] move block and unblock definitions

- source/grammar.tex
Annex A is a summary of grammar, but not only syntactic grammar. Even in contexts without need of grammatical disambiguation, pure syntactically handling (reduction merely based on parsing of the token stream without semantic information) of several context-sensitive constructs (e.g. _constant-expression_ and several kinds of _type-id_) has already been insufficient. Since the remained difference is acknowledged in the same paragraph, I think my change is also editorial. (On the contrary, ISO C may have more problems because it uses "syntax" everywhere.)
However, I have no idea to change `\indextext{summary!syntax}` ...
> [gram] Change "syntax" to "grammar".

- source/expressions.tex
I find the phrasing to be a little weird to just say "is undefined" and think it's nominally more clear to state that the behavior of the call is what's undefined.
> [expr.call]p1 Use a more idiomatic way to specify the expression has undefined behavior

- source/basic.tex
- source/classes.tex
- source/declarators.tex
- source/expressions.tex
- source/special.tex
To fix dead "links" and make the operator index entries more consistent.
> Fix lots of see/seealso references, especially regarding operators.

- source/expressions.tex
- source/lib-intro.tex
- source/regex.tex
- source/strings.tex
- [re.synopt, string.view.cons, string.view.comparison] table~/ref -> Table~/ref
- [expr.new] annex~/ref -> Annex~/ref
- [utility.arg.requirements] tables~/ref -> Tables~/ref
> [whole standard] fix typos (#647)

- source/iostreams.tex
> [istream.extractors] rename stable name from istream::extractors

- source/iostreams.tex
This is consistent with rest of the file.
> [iostreams] Refer to int values as nonzero instead of true

- source/basic.tex
Ensure all definitions of 'translation unit' sort together
in the index, with a common spelling of the white-space.
> [basic.link] consistent indexing of 'translation unit'

- source/compatibility.tex
> [diff.cpp11.lex] fix example for digit separators

- source/lex.tex
Provide a consistent indexing of integer, character, and string
literals - particularly regarding prefix and suffix entries that
were not completely indexed before.
> [lex.literal] consistent indexing of prefix and suffix

- source/algorithms.tex
- source/numerics.tex
- source/utilities.tex
Add a copy of the parallel algorithm signature below each corresponding
non-parallel signature in the specification for each algorithm in the
<algorithm> and <numeric> headers.  This is _mostly_ an exercise in
copy/paste - however a small subset of algorithms have wording that
either refers to the signatures obliquely, requiring a minor wording
tweak, or uses the 'Effects: as if ...' formulation, which requires a
separate specification for the parallel form to perfectly forward the
execution policy.
This change corresponds to (known to be pending) national body comments
requesting more clarity in the specification of each algorithm that has
a parallel overload.
A further tweak disambiguates the indexing of the various 'move'
functions.
> NB US-91 (C++17 CD): [algorithm][numeric] Specify all parallel algorithms

- source/support.tex
Fixes #343.
We should probably add a bullet to 1.2 "normative references", too, but that didn't exist before, so would be a more substantive change.
> [numeric.limits.members] replace IEC 559 by ISO/IEC/IEEE 60559

- source/locales.tex
> [facet.num.get.virtuals] Clarify 'fails to convert' for empty sequence

- source/declarations.tex
simple-type-specifiers.
Fixes #436.
> [dcl.type.simple] Add decltype(auto) to the table giving meaning to

- source/intro.tex
> [intro.execution] Adjust example to new rules for sequencing of

- source/expressions.tex
for a dynamic_cast to reference type.
Fixes #450.
> [expr.dynamic.cast] Remove redundant specification of value category

- source/compatibility.tex
- source/containers.tex
- source/special.tex
> [vector.bool] Excise use of undefined term 'conversion operator'

- source/expressions.tex
constant expressions.
Fixes #594.
> [expr.const] Avoid 'value' of a glvalue in definition of

- source/strings.tex
charT for basic_string specializations.
Fixes #198.
> [string.require] Add note that traits::char_type is the same as

- source/basic.tex
- source/declarations.tex
- source/declarators.tex
- source/locales.tex
Add missing spaces before examples and normalize an odd codeblock.
> [whole standard] Add a space before \begin{example}

- source/lex.tex
> [lex.ext] Add hyphen in index entry for user-defined literals

- source/declarations.tex
> [dcl.align] Avoid 'shall' for a requirement on the implementation

- source/strings.tex
Adds entries to the library index for every cstd... header
in the strings clause, pointing to their synopsis.
> [clause 21] Index cstd header synopses

- source/compatibility.tex
A section called "modifications to headers" should not fail to explain what happened to all the other C headers.
Part of Issue #1006.
> [diff.mods.to.headers] Explain what happened to meaningless C headers

- source/basic.tex
- source/compatibility.tex
- source/exceptions.tex
- source/expressions.tex
- source/lib-intro.tex
- source/utilities.tex
> Replace 'run-time' by 'runtime' for consistency.

- source/utilities.tex
memory.resource -> mem.res
optional.bad_optional_access -> optional.badaccess
memory.polymorphic -> mem.poly
func.searchers -> func.search
... boyer_moore -> ... bm
... boyer_moore_horspool -> ... bmh
Fixes #794.
> [utility] shorten stable names

- source/containers.tex
- source/numerics.tex
- source/special.tex
> Change 'result is undefined' to 'has undefined behavior'

- source/compatibility.tex
> [diff.cpp03.input.output] Use code font for 'explicit'

- source/compatibility.tex
- source/support.tex
for meta-variables in offsetof description, not \textit and not \grammarterm.
Fixes #456.
> [support.types.layout], [diff.offsetof] Use \placeholder

- source/basic.tex
Also removes \term from the introductory note in 3p1 and uses \defnx instead of separate \term and \indextext where applicable.
diffpdf shows only whitespace differences in the main body, plus one slightly moved footnote. The index has a few more entries now, e.g. for "object, const".
> [basic] Replace \term with \defnx as appropriate

- source/basic.tex
- source/intro.tex
> [intro] Replace \term with \placeholder or \defn as appropriate

- source/intro.tex
remove redundant description of same-thread signal handler execution
Fixes #285.
(If something is sequenced before something else, it's also on the same thread. No need to say that again.)
> [intro.multithread] add 'std' to standard library names

- source/overloading.tex
> [over.match] 'underlying type' for a reference is undefined

- source/containers.tex
The tables that list requirements contain both expressions and variable definitions. Most of the standard is consistent in using semicolons after the variable definitions, but not after expressions. This patch fixes the deviations from that.
> [containers] Consistent semicolons in tables

- source/algorithms.tex
- source/atomics.tex
- source/containers.tex
- source/declarations.tex
- source/tables.tex
- source/utilities.tex
> Resolve some 'Overfull \hbox' warnings.

- source/lex.tex
> [lex] Replace \term with \placeholder or \defn as appropriate

- source/numerics.tex
This is the analog to ballot comment JP-21, ordering the
Requires/Effects/Returns clauses correctly through clause
26.  A couple of re-orderings are deliberately skipped,
due to a dependency in the wording, introducing terms in
the out-of-order elements.
> [numeric] Order elements correctly

- source/diagnostics.tex
Move definitions of less-than operators to [syserr.compare]
Fixes #880
> [system_error.syn] [syserr.compare] Declare all nonmembers in the synopsis

- source/containers.tex
The allocator requirements already require move construction to not throw, so there's no need to repeat it here.
> [container.requirements.general] Remove redundant Requires

- source/atomics.tex
Reverse class/member names in indexlibrarymember macros to be
consistent with the prefered style in other clauses.
Expand in the index several functions that are documented as a
pattern-match, such as fetch_add and fetch_sub.
Use 'atomic<type>' rather than 'atomic type' for index references
to the atomic template.  This allows for a more intuitive indexing
of the conversion operator.
> [atomics] Clean up indexing of atomics clause

- source/utilities.tex
Also includes the changes to [ans.cons] p9 from P0504R0 (LWG Motion 19)
which modify the same paragraph.
> LWG2754 The in_place constructors and emplace functions added by P0032R3 don't require CopyConstructible

- source/declarators.tex
> [dcl.ref] Introduce the phrase 'reference collapsing' in a note.

- source/declarators.tex
- source/exceptions.tex
- source/overloading.tex
- source/utilities.tex
diffpdf shows no differences other than the two cv-qualified -> \cv{} replacements.
> Replace \textit{cv} with \cv{} or \cvqual{...} as appopriate.

- source/threads.tex
> [futures.overview], [futures.async] Use 'bitmask type' terminology.

- source/algorithms.tex
- source/lib-intro.tex
- source/numerics.tex
> [library] Use \effects etc. when referring to them in text

- source/intro.tex
Provides a case where side effects to the same memory location are unsequenced. Also removes an unreferenced function declaration.
> [intro.execution] Adjust example for unsequenced side effects

- source/iostreams.tex
Also replace cross-references referring to their own section with 'above'.
Fixes #702.
> [istream], [ostream] Remove paragraph numbers in cross-references.

- source/iostreams.tex
> [quoted.manip] operator>> is not a member of basic_istream.

- source/iterators.tex
for output iterators.
Fixes #698.
> [iterator.requirements.general] Rephrase definition of 'writable to'

- source/expressions.tex
- source/macros.tex
This command is only used once, and it has the same effect as `\caret`, except that `\exor` produces the wrong character.
> remove \exor command

- source/containers.tex
for sequence containers.
Any container is nowadays required to have forward iterators;
see the table entries for X::iterator and X::const_iterator in
[container.requirements.general].
Fixes #461.
> [sequence.reqmts] Remove redundant 'forward iterator' requirement

- source/basic.tex
> [basic.def.odr] Avoid counting bullets in normative text.

- source/basic.tex
- source/conversions.tex
- source/declarations.tex
- source/lex.tex
> Adjust italics and index entries for 'underlying type'.

- source/templates.tex
> [temp.deduct.call] Add example involving cv-qualifiers and references.

- source/compatibility.tex
Consistently end the 'Changes' phrase with a period.
Add missing newlines.
Remove spurious 'Rationale' item.
Fix typos.
Fixes #214.
> [diff] Miscellaneous fixes.

- source/algorithms.tex
- source/atomics.tex
- source/containers.tex
- source/iostreams.tex
- source/lib-intro.tex
- source/locales.tex
- source/numerics.tex
- source/regex.tex
- source/threads.tex
The standard library specifies that references to its names are assumed to be prefixed by '::std::'. Therefore, we can remove any explicit 'std::' prefixes.
[iterator.range] was not touched, because it is unclear whether argument-dependent lookup was intended to be disabled here.
Fixes #431.
> [lib] Remove 'std::' prefix from library names.

- source/iostreams.tex
Some of the logic in this section is needlessly convoluted. A slight rewrite makes the exposition more compact and fluent.
Before:
After:
> [streambuf.virtuals] Simplify the logic of exposition; remove several unneeded lists

- source/utilities.tex
> [meta.logical] Fix application of LWG 2567 and add further explicit boolean conversions editorially.

- source/utilities.tex
> [variant] Use \tcode for type designators, not math mode.

- source/threads.tex
> [thread.lock] Extract error conditions from 'Throws' element.

- source/algorithms.tex
- source/basic.tex
- source/classes.tex
- source/compatibility.tex
- source/conversions.tex
- source/declarations.tex
- source/derived.tex
- source/expressions.tex
- source/future.tex
- source/intro.tex
- source/iostreams.tex
- source/iterators.tex
- source/lex.tex
- source/locales.tex
- source/numerics.tex
- source/overloading.tex
- source/regex.tex
- source/special.tex
- source/std.tex
- source/support.tex
- source/templates.tex
- source/utilities.tex
> For some X, choose a consistent spelling between non-X vs. nonX.

- source/declarators.tex
This footnote
- is very large
- has very dense vertical layout in the pdf (as a result of being a footnote)
- uses unusual commands for its code formatting (\indent for indentation, \textrm for comments) 
- forgets to escape curly brackets in its tcode fragments, so they're missing in the pdf
- uses unusual commands for its prose formatting (\noindent)
- has unusual code formatting in the pdf (non-italic comments)
Some or all of these issues might be addressable individually, but the easiest way to fix them all in one fell swoop is to just turn this weird creature into a normal note that needs no special treatment or commands. :)
(I tried diffpdf's other comparison modes, but they produced even less useful coloring.)
> [dcl.decl] Turn very large footnote into ordinary note.

- source/special.tex
Fixes #490.
This should probably be reviewed by Richard. Note that I moved the "accessible" paragraph to the top, although I think that's redundant nowadays that we always perform overload resolution for copy/move, and access checking is on of the last steps there. Also, the "accessible" paragraph should say in which context the access is checked (existing defect).
> [class.copy] Introduce three subsections.

- source/classes.tex
initializer may prevent a defaulted special member function
from being implicitly deleted.
Fixes #1073.
> [class.union] Clarify in the note that a default member

- source/preprocessor.tex
non-directive is not a thing anymore (renamed to conditionally-supported-directive by CWG 2001) and the new name makes it clear that it's a directive.
> [cpp.replace] Delete obsolete footnote

- source/exceptions.tex
It seems "noexcept throw()" is ment to be split as different possibilities
> [except.spec] missing linebreak

- source/support.tex
I didn't notice these in https://github.com/cplusplus/draft/pull/977 because of the capitalization.
> [numeric.limits] Add missing \tcode around true

- source/basic.tex
- source/compatibility.tex
- source/derived.tex
- source/intro.tex
- source/iostreams.tex
- source/lib-intro.tex
- source/numerics.tex
- source/preprocessor.tex
- source/support.tex
Grep shows that putting commas and periods outside quotes is much more common.
> [whole standard] Put commas outside quotes

- source/basic.tex
- source/declarations.tex
- source/expressions.tex
- source/iterators.tex
- source/lib-intro.tex
- source/limits.tex
- source/special.tex
- source/templates.tex
- source/utilities.tex
> Do not use code font for constexpr constructor and constexpr function

- source/regex.tex
> [re.regex] Add missing 'multiline' constant.

- source/utilities.tex
This is a regular English phrase used as a technical term.
Fixes #1154.
> [utilities] Do not use CamelCase for 'BaseCharacteristic'.

- source/future.tex
- source/lib-intro.tex
> [headers], [depr.c.headers] Avoid brittle counts of headers.

- source/utilities.tex
Technical terms should not be in italics everywhere they are referenced.
Common terms such as 'owns' or 'empty' that are used as technical terms
in this subsection only are not italicized or entered into the index.
Fixes #533.
> [util.smartptr] Cleanse of italics infestation.

- source/algorithms.tex
- source/iostreams.tex
> [lib] Adjust whitespace to attach & to the type, not the declarator-id.

- source/algorithms.tex
- source/containers.tex
Harmonize the punctuation in complexity requirements where a definition
for N is introduced.
Add a missing closing parenthesis.
Add a full stop.
Fixes #191.
> [containers], [alg.transform] Minor presentation fixes.

- source/containers.tex
> [sequence.reqmts] Use placeholders for 'member functions of the form'.

- source/utilities.tex
> [intseq.general] Remove example not quite mirroring a standard function.

- source/access.tex
- source/basic.tex
- source/classes.tex
- source/compatibility.tex
- source/conversions.tex
- source/declarations.tex
- source/declarators.tex
- source/derived.tex
- source/exceptions.tex
- source/expressions.tex
- source/intro.tex
- source/iterators.tex
- source/lex.tex
- source/lib-intro.tex
- source/overloading.tex
- source/preprocessor.tex
- source/special.tex
- source/statements.tex
- source/templates.tex
- source/utilities.tex
Fixes #1064 and #664.
diffpdf doesn't really work here, because a lot of index entries are shuffled around (and are now sorted correctly).
> Remove tildes from index entries.

- source/support.tex
'inline' is doubly redundant here because these member functions are defined inside the class definition as well as constexpr.
> [numeric.special] Remove redundant 'inline' specifiers in example.

- source/numerics.tex
The `void` return type in the constructor is clearly an error, and I think adding `A::` to the member functions is good for clarity.
> [rand.req.adapt] Fix syntax error

- source/classes.tex
For reference, the C standard says `bit-field declaration`.
> [class.bit] Add missing "bit-" to "field declaration" in index entry

- source/strings.tex
Those quotes look really strange to me.
> [char.traits] Use \tcode around parameter name

- source/algorithms.tex
- source/atomics.tex
- source/containers.tex
- source/diagnostics.tex
- source/future.tex
- source/iostreams.tex
- source/iterators.tex
- source/lib-intro.tex
- source/locales.tex
- source/numerics.tex
- source/strings.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
> [lib] Add main index entries for all headers.

- source/utilities.tex
Other similar terms like *`INVOKE`*, *`DECAY_COPY`*, and *`GENERALIZED_SUM`* are always in code font and italics.
> [allocator] Format OUTERMOST in code font

- source/support.tex
Also add index entries for 'denormalized value' and 'value,
denormalized', pointing to 'number, subnormal'.
Fixes #1017.
> [limits] Use 'subnormal number' as defined by IEEE 754-2008 = ISO 60559.

- source/utilities.tex
This idiosyncrasy seems to have been partially copied from `pair`, but it has eventually been abandoned. We never name the constructor in any other class or class template description.
This shortening has the pleasant effect of simplifying some previously awkward linebreaks (#693).
> [pairs.pair, tuple.cnstr] Replace 'The constructor initializes' with just 'Initializes', which is how we say it in many other places.

- source/utilities.tex
Fixes #491.
(I agree that the formatting of the U_i indexed type-variables is dreadful in either case, but that is the subject of another issue.)
> [pairs.spec], [tuple.creation] Avoid 'equality' of types phrasing.

- source/utilities.tex
> [bitset.members] Remove confusing index entries for 'set' and 'any'.

- source/utilities.tex
> [utility], [bitset] Introduce a separate heading for the synopsis.

- source/containers.tex
Also reorder the elements so that 'Requires' is before 'Effects'.
Fixes #796.
> [list.ops] Move effects to 'Effects' element.

- source/declarators.tex
> [dcl.init.ref] Replace 'type qualifier' with 'cv-qualifier' in example.

- source/utilities.tex
The parameter has a confusing name: It is not actually the value type
contained in the 'any'.
Where the new T clashes with an existing use of T, rename the latter to VT,
since this is actually the value type of the 'any'.
Fixes #1202.
> [any] Rename the ValueType template parameter to T.

- source/containers.tex
- source/diagnostics.tex
- source/lib-intro.tex
- source/utilities.tex
When talking about an operator function, use the term defined in
[defns.comparison].
Fixes #612.
> [lib] Use 'comparison function', not 'comparison operator'.

- source/iostreams.tex
Remove now-empty 'Overview' sections.
Partially addresses #566.
> [input.output] Add numbered headings for synopses.

- source/algorithms.tex
> [algorithms] Add numbered heading for synopsis.

- source/lib-intro.tex
- source/macros.tex
[res.on.functions] Do not use \synopsis for emphasis.
Fixes #566.
> Remove \synopsis macro.

- source/intro.tex
The \defn on the next line already creates an index entry.
> [intro.races] Remove duplicated index entry for 'data race'.

- source/iostreams.tex
Diff:
This removes the most egregious instance in the document of a note spanning multiple numbered paragraphs, and I think it actually reads and looks nicer as an itemization (and with the examples marked as examples).
Thoughts? :)
> [path.non-member] Structure multi-paragraph note using an itemization instead.

- source/containers.tex
- source/iostreams.tex
- source/regex.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
My understanding is that we want to always end \returns and other elements in a full stop. The wiki (https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines) seems to agree with this, although it doesn't talk about all elements and there is one conflicting "*Returns:* `T{0}`" example.
I haven't gone through the whole draft so there are likely a lot more remaining. These are just ones I've noticed so far.
> [library] Add full stops to \returns etc.

- source/derived.tex
While I think this change is definitely merited on its own, its real significance is that it gets rid of the very last (as far as I can tell) multi-paragraph note in the document, thereby fixing half of #781.
> [class.derived] Don't bother splitting last remark in note off into separate paragraph.

- source/containers.tex
Replaces occasional uses of 'key equality function'.
Fixes #630.
> [unord] Use 'key equality predicate' consistently.

- source/iostreams.tex
to normative text.
Fixes #494.
> [iostream.forward.overview] Promote introductory sentences

- source/numerics.tex
Addresses #693 for this part, but is also clearer.
**Exclusive:**
Note that the range is *empty* when `K` is zero.
**Inclusive:**
> [{ex,in}clusive.scan]: Rephase 'for each *j' in terms of indexes

- source/basic.tex
- source/classes.tex
- source/conversions.tex
- source/declarations.tex
- source/declarators.tex
- source/exceptions.tex
- source/expressions.tex
- source/future.tex
- source/numerics.tex
- source/overloading.tex
- source/statements.tex
- source/support.tex
- source/templates.tex
- source/utilities.tex
As previously discussed with the Project Editor, changed (mainly in <type_traits> tables but also in other places) occurrences of "(possibly cv-qualified)" followed by a type (usually void, but also occasionally bool, etc.) by the \cv{} macro.  To avoid a line break after \cv{}, replaced the space by a tilde (i.e., by a non-breaking space).
> s/(possibly cv-qualified)/\\cv{}~/ and allied changes.

- source/special.tex
in a throw-expression or a return statement.
Fixes #712.
> [class.copy] Rephrase rule preferring a move constructor

- source/numerics.tex
to un-parenthesized.
Fixes #1250.
> [sf.math] Promote parenthesized parts of function names

- source/utilities.tex
> [unique.ptr.single.modifiers] Use 'if and only if' when calling deleter.

- source/access.tex
- source/basic.tex
- source/declarations.tex
- source/derived.tex
- source/iostreams.tex
- source/statements.tex
- source/templates.tex
With the exception of [facets.examples].
Fixes #781.
> Avoid \pnum inside examples.

- source/iterators.tex
with \tcode, not italics.
Fixes #550.
> [ostream.iterator], [istream.iterator] Format exposition-only members

- source/containers.tex
Older entries seem to start with a lowercase letter and only
have a full stop if a second sentence follows.  For newer
entries (initializer lists, node_handle functions), apply
that style, too.
Fixes #328.
> [associative.reqmts] Harmonize capitalization.

- source/utilities.tex
(Obviously a typo since there is no "T" in scope.)
Also trim trailing whitespace in utilities.tex.
> Fix typos in [mem.poly.allocator.mem]/9.1 and /9.5

- source/containers.tex
to avoid 'Overfull hbox' warnings.
Partially addresses #693.
> [unord.req] Split column heading into two rows

- source/containers.tex
with \requires and \postcondition, respectively.
Fixes #792.
The number and location of overfull hboxes in this section is exactly the same before and after the change.
> [containers] Replace pre: and post: in requirements tables

- source/derived.tex
(Note the proper alignment in the member declarations for class Base, earlier in the same example.)
> [class.virtual] Adjust whitespace to fix vertical alignment in code example.

- source/basic.tex
- source/declarators.tex
- source/expressions.tex
- source/iostreams.tex
- source/special.tex
- source/templates.tex
For consistency. This only modifies non-mid-sentence notes.
Addresses #293.
> Capitalize notes.

- source/derived.tex
Currently there is no index entry for covariant return types. Diff:
> [class.virtual] Add index entry for covariant return types.

- source/limits.tex
This is the only place where "try block" uses code font for the first word.
> [limits] Use normal font in "try block"

- source/statements.tex
> [stmt.stmt] Remove stray {} after \grammarterm.

- source/basic.tex
(The whitespace is visible in the PDF.)
> [basic] Remove stray whitespace after \tcode{...}

- source/expressions.tex
> [expr.unary.noexcept] Use \grammarterm{expression}, not \tcode.

- source/utilities.tex
P0435R1 says 'cv void', but the cv part was dropped.
> [meta.trans.other] add missing cv for common_type

- source/derived.tex
Some instances were overlooked in the previous patch.
Fixes #781.
> [class.derived] Avoid \pnum inside examples.

- source/utilities.tex
> [util.smartptr.enab] Remove leftover postcondition after P0033R1.

- source/numerics.tex
> [sf.cmath] Fix 'where' associations of Greek variable names.

- source/regex.tex
(... and remove an invisible but unnecessary pair of curlies.)
> [re.submatch.op] Remove excessive parentheses in "Returns:" element.

- source/declarators.tex
The typo was from [p0490r0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0490r0.html).
> [dcl.init] Fix a typo in definition of const-default-constructible

- source/numerics.tex
in which initialization is described.
Fixes #1331.
> [rand.adapt.shuf] Show exposition-only members in the order

- source/numerics.tex
The use of double dollars for math is an old TeX practice that is discouraged in LaTeX.
This patch removes the only two uses of double dollar math in the document.
No visual difference (because `\[...\]` is equivalent here).
(Incidentally, this helps my HTML version of the standard, because cxxdraft-htmlgen uses HaTeX, a Haskell LaTeX parsing library that does not support archaic double dollar math.)
> [class.gslice.overview] Replace $$...$$ with \[...\].

- source/compatibility.tex
- source/diagnostics.tex
- source/expressions.tex
- source/iostreams.tex
- source/iterators.tex
- source/lex.tex
- source/locales.tex
- source/macros.tex
- source/numerics.tex
- source/overloading.tex
- source/regex.tex
- source/strings.tex
- source/templates.tex
- source/threads.tex
- source/utilities.tex
Visible differences are:
1) inserts missing whitespace:
2) reorders some index entries, e.g:
> Remove \shl and \shr.

- source/classes.tex
- source/declarations.tex
- source/declarators.tex
- source/expressions.tex
- source/overloading.tex
- source/special.tex
- source/statements.tex
- source/templates.tex
> Replace \nonterminal with \grammarterm or \cvqual, as appropriate.

- source/numerics.tex
For consistency with the start of the paragraph, where T is defined as an ordinary math function.
Using `\left(` and `\right)` instead of plain `(` and `)` here seems to have no effect other than introducing unwanted whitespace between the T and opening parenthesis.
Diff:
> [rand.util.seedseq] Consistently format T(...) as ordinary math, not code.

- source/basic.tex
- source/overloading.tex
- source/utilities.tex
The rest of the document already uses \tcode directly inside math, which works fine.
No visual difference.
(Incidentally, this helps my HTML version of the standard, which relies on MathJax, which sadly does not support \texttt inside \text inside math.)
> In math, do not needlessly wrap \tcode inside \text.

- source/exceptions.tex
with \grammarterm or \defn/x as appropriate.
Also add an index entry.
Partially addresses #701.
> [except] Replace \term and \textit

- source/expressions.tex
- source/locales.tex
- source/templates.tex
> Remove stray whitespace around scope resolution operator.

- source/declarators.tex
No visual difference in the PDF, but it makes the source look nicer and more consistent.
(Incidentally, it makes life a tiny bit easier for cxxdraft-htmlgen.)
> [dcl.fct] Make bnf indentation in source match presentation.

- source/compatibility.tex
For consistency with all the other `\change`s.
Only visual difference is removal of the unwanted whitespace, and resulting reflow.
> [diff.expr] Remove stray paragraph break.

- source/compatibility.tex
- source/utilities.tex
I believe this patch catches the last two places in the current
draft that should be using a variant of the \Cpp macros to
better render the 'C++' string.
> Fix remaining uses of \Cpp macro

- source/declarators.tex
The comment easliy fits on one line:
> [dcl.ptr] Remove unnecessary line break in comment in example code.

- source/declarations.tex
- source/statements.tex
> [stmt.stmt], [dcl.attr.deprecated] Remove hyphen in 're-declared'

- source/basic.tex
- source/conversions.tex
- source/expressions.tex
- source/lex.tex
- source/support.tex
Adjust occurrences that spanned a line break in the LaTeX
source and were therefore missed in commit
cd3deb891cee5436a64ff9a8f7bb304a4fcc6c00.
> 'floating-point something', not 'floating point something'

- source/algorithms.tex
- source/atomics.tex
- source/future.tex
- source/intro.tex
- source/lib-intro.tex
- source/numerics.tex
- source/preprocessor.tex
- source/templates.tex
For consistency with all other occurrences.
A related question is whether all occurrences of "this Standard" should really say "this International Standard". (IMHO saying the latter over and over sounds pointless and pompous, but if it's to satisfy some legal requirement, perhaps we ought to do it consistently.)
> Consistently use 'this International Standard'.

- source/declarators.tex
First I thought "hey that semicolon should be styled like the one on line 368", but then I noticed that it shouldn't be a semicolon at all.
> [dcl.ambig.res] Describe example ambiguous case more clearly.

- source/expressions.tex
- source/intro.tex
- source/lib-intro.tex
- source/numerics.tex
- source/preprocessor.tex
> Remove space between period/comma and footnote reference.

- source/preprocessor.tex
[[cpp.pragma.op]](http://eel.is/c++draft/cpp#pragma.op) currently lacks numbered paragraphs altogether.
> [cpp.pragma.op] Add missing \pnums and remove unwanted paragraph breaks.

- source/declarations.tex
Mainly by removing the stray curlies in \term{}{unscoped enumeration}, but I took the opportunity to also merge it with its corresponding index entry, into a \defnx. (And then the same for "scoped enumeration").
> [dcl.enum] Italicize 'unscoped enumeration' in its definition.

- source/algorithms.tex
The \mathcal 'O' looks different from the \mathscr 'O' that \bigoh uses.
As far as I can tell, this is actually the only use of \mathcal in the document.
> [alg.heap.operations] Use \bigoh instead of \mathcal{O}.

- source/numerics.tex
By not abusing \emph for math. Diff:
> [valarray.members] Style unary minus sign as math symbol, not as hyphen.

- source/classes.tex
- source/containers.tex
- source/declarations.tex
- source/iostreams.tex
- source/locales.tex
- source/support.tex
- source/templates.tex
For consistency with the rest of the document.
> Don't parenthesize \refs after 'in'/'of'/'notwithstanding'.

- source/support.tex
After the synopsis for <cstddef>, add a sentence (cloned from cstdlib.syn)
that the contents are the same as <stddef.h> except for wchar_t,
[support.types.nullptr], and [support.types.layout].
Fixes #1404.
> [support.types] Properly describe <cstddef> header

- source/iostreams.tex
We should discuss this before merging, I'm ambivalent about it.
> [streambuf.virt.get] use half-open ranges in underflow effects

- source/algorithms.tex
- source/atomics.tex
- source/containers.tex
- source/iostreams.tex
- source/lib-intro.tex
- source/macros.tex
- source/numerics.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
Remove the \realnotes and \realnote macros.
No longer mention 'Notes:' in [structure.specifications].
Fixes #492.
> [lib] Replace 'Notes:' elements with regular [ Note: ... -- end note]

- source/macros.tex
- source/styles.tex
Removes minpages; adds custom enumitem list.
BNF entries are now spaced like normal paragraphs. Individual paragraphs are kept on a single page by setting a high widow penalty.
It is now immaterial whether multiple nontermdefs are contained in a single bnf environment, or whether each def is in its own environment. Pages can break between elements, not within.
> [macros, styles] Make BNF vertical spacing like that of normal paragraphs

- source/algorithms.tex
from [alg.modifying.operations].
For is_partitioned, create a new subsection [alg.is_partitioned]
under [alg.nonmodifying].
For partition_point, create a new subsection [partition.point]
under [alg.binary.search].
Fixes #289.
> [algorithms] Move non-modifying algorithms away

- source/declarations.tex
- source/templates.tex
when discussing template instantiations.
> [temp.deduct] Avoid talking about 'side effect' and 'evaluation'

- source/utilities.tex
> [meta.rel] Fix incorrect use of \grammarterm{return-statement}.

- source/lex.tex
unless the \grammarterm is intended.
Fixes #322.
> [lex.literal] Avoid references to plain 'literal'

- source/intro.tex
Btw, while looking at capitalized index entries, I also noticed a [weird index entry](https://github.com/cplusplus/draft/blob/master/source/overloading.tex#L334) for "Ben". Is that one an inside joke or reference of some kind?
> [intro] Uncapitalize index entries for 'sequenced before' and 'evaluate'.

- source/preprocessor.tex
These entries don't seem to add a lot of value.
> [cpp.preprocessor] Remove additional "implementation defined" index entries.

- source/iterators.tex
- source/numerics.tex
- source/utilities.tex
Also cross-reference the sections, not the tables, for
iterator requirements.
Fixes #696.
> [lib] Harmonize casing for 'shall meet the requirements of ... iterator'.

- source/statements.tex
> [stmt.dcl] Clarify footnote about deadlock avoidance.

- source/utilities.tex
Here is a slight simplification of [tuple.creation]. I bugged me that the introduction was defining things that were only tangentially useful. I changed it to introduce the concept of indexing into a pack only once, and I used the "variable-pack" notation (e.g. `TTypes`, `VTypes`) in all the functions in this subclause.
I will work on `tuple_cat` separately.
Before:
After:
> [tuple.creation] Simplify the introductory notation, and then use notation that matches the introduction.

- source/strings.tex
This removes remarks that literally repeat what was just stated, but leaves intact instances where the same remarks do _not_ repeat what was just stated, e.g. http://eel.is/c++draft/string.cons#28.
Representative diff:
> [strings] Remove remarks that repeat what was stated a few lines before.

- source/classes.tex
- source/containers.tex
- source/expressions.tex
- source/intro.tex
- source/iterators.tex
- source/special.tex
> Consistently italicize definitions' plural 's'.

- source/expressions.tex
This splits up a long paragraph that defines two complex terms ("cv-combined type" and "composite pointer type") using itemized lists. It reads and looks so much better to me this way that I suspect the \pnum was accidentally lost at some point.
> [expr] Split off definition of 'composite pointer type' into dedicated paragraph.

- source/basic.tex
- source/compatibility.tex
- source/exceptions.tex
- source/iostreams.tex
- source/support.tex
Consistently use \tcode{main}.
Add cross-references to [basic.start.main].
Fixes #1304.
> Harmonize formatting of 'main' function.

- source/conversions.tex
This is a long paragraph that describes two things:
- the conditions under which the conversion does not access the referenced object's value;
- the rules for determining the result of the conversion.
Doing this in two paragraphs seems clearer to me:
> [conv.lval] Split off description of conversion result into dedicated paragraph.

- source/iostreams.tex
- source/iterators.tex
- source/lib-intro.tex
- source/numerics.tex
- source/strings.tex
with \requires and \postcondition, respectively.
Also replace yields: with \returns and effect: with \effects.
Fixes #1281.
> [lib] Replace pre: and post: in requirements tables

- source/strings.tex
[[string.io]#2](http://eel.is/c++draft/string.io#2) and [#7](http://eel.is/c++draft/string.io#7) refer to "sentry object k", but the sentry object was never given that name.
> [string.io] Don't refer to sentry by name it was not given.

- source/atomics.tex
They aren't partial specializations -- there are no partial specializations of function templates.
> Cleanup "partial specializations" language in [atomics.syn]

- source/access.tex
- source/basic.tex
- source/classes.tex
- source/declarations.tex
- source/declarators.tex
- source/expressions.tex
- source/intro.tex
- source/iterators.tex
- source/overloading.tex
- source/special.tex
- source/templates.tex
> Capitalize examples where appropriate.

- source/preprocessor.tex
The comment easily fits on one line:
(See [expr.dynamic.cast]/5 for a code comment that already has identical formatting.)
> [cpp.concat] In example code comment, remove unnecessary line break and format code as code.

- source/compatibility.tex
- source/macros.tex
- source/special.tex
1. Removes the need to use `\textit{\textrm{...}}`to prevent the `columns=flexible` listings option from inserting unwanted spaces.
2. Improves spacing in a few places where that workaround was not yet used.
[diffs.pdf](http://eel.is/fullflexiblediffs.pdf)
> Use columns=fullflexible listings option.

- source/basic.tex
- source/declarators.tex
as non-static data member.
Addresses core issue 1985.
Fixes #396.
Consistently refer to 'array of unknown bound' not 'array of unknown size'; see [dcl.array].
> [dcl.init.aggr] Add example for array of unknown bound

- source/numerics.tex
Partially addresses #1071.
This is a first step. I've only inserted description elements such as \effects and \returns and removed boilerplate introductory phrases where appropriate.
> [numarray] Add standard description elements.

- source/numerics.tex
These are the only three occurrences of 'evaluates as' in the document.
> [valarray.access] 'evaluates as' -> 'evaluates to'.

- source/templates.tex
Thereby also improving the index.
> [temp] Replace \term with \defn or \placeholder

- source/basic.tex
- source/intro.tex
There were only a few references to the definition in
1.8 [intro.object], so drop that definition and refer
to 'an object's type' instead.
Fixes #511.
> Define 'object type' only once.

- source/lib-intro.tex
I took the opportunity to also merge it with its corresponding \indextext, into a \defnx.
Only visual difference is that the comma is unitalicized.
> [multibyte.strings] Move punctuation out of \term.

- source/utilities.tex
These renames were overlooked in commit 8b1f6cc8d73eec0306db1dec66f2da52a03ea274.
Fixes #1443.
> [any.assign] Rename T to VT.

- source/expressions.tex
fix naming of global deallocation functions.
Fixes #1417.
> [expr.delete] Remove bad index entry and

- source/containers.tex
LWG 2540 changed the hint for insert from 'q'
(a valid and dereferenceable iterator) to 'p'
(a valid, but not necessarily dereferenceable iterator),
but neglected to adjust the description text.
Fixes #1423.
> [unord.req] Insert hint is 'p', not 'q'

- source/basic.tex
- source/classes.tex
- source/declarators.tex
- source/expressions.tex
- source/iostreams.tex
- source/iterators.tex
- source/locales.tex
- source/macros.tex
- source/numerics.tex
- source/preprocessor.tex
- source/strings.tex
- source/support.tex
Explicit line-break hints are added after the :: where necessary.
Fixes #1359.
> Replace \colcol by ::

- source/algorithms.tex
Effect:
Unfortunately, while this stretches the \lfloor/\rfloor nicely, it also seems to introduce some extra space before the comma. Anybody know a trick to avoid that?
> [alg.min.max] Make lfloor/rfloor delimiters stretchable.

- .travis.yml
Per @tkoeppe's [suggestion](https://github.com/cplusplus/draft/pull/1468#issuecomment-280022177).
This adds a new build type to the Travis CI build which only checks for whitespace at the ends of lines. If it finds any, it will fail the build.
Having this test as a separate 'build type' makes it easy to determine whether the whitespace test failed or whether the PDF compilation failed.
Note: If we plan on adding more tests in the future (e.g., checks for other nonconformant usage)—which I'm in favor of—then I'd recommend we migrate the code from `.travis-ci.yml` to a separate shell script where we can write more succinct code. (Travis CI wraps the `.travis-ci.yml` code in its own function and hijacks the exit code `$?` variable, so we have to capture it to test it later. Within our own …
> Add Travis CI check for whitespace at the ends of lines.

- source/basic.tex
- source/conversions.tex
- source/expressions.tex
- source/numerics.tex
- source/strings.tex
Where a type contains embedded whitespace, such as 'long long',
the tex files have been inconsistent in rendering this as
'\tcode{long long}' or '\tode{long} \tcode{long}', even within
a list of such types.
This patch consistently reduces the numbwr of \tcode macros
by combining whitespaced keywords into a single \txode element.
There may be some minimal kerning adjustments through the use of
non-proportional whitespace, but I don't immediately see any
tezt reflowing.  The end result is source for the standard that
is easier to grep.
> consistent whitespace in \tcode types

- source/expressions.tex
See the definition at [conversions.tex#L536](https://github.com/cplusplus/draft/blob/master/source/conversions.tex#L536)
> [expr.mptr.oper] Use defined term 'null member pointer value'.

- source/classes.tex
- source/declarations.tex
- source/lib-intro.tex
The 'inline' specifier is defined in [dcl.inline];
adjust cross-references still pointing to [dcl.fct.spec].
Fixes #1458.
> Fix cross-reference for 'inline'.

- source/declarations.tex
Add rationale why a warning is not encouraged for this case.
Fixes #1470.
> [dcl.attr.nodiscard] Clarify example with reference return type.

- source/compatibility.tex
- source/locales.tex
As far as I can tell, these are the only 4 occurrences (out of 33 `main` functions in the document).
> [localization, diff] Omit superfluous 'return 0;' in main.

- source/lex.tex
- source/statements.tex
> [lex.ccon, stmt.ranged] Fix index entries that misuse \idxcode.

- source/basic.tex
The other two are similar (but harder to show due to reflow caused by this last one.)
> [basic] Use less monospace in index entries.

- source/declarators.tex
And fix \grammarterm misuse in the process.
Index entries do already exist for value-initialization, zero-initialization, list-initialization, default-initialization, and copy-initialization.
> [dcl.init] Add index entry for direct-initialization.

- source/intro.tex
- source/iostreams.tex
- source/lib-intro.tex
- source/macros.tex
to top-level clauses per ISO directives.
Modify \definition macro so we can more easily have definitions at
different depths in different lists.
> [intro] Promote "Scope", "Normative references", "Terms and definitions"

- source/lex.tex
The redirects should probably point to the indexed phrase "backslash character" (line 1202).
(Since cxxdraft-htmlgen linkifies index redirects, this also fixes broken links on http://eel.is/c++draft/generalindex)
> [lex] Complete index redirects to 'backslash character'.

- source/basic.tex
> [basic.types] Remove excessive references to [basic.type.qualifier].

- source/declarations.tex
- source/overloading.tex
- source/special.tex
- source/templates.tex
> Harmonize punctuation for 'ill-formed, no diagnostic required'

- source/macros.tex
Following the approach of http://stackoverflow.com/a/2785740.
> [macros] Remove terms-and-definitions entries from TOC and bookmarks

- source/utilities.tex
This harmonizes the use of 'constained value' across
optional, variant, and any, with appropriate index
entries.
Fixes #1401.
> [any] Use 'contained value' consistently.

- source/expressions.tex
The index entry for "::" redirects to "scope resolution operator", but the index entry for "scope resolution operator" is [itself](https://github.com/cplusplus/draft/blob/master/source/basic.tex#L1637) a redirect to "operator, scope resolution". Might as well redirect "::" directly to "operator, scope resolution" and save the reader a hop. :)
> [expr.prim.id.qual] Redirect '::' index entry directly to 'operator, scope resolution'.

- source/conversions.tex
- source/expressions.tex
- source/special.tex
> Consistently use repeated \indextext for index redirects with multiple targets.

- source/algorithms.tex
- source/containers.tex
and not $N \log(N)$ or other variants.
Partially addresses #1088.
> [lib] For showing complexity, use $N \log N$

- source/preprocessor.tex
> [cpp] Change index redirect from '#' to '# operator' (and same for ##).

- README.rst
Getting started on Ubuntu turns out to be a bit more complex than just getting latexmk and running with it. Building the documentation fails without these other packages installed, so we might as well mention that.
> Add instructions for helpless Ubuntu users like myself.

- source/classes.tex
- Changes the peculiar redirection entries "class nested" and "class local" to the more conventional "class, nested" and "class, local".
- Adds main index entries for "local class" and "nested class" (fixing some abuse of \grammarterm in the process)
[diffs.pdf](http://eel.is/classindex.pdf)
> Fix index entries for 'nested/local class'.

- source/basic.tex
- source/declarations.tex
- source/declarators.tex
- source/exceptions.tex
- source/expressions.tex
- source/special.tex
- source/statements.tex
Found a bunch more, not sure why I missed these in #1462.
> Move plural 's' out of \grammarterm.

- source/preprocessor.tex
For consistency with [line 691](https://github.com/cplusplus/draft/blob/master/source/preprocessor.tex#L691) and all other code commas in the bnf.
> [gram.cpp] Add space before comma in bnf.

- source/utilities.tex
LWG issue 2857 was applied verbatim, without noticing
that 'ValueType' had been previously changed to 'T'.
This makes things consistent by choosing 'T' as the
simpler form, more consistent with 'optional' and
'variant'.
> [any.modifiers] fix emplace return type for 'any'

- source/regex.tex
Correctly index match_result::ready, instead of the
non-existant match_result::status.
> [re.results.state] fix bad index for match_result

- source/basic.tex
- source/classes.tex
- source/declarators.tex
- source/expressions.tex
- source/overloading.tex
- source/statements.tex
- source/support.tex
- source/templates.tex
Thereby also improving the index.
> Fix misuses of \grammarterm.

- source/iostreams.tex
Addresses #1502 
This doesn't change the [class.*] names mentioned in the issue: [class.directory_entry], [class.rec.dir.itr], [class.directory_iterator], [class.file_status], [class.filesystem_status], [class.path]
> Change stable names for Filesystem subclause

- source/iostreams.tex
> [enum.copy_options] Rephrase restriction on copy_options values.

- source/atomics.tex
- source/declarations.tex
- source/lib-intro.tex
- source/tables.tex
For consistency with the other tables.
[diffs.pdf](http://eel.is/tableheaders.pdf)
In Table 140, I also changed the capitalization and italicization of the 'key' placeholder to match its appearance in the subsequent itemdecl.
> Consistently use bold font for table headers.

- source/atomics.tex
- source/numerics.tex
No visible difference. The 'underscore' package already makes `_` in text behave as `\_`.
> [rand, atomics] Don't needlessly escape underscores.

- source/numerics.tex
> [numerics] Use absolute-value markers in math mode.

- source/threads.tex
- source/utilities.tex
This changes pseudocode expressions of the form `INVOKE(f, t1, t2, ..., tN)` so that the index notation and ellipsis are in math mode, and so not mistaken for C++ variables or the `...` token.
[func.require]:
and:
[func.bind] already formatted the indices this way, but used code font for the `...` between the metavariables:
[func.memfn]:
[futures.task.members]:
and:
> Consistently use math mode for index notation and ellipses in INVOKE expressions

- source/utilities.tex
Looks like a copy-paste mistake, because the next one is is_signed.
Note that '!class' makes sense for is_signed's index entry because there is also an entry for 'is_signed!numeric_limits', but there is no other is_aggregate in the stdlib, so I removed the '!class' (making it consistent with the index entries for e.g. is_final and is_abstract).
> [meta.unary.prop] Fix index entry for is_aggregate.

- source/containers.tex
- source/support.tex
> [support.runtime, list.ops] Move non-code punctuation out of \tcode.

- source/basic.tex
> [basic.start.main] Remove space before plural 's'.

- source/iostreams.tex
> [filesystems] Change '!predicate' phrasing to 'predicate is false'.

- source/iostreams.tex
- source/numerics.tex
- source/strings.tex
Fix a few "compiler errors" in header synopses:
* missing semicolons in strings.tex
* parameter type in `long double hypot(...)`
* missing `class` in `template<class charT> T4 setfill(charT c);`
> Fix header synopses

- source/iostreams.tex
The problem was introduced by commit 0b640ed8.
> [streambuf.virt.put] Fix logic in overflow() effects specification.

- source/declarations.tex
The paragraph break is visible in the PDF.
> [dcl.attr.depend] Remove paragraph break before end of example.

- source/strings.tex
- source/support.tex
- source/utilities.tex
(Because [support.signal] is where 'signal-safe' is defined.)
> For 'signal-safe', refer to [support.signal] (21.10.4), not [csignal.syn] (21.10.3).

- source/basic.tex
Updated the Note describing "invalid pointer values" to refer to [basic.stc] rather than [basic.stc.dynamic.deallocation].
The relevant description of "invalid pointer values" reads:
"Indirection through an invalid pointer value and passing an invalid pointer value to a deallocation function have undeﬁned behavior. Any other use of an invalid pointer value has implementation-deﬁned behavior."
Previously the reference was correct, as this text was in [basic.stc.dynamic.deallocation]/4, but the text was moved to [basic.stc]/4 by P0137R1; without updating the reference.
The Note also incorrectly claims that using an invalid pointer value is always undefined, when it can be implementation defined in certain cases, but I did not fix this in this commit; as updating the reference makes this …
> Fixed ref to effects of invalid pointer values.

- source/exceptions.tex
I think an index entry for this term would be useful because it is used in 18.1p4 ([except.throw]), but not defined until 18.3p7 ([except.handle]).
> [except.handle] Add index entry for 'active handler'.

- source/iostreams.tex
- source/threads.tex
- source/utilities.tex
> Spell 'well-defined' with a hyphen when it is an adjective.

- source/templates.tex
See https://github.com/cplusplus/draft/blob/master/source/declarators.tex#L141
> [temp.deduct.type] Use \cv instead of \grammarterm{cv-list}.

- source/classes.tex
with their members.
Fixes #1624.
> [class.union] Only standard-layout unions are pointer-interconvertible

- source/atomics.tex
The "thus" part absolutely does not follow from the preceding note text, and isn't even correct on its own. Since this is a note I assume this is an editorial change and doesn't need an issue.
> Clarify a note on cmpxchg

- source/regex.tex
> [re.traits] Use \placeholdernc for a placeholder.

- source/expressions.tex
There are two things known as "object expression":
- the E1 in "E1.E2" ([expr.ref]/3)
- the E1 in "E1.*E2" ([expr.mptr.oper]/4)
Because currently only the first of these is indexed, this patch adds an entry for the second one.
> [expr.mptr.oper] Index second definition of 'object expression'.

- source/declarators.tex
- source/expressions.tex
- source/overloading.tex
- source/special.tex
- source/templates.tex
No visual difference.
Makes the check-whitespace CI check pass again.
> Remove trailing whitespace.

- source/utilities.tex
@burblebee, @zygoloid, @jwakely: the wording in http://wg21.link/P0463R1 seems needlessly verbose. I'd like to propose this simplification.
> [meta.endian] Simplify wording, avoid "shall"

- source/overloading.tex
The grammar production corresponding to the call syntax has _postfix-expression_ as the callee operand. [over.call.object] appears to refer to this operand as the _primary-expression_ in the syntax.
> [over.call.object] Reference postfix-expression in call syntax correctly

- source/special.tex
And move the surviving part of the note to before the
corresponding example.
Fixes #1674.
> [class.temporary] Remove note giving questionable implementation advice.

- source/declarators.tex
- source/derived.tex
- source/expressions.tex
- source/lib-intro.tex
- source/special.tex
- source/strings.tex
- source/threads.tex
- source/utilities.tex
No visual difference.
Makes some progress on #329.
> Replace \term+\indextext pairs with \defn(x).

- source/intro.tex
- source/iostreams.tex
- source/lib-intro.tex
- source/macros.tex
- source/regex.tex
> Remove need to redefine \definition.

- source/strings.tex
Superficially, this change removes a fair amount of duplication in the specification.
More importantly, though, this may be a step towards getting rid of those string effect tables that seem awkward and presentationally wasteful.
> [string.cons] Consolidate two functions into one description

- source/utilities.tex
... to `monotonic_buffer_resource&` for consistency with the default definition of the builtin assignment operator. This change has no normative effect, it only eliminates the inconsistency as a potential source of confusion.
Since the return type of deleted functions is not observable, this change is editorial.
> Change the return type of monotonic_buffer_resource's deleted assignment

- source/classes.tex
> [class.mfct.non-static], [class.this] Define and use cv member function.

- source/expressions.tex
> [expr] Use 'possibly converted' for discarded-value expression.

- source/iostreams.tex
- source/regex.tex
- source/strings.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
> Capitalize after "Effects:"/"Returns:"/"Throws:"/"Requires:".

- source/intro.tex
Per Directives Part 2, 16.5.5, definitions "shall not [...] end with a full stop".
> [defns.well.formed] remove full stop

- source/intro.tex
When making a normative reference to another document, all relevant
Technical Corrigenda are assumed and need not be listed explicitly.
Fixes ISO 1 (C++17 DIS)
> [intro.refs] Remove redundant reference to C11 Technical Corrigendum 1.

- source/overloading.tex
from the introductory text.
It has become out of date relative to the actual number, and listing a
number here is not useful.
Fixes NB JP 5 (C++17 DIS)
> [over.match.funcs] Remove the number of overload resolution contexts

- source/algorithms.tex
- source/basic.tex
- source/compatibility.tex
- source/declarations.tex
- source/diagnostics.tex
- source/expressions.tex
- source/future.tex
- source/intro.tex
- source/iterators.tex
- source/lex.tex
- source/lib-intro.tex
- source/numerics.tex
- source/strings.tex
- source/support.tex
- source/templates.tex
- source/threads.tex
referring to the document as a body of text.
Cases where that phrasing is used to compare this standard to other
revisions of the C++ standard retain this phrasing for clarity.
Fixes ISO 20 (C++17 DIS)
> Replace "this International Standard" with "this document" when

- source/iostreams.tex
- source/lib-intro.tex
- source/locales.tex
- source/numerics.tex
- source/templates.tex
- source/threads.tex
- source/utilities.tex
necessity to a different form.
Normative requirements use "shall". Advice to users uses "should".
Description of the behavior of the implementation that does not of
itself constitute a requirement uses the imperative mood.
Fixes ISO 21 (C++17 DIS)
> Convert "must"s in normative wording that do not indicate logical

- source/special.tex
> [class.copy.assign] Remove extraneous space before the first word of para 1

- source/threads.tex
We're referring to the function name, not trying to call it with no arguments.
> [futures.async] remove parens from DECAY_COPY()

- source/front.tex
- source/preface.tex
Fixes ISO 16 (C++17 DIS)
The main wording was supplied by the TC secretariat; the list of changes has been reviewed by the relevant working group chairs for correctness.
> Add Foreword.

- source/utilities.tex
> [mem.res.private] Remove misleading 'typical' in note.

- source/algorithms.tex
> [alg.count,mismatch,alg.equal] Fix indentation of declaration.

- source/derived.tex
> [class.virtual] Correct function names in example comments.

- source/iostreams.tex
This avoids the requirement to compare newoff to zero when the value of
newoff hasn't been determined.
> [stringbuf.virtuals] Rephrase DR 453 resolution for seekoff

- source/derived.tex
- source/numerics.tex
- source/special.tex
- source/utilities.tex
> Use 'well-formed' (with hyphen) consistently.

- source/layout.tex
- source/macros.tex
- source/styles.tex
Strongly discourage breaking between itemdecl and itemdescr.
Mildly discourage breaking before an itemized list.
Add stretchable vertical space between paragraphs and before listings.
Allow substantial whitespace at the end of a page.
Fixes #1752.
> [styles] Improve automatic page breaking

- source/declarators.tex
- source/templates.tex
> [dcl.decl, temp.deduct.type] Fix inappropriate uses of \grammarterm.

- source/containers.tex
- source/future.tex
- source/iostreams.tex
- source/locales.tex
- source/numerics.tex
- source/regex.tex
- source/strings.tex
- source/threads.tex
- source/utilities.tex
Even if no section reference is given, make them lowercase
and remove trailing colons.
Fixes #1709.
> [lib] Harmonize introductory comments in synopses

- source/containers.tex
- source/xrefdelta.tex
> [array] Dissolve single-item subclauses.

- source/declarators.tex
> [dcl.init] A declarator does not have an initializer.

- source/declarators.tex
- source/derived.tex
- source/expressions.tex
- source/intro.tex
- source/overloading.tex
where the requires-clause in a template-head is not meant.
Fixes #1672.
> Use 'trailing requires-clause'

- source/algorithms.tex
- source/atomics.tex
- source/back.tex
- source/basic.tex
- source/containers.tex
- source/declarations.tex
- source/declarators.tex
- source/diagnostics.tex
- source/exceptions.tex
- source/expressions.tex
- source/future.tex
- source/intro.tex
- source/iostreams.tex
- source/iterators.tex
- source/lib-intro.tex
- source/numerics.tex
- source/overloading.tex
- source/preprocessor.tex
- source/strings.tex
- source/templates.tex
- source/threads.tex
- source/utilities.tex
The ISO Directives, Part 2, prescribe the term 'subclause'.
Fixes #307.
> Use 'subclause', not 'section'.

- source/basic.tex
- source/compatibility.tex
- source/conversions.tex
- source/declarations.tex
- source/expressions.tex
- source/intro.tex
- source/templates.tex
> Remove \tcode from 'const object'.

- source/access.tex
- source/basic.tex
- source/classes.tex
- source/declarations.tex
- source/derived.tex
- source/expressions.tex
- source/lib-intro.tex
- source/locales.tex
- source/numerics.tex
- source/special.tex
This applies to inline, public, protected, private, and friend.
Fixes #106.
> Do not use \tcode for non-syntax.

- source/utilities.tex
Also slightly rephrases one bullet to avoid "overfull hbox".
Fixes #1398.
> [variant] Move 'Otherwise' to start of following bullet.

- source/expressions.tex
> [expr.compound] Expression operators do not 'return' results.

- source/atomics.tex
> [atomics.types.operations] Remove spurious paragraph break.

- source/algorithms.tex
- source/back.tex
- source/basic.tex
- source/compatibility.tex
- source/containers.tex
- source/conversions.tex
- source/cover-reg.tex
- source/cover-wd.tex
- source/declarations.tex
- source/declarators.tex
- source/diagnostics.tex
- source/expressions.tex
- source/future.tex
- source/grammar.tex
- source/intro.tex
- source/iostreams.tex
- source/iterators.tex
- source/lex.tex
- source/lib-intro.tex
- source/limits.tex
- source/locales.tex
- source/macros.tex
- source/numerics.tex
- source/regex.tex
- source/support.tex
- source/templates.tex
- source/threads.tex
- source/utilities.tex
As a first step towards `\xspace` removal (see #1433), these changes remove `\xspace` everywhere except for `\opt`.
(The consensus for \opt was to change its use from `xxx\opt`  to `\opt{xxx}`.)
> Remove \xspace everywhere except for \opt

- source/utilities.tex
- source/xrefdelta.tex
> [util.sharedptr] Dissolve subclause and integrate contents into parent.

- source/atomics.tex
- source/iterators.tex
- source/numerics.tex
- source/strings.tex
- source/utilities.tex
Only affects the library index.
> Index additional member typedefs.

- source/expressions.tex
Elsewhere in this subclause, delete array and delete object are italicized on use; this makes this usage consistent. I spoke with Richard about it at the Kona meeting, and he mentioned this seemed like the correct way to fix it.
> [expr.delete] Properly italicize the term 'delete array', as done elsewhere

- source/lib-intro.tex
> [allocator.requirements] Fix pointer_to expression

- source/utilities.tex
Unfortunately I forgot the `_adaptor` part in #1712
> [allocator.adaptor.syn] Fix index entries for scoped_allocator_adaptor member typedefs.

- source/containers.tex
- source/iostreams.tex
Some other places that might require change (wording relative to N4700):
- [string.view.modifiers] p2: Maybe convert to code block, but there are others like this.
- [string.view.modifiers] p4: Convert to expression style. Unlike the above, this is unique.
- [mem.poly.allocator.mem] p1: Maybe this was meant to be an _Effects:_ element.
> [unord.req], [fs.path.io] Fix "Effects: Equivalent to" styles

- source/basic.tex
- source/declarations.tex
- source/expressions.tex
- source/lex.tex
- source/macros.tex
- source/special.tex
This was a FIXME in macros.tex.
No visible difference.
> Remove \tilde in favour of \~.

- source/basic.tex
- source/utilities.tex
6.6.4.4.2 [basic.stc.dynamic.deallocation] only mentions "storage" once, in "the deallocation function shall deallocate the storage referenced by the pointer".
I think the references are supposed to be to 6.6.4.4.1 [basic.stc.dynamic.**allocation**] instead, which has lots to say about "allocated storage".
Fixes #1841 (assuming I'm right about the references being wrong).
> [basic.life],[mem.res.private],[mem.res.pool.mem],[mem.res.monotonic.buffer] fix cross-references

- source/numerics.tex
> [complex.numbers] Use \xref for references to the C standard.

- source/iostreams.tex
> [fs.op.funcs] Separate effects from returns.

- source/basic.tex
never have external linkage.
Fixes #1797.
> [basic.link] Entities declared in an unnamed namespace

- source/algorithms.tex
- source/atomics.tex
- source/containers.tex
- source/diagnostics.tex
- source/future.tex
- source/iostreams.tex
- source/iterators.tex
- source/lib-intro.tex
- source/locales.tex
- source/numerics.tex
- source/regex.tex
- source/strings.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
Use `template<class T>`.
Also remove space between two closing template brackets in [lib].
Leave [temp] unchanged, intentionally showing a variety of styles.
Fixes #53.
> Harmonize spacing for template headers.

- source/templates.tex
confusing introductory paragraph.
Fixes #1699.
> [temp.constr.order] In definition of 'subsumes', remove

- source/iostreams.tex
Use the function call root_path() instead.
> [fs.path.decompose] 'root-path' is not a grammar non-terminal     

- source/utilities.tex
> [utilities] Remove \placeholder when naming a specific type

- source/basic.tex
- source/expressions.tex
- source/lex.tex
- source/overloading.tex
- source/preprocessor.tex
> Fix misuses of \grammarterm for other purposes

- source/compatibility.tex
- source/lib-intro.tex
Three C11 headers are called out as not being part of C++.
They should not be listed in the index of headers, which
currently points to the two places that explicitly state
these headers do not exist.
> [diff.mods.to.headers] De-index non-existent headers

- source/lex.tex
The grammar for literals consistently prefers using the 'one of' a set
formulation for character sets, rather than listing each character as
an option.  This holds for other parts of this grammar, even when the
set of options is just two items, such as hexadecimal-prefix,
unsigned-suffix, or long-suffix.
As binary-digit is the odd one out, this simple update makes it
consistent with the rest of the grammar specifications in this
clause.
> Use 'one of' formulation for binary-digit

- .travis.yml
- source/utilities.tex
...because Library always qualifies `move` and `forward`.
Also, my editor hates extra newlines at end-of-file.
> [variant.visit] qualify std::forward for consistency

- source/declarators.tex
[basic]/3:
> An *entity* is a value, object, reference, structured binding, function, enumerator, type, class member, bit-field, template, template specialization, namespace, or parameter pack.
The term "structured binding" is consistently used to denote a kind of entity, e.g. [dcl.type.simple]/(4.1):
> if e is an unparenthesized id-expression naming a structured binding, ...
Saying that something names a name would be nonsense.
> [dcl.struct.bind] Clarify that structured bindings are entities (as contrast to names)

- source/conversions.tex
The mismatch currently causes broken links at [eel.is/c++draft/generalindex](http://eel.is/c++draft/generalindex#:decay).
> Fix decay index redirects.

- source/containers.tex
LWG issue 704 ("MoveAssignable requirement for container value type overly strict") added a reference from [associative.reqmts] to what was at the time table 93 ("Allocator-aware container requirements").
That table is now table 86, but the cross reference is now (incorrectly) to table 83 ("Container requirements").  It should still refer to the Allocator-ware container requirements table.  This patch changes it to do so, matching what the committee voted in (many years ago).
> Fix references to container requirements tables.

- source/declarations.tex
Relegate a duplicate normative statement in [namespace.udir]
to a note and add a cross-reference to [basic.lookup].
> [namespace.udir] Ambiguous lookup results are covered in [basic.lookup]

- source/declarations.tex
Everywhere else we say that an enumeration type has _a_ fixed underlying type.
> [dcl.enum] use indefinite article before "fixed underlying type"

- source/templates.tex
It's not quite correct to say it "is" a type; in particular if the following "decltype" bullet also uses "denotes".
> [temp.dep.type] Clarify that a simple-template-id denotes a type

- source/classes.tex
> [class] Replace \term with \defn or \defnx

- source/iostreams.tex
> [filesystems] 'dot' and 'dot-dot' are not \grammarterms

- source/atomics.tex
We now have explicit floating-point specializations for atomic. We had cmpxchg for them before, but people are now looking at increased usage and are confused about what the behavior is for `-0.` with `0.`, as well as NaNs. I propose clarifying the note to make this extra clear. This is a note and is therefore purely editorial, and would be a waste of SG1's time.
> Atomic cmpxchg note clarification

- source/basic.tex
- source/conversions.tex
- source/declarators.tex
- source/exceptions.tex
- source/lib-intro.tex
- source/preprocessor.tex
- source/special.tex
- source/statements.tex
- source/utilities.tex
> Use \tcode for return/if/switch statement.

- source/basic.tex
> [basic.def] 'class name declaration' is undefined.

- source/numerics.tex
> [rand.req.eng] Use \text, not \mbox, in math mode

- source/strings.tex
> [string.classes] Remove class name repeated in subheadings

- source/iostreams.tex
English plural possessives end with "s'".
> [fs.path.nonmember] Grammar

- source/declarations.tex
\fakegrammarterm is the right approach here.
Fixes #1945.
> [dcl.type.cv] Do not use \grammarterm in heading

- source/access.tex
Also turns a "It should be noted that ..." sentence into a proper note.
> [access] Remove inappropriate uses of \term

- source/declarations.tex
> [dcl.dcl] Replace \term with  \defn or \defnx

- source/iostreams.tex
> [error.reporting] Change \rSec3 to \rSec2

- source/special.tex
In p6.8, `i` was used without a prior declaration.
> [class.temporary] Repair example

- source/conversions.tex
- source/expressions.tex
- source/templates.tex
- source/utilities.tex
> [conv,expr] Use \cv{} where appropriate

- source/regex.tex
- source/xrefdelta.tex
Shorten the synopsis and remove [re.regex.const].
Fixes #1163.
> [re.regex] Avoid duplicate list of constants

- source/templates.tex
> [temp.local] Fix example not to name the constructor.

- source/templates.tex
> [temp.spec] Fix cross-reference to one-definition rule.

- source/declarators.tex
> [dcl.fct.def.delete] Adjust 'onlydouble' example.

- source/overloading.tex
To avoid confusion, occurrence of "derived-to-base conversion" should not be with capital letter "C", which implies the name of a conversion category. The rank is already specified at the end of the paragraph.
> [over.best.ics] p6, [over.ics.ref] p1 Fix case

- source/utilities.tex
> [time.duration.nonmember] Replace type designator CR with its definition

- source/iostreams.tex
Renames parameters named "index" to "idx".
Fixes #1955.
> [ios.base] Disambiguate parameters from static data members

- source/containers.tex
- source/locales.tex
- source/numerics.tex
- source/templates.tex
- source/utilities.tex
> More places to use i^\text{th} for i-th

- source/iostreams.tex
- source/support.tex
- source/templates.tex
> Index all mentions of 'implementation-dependent'

- source/diagnostics.tex
- source/future.tex
- source/iostreams.tex
- source/lib-intro.tex
- source/locales.tex
- source/macros.tex
- source/numerics.tex
- source/regex.tex
- source/strings.tex
- source/support.tex
- source/utilities.tex
Also, use \xrefc instead of \xref ISO C to refer to the ISO C standard.
Fixes #1822.
> [lib] \xref may refer to standards other than C

- source/algorithms.tex
- source/basic.tex
- source/iterators.tex
> Remove uses of 'concept' with ordinary English meaning.

- source/expressions.tex
> [expr.rel] Clarify auxiliary partial ordering

- source/iterators.tex
- source/xrefdelta.tex
> [reverse.iterators] Dissolve single-item subclauses.

- source/iostreams.tex
> [ostream.manip] fix "basic_osyncbuf" typo

- source/iostreams.tex
- source/numerics.tex
- source/preprocessor.tex
> [lib] Avoid 'shall' and 'should' in footnotes.

- source/basic.tex
- source/classes.tex
- source/derived.tex
- source/expressions.tex
- source/overloading.tex
- source/special.tex
Cross-references to [expr.prim] should instead point to one
of its subclauses.
> [std] Review cross-references to [expr.prim]

- source/declarations.tex
As discussed for CWG 2285, variables declared with a
placeholder type should never reference itself in the
initializer.  Similarly, clarify the treatment of
deduced function return types.
Fixes #1942.
> [dcl.spec.auto] Use of undeduced placeholder types

- source/utilities.tex
It is mostly subsumed by the detailed descriptions of the move
constructors and assignment operators.
Fixes #1643.
> [unique.ptr] Remove definition of 'transfers ownership'.

- source/overloading.tex
> [over.match.oper] Add a note for conversions on synthesized candidates.

- source/expressions.tex
and fix the null pointer provision.
Fixes #1934.
> [expr.dynamic.cast] Remove redundant statements on casting away constness

- source/expressions.tex
To quote [expr.ass]p2,
In simple assignment (=), the value of the expression replaces that of the
object referred to by the left operand.
End quote.
I think "the value of the expression" means the right operand of a simple
assignment, not the whole simple assignment expression, because [expr.ass]p2
describes the semantics of a simple assignment and because of the following
that I quote from Footnote 64 in 6.3.2.1/1 of WG14 N1570, the latest publicly
available draft of the C11 standard accessible at
http://open-std.org/jtc1/sc22/wg14/www/standards:
The name ‘‘lvalue’’ comes originally from the assignment expression E1 =
E2, [...] What is sometimes called ‘‘rvalue’’ is in this International
Standard described as the ‘‘value of an expression’’.
End quote.
Since this ISO C++ draft does not …
> Clarifying "the value of the expression" in simple assignment expression

- source/iostreams.tex
- source/utilities.tex
"can not" represents the (technical) ability not to do something, whereas "cannot" is the (technical) inability to do something. We mean the latter.
> [ostream.manip,time] Replace "can not" with "cannot"

- .travis.yml
This changes the Travis CI build server to use a Docker container that's running a newer version of Ubuntu (16.04) which comes with a newer version of TeX Live (2016).
This is, in part, to address issue #1830.
It will also allow us to easily upgrade TeX Live versions in the future by swapping in a newer Docker image.
> Travis CI: Upgrade to newer TeX Live distribution.

- source/templates.tex
Explicit specialization, etc. of a concept cannot be formed
syntactically. As such, a further rule to prevent such constructs is
redundant as normative text.
Implements the proposed direction from core/2017/07/2719.
> [temp.concept]: Use note; no syntax for explicit specialization, etc.

- source/utilities.tex
> [time.syn] Add comments pointing to specification of literal operators

- source/utilities.tex
- Add missing semicolons.
- Write out `operator!=` for `zoned_time`. [operators] does not apply because this comparison is heterogeneous (can have different `Duration` types).
- Fixes `TimeZonePtr2`-related typos in `zoned_time`.
> [time.syn][time.zone] Various editorial fixes

- source/declarators.tex
- source/expressions.tex
- source/iostreams.tex
> Use \commentellip macro for omitted program text.

- source/numerics.tex
Fixes #2032.
No differences with diffpdf "appearance" mode.
> [rand] Use \dotsc, not \ldots for comma-separated lists

- source/lex.tex
- source/overloading.tex
- source/preprocessor.tex
Same as #1362:
- makes the source look nicer and more consistent
- no visual difference in PDF
- makes life easier for cxxdraft-htmlgen
> [cpp, lex, over] Make bnf indentation in source match presentation.

- source/special.tex
not just for the subscript.
Also use \dotsc, not center dots, for comma-separated lists.
> [class.spaceship] Use math mode for the entire formula,

- source/algorithms.tex
When [algorithms.general] was split into three subclauses (#1230) the
requirements moved to a new subclause, [algorithms.requirements]. That
invalidated the cross-reference in [algorithms.parallel.defns].
> [algorithms.parallel.defns] Fix cross-reference to [algorithms.requirements]

- source/basic.tex
... now that _alias-declaration_ uses the _defining-type-id_ nonterminal.
> [basic.scope.pdecl] Change "type-id" to "defining-type-id"

- source/containers.tex
- source/diagnostics.tex
- source/iostreams.tex
- source/iterators.tex
- source/lib-intro.tex
- source/numerics.tex
- source/overloading.tex
- source/regex.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
The order [`==`, `!=`, `<`, `>`, `<=`, `>=`] seems to be most common. Let's make it canonical and use it uniformly.
> Order library comparisons canonically

- source/declarators.tex
[basic.lval]/10 says about (non-)modifiable lvalues (http://eel.is/c++draft/basic.lval#def:modifiable):
> An lvalue is modifiable unless its type is const-qualified or is a function type.
Nothing about arrays. 2 other places in [basic.lval] which mention arrays are:
> [ Note: Except when the prvalue is the operand of a decltype-specifier, a prvalue of class or **array** type always has a result object.
For a discarded prvalue, a temporary object is materialized; see [expr.prop]. — end note ]
> [ Note: A glvalue may have complete or incomplete non-void type. Class and **array** prvalues can have cv-qualified types; other prvalues always have cv-unqualified types. See [expr.prop]. — end note]
Probably the statement is an artifact from [the stone …
> [dcl.array]: delete note about non-modifiability of arrays

- source/expressions.tex
Also add cross-references pointing to the normative statements.
Fixes #2044.
> [basic.lval] Add array subscripting to note enumerating xvalues.

- source/expressions.tex
1. Returning/casting to rvalue reference of *object type* is an xvalue. The example misses the "object type" part.
2. A(n almost, the PR is waiting to be merged) complete and correct list of xvalue expressions is just 2 (or 3? I'm bad at counting) paragraph below. So, fixing the example is not rational, better to delete it.
> Delete redundant and wrong example

- source/compatibility.tex
- source/overloading.tex
> [over.match.copy] Clarify candidate function selection for references.

- source/overloading.tex
> [over.match,over.match.ref] Drop obsolete mention of class prvalues.

- source/overloading.tex
> [over.oper] Remove incorrect and redundant sentence in a note.

- source/containers.tex
It's present in all other clauses of that form in this chapter.
> [(forward)list.modifiers] fix missing 'to' in 'referred [to] by'

- source/support.tex
> [cmp.syn] Rename to [compare.syn] to match the header name

- source/containers.tex
> [views.general] Remove redundant introduction for span.

- source/declarations.tex
The comment in the example is not consistent with the commented code.
> Fixed example about [[likely]] attribute

- source/macros.tex
- source/numerics.tex
This PR improves the spacing around the bit operators `\bitand`, `\bitor`, `\xor`, `\rightshift`, and `\leftshift` by declaring them as `\mathbin` tokens.
> Improves the spacing around bit operators.

- source/intro.tex
Currently index entries point to the end of the previous paragraph, see pic. ![image](https://user-images.githubusercontent.com/38548419/40606617-95168154-626e-11e8-87e9-7b491efaedfe.png)
> [intro.abstract] Move \indextext under \pnum

- source/declarators.tex
There is already an index entry for 'pointer to member', but
it does not point to 11.3.3 [dcl.mptr] that provides the rules
for the declarator.  This bit me just today when I could not
find the magic words to find exactly this clause, so adding
an extra reference under the existing index entry.
> [dcl.mptr] Add index entry for pointer to member clause

- source/basic.tex
- source/classes.tex
- source/declarators.tex
- source/expressions.tex
- source/templates.tex
FIxes #2113.
Note the comment in that issue.
> P1113R0 CWG "ready" Issues for the June, 2018 (Rapperswil) meeting

- source/basic.tex
- source/classes.tex
- source/declarations.tex
- source/declarators.tex
- source/derived.tex
- source/exceptions.tex
- source/expressions.tex
- source/templates.tex
Added cross-reference from the new use of 'abstract class
type' in [except.throw], pointing to [class.abstract].
Fixes #2117.
> P0929R2 Checking for abstract class types

- source/future.tex
- source/intro.tex
Changes were applied to [depr.locale.stdcvt.req] instead of
[depr.locale.stdcvt].
Fixes #2120.
> P1025R1 Update the reference to the Unicode standard

- source/atomics.tex
Added a cross-reference for "padding bits".
Fixes #2121.
> P0528R3 The curious case of padding bits, featuring atomic compare-and-exchange

- source/algorithms.tex
- source/containers.tex
- source/diagnostics.tex
- source/iostreams.tex
- source/lib-intro.tex
- source/locales.tex
- source/numerics.tex
- source/regex.tex
- source/strings.tex
- source/utilities.tex
> P1082R0 LWG Issues to be moved in Rapperswil (except issue 3071)

- source/lib-intro.tex
- source/numerics.tex
* Added an entry into Table tab:numerics.lib.summary.
* Renamed heading "bit manipulation library" to just "bit manipulation".
* Reordered itemdescr elements to the canonical order.
Fixes #2131.
TODO: add feature test macros once CWG-15 has been merged.
> P0476R2 Bit-casting object representations

- source/lib-intro.tex
- source/macros.tex
> P0788R3 Standard library specification in a concepts and contracts world

- source/containers.tex
> P1023R0 constexpr comparison operators for std::array

- source/containers.tex
- source/future.tex
- source/iostreams.tex
- source/numerics.tex
- source/regex.tex
> P0935R0 Eradicating unnecessarily explicit default constructors from the standard library

- source/algorithms.tex
- source/compatibility.tex
- source/concepts.tex
- source/containers.tex
- source/exceptions.tex
- source/future.tex
- source/iostreams.tex
- source/iterators.tex
- source/lib-intro.tex
- source/locales.tex
- source/macros.tex
- source/numerics.tex
- source/regex.tex
- source/std.tex
- source/strings.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
- source/xrefdelta.tex
Fixes #2145.
Pushing from a branch in a remote repo rather than `motions-2018-06-lwg-28` as directed in the [new application procedure](https://github.com/cplusplus/draft/wiki/Applying-papers-to-the-Working-Draft) since I don't have commit access and cannot make new branches.
Reviewers: Please be brutal. Tiny errors I've made herein will be magnified by one to two orders of magnitude when the One Ranges Proposal is merged - I need the practice.
I'd appreciate if someone could assign this to the "post-2018-06" milestone as well.
> P0898R3 Standard Library Concepts

- source/containers.tex
This fixes an oversight in the wording of
N4258 Cleaning‐up noexcept in the Library,
which updated the overview, but not the description.
Fixes #2178.
> [vector.cons] vector(Allocator) should be noexcept

- source/compatibility.tex
Pretty sure p0619 meant to say `raw_storage_iterator` there, since that's what was actually removed.
> [diff.cpp17.depr] apparent typo in p0619r4: raw_memory_iterator

- source/expressions.tex
> [expr.spaceship] Fix typo for std::strong_equality::nonequal

- source/iterators.tex
- source/utilities.tex
Inspired by P0602 https://lichray.github.io/trivially_variant.html
Zhihao suggested I open an editorial issue if I want to harmonize
"trivially destructible" wording across the rest of the Standard,
so, here's that editorial issue.
I may have gotten carried away while harmonizing
http://eel.is/c++draft/tuple.cnstr#4
with
http://eel.is/c++draft/variant.ctor#1
but I think it's still "editorial."
> Harmonize phrasings of "this destructor is trivial"

- source/iterators.tex
There's no such thing as an "insert ~~iterator~~pointer," and the rest of this sentence isn't much better. Let's just strike it.
> [output.iterators] Strike useless sentence from note

- source/containers.tex
There is a common convention to omit 'std::' when not strictly needed,
other than for 'std::move' and 'std::forward'.  A third case is for
'reverse_iterator' and 'const_reverse_iterator' type aliases inside a
class definition, as the leading 'reverse_iterator' type alias hides
the 'std' version from the 'const_reverse_iterator' definition, and
subsequently fails to compile.  This patch restore the class definition
to a safely copy/pastable state.
An additional review indicated this convention has been applied correctly
for every othert potential occurrence in the library.
> [span.overview] fix reverse_iterator for span

- source/iterators.tex
- source/xrefdelta.tex
> [move.iterators] Dissolve single-item subclauses.

- source/algorithms.tex
between the "binary_search" family and the "merge" family, to agree with
the order of the detailed specifiations as reordered by #1245.
Fixes #2218.
> [algorithm.syn] Relocate the "partitions" algorithms

- source/atomics.tex
> [atomics.types.operations] Avoid inappropriate use of 'underlying type'

- source/lex.tex
> [lex] Correctly cite ISO/IEC 10646

- source/classes.tex
- source/containers.tex
- source/conversions.tex
- source/expressions.tex
- source/numerics.tex
- source/utilities.tex
when calling out a value category.
Fixes #2069.
> Drop redundant 'expression'

- source/expressions.tex
- source/future.tex
- source/templates.tex
with the grammar term 'lambda-expression'.
Also remove the unused definition of 'local lambda expression'.
Fixes #2094.
> [expr.prim.lambda,depr.capture.this] Replace 'lambda expression'

- source/concepts.tex
These paragraphs are in magenta in P0898R3 and are not meant to be included into the IS working draft.
> [concept.swappable] remove wrongly included text

- source/special.tex
In one of the code examples in the [class.copy.elision] section of the document:
As a result of what appears to have been a typo, the function g was
defined twice in the code example.  The second definition of g has been
renamed to h to fix this problem.
> Fix for typo in code example in [class.copy.elision] section of document

- source/compatibility.tex
> [diff] Use plural form of \diffref for changes affecting multiple subclauses.

- source/basic.tex
- source/classes.tex
and use it, instead of having separate redundant lists
in [basic.scope.class] and [basic.lookup.unqual].
Fixes #2107.
> [class.mem] Define complete-class context

- source/regex.tex
This change refers to the table introducing the first-level subclauses as done in the summary of the other clauses.
> [re.general] Refer to table as done in the other clauses

- source/declarators.tex
> [dcl.init.ref] Avoid use of 'underlying type' for references

- source/overloading.tex
Right now, the cross-reference is not really pointing to the right place.
> [over.match.viable] Fix cross-reference to satisfaction of constraints

- source/basic.tex
- source/declarations.tex
- source/exceptions.tex
- source/support.tex
> [basic.start,except] Harmonize references to std::terminate

- source/classes.tex
This paragraph seems excessively long:
> [class] Split paragraph defining standard-layout class

- .travis.yml
This adds a Travis CI check for undefined references (e.g., a `\ref` that points to a nonexistent `\label`).
This PR causes no change in the PDF output.
> Travis CI: Check for undefined references.

- source/lib-intro.tex
This affects the grammar term index.
> [structure.specifications] spell static_assert-declaration without \_

- source/declarations.tex
The effects of using-declarations naming member functions
are discussed in other parts of the standard.
The effects of initializing with an inherited constructor are
discussed elsewhere, too.
Fixes #1975.
> [namespace.udecl] Demote normative duplication to notes

- source/iterators.tex
by correcting the title for [predef.iterators] to "Iterator adaptors", and adding rows for [iterator.range] and [iterator.container].
> [iterators.general] Fixup Iterators library summary table

- source/containers.tex
As described in [structure.specifications].
Fixes #2235.
> [span.overview] Move requirements on types to after the synposis.

- source/utilities.tex
The addition of a copy constructor by P0619R4 caused the default
constructor to be suppressed, which was not intended.
> [mem.res.class] Add default constructor

- source/declarations.tex
> [dcl.dcl] Remove incorrect footnote about the implicit int rule.

- source/containers.tex
There is no such member. The previous overload of forward_list::erase is
already indexed.
> [forwardlist.modifiers] Remove index entry for forward_list::erased

- source/numerics.tex
...for consistency with the other `for` loops in the IS.
> [rand.util.seedseq] Typo "for( " should be "for ("

- source/basic.tex
This seems to be cruft accidentally left over from the dueling resolutions of CWG 1746 (which added "cv-unqualified") and CWG 2094 (which added "and cv-qualified versions of these types").
Editorial.
> "cv-qualified versions of cv-unqualified scalar types" are just "scalar types"

- source/declarations.tex
> [dcl.init.aggr] initializer-list (grammar) is never empty

- source/classes.tex
Add the missing cross-references to corresponding Annex D entry
for the deprecated implicit declaration of copy constructor and
copy assignment operator when either the destructor or other
copy operation is user-declared.
> [class.copy.ctor] Add missing cross-references to Annex D

- source/expressions.tex
- source/intro.tex
moved from [intro.abstract].
Fixes #2251.
> [expr.pre] Add note on operator regrouping here,

- source/classes.tex
Bit simpler this way, and slightly shortens a pretty long sentence.
> [class.dtor] Clean up awkward '.. is the type of the class' phrasing.

- source/containers.tex
- source/utilities.tex
with italics teletype and use hyphens, not underscores,
to highlight that these are not standard-prescribed names.
Fixes #2014.
There is also a drive-by that adjusts "type" to "template".
> [containers,utilities] Mark exposition-only names

- source/expressions.tex
The term 'entity' is too generic here.
Also move the specification of the non-array return
value just before the array case, after the description
of the parsing disambiguation.
Fixes #2279.
> [expr.new] Use 'object', not 'entity', for new-expression.

- source/templates.tex
A two parameter spaceship can't be a member, and the parameter types for a defaulted operator can only be const C& ([class.compare.default]p1).
> [temp.param] fix spaceship example

- source/basic.tex
- source/iostreams.tex
- source/regex.tex
- source/time.tex
- source/utilities.tex
Fixes #2289.
Both "empty structure type" and "empty class type" (i.e. the before and after phrases) are undefined.
It's unclear, for example, whether such an "empty" type may contain member typedefs or nested types.
> [std] Replace use of 'structure' by 'class'

- source/declarations.tex
1. The conversion sequence is "governed by" the rules defined here ([\[over.best.ics\]](http://eel.is/c++draft/over.best.ics#1.sentence-2)). Saying "conversion sequence" here will cause circular definition.
2. Overload resolution selects a function, not a conversion sequence.
Also perform a minor reflow to keep "overload" and "resolution" in the same line.
> [dcl.init] Rephrase "user-defined conversion sequence"

- source/expressions.tex
> [expr.add] Clarify if/otherwise ladder

- source/iostreams.tex
The synopsis of <filesystem> refers to the types chrono::time_point and chrono::file_clock, so it must include <chrono> for their declarations
The removed paragraph refers to trivial-clock that has now been replaced by chrono::file_clock. The paragraph is now unnecessary since chrono::file_clock is fully described in [time.clock.file].
See also http://cplusplus.github.io/LWG/lwg-active.html#3145
> [fs.filesystem.syn] Fixes related to chrono::file_clock usage in <filesystem>

- source/utilities.tex
> [utilities] Remove class name repeated in subheadings

- source/regex.tex
- source/xrefdelta.tex
> [re] Remove class name repeated in subheadings

- source/iterators.tex
> [iterators] Remove class name repeated in subheadings

- source/iterators.tex
Since LWG asked me to remove these from P0896's `OutputIterator`, they probably don't belong in *`Cpp17OutputIterator`* either.
> [output.iterators] Remove misleading italics from note

- source/numerics.tex
> [numerics] Remove class name repeated in subheadings

- source/locales.tex
> [localization] Remove class name repeated in subheadings

- source/threads.tex
> [thread] Remove class name repeated in subheadings

- source/classes.tex
And turn a bunch of `\tcode{const} \tcode{X}` into `\tcode{const X}` on the assumption that this is better. (I see the latter style being used elsewhere, and it's certainly more readable in the TeX source.)
> Use the Oxford comma in [class.copy.assign].

- source/atomics.tex
- source/basic.tex
The paper did not highlight two changes of "strongly happens before"
to "simply happens before" in the definition of "simply happens before".
Fixes #2395.
> P0668R5 Revising the C++ memory model

- source/concepts.tex
- source/expressions.tex
[expr.prim.req.compound] Renamed C5 to C3 in remaining example.
Fixes #2397.
> P1084R2 Today’s return-type-requirements Are Insufficient

- source/atomics.tex
- source/basic.tex
- source/compatibility.tex
- source/declarations.tex
- source/expressions.tex
- source/future.tex
- source/iostreams.tex
- source/lex.tex
- source/lib-intro.tex
- source/locales.tex
- source/overloading.tex
- source/preprocessor.tex
- source/strings.tex
- source/support.tex
> P0482R6 char8_t: A type for UTF-8 characters and strings

- source/basic.tex
- source/classes.tex
- source/compatibility.tex
- source/declarations.tex
- source/expressions.tex
- source/lex.tex
- source/macros.tex
- source/templates.tex
> P1073R3 Immediate functions

- source/basic.tex
- source/expressions.tex
- source/support.tex
- source/utilities.tex
> P0595R2 std::is_constant_evaluated()

- source/declarations.tex
- source/expressions.tex
- source/templates.tex
[dcl.fct] Replaced the reference to the non-existant section 17.6.5 with
[temp.over.link] where function template equivalence is defined.
[temp] Clarified "This" as being the "type-constraint Q".
[temp.param] Add reference to "immediately-declared constraint".
[temp.param] Add reference to "the invented type corresponding to the placeholder".
[temp.constr.decl] Added "a" to and "and" after the new item in the bulletted list.
Fixes #2407.
Note: you might want to fix the spelling of "bulletted" in the commit message when committing to master :)
> P1141R2 Yet another approach for constrained declarations

- source/compatibility.tex
- source/iostreams.tex
Also fixes LWG2499.
Fixes #2412.
> P0487R1 Fixing operator>>(basic_istream&, CharT*) (LWG 2499)

- source/utilities.tex
> P0602R4 variant and optional should propagate copy/move triviality

- source/utilities.tex
> P0655R1 visit<R>: Explicit Return Type for visit

- source/time.tex
> P0972R0 <chrono> zero(), min(), and max() should be noexcept

- source/containers.tex
- source/iterators.tex
- source/strings.tex
- source/support.tex
- source/utilities.tex
[tuple], [pairs.pair] Fixed relative order of 'explicit' and 'constexpr'
Change 9: formatting and grammar fixes, replaced meaningless phrase
"operations are constexpr" with intended "operations are implemented
with constexpr functions" after consultation with LWG.
Change 10: green line editing instruction ignored, there do not appear
to be any other places that need changes.
Fixes #2417
> P1032R1 Misc constexpr bits

- source/iostreams.tex
- source/strings.tex
- source/xrefdelta.tex
> P1148R0 Cleaning up Clause 20

- source/utilities.tex
Add the type trait as subclause [refwrap.unwrapref],
instead of as a sibling of [refwrap].
Rephrase the wording to avoid referencing X before it
is introduced.
Do not refer to 'equals' as referring to types.
Fixes #2419.
> P0318R1 unwrap_ref_decay and unwrap_reference

- source/utilities.tex
> P0608R3 A sane variant converting constructor

- source/utilities.tex
> P0771R1 std::function move constructor should be noexcept

- source/utilities.tex
[memory.syn] Merged the new function in with [ptr.align] and
renamed the section to "Pointer alignment".
[ptr.aligned] Added "a" before "type similar".
Fixes #2423.
> P1007R3 std::assume_aligned

- source/utilities.tex
[memory.syn] Move return types to before function names for consistency.
Fixes #2424.
> P1020R1 Smart pointer creation with default initialization

- source/algorithms.tex
- source/compatibility.tex
- source/concepts.tex
- source/containers.tex
- source/iterators.tex
- source/lib-intro.tex
- source/numerics.tex
- source/ranges.tex
- source/std.tex
- source/strings.tex
- source/support.tex
- source/threads.tex
- source/utilities.tex
> P0896R4 The One Ranges Proposal

- source/support.tex
- source/utilities.tex
[support.limits.general] Introduce feature-test macro even though it
was not presented as a wording diff in the paper.
[functional.syn] Use proper subclause name in cross-reference.
[func.bind_front] Do not use 'equals' when discussing types identity.
Fixes #2432.
> P0356R5 Simplified partial function application

- source/containers.tex
- source/macros.tex
- source/support.tex
> P0919R3 Heterogeneous lookup for unordered containers

- source/basic.tex
> [basic.stc.dynamic.allocation] Fix cross-reference for get_new_handler

- source/expressions.tex
"[lx]value denoting ..." is already used in half a dozen other places, "lvalue to ..." is not used anywhere else.
> [expr.static.cast] Say 'lvalue denoting ...' instead of 'lvalue to ...'

- source/expressions.tex
The meaning of "fetched from memory" is vague, and the two uses of term
"access" [defns.access] are inappropreate here because
- it causes undefined behavior to access an inactive member of a
union, based on the rule of out-of-lifetime object [basic.life]:
> The program has undefined behavior if:
>   - the glvalue is used to access the object, or
- it implies reading the referenced object of std::nullptr_t,
which is defined to be a side effect for volatile-qualified case.
[intro.execution]
> Reading an object designated by a volatile glvalue, ... are all
> side effects, ...
---
The change blindly assumes that "no value is fetched from memory" is
true and rephrases it as "the conversion does not read the object", but
I'm not sure how it is true. In fact, gcc 8.2 emits read instruction for …
> [conv.lval] Improve the note about std::nullptr_t case

- source/templates.tex
in comments explaining examples
Fixes #2390.
> [temp] Use 'deduced as' instead of 'deduced to'

- source/expressions.tex
to refer to [expr.type], not [expr.prop].
Fixes #2391.
> [expr] Fix cross-references for 'composite pointer type'

- source/algorithms.tex
which were using the term 'subsequence' incorrectly.
Fixes #2377.
> [alg.find.end,alg.search] Remove redundant 'Effects' paragraphs

- source/algorithms.tex
- source/numerics.tex
> [numeric.ops] Move [numerics.defns] to the point-of-use.

- source/declarations.tex
initialized by a designated-initializer-list.
Fixes #2345.
> [dcl.init.aggr] Add example for anonymous union

- source/utilities.tex
there is nothing called "allocator" in this section, but there is an allocator called "alloc"
> [allocator.uses.construction] the argument name is alloc, not allocator

- source/overloading.tex
not 'standard conversion sequence' where applicable.
Fixes #2388.
> [over.ics.ref] Use 'implicit conversion sequence',

- source/algorithms.tex
\tcode{min} is only appropriate when referring to the C++
function std::min.
Fixes #2385.
> [algorithms] Use math \min when computing complexities.

- source/declarations.tex
> [dcl.init] Clarify standard conversions for built-in types

- source/utilities.tex
No '...' for a pack expansion should appear after 'Types',
and no index on 'T'.
Fixes #974.
> [utilities] Harmonize 'For T in Types' phrasing.

- source/basic.tex
- source/iostreams.tex
- source/ranges.tex
- source/regex.tex
- source/templates.tex
- source/utilities.tex
For consistency and readability.
> Use \logop consistently.

- source/atomics.tex
> [atomics.types.operations]/20 Replace "E.g." at start of sentence with "For example".

- source/compatibility.tex
- source/iostreams.tex
- source/numerics.tex
- source/time.tex
Without the `\@`, LaTeX thinks these are mid-sentence periods because they are preceded by a capital letter. Consequently, it applies word-spacing instead of sentence-spacing.
See Rule 2 at https://tex.stackexchange.com/a/55112.
The only visual effect is an ever-so-slightly wider space after these periods.
(Incidentally, this also helps cxxdraft-htmlgen's sentence splitting, since I'm making it use the same heuristic as LaTeX.)
> Fix spacing after full stops that LaTeX mistakenly thinks are mid-sentence.

- source/iostreams.tex
> [iosfwd.syn] Change char_traits from 'class' to 'struct'.

- source/compatibility.tex
- source/iostreams.tex
- source/xrefdelta.tex
> [input.output] Avoid colons in stable labels

- source/templates.tex
> [temp.func.order] Adjust example to rules in [temp.deduct.partial].

- source/preprocessor.tex
to avoid repeated quotes of the token sequence.
Fixes #2185.
> [cpp.subst] Introduce grammar non-terminal 'va-opt-replacement'

- source/algorithms.tex
except:
Move \begin{note} and \end{note} to lines of its own.
[alg.unique] fix two English-level typos
[alg.transform] remove superfluous space before period
[alg.partitions] remove duplicate \pnum
[alg.is_permutation,alg.move,is.sorted] add missing \tcode
[algorithms.parallel.exec] move comment in example
Fixes #2509.
> [algorithms] Compactify and reformat source with no visual change

- source/iterators.tex
Or could the convention have changed for this kind of constraints?
> [iterator.traits] Remove space between type and ref-qualifier

- source/templates.tex
Per [Specification-Style-Guidelines/describing-function-calls](https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines#describing-function-calls).
> [temp.mem.func] Remove inappropriate parentheses in 'Array<T>::operator[]()'.

- source/compatibility.tex
The space is visible in the pdf.
> [diff.dcl] Remove space before colon.

- source/declarations.tex
The [dcl.constexpr] section was recently expanded to describe the consteval specifier. I believe the title of the section should reflect that.
> Fixed title of [dcl.constexpr] section to include consteval

- source/lib-intro.tex
and add paragraph number.
Fixes #2639.
> [allocator.requirements] relocate example to end of subclause

- source/basic.tex
- source/overloading.tex
Also add cross-references to [class.member.lookup] when
talking about 'looked up in the class of the object expression'
in [basic.lookup.classref].
Fixes #2365.
> [basic.lookup,over.call.func] Clarify lookup rules for function calls.

- source/basic.tex
- source/expressions.tex
This pull request will:
* remove void expressions from temporary object materialization;
* add void expressions to the prvalue definition and precise that they have no results/result objects.
> Clarify the contexts where void expressions appear

- source/expressions.tex
It seems like every binary expression has a sentence which says which way the operator groups, except for and, or and xor.
For consistency, add a sentence saying that they group left-to-right.
> [expr.and][expr.or][expr.xor] Add grouping sentence to the binary and/or/xor operators.

- source/iterators.tex
not the exposition-only member 'current', from non-member functions.
Fixes #2579.
> [reverse.iterators] Use the public accessor function,

- source/expressions.tex
> [expr.new] A new-expression might not invoke a constructor

- source/basic.tex
and clarify that references are treated as-if requiring storage.
Fixes #2601.
> [basic.life] Adjust subclause heading

- source/declarations.tex
> [dcl.typedef] Use 'redeclare', not 'redefine'

- source/ranges.tex
Range adaptors take a range and produce a new range;
range factories take something else (or nothing) and produce a range.
Fixes #2615.
> [range.factories] New subclause, split off from [range.adaptors]

- source/ranges.tex
'Common range' means iterator and end marker have the same type;
see [range.req.general].  This is not what this subclause is about.
Fixes #2590.
> [range.refinements] Rephrase heading to not use 'common range'

- source/threads.tex
I've been looking far and wide but nowhere in the papers about condition variables have I found note about efficiency of them being platform dependent. The implementation of `std::condition_variable_any` in libc++ and in libstdc++ is a generalization of `std::condition_variable`, which points towards the efficiency being bound more to the implementation than the platform.
> Clear up a note about condition variables

- source/utilities.tex
The function name is spelled as `std::is_constant_evaluated()` in other places of the draft standard and in the original [p0595r2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0595r2.html) proposal, so I think this can be treated as an obvious typo.
> [meta.const.eval] Fix typo in function name

- source/iterators.tex
- source/ranges.tex
- source/xrefdelta.tex
> [range.prim,iterator.container] merge into preceding subclause

- source/templates.tex
It appears that [CWG 249](https://wg21.link/cwg249) fixed only the normative text, but did not also fix the following example.
> Fixed text in [temp.mem.func]/1 example, which was not updated by CWG249

- source/utilities.tex
All the other traits that use the phrase 'is known not
to throw exceptions' also cross-reference the core
clause for the noexcept operator, so add the missing
cross reference to the more recently added traits.
> [meta.rel] Add missing noexcept cross-refs for invokable traits

- source/expressions.tex
because
> If an expression initially has the type “reference to T” ([dcl.ref], [dcl.init.ref]), the type is adjusted to T prior to any further analysis.
Fixes #2652.
> [expr.sizeof]/2: there are no expressions of reference type

- source/containers.tex
I retain the heading removed in #1933, since fixes to #1242 don't change them in the synopses.
> [array.syn] Add reference to [array.tuple]

- source/containers.tex
- source/utilities.tex
It was declared as structures and specializations were classes. All tuple_size and tuple_elements are now structures.
Touched sections: pair.astuple and tuple.helper
> Incosistency in tuple_size/tuple_element struct/class. 

- source/basic.tex
- source/classes.tex
- source/declarations.tex
- source/exceptions.tex
- source/expressions.tex
- source/overloading.tex
- source/statements.tex
- source/templates.tex
> Motions 2019 02 cwg 1

- source/basic.tex
- source/classes.tex
- source/declarations.tex
- source/exceptions.tex
- source/expressions.tex
- source/lib-intro.tex
- source/templates.tex
Fixes #2682.
FYI: CWG2083 Also fixes CWG2103 and CWG2170.
> Motions 2019 02 cwg 2

- source/declarations.tex
Also fixes CWG1778.
[dcl.fct.def.default]/2 Remove "and" from previous bullet.
Fixes #2683.
> P1286R2 Contra CWG DR1778

- source/lex.tex
- source/preprocessor.tex
[lex] Turn notes into separate sentences.
Fixes #2687.
> P1139R2 Address wording issues related to ISO 10646

- source/declarations.tex
- source/templates.tex
> P1323R2 Contract postconditions and return type deduction

- source/expressions.tex
> P1009R2 Array size deduction in new-expressions

- source/basic.tex
- source/classes.tex
- source/compatibility.tex
- source/declarations.tex
- source/lex.tex
- source/macros.tex
- source/modules.tex
- source/overloading.tex
- source/preprocessor.tex
- source/std.tex
- source/templates.tex
[basic.lookup.argdep] Make missed "associated classes" ->
"associated entities" change.
Replaced comments indicating the start of a translation unit codeblock
in examples with a title.
Fixes #2691.
> P1103R3 Merging Modules

- source/classes.tex
- source/overloading.tex
- source/templates.tex
> P1185R2 <=> != ==

- source/algorithms.tex
- source/atomics.tex
- source/concepts.tex
- source/containers.tex
- source/diagnostics.tex
- source/iostreams.tex
- source/lib-intro.tex
- source/numerics.tex
- source/ranges.tex
- source/strings.tex
Fixes #2711.
Drafting notes:
* LWG3180: I didn't indent "using" (as we had discussed in Kona), in order to be consistent with the existing coding style.
* LWG3112: I used `\hfill\break` to workaround an Overfull issue.  Is there a better way to do this?
> Motions 2019 02 lwg 2

- source/utilities.tex
> P0340R3 Making std::underlying_type SFINAE-friendly

- source/iterators.tex
> P0738R2 I Stream, You Stream, We All Stream for istream_iterator

- source/containers.tex
Used capital letters after descriptive element headers.
Fixes #2701.
> P1463R1 Mandating the Standard Library: Clause 21 - Containers library

- source/iterators.tex
Fixes #2702.
FYI: "current" was changed to "base()" in commit 597b69001.
> P1464R1 Mandating the Standard Library: Clause 22 - Iterators library

- source/iostreams.tex
For create_directory copying attributes from existing_p,
- Removed 'already' from failure description, to align with
simple create_directory.
- Removed 'The signature with argument ec returns false
if an error occurs.'; this was struck in the parallel cases
and is omitted entirely (not shown as struck) in the editing
instructions.
Fixes #2703.
> P1164R1 Make create_directory() Intuitive

- source/algorithms.tex
- source/support.tex
- source/utilities.tex
Move the example in the added paragraph of [algorithms.parallel.defns]
into a function, since statements cannot appear at namespace scope.
Fixes #2705.
> P1001R2 Target Vectorization Policies from Parallelism V2 TS to C++20

- source/containers.tex
- source/iterators.tex
> P1227R2 Signed ssize() functions, unsigned size() functions

- source/algorithms.tex
- source/future.tex
- source/iterators.tex
- source/lib-intro.tex
- source/ranges.tex
- source/utilities.tex
Renamed some suggested stable labels for new sections.
Fixes #2707.
> P1252R2 Ranges Design Cleanup

- source/containers.tex
- source/utilities.tex
Moved the declaration of the undefined partial specialization
tuple_size<span<ElementType, dynamic_extent>> to the header
synopsis.
Fixes #2708.
> P1024R3 Usability Enhancements for std::span

- source/support.tex
- source/utilities.tex
> P1357R1 Traits for [Un]bounded Arrays

- source/locales.tex
- source/numerics.tex
- source/strings.tex
to indicate inclusive ranges in prose.
Fixes #2672.
> [lib] Use '(inclusive)', not other punctuation

- source/declarations.tex
Avoid confusion caused by using the words "makes [...]
modifications of the value of [a] parameter" by excluding
references.
Fixes #2669.
> [dcl.attr.contract.cond] References cannot be modified.

- source/declarations.tex
> [dcl.init] Prepend 'Otherwise' to a bullet

- source/templates.tex
> [temp.deduct.conv] Add missing formatting for 'noexcept'.

- source/declarations.tex
- source/expressions.tex
> [conv.prom] b_min and b_max are no longer defined in [dcl.enum]

- source/statements.tex
and avoid starting a new paragraph after a single sentence.
Fixes #2753.
> [stmt.iter,stmt.select] Add formatting for grammar terms

- source/declarations.tex
The function in the example returns int but fails to actually return.
> [dcl.attr.contract.cond] example fails to return

- source/expressions.tex
[expr.sizeof]/1 already covers the "shall not" part using more formal wording: "The sizeof operator shall not be applied to an expression that has function or incomplete type, to the parenthesized name of such types"
And I don't see why applying to a pointer to a function has to be explicitly and normatively allowed.
> Remove [expr.sizeof]/3

- source/templates.tex
Specializations are defined as classes and functions that are instantiated or explicitly specialized as stated on **[temp.spec]/4 sentence 2**. **[temp.class.spec.mfunc]/1 sentence 3** defines class template specializations as distinct templates, which is incorrect. 
Presumably, the intended meaning was that class template partial specializations are distinct templates, which would be correct.
> Fixed wording on [temp.class.spec.mfunc]/1 sentence 3

- source/utilities.tex
The Mandates: element should just state its condition, not say that it
"shall be true". Cpp17 concept requirements should be phrased as "X meets the
Y requirements" not "X shall meet the requirements of Y".
> [func.not_fn], [func.bind_front] fix phrasing of \mandates and \expects

- source/utilities.tex
`ptr` is an odd name for a parameter that is a reference to storage for an object.
> [specialized.algorithms] Rename voidify's parameter

- source/classes.tex
`x` and `y` have the same type (this is in the context of a defaulted relational operator, so they have to be per [class.compare]/1). So either `x <=> y` finds something or it doesn't - there's no situation where we'd select the reversed candidate `y <=> x`, so we can simplify this wording. Same thing Richard pointed out http://lists.isocpp.org/core/2019/03/5706.php about defaulted `!=`.
Also, we never changed that `x <=> y @ 0` is actually convertible to `bool`, so added that too.
> Simplifying [class.rel] wording.

- source/numerics.tex
- source/time.tex
> [time.clock.req] Simplify requirements for Cpp17TrivialClock.

- source/algorithms.tex
> [mismatch] LWG3178 std::mismatch is missing an upper bound

- source/declarations.tex
- source/macros.tex
- source/statements.tex
We already used this typeface for exposition-only identifiers in the
library wording.
Fixes #2783.
> Switch to using constant-width italics for exposition-only names in the core wording

- source/declarations.tex
According to [basic.start.static]/2, for objects with static storage duration,
zero initialization performs only if constant initialization does not.
[decl.init]/10 can be generalized to static initialization.
This is an editorial note change.
> [decl.init]/10 Fix specified initialization.

- source/templates.tex
Added "an" before "explicit" to make the sentence grammatically correct.
> Fixed grammar of [temp.expl.spec]/18 sentence 2

- source/utilities.tex
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0718r2.html
Or, I think the synopsis needs forward declaration of `atomic` class for specialization.
> add forward declaration of atomic class for atomic<shared_ptr<T>> (P0718R2)

- source/algorithms.tex
> [equal.range] Fix formatting of 'Returns' clause.

- source/macros.tex
Fixes #2835.
No layout differences (checked via "diffpdf").
> [macros] Adjust \tref to enlarge active link text.

- source/basic.tex
Intention is to allow pointer to storage out of lifetime to be treated as `void*` in a well-defined manner. The erroneous comma makes the sentence gramatically incorrect.
> [basic.life]/6 Remove erroneous comma in description of treatment of storage out of lifetime

- source/lib-intro.tex
Following the same principle as locating GENERALIZED_SUM in
the library index, add an entry for the exposition-only function
decay-copy, which is used to specify several parts of the library
quite remote from where it is now defined.
> [expos.only.func] Add library index entry for decay-copy

- source/iostreams.tex
The second parameter name "new" of function "rename" is a keyword, so it should be renamed.
> [cstdio.syn] Rename parameter name of function "rename"

- source/utilities.tex
> [pointer.conversion] Reorder overloads of to_address

- source/support.tex
...which is the proper spelling of this particular Word of Power.
> [coroutine.traits.primary] Hyphenate "program-defined"

- source/iterators.tex
`inserter` and `insert_iterator` are in namespace `std`, so `ranges::iterator_t` should be used while introducing them.
Fixes #2859.
> [iterators] Add "ranges::" for "iterator_t"

- source/basic.tex
> [basic.start.static] Repair index entry for zero-initialization.

- source/classes.tex
- source/declarations.tex
- source/exceptions.tex
- source/expressions.tex
- source/statements.tex
- source/templates.tex
> [std] Do not use teletype spaces in BNF

- source/expressions.tex
> [expr.prim.lambda] Simplify grammar for lambda-expression.

- source/tables.tex
No visual differences, but less redundant LaTeX source.
@tkoeppe, could you please apply this?
> [tables] Various cleanups.

- source/styles.tex
MacTex 2019 comes with listings in version 1.8b. Without this change, it does not compile.
> [styles] Also allow 'listings' package v1.8b

- source/numerics.tex
These have been there since C++11; it looks like the parameter names were removed, but the spaces left. NFC.
> Remove four extraneous spaces from parameter lists ([rand.device] and [rand.util.seedseq])

- source/concepts.tex
`requires ConvertibleTo<const remove_reference_t<B>&, bool>;` is a simplification of `b1; requires ConvertibleTo<decltype(b1), bool>;` which would have been cleaned up to `{ b1 } -> ConvertibleTo<bool>;` (the intended requirement) post P1084, had it not been simplified in P0896.
~Drive-by: reorder the binary expression requirements consistently as b1 op b2, b1 op a, a op b2.~
> [concept.boolean] Rephrase first requirement

- source/ranges.tex
Exposition-only entities "range-common-iterator-impl" and "range-common-iterator" are unused. They are redundant and should be dropped.
> [view.interface] Drop unused exposition-only items

- source/declarations.tex
if they are not direct, like in the code below:
```c++
class B { int i; };      // i is private
struct A : B { int j; }; // but A is still an aggregate
A a = { {}, 1 }; // OK
```
> [dcl.init.aggr]/1 An aggregate can have private or protected data members

- source/expressions.tex
> [expr.alignof,expr.unary.noexcept] Reorder to after [expr.sizeof].

- source/iostreams.tex
As discussed on the LWG reflector, it doesn't make sense to state this as a postcondition of the function.
> [fs.rec.dir.itr.members] change \ensures to \remarks for pop()

- source/containers.tex
> [views.span] Move description of iterators to [span.iterators].

- source/time.tex
> [time.cal.ymwd.nonmembers] Fix typo in parameter names.

- source/strings.tex
Fix missed application of P1032R1 to the result of applying P0482R6;
both papers were moved at the 2018-11 meeting.
Fixes #2795.
> [char.traits.specializations.char8.t] Make all members constexpr.

- source/exceptions.tex
The copy-assignment operator for std::thread is deleted, but the
move-assignment operator documents a call to std::terminate as
expected.  Suggesting this is an editorial fix rather than something
to run through the Core issues lists.
> [except.terminate] thread has move-assignment, not copy

- source/utilities.tex
> [allocator.adaptor.syn] Avoid confusing term 'memory resource'.

- source/declarations.tex
This note doesn't seem to be specific to paragraph 3, so I think it's correct that it's in its own paragraph (rather than being part of p3) but that means it should have its own `\pnum`:
> [dcl.mptr] Add \pnum to note

- source/support.tex
Per the Specification Style Guidelines.
> [coroutine.handle,coroutine.handle.export.import] "static" before "constexpr"

- source/algorithms.tex
- source/atomics.tex
- source/containers.tex
- source/iostreams.tex
- source/lib-intro.tex
- source/locales.tex
- source/numerics.tex
- source/regex.tex
- source/strings.tex
- source/support.tex
- source/tables.tex
- source/threads.tex
- source/utilities.tex
> [lib] Reformat summary tables.

- source/support.tex
- source/utilities.tex
- source/xrefdelta.tex
> [language.support, utilities] Condense description of exception classes

- source/containers.tex
instead of having 'worst case' in a separate sentence.
Fixes #2749.
> [unord.req] Consistently use 'Average case x, worst case y.'

- source/algorithms.tex
When referring to a function, use its name, not a call expression.
> [algorithms.parallel.exec],[alg.set.operations],[alg.min.max],[alg.clibrary] remove empty parens

- source/xrefdelta.tex
> [xrefdelta] Remove spurious entry for no-op rename.

- source/time.tex
to [time.cal.ymwdlast.overview], consistent with
neighboring similar subclauses.
Fixes #2915.
> [time.cal.ymwdlast.members] Move statement on class properties

- source/algorithms.tex
Per [rand.req.urng]/1, the result type of a `UniformRandomBitGenerator` must model `UnsignedIntegral`, i.e., it must be an integral type. [alg.random.sample]/1.5 requires `Distance` to be an integer type. Since all integer types are convertible to all other integer types, the result type of any `UniformRandomBitGenerator` is convertible to `Distance`. The library need not enforce the rules of the core language.
> [alg.random.sample] Remove redundant requirement

- source/iostreams.tex
The examples for path::append show the wrong results for Windows, not matching the description of the function. This has been discussed with Billy O'Neal who confirmed the correct results.
> [fs.path.append] Fix examples to show correct results for Windows

- source/support.tex
Affects `eq`, `ord`, and `ncmp` - as well as their enumerators - defined in [cmp.categories.pre]/1 and used throughout [cmp.categories].
Fixes #2801.
> [cmp.categories] Use kebab-case for \expos enumerations

- source/declarations.tex
Extend the example to show that the choice of `class` or `struct` in an
_elaborated-type-name_ referring to a class is not significant.
> [dcl.type.elab] Mix struct/class in example

- source/iostreams.tex
I have no idea how this got here - it was in the initial git commit - or why it isn't `\\expos`, but in any case it's unused.
> [istream.sentry] Remove unreferenced typedef-name traits_type

- source/basic.tex
> [basic.lookup.elab] Clarify example to refer to injected-class-name
