cplusplus/draft

source/intro.tex

This pull request implements the suggestions in https://github.com/cplusplus/draft/issues/428

Fix "ill-formed program" definition.

---

source/utilities.tex

Aligning the declarations in the declaration of system_clock.

Align declarations

---

source/containers.tex

[containers] Minor whitespace and ordering improvements

---

source/iostreams.tex

Fixes #503, though not in the way suggested by that issue :)

Fix "returns returns"

---

source/expressions.tex

Adding the closing paren within a note.

[expr.new] Terminate a parenthetical

---

source/numerics.tex

[numerics] Use simpler table for header content

---

source/algorithms.tex
source/containers.tex

This is a rebasing of the abandoned PR #305 by @cassioneri.

Improve consistency of complexity descriptions

---

source/iostreams.tex

[class.path] escape backslash in character literal

---

source/lex.tex

"preprocessor token" -> "preprocessing token"

[lex.pptoken] fix term

---

README.rst

[Readme] Fix isocpp link for DR submission

---

source/overloading.tex

[overloading] Make operators appear in code font

---

source/iostreams.tex
source/strings.tex

Replace NULL with "null pointer value"

---

source/classes.tex

s/initialiation/initialization/.

[class.union] Fix typo.

---

source/support.tex
source/utilities.tex

[support,utilities] More uses of \indexlibrarymember

---

source/iostreams.tex

[file_status.obs] Remove stray \begin{itemdecl}.

---

source/future.tex

[depr.strstream.dest] Move rdbuf() to [depr.strstream.oper].

---

source/iostreams.tex

This is @AlisdairM's work, just repackaged.

Editorial review of Clause 27 [input.output]

---

source/utilities.tex

@zygoloid: It's just a bunch of whitespace and newlines, is this OK during balloting?

[time.syn] Format whitespace more consistently with the rest of the WD

---

source/iterators.tex

[input.iterators] Fix formatting of parentheses and p.

---

source/iostreams.tex

Is is unspecified ... -> It is unspecified ...

[streambuf.virt.put] Fix typo

---

source/numerics.tex
source/templates.tex

Correct indefinite articles: "a" --> "an"

[temp.alias, rand.dist.pois.exp] Fix typos

---

source/declarators.tex

[dcl.init] don't mention expresion where braced-init-list may appear

---

source/special.tex

[class.dtor] add paragraph number

---

source/intro.tex

[intro.races] remove redundant constraint on modification order

---

source/algorithms.tex

[alg.reverse] use ValueSwappable instead of swappable requirement

---

source/strings.tex

[string.capacity] improve max_size() description by copying from string_view

---

source/strings.tex

[string::compare] replace smallest by smaller

---

source/threads.tex

Switch to using neither/nor instead of neither/or.

[future.async]p3 use neither/nor

---

source/utilities.tex

[func.bind.bind] fix intro sentence for local definitions

---

source/declarators.tex

[dcl.init] clarify invocation of list-initialization for '= braced-init-list'

---

source/future.tex
source/iostreams.tex
source/iterators.tex
source/locales.tex
source/strings.tex

[lib] modernize closing template brackets

---

source/special.tex

[class.ctor] split into numbered paragraphs

---

source/threads.tex
source/utilities.tex

[any,thread] Whitespace for template parameter packs

---

source/containers.tex
source/iterators.tex

[containers] 'const iterator' should be 'constant iterator'

---

source/atomics.tex

[atomics] Fix standard-layout requirement for atomic types

---

source/lib-intro.tex

[type.descriptions.general] Remove reference to undefined library concepts.

---

source/declarations.tex

[namespace.udecl] Remove stray newline in grammar production

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/expressions.tex
source/overloading.tex
source/support.tex
source/templates.tex

Harmonize formatting of 'cv-qualified'

---

source/expressions.tex
source/iostreams.tex
source/numerics.tex
source/threads.tex
source/utilities.tex

Replace 'sub-clause' by 'subclause'

---

source/utilities.tex

[meta] add cross-references to 'referenceable type'

---

source/algorithms.tex

Correct typo in algorithms.tex

---

source/support.tex

[exception] Rephrase to avoid overfull hbox

---

source/atomics.tex
source/expressions.tex
source/lex.tex
source/macros.tex
source/numerics.tex
source/overloading.tex
source/utilities.tex

Define a new macro \caret and use it

---

source/expressions.tex

[expr.rel] Complete the definition of 'compares greater than'

---

source/locales.tex

[facet.num.put.virtuals] define showpoint and don't apply & twice

---

source/containers.tex
source/iterators.tex
source/utilities.tex

[lib] Spell value-initialization with a hyphen.

---

source/locales.tex

First two pages of diffs:
Rest is reflow.

[locale.facet] Don't bother itemizing a single item.

---

source/threads.tex

[thread.lock.shared] Add sectioning comments to synopsis.

---

source/algorithms.tex
source/atomics.tex
source/containers.tex
source/diagnostics.tex
source/iostreams.tex
source/iterators.tex
source/locales.tex
source/numerics.tex
source/regex.tex
source/strings.tex
source/support.tex
source/threads.tex
source/utilities.tex

[lib] Harmonize sectioning comments of synopses.

---

source/macros.tex

@zygoloid, @jwakely: Please have a look. I think we can afford to lose that whitespace.

[macros] Reduce whitespace at the end of code blocks

---

source/support.tex

Similar to https://github.com/cplusplus/draft/pull/1093.

[new.delete] Use \replaceable instead of \textit

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/declarators.tex
source/exceptions.tex
source/special.tex
source/support.tex
source/templates.tex
source/threads.tex
source/utilities.tex

Capitalize notes.

---

source/basic.tex
source/expressions.tex
source/lib-intro.tex

Capitalize examples outside sentences.

---

source/derived.tex

[class.virtual] Remove awkward 'but'.

---

source/algorithms.tex
source/utilities.tex

Clean up duplicate 'itemdescr' items.

---

source/threads.tex

[thread] Add numbered headings for synopses.

---

source/locales.tex

[localization] Fix indentation in class template synopses.

---

source/locales.tex

[localization] Add numbered headings for synopses.

---

source/strings.tex

From http://lists.isocpp.org/lib/2016/12/1531.php.

[string.view.hash] Add a note about equality to string hashes.

---

source/overloading.tex

[over.built] Rework formatting of placeholders.

---

source/algorithms.tex
source/compatibility.tex
source/strings.tex

These are the only occurrences.

[strings, algorithms, diff] Replace 'routine' with 'function'.

---

source/templates.tex

[temp] Add variable templates to the definition of 'template'.

---

source/utilities.tex

https://github.com/cplusplus/draft/issues/516

[utilities] Use code font for named requirements

---

source/templates.tex

[temp.class] Reorganize examples into separate paragraph

---

source/conversions.tex
source/declarators.tex
source/utilities.tex

"diffpdf" shows no differences.
Partially addresses #1139.

Mechanically harmonize indexed types to $\tcode{T}_i$.

---

source/expressions.tex

[expr.reinterpret.cast] Index implementation-defined behavior.

---

source/numerics.tex

of implementation-defined behavior.

[sf.cmath.cyl_bessel_j] Remove parentheses for index entry

---

source/numerics.tex

[complex.ops] Don't repeat declaration in "Effects:" element.

---

source/declarations.tex
source/overloading.tex

Fix range_close markers for index ranges

---

source/numerics.tex

[rand.adapt.ibits] Don't typeset binary + as unary +.

---

source/numerics.tex

[numerics] Remove useless \mbox wrappings.

---

source/expressions.tex

[expr.prim.fold]  Fix alignment in list of fold-operators.

---

source/basic.tex
source/conversions.tex
source/expressions.tex
source/lex.tex
source/support.tex

For consistency. Addresses #440.

Add missing hyphen in 'floating-point'.

---

source/declarations.tex

[dcl.link] Index implementation-defined behavior.

---

source/iostreams.tex

[basic.ios.cons] Remove stray semicolon.

---

source/utilities.tex

[func.bind.bind] Reformat to use math-style indexing.

---

source/special.tex

[class.temporary] Use 'Clause~\ref{class.access}'

---

source/derived.tex
source/iostreams.tex
source/special.tex

Use 'base class subobject', not 'base subobject'

---

source/templates.tex

[temp.class.spec] Fix index entry for 'primary class template'.

---

source/basic.tex

[basic.fundamental] Fix index entries for sizeof

---

source/containers.tex
source/iostreams.tex
source/iterators.tex
source/locales.tex
source/numerics.tex
source/strings.tex
source/utilities.tex

..and apparently some trailing whitespace cleanup because my text editor hates it as much as I do.

Fix destructor declaration indentation

---

source/compatibility.tex

Found using [anorack](https://github.com/jwilk/anorack).

[diff.decl] Fix typo

---

source/algorithms.tex
source/compatibility.tex
source/containers.tex
source/declarators.tex
source/iostreams.tex
source/numerics.tex
source/regex.tex
source/strings.tex
source/support.tex
source/templates.tex
source/utilities.tex

http://eel.is/tcodediffs.pdf (45 pages)

Add missing \tcode.

---

source/intro.tex
source/support.tex

[intro.refs] Add normative references to LIA-1 and IEEE 754.

---

source/utilities.tex

[meta.trans] replace "shall name" with "names" in traits tables

---

source/algorithms.tex

[partial.sort] Remove 'It takes' from complexity specification.

---

source/intro.tex

[intro.memory] Replace undefined 'field' with 'member' in note.

---

source/utilities.tex

[any.cons] Use 'contained value', not 'contained object'.

---

source/future.tex
source/locales.tex
source/strings.tex
source/utilities.tex

[lib] Use nullptr, not 0, for null pointer values.

---

source/tables.tex

[tables] Do not show labels for 'concepttable' environment.

---

source/statements.tex

Fix spelling mistake in 'if constexpr' wording

---

source/iostreams.tex

[filesystem_error.members] Rename to [fs.filesystem_error.members]

---

source/expressions.tex

[expr.type.conv] Clarify if ... otherwise ladder.

---

source/expressions.tex

These two paragraphs are closely related.

[expr.const] Move p7 next to p3.

---

source/algorithms.tex

Fixes ISO 2 (C++17 DIS)
Fixes #1726

[alg.reverse] remove duplicated Requires: element

---

source/templates.tex

[temp.over.link] Change leading letter in comments in example to lowercase.

---

source/compatibility.tex

[diff.cpp14.library] Add Annex C entry for new headers in C++17

---

source/threads.tex

[thread.condition.condvarany] Remove note made incorrect by LWG 2135.

---

source/intro.tex

I realize these notions are only mentioned in notes, but I think it would be useful if people could find the relevant paragraphs if they searched the index for "coherence".

[intro.races] Add index entries for notions of coherence.

---

.travis.yml

Also delete the "manual" check since "complete" subsumes "manual".
@zygoloid, @godbyk: Could you please take a look whether this looks right?

[travis] Make overfull hboxes a presubmit error.

---

source/containers.tex

[array.size] Remove full template declaration.

---

source/iterators.tex
source/locales.tex
source/threads.tex

[lib] Add hyphen to 'well-defined'

---

source/back.tex
source/locales.tex

[locale.moneypunct.virtuals] Add reference to ISO 4217.

---

source/basic.tex

[intro.execution] Clarify full-expression in example.

---

source/lib-intro.tex

This follows the style of the surrounding comments.

[swappable.requirements] Merge example's comment to one line

---

source/lex.tex

Implements review comment from closed #1678.

[lex.ccon] Align char16_t phrasing to UTF-8 one

---

source/atomics.tex
source/iostreams.tex
source/regex.tex
source/strings.tex
source/utilities.tex

[lib] Harmonize punctuation of 'Effects: Equivalent to'

---

source/Makefile
source/back.tex
source/macros.tex
source/std.tex

and remove them from the index of library names.
Fixes #1807.

Create a new index for library headers

---

source/access.tex
source/basic.tex
source/classes.tex
source/declarations.tex
source/declarators.tex
source/derived.tex
source/exceptions.tex
source/expressions.tex
source/intro.tex
source/iostreams.tex
source/lex.tex
source/macros.tex
source/overloading.tex
source/preprocessor.tex
source/special.tex
source/statements.tex
source/templates.tex
source/utilities.tex

Convert blah\opt to \opt{blah}

---

source/templates.tex

[temp.arg.explicit] Remove note obsoleted by P0846R0

---

source/compatibility.tex
source/macros.tex

[diff] Introduce numbered paragraphs

---

source/access.tex
source/expressions.tex

[class.friend], [expr.ref], [expr.mptr.oper] Apply \grammarterm markings

---

source/basic.tex
source/conversions.tex

[basic.compound], [conv.ptr] Improve index for 'null pointer value'

---

source/xrefdelta.tex

[xrefdelta] Add deprecation of [util.smartptr.shared.atomic]

---

source/intro.tex

[intro.scope] C++ is not a strict superset of C

---

source/utilities.tex

[charconv.to.chars, charconv.from.chars] Replace 'minus sign' with '-'

---

source/locales.tex

[facet.num.put.virtuals] Fix definition and use of 'loc'

---

source/strings.tex

[string.cons] Replace postcondition tables by ordinary Postcondition elements

---

source/containers.tex

Make it match the one for `vector`.
Compare [vector.data]/1 with the proposed [array.data]/1

Update the description for array.data

---

source/lib-intro.tex

[library] Replace \term with \defnx

---

source/preprocessor.tex

[cpp] Replace \term with \defn

---

source/overloading.tex

[over.best.ics] Adjust example for [over.match.list] case

---

source/overloading.tex

[over] Replace \term with \defnx to add index entries

---

source/conversions.tex

[conv] Replace \term with \defn or \defnx

---

source/future.tex

[depr.str.strstreams] Add synopsis for <strstream> header

---

source/declarations.tex

[dcl.dcl] Change example for static_assert

---

source/iterators.tex
source/xrefdelta.tex

[insert.iterators] Dissolve single-item subclauses.

---

source/intro.tex

[intro.abstract] Change example for unspecified behavior.

---

source/access.tex
source/basic.tex
source/classes.tex
source/declarations.tex
source/declarators.tex
source/derived.tex
source/special.tex

[index] Do not index examples

---

source/containers.tex

[span.cons] Fix indentation of remarks.

---

source/conversions.tex
source/special.tex

[conv.fctptr,special] Pointers to members designate their target

---

source/support.tex

[support.types.byteops] Move 'Remarks' to after 'Effects'

---

source/utilities.tex

[utilities] Move chars_format bitmask statement to [charconv.syn]

---

source/containers.tex

[containers] Remove class name repeated in subheadings

---

source/locales.tex

[locale] Remove class name repeated in subheadings

---

source/basic.tex
source/conversions.tex
source/locales.tex
source/overloading.tex
source/support.tex

Thus, replace it with "floating-point type".

'floating type' is not a defined term in C++

---

source/statements.tex

[stmt.while] Generalize the equivalence for a declaration as the condition.

---

source/containers.tex

[associative.reqmts] Turn emphasis into a note.

---

source/containers.tex
source/xrefdelta.tex

[containers] Removed redundant specifications of non-member swap

---

source/limits.tex

[implimits] Clarify meaning of implementation limits

---

source/containers.tex

Still somewhat out of date, but better.

Update container advice

---

source/utilities.tex

[any.class] Rephrase small-object optimization

---

source/expressions.tex
source/future.tex
source/templates.tex
source/utilities.tex

Clarify which kind of parameter pack is intended.

---

source/utilities.tex

[pairs.pair] Missed rename from U,V to U1,U2.

---

source/containers.tex

[span.overview] Fix typo

---

source/special.tex

[class.dtor] Typo.

---

source/numerics.tex

[template.gslice.array.overview] Join two single-sentence paragraphs.

---

source/declarations.tex
source/expressions.tex

[dcl.type.cv,expr.ass] Clarify the meaning of "modify" for an object.

---

source/expressions.tex

[expr.new] Remove misplaced index entries

---

source/classes.tex

[class] Remove misplaced index entries

---

source/basic.tex
source/declarators.tex
source/expressions.tex
source/overloading.tex

P1114R0 CWG "tentatively ready" Issues for the June, 2018 (Rapperswil) meeting

---

source/expressions.tex
source/future.tex

P0806R2 Deprecate implicit capture of this via [=]

---

source/declarations.tex
source/expressions.tex
source/lex.tex
source/overloading.tex
source/special.tex
source/templates.tex

P0732R2 Class types in non-type template parameters

---

source/basic.tex
source/expressions.tex
source/special.tex
source/support.tex

 P0722R3 Efficient sized delete for variable sized classes

---

source/declarations.tex

P1064R0 Allowing virtual function calls in constant expressions

---

source/expressions.tex
source/future.tex

P1120R0 Consistency improvements for <=> and other comparison operators

---

source/utilities.tex

P0475R1 LWG 2511: guaranteed copy elision for piecewise construction

---

source/containers.tex

P0458R2 Checking for existence of an element in associative containers

---

source/iostreams.tex

P0759R1 fpos requirements

---

source/algorithms.tex

P0769R2 Add shift to <algorithm>

---

source/utilities.tex

P0887R1 The identity metafunction

---

source/algorithms.tex
source/iterators.tex
source/utilities.tex

P0879R0 Constexpr for swap and swap-related functions

---

source/utilities.tex

P0758R1 Implicit conversion traits and utility functions

---

source/numerics.tex

P0556R3: Integral power-of-2 operations

---

source/atomics.tex

P0019R8 Atomic ref

---

source/compatibility.tex
source/containers.tex

P0646R1 Improving the return value of erase-like algorithms

---

source/iterators.tex

[iterator.requirements.general] eliminate extra leading space in para 13

---

source/utilities.tex

[smartptr] Remove class name repeated in subheadings

---

source/diagnostics.tex

[syserr] Remove class name repeated in subheadings

---

source/atomics.tex

[atomics.order] Index entries for memory_order should be in code font

---

source/templates.tex

[temp.dep] Typo fix: 'An expressions...'

---

source/basic.tex

[basic.fundamental] Add definition of 'fundamental type'

---

source/utilities.tex

[optional] Move requirements from header synopsis to class template

---

source/future.tex

[depr.locale.stdcvt.req] Add normative references for encoding forms

---

source/declarations.tex

[dcl.attr.contract] Introduce subheadings and reorder paragraphs to fit

---

source/iterators.tex
source/regex.tex
source/templates.tex

[temp.constr.constr]/2, [iterator.requirements.general]/14, [re.results.size]/1 Replace "section" with "subclause"

---

source/classes.tex

Partially addresses #1771 and #1730.

[class] Introduce a subheading 'Properties of classes'.

---

source/lib-intro.tex

by ordering [localization] correctly, and adding a row for [time]

[library.general] Fixup the library categories table

---

source/strings.tex

[string.view] Move complexity requirement into [string.view.template].

---

source/basic.tex

and avoid duplicate definitions of some terms.

[basic] Fix index entry for 'odr-use'

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/containers.tex
source/declarations.tex
source/templates.tex

[copy.ctor] Rearrange constructor subclauses

---

source/statements.tex

[stmt.switch] Clarify comparison for case labels

---

source/classes.tex

[class.virtual] Define 'virtual function'

---

source/basic.tex

"aggregate" is an array or a class type with some restrictions.

[basic.life] Change "class or aggregate type" to "class or array type"

---

source/expressions.tex

[basic.lval] Clarify result object for prvalues as operands

---

source/classes.tex

[class.this] A pointer represents more than an address

---

source/basic.tex

temporary objects are.
Fixes #2305.

[class.temporary] prvalues are not materialized,

---

source/basic.tex

[basic.def.odr] Replace undefined term 'non-trivial function'

---

source/basic.tex

[basic.def.odr] Clarify antecedent for declarative region

---

source/utilities.tex

[unique.ptr.single.ctor] Simplify description of unique_ptr constructors

---

source/basic.tex

Jens and Tony believe it isn't normative and doesn't need a DR to fix. Let's do it now.

Move "plain ints" statement to a note

---

source/containers.tex
source/diagnostics.tex
source/iostreams.tex
source/iterators.tex
source/lib-intro.tex
source/macros.tex
source/numerics.tex
source/regex.tex
source/strings.tex
source/support.tex
source/threads.tex
source/time.tex
source/utilities.tex

Addresses a leftover from #2132.

[lib] Replace \postconditions with \ensures

---

source/iostreams.tex

[input.output] Remove class name repeated in subheadings

---

source/styles.tex

[styles] Also allow 'listings' package v1.7

---

source/declarations.tex
source/expressions.tex
source/overloading.tex
source/templates.tex

P1350R0 Core Language Working Group "tentatively ready" Issues (San Diego)

---

source/basic.tex
source/compatibility.tex

P0982R1 Weaken Release Sequences

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/expressions.tex
source/grammar.tex
source/iterators.tex
source/overloading.tex
source/templates.tex
source/xrefdelta.tex

 P1131R2 Core Issue 2292: simple-template-id is ambiguous between class-name and type-name

---

source/declarations.tex

P1094R2 Nested Inline Namespaces

---

source/expressions.tex

P1330R0 Changing the active member of a union inside constexpr

---

source/algorithms.tex
source/atomics.tex
source/concepts.tex
source/containers.tex
source/future.tex
source/iostreams.tex
source/iterators.tex
source/lib-intro.tex
source/regex.tex
source/strings.tex
source/support.tex
source/threads.tex
source/time.tex
source/utilities.tex

P1224R0 C++ Standard Library Issues to be moved in San Diego except 2697, 2960 and 3134

---

source/atomics.tex

P1123R0 Editorial Guidance for merging P0019r8 and P0528r3

---

source/utilities.tex

P1006R1 Constexpr in std::pointer_traits

---

source/utilities.tex

P1285R0 Improving Completeness Requirements for Type Traits

---

source/utilities.tex

Also fixes #1757.
Fixes #2428.

P0899R1 LWG 3016 is Not a Defect (issue #2428)

---

source/containers.tex

Fixes #2429. (This supercedes https://github.com/cplusplus/draft/pull/2478.)

P1085R2 Should Span be Regular?

---

source/declarations.tex

[dcl.spec.auto] Return type deduction should refer to templated entity

---

source/basic.tex

[basic.type.qualifier] Clarify the definitions of const/volatile object

---

source/utilities.tex

[func.bind_front] Use unwrap_ref_decay_t

---

source/lib-intro.tex

[structure.summary] Add missing templated entities

---

source/iterators.tex
source/lib-intro.tex
source/ranges.tex
source/utilities.tex

[ranges] Shorten and adjust stable labels

---

source/overloading.tex

[over.best.ics] Turn 'such as' list into a note

---

source/statements.tex

[stmt.while] Simplify rewrite rule.

---

source/declarations.tex

[dcl.enum] Merge duplicate normative paragraphs on redeclarations.

---

source/overloading.tex

[over.best.ics] Clarify ambiguous conversion sequence

---

source/iterators.tex

See the concept just below the modified one.

[iterator.traits] Present concept requirements consistently

---

source/basic.tex

undefined boolean note clarification

---

source/iterators.tex

[iterator.concepts.readable] Turn parenthesized explanation into a note.

---

source/iterators.tex

[iterator.concept.bidir] Add comma for clarity

---

source/iterators.tex

Just 6 lines below, it is correct.

[indirectcallable.general] Fix reference

---

source/compatibility.tex

[diff.cpp17.library] add <ranges>

---

source/iterators.tex

[iterator.primitives] Rescue introductory sentence.

---

source/iterators.tex

[iterators] Remove duplicated declarations

---

source/iterators.tex

[iterators] Qualify declarator-id with sub-namespace.

---

source/declarations.tex
source/expressions.tex

P1091R3 Extending structured bindings to be more like variable declarations

---

source/expressions.tex

P1381R1 Reference capture of structured bindings

---

source/compatibility.tex
source/declarations.tex
source/lex.tex

P1041R4 Make char16_t/char32_t string literals be UTF-16/32

---

.gitignore
source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/expressions.tex
source/lex.tex
source/lib-intro.tex
source/overloading.tex
source/preprocessor.tex
source/statements.tex
source/support.tex

P0912R5 Merge Coroutines TS into C++20 working draft

---

.gitignore
source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/expressions.tex
source/lex.tex
source/lib-intro.tex
source/overloading.tex
source/preprocessor.tex
source/statements.tex
source/support.tex

(Merged from #2747.)
Fixes #2693

P0912R5 Merge Coroutines TS

---

source/support.tex
source/utilities.tex

P0339R6 polymorphic_allocator<> as a vocabulary type

---

source/iterators.tex

Fixes #2697.
Cloned from #2714.

P0738R2 I Stream, You Stream, We All Stream for istream_iterator

---

source/diagnostics.tex

P1459R1 Mandating the Standard Library: Clause 18 - Diagnostics library

---

source/strings.tex

P1462R1 Mandating the Standard Library: Clause 20 - Strings library

---

source/algorithms.tex
source/numerics.tex
source/support.tex

P0811R3 Well-behaved interpolation for numbers and pointers

---

source/containers.tex
source/support.tex

P0920R2 Precalculated hash values in lookup

---

source/basic.tex

[basic.lookup.argdep] Reorder bullets to group semantics.

---

source/classes.tex

[class.eq,class.spaceship] Clarify order of comparison.

---

source/overloading.tex

"Given these definitions" should start a new paragraph.

[over.match.best] Add number for paragraph 2.

---

source/expressions.tex

[expr.type] Fix missing formatting for 'T'.

---

source/containers.tex

[queue.syn,stack.syn] Add partial specialization of uses_allocator

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/expressions.tex
source/lex.tex
source/macros.tex
source/modules.tex
source/overloading.tex
source/statements.tex
source/templates.tex

[std] Index all mentions of keywords in grammar productions.

---

source/containers.tex

On:
[container.node.overview]/4
[container.node.cons]/3.1
[container.node.dtor]/1

[container.node] Add 3 template keywords for dependent name

---

source/algorithms.tex
source/basic.tex
source/containers.tex
source/declarations.tex
source/expressions.tex
source/future.tex
source/iostreams.tex
source/overloading.tex
source/preprocessor.tex
source/statements.tex
source/templates.tex
source/utilities.tex

This is intended as a purely editorial changeset.

Fix a bunch of faulty parallelism with "either".

---

source/algorithms.tex

[algorithms] Qualify declarator-id with sub-namespace.

---

source/iterators.tex

All such lists in [ranges] don't include ~~the following~~.

[iterator.cust] Introduce expression-equivalent list as in [ranges]

---

source/ranges.tex

[ranges.dangling] Fix namespace of ranges::dangling

---

source/containers.tex
source/utilities.tex

[utilities,containers] Harmonize presentation of tuple_element.

---

source/containers.tex

[map,multimap] Add index entries for members of value_compare.

---

source/time.tex

[time.zone.info] Add missing 'Returns' items.

---

source/modules.tex

not the undefined term 'namespace-declaration'.

[module.interface] Use 'namespace-definition',

---

source/iterators.tex

I also reflowed the paragraph with semantic breaks since I'm here.
(Fixes #2931.)

[iterator.requirements.general] "counted range" defines a term of art

---

source/ranges.tex

[range.counted] Introduce "Counted view"

---

source/iterators.tex

...which P0896R4 added in one place instead of two =(

[iterator.synopsis] Copy constraint for iterator_traits<T*> from [iterator.traits]/5

---

source/basic.tex

P0735R1 Interaction of memory_order_consume with release sequences

---

source/basic.tex
source/classes.tex
source/overloading.tex
source/preprocessor.tex

 P1186R3 When do you actually use <=>?

---

source/declarations.tex
source/preprocessor.tex

 P1301R4 [[nodiscard("should have a reason")]]

---

source/overloading.tex

P1816R0 Class template argument deduction for aggregates

---

source/basic.tex
source/compatibility.tex
source/declarations.tex

P1766R1 Mitigating minor modules maladies

---

source/compatibility.tex
source/declarations.tex
source/lex.tex
source/preprocessor.tex

P1143R2 Adding the constinit keyword

---

source/expressions.tex
source/iterators.tex
source/ranges.tex
source/templates.tex

P1452R2 On the non-uniform semantics of return-type-requirements

---

source/declarations.tex
source/expressions.tex
source/future.tex

P1152R4 Deprecating volatile

---

source/basic.tex
source/lex.tex
source/modules.tex
source/preprocessor.tex

P1703R1 Recognizing header unit imports requires full preprocessing

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/expressions.tex
source/preprocessor.tex
source/support.tex
source/utilities.tex

P0784R7 More constexpr containers

---

source/numerics.tex

- Also adjusted the synopsis.
Fixes #3006.

P1355R2 Exposing a narrow contract for ceil2

---

source/numerics.tex
source/support.tex

- Renamed stable labels.
Fixes #3007.

P0553R4 Bit operations

---

source/support.tex

P1424R1 'constexpr' feature macro concerns

---

source/lib-intro.tex
source/locales.tex
source/macros.tex
source/support.tex
source/time.tex
source/utilities.tex

P0645R10 Text formatting
P1361R2 Integration of chrono with text formatting
P1652R1 Printf corner cases in std::format
Fixes #3009, #3010, #3011.

2019-07 LWG Motions 5, 6, and 7

---

source/compatibility.tex
source/concepts.tex
source/lib-intro.tex
source/numerics.tex
source/support.tex

P0631R8 Math constants

---

source/atomics.tex
source/lib-intro.tex
source/support.tex
source/threads.tex
source/utilities.tex

- [atomics.wait] Make singular.
Fixes #3013.

P1135R6 The C++20 synchronization library

---

source/containers.tex
source/support.tex

P0325R4 to_array from LFTS with updates

---

source/numerics.tex
source/support.tex
source/utilities.tex

P1612R1 Relocate endian’s specification

---

source/containers.tex
source/support.tex

P1661R1 Remove dedicated precalculated hash lookup interface

---

source/time.tex

P1650R0 Output std::chrono::days with 'd' suffix

---

source/support.tex
source/utilities.tex

P1651R0 bind_front should not unwrap reference_wrapper

---

source/algorithms.tex
source/iterators.tex
source/ranges.tex
source/utilities.tex

P1035R7 Input range adaptors

---

source/iterators.tex
source/ranges.tex

P1522R1 Iterator difference type and integer overflow

---

source/iterators.tex
source/ranges.tex

[range.iota.view]p2 Added "be" in "Let ... c be a ..."
Fixes #3033.

P1474R1 Helpful pointers for ContiguousIterator

---

source/ranges.tex

P1523R1 Views and Size Types

---

source/basic.tex

[basic.lookup.argdep]/5 Added export to `apply(T t, U u)`

---

source/expressions.tex

[expr.ass] Remove mention of class types.

---

source/utilities.tex

[tuple.elem] Canonicalize comments in example.

---

source/numerics.tex
source/utilities.tex

[func.wrap.func,rand] Index 'result_type'.

---

source/compatibility.tex

[diff] Move markers to lines of their own.

---

source/templates.tex

[temp.param] Define X in the example.

---

source/iterators.tex

[ostream.iterator] Correct typo

---

source/algorithms.tex
source/atomics.tex
source/basic.tex
source/compatibility.tex
source/concepts.tex
source/containers.tex
source/diagnostics.tex
source/exceptions.tex
source/expressions.tex
source/future.tex
source/iostreams.tex
source/iterators.tex
source/lib-intro.tex
source/locales.tex
source/macros.tex
source/numerics.tex
source/ranges.tex
source/regex.tex
source/statements.tex
source/strings.tex
source/support.tex
source/threads.tex
source/time.tex
source/utilities.tex

[lib] Use more abstract library indexing macros

---

source/algorithms.tex
source/atomics.tex
source/back.tex
source/basic.tex
source/classes.tex
source/compatibility.tex
source/concepts.tex
source/containers.tex
source/declarations.tex
source/diagnostics.tex
source/expressions.tex
source/future.tex
source/iostreams.tex
source/iterators.tex
source/lib-intro.tex
source/locales.tex
source/macros.tex
source/numerics.tex
source/ranges.tex
source/regex.tex
source/strings.tex
source/support.tex
source/templates.tex
source/threads.tex
source/time.tex
source/utilities.tex

[std] Improve indexing of standard library headers.

---

source/Makefile
source/back.tex
source/concepts.tex
source/iterators.tex
source/macros.tex
source/ranges.tex
source/std.tex
source/support.tex
source/threads.tex
source/utilities.tex

[index] Add index of concept names.

---

source/utilities.tex

[meta] Harmonize ordering in descriptions.

---

source/utilities.tex

[tuple] Make descriptions of non-members siblings of [tuple.tuple].

---

source/threads.tex

[thread.jthread.class] Rephrase introductory sentence.

---

source/lex.tex

[lex.pptoken] Mention import keywords in the category list.

---

source/classes.tex

[class.dtor] Group declaration properties vs. behavior.

---

source/locales.tex

[locale] Fix example.

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/exceptions.tex
source/overloading.tex
source/preprocessor.tex
source/statements.tex
source/templates.tex

Fixes #3250.
Partially addresses #574.

[std] Introduce 'Preamble' sections to avoid hanging paragraphs.

---

source/algorithms.tex
source/atomics.tex
source/basic.tex
source/classes.tex
source/compatibility.tex
source/containers.tex
source/declarations.tex
source/future.tex
source/iostreams.tex
source/iterators.tex
source/lex.tex
source/lib-intro.tex
source/locales.tex
source/numerics.tex
source/overloading.tex
source/ranges.tex
source/regex.tex
source/strings.tex
source/support.tex
source/templates.tex
source/threads.tex
source/time.tex
source/utilities.tex
tools/check.sh

[std] Align all comments to multiples of four

---

source/ranges.tex

[ranges] Harmonize index entries.

---

source/support.tex

[version.syn] Add synopsis for <version> header.

---

source/numerics.tex

[rand.predef] Add digit separators to large numbers.

---

source/ranges.tex

[ranges] Add index entries.

---

source/intro.tex

[intro.defs] Hyphenate parameter-type-list.

---

source/algorithms.tex

...from incorporation of P0896R4.

[alg.min.max] Correct errors in paragraph 22

---

source/intro.tex

Fixes NB JP 23 (C++20 CD)
Fixes cplusplus/nbballot#23.

[intro.structure] 'Note n to entry' is also a note.

---

source/xrefdelta.tex

Fixes NB NL 374 (C++20 CD)
Fixes cplusplus/nbballot#370.

[xrefdelta] Fix typo for 'fmtflags'.

---

source/algorithms.tex

and avoid hanging paragraph in [algorithms.parallel]
by moving it here.
Fixes NB JP 314 (C++20 CD)
Fixes cplusplus/nbballot#310

[algorithms.parallel.defns] Rename to 'Preamble'

---

source/threads.tex

Fixes NB JP 362 (C++20 CD)
Fixes cplusplus/nbballot#358.

[thread.jthread.static] Repeat '[[nodiscard]]' from synopsis.

---

source/intro.tex

Fixes NB GB 022 (C++20 CD)
Fixes cplusplus/nbballot#22

[intro.compliance] The standard library also offers header units.

---

source/ranges.tex

[range.join.iterator] Remove spurious paragraph number

---

source/ranges.tex

Fixes NB US 295 (C++20 CD)
Fixes cplusplus/nbballot#291

[range.join.iterator] Clarify if ... otherwise ladder.

---

source/basic.tex

[conv.rank] Fix cross reference to expr.arith.conv

---

source/basic.tex
source/modules.tex

Fixes NB FR 039 (C++20 CD)
Fixes cplusplus/nbballot#38

[basic.lookup.argdep] Inline the definition of 'interface'.

---

source/classes.tex

Fixes #3400.
Also fixes LWG3295.

P1946R0 Allow defaulting comparisons by value

---

source/modules.tex

Also fixes NB US 086 (C++20 CD)
Fixes #3402 
Fixes cplusplus/nbballot#85

P1979R0 Resolution to US086

---

source/algorithms.tex
source/concepts.tex
source/iterators.tex
source/support.tex

Fixes #3409.
Fixes cplusplus/nbballot#181.
Fixes cplusplus/nbballot#263.
Fixes cplusplus/nbballot#302.
Fixes cplusplus/nbballot#308.
Fixes cplusplus/papers#482
Also fixes NB GB 183, US 267, US 306, and PL 312 (C++20 CD).

P1716R3 ranges compare algorithm are over-constrained

---

source/support.tex
source/threads.tex

Also fixes NB PL 363 (C++20 CD)
Fixes #3410 
Fixes cplusplus/nbballot#360
Fixes cplusplus/papers#619

P1869R1 Rename condition_variable_any interruptible wait methods

---

source/ranges.tex

Partially addresses NB US 272 and DE 288 (C++20 CD)
Fixes #3417
Fixes cplusplus/nbballot#266
Partially addresses cplusplus/nbballot#268
Partially addresses cplusplus/nbballot#284
Fixes cplusplus/papers#616

P1862R1 Ranges adaptors for non-copyable iterators

---

source/atomics.tex
source/threads.tex

NB US 355, US 358, US 359, US 356, US 364 (C++20 CD):
P1960R0 NB Comment Changes Reviewed by SG1
Fixes  #3420.
Issues: Is the commit message correct?  I did my best to follow our [guidelines](https://github.com/cplusplus/draft/wiki/Commit-message-format).
Fixes cplusplus/nbballot#351
Fixes cplusplus/nbballot#352
Fixes cplusplus/nbballot#354
Fixes cplusplus/nbballot#359

LWG Motion 18: P1960R0 NB Comment Changes Reviewed by SG1

---

source/algorithms.tex
source/support.tex

Fixes #3425.
Fixes cplusplus/nbballot#316
Fixes cplusplus/papers#432

P1645R1 constexpr for <numeric> algorithms

---

source/algorithms.tex

Fixes #3426.
Fixes cplusplus/papers#484.

P1718R2 Mandating the Standard Library: Clause 25 - Algorithms library

---

source/numerics.tex

Fixes #3427.
Fixes cplusplus/papers#485.

P1719R2 Mandating the Standard Library: Clause 26 - Numerics library

---

source/time.tex

Fixes #3428.
Fixes cplusplus/papers#463.

P1686R2 Mandating the Standard Library: Clause 27 - Time library

---

source/iostreams.tex

Fixes #3430.
Fixes cplusplus/papers#487.

P1721R2 Mandating the Standard Library: Clause 29 - Input/output library

---

source/regex.tex

Fixes #3431.
Fixes cplusplus/papers#488.

P1722R2 Mandating the Standard Library: Clause 30 - Regular Expression library

---

source/atomics.tex
source/future.tex

Fixes #3432.
Fixes cplusplus/papers#489.

P1723R2 Mandating the Standard Library: Clause 31 - Atomics library

---

source/threads.tex

Fixes #3433.
Fixes cplusplus/papers#394.

P1622R3 Mandating the Standard Library: Clause 32 - Thread support library

---

source/declarations.tex

[dcl.decl] Avoid double negative.

---

source/concepts.tex
source/containers.tex
source/diagnostics.tex
source/iostreams.tex
source/ranges.tex
source/regex.tex
source/support.tex
source/threads.tex
source/utilities.tex

[lib] Replace 'this subclause' with numbered subclause references.

---

source/ranges.tex

[range.istream] Relocate under [range.factories]

---

source/overloading.tex

[over.match.list] Acknowledge [over.ics.list] and clarify text.

---

source/basic.tex

[basic.def.odr] Split long-winded bulleted sentence.

---

source/templates.tex

[temp.constr.contr] Add index entry for 'satisfy'.

---

source/containers.tex

[span.cons] to_address cannot throw

---

source/ranges.tex

[ranges] Mark exposition-only names as kebab-case.

---

source/ranges.tex

[ranges] Missed kebab-case markings for exposition-only names.

---

source/statements.tex

[stmt.cont] Fix formatting.

---

source/styles.tex

From https://ctan.org/pkg/listings: 1.8c 2019-09-10

Allow 'listings' package v1.8c

---

source/ranges.tex

[range.subrange] Align comments.

---

source/numerics.tex

Also replace a numbered list with a bulleted one.
Fixes #1249.

[cmath.syn] Turn a consequence into a note.

---

source/iterators.tex

[iterator.requirements.general] Consistently index iterator terms.

---

source/containers.tex
source/lib-intro.tex
source/macros.tex
source/tables.tex
source/time.tex
source/utilities.tex

[index] Harmonize indexing for Cpp17 concepts.

---

source/ranges.tex

[ranges] Integrate adaptor subclauses into overviews.

---

source/algorithms.tex

All other _Returns:_ elements with the same form use "or".

[algorithms] Split list items conventionally

---

source/containers.tex

[span.overview] Correct typo

---

source/declarations.tex
source/macros.tex

[dcl.attr] Introduce 'Recommended practice' paragraphs.

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/expressions.tex
source/lib-intro.tex
source/macros.tex
source/numerics.tex
source/strings.tex
source/utilities.tex

Fixes #3688.
Fixes cplusplus/papers#106.
Fixes cplusplus/nbballot#39.

CWG Poll 4: P0593R6 Implicit creation of objects for low-level object manipulation

---

source/templates.tex

Also fixes NB GB 046 (C++20 CD).
Fixes #3690.
Fixes cplusplus/nbballot#45.

CWG Poll 6: P2104R0 Disallow changing concept values

---

source/expressions.tex
source/templates.tex

CWG Poll 8: P2092R0 Disambiguating nested requirements

---

source/declarations.tex
source/expressions.tex
source/templates.tex

Fixes #3693.
Note: CWG2053 fixed by CWG2447.

CWG Poll 9: P2108R0 Core Language Working Group "ready" Issues for the February, 2020 (Prague) meeting

---

source/modules.tex

Also fixes NB US 084 (C++20 CD).
Fixes #3694.
Fixes cplusplus/nbballot#83.

CWG Poll 10: P2109R0 Disallow "export import foo" outside of module interface

---

source/overloading.tex

Fixes #3695.
Fixes cplusplus/papers#809.

CWG Poll 11: P2082R1 Fixing CTAD for aggregates

---

source/templates.tex

Also fixes NB CA 112 (C++20 CD).
Fixes #3696.
Fixes cplusplus/nbballot#111.
Fixes cplusplus/nbballot#119.

CWG Poll 12: P2113R0 Proposed resolution for 2019 comment CA 112

---

source/expressions.tex
source/templates.tex

CWG Poll 15: P2095R0 Resolve lambda init-capture pack grammar (CWG2378)

---

source/expressions.tex

CWG Poll 19: P1937R2 Fixing inconsistencies between constexpr and consteval functions

---

source/atomics.tex
source/lib-intro.tex
source/support.tex

Fixes #3706.
Fixes cplusplus/papers#775.

LWG Poll 4: P2045R1 Missing Mandates for the standard library

---

source/utilities.tex

Fixes #3707.
Also fixes cplusplus/papers#726.

LWG Poll 5: P1460R1 Mandating the Standard Library: Clause 20 - Utilities library

---

source/algorithms.tex
source/utilities.tex

Also fixes NB US 313 (C++20 CD) and LWG3156.
Fixes #3708.
Fixes cplusplus/papers#697.
Fixes cplusplus/nbballot#309.

LWG Poll 6: P1963R0 Fixing US 313

---

source/time.tex

Also fixes NB DE 346 (C++20 CD).
Fixes #3711.
Fixes cplusplus/papers#712.
Fixes cplusplus/nbballot#342.

LWG Poll 9: P1982R0 Rename link to time_zone_link

---

source/concepts.tex
source/iterators.tex

Also fixes NB US 185 (C++20 CD).
Fixes #3714.
Fixes cplusplus/nbballot#183.

LWG Poll 12: P2102R0 Make 'implicit expression variations' more explicit

---

source/ranges.tex

Fixes #3720.
Fixes cplusplus/nbballot#271.

LWG Poll 18: P2091R0 Issues with range access CPOs

---

source/support.tex
source/utilities.tex

Also fixes NB DE 002 (C++20 CD).
Fixes #3723.
Fixes cplusplus/nbballot#2.

LWG Poll 21: P1973R1 Rename "_default_init" Functions, Rev1
