source/ranges.tex
source/support.tex

Fixes #5612
Fixes cplusplus/papers#1111

P2446R2 views::as_rvalue

---

source/basic.tex
source/declarations.tex
source/expressions.tex
source/lib-intro.tex
source/support.tex

Fixes #5613
Fixes cplusplus/papers#1115

P2465R3 Standard Library Modules std and std.compat

---

source/support.tex
source/utilities.tex

Fixes #5614
Fixes cplusplus/papers#1117

P2445R1 std::forward_like

---

source/ranges.tex
source/support.tex

Fixes #5617
Fixes cplusplus/papers#1156

P2494R2 Relaxing range adaptors to allow for move only types

---

source/lib-intro.tex
source/ranges.tex
source/support.tex

Fixes #5619
Fixes cplusplus/papers#1151

P2502R2 std::generator: Synchronous Coroutine Generator for Ranges

---

source/ranges.tex

This seems to be the only place in `<ranges>` and other libraries where there is a space between `template` and `<`.

[range.join.with.sentinel] Fix template format

---

source/ranges.tex

[ranges.syn] Add missing "freestanding" comment for as_rvalue.

---

source/modules.tex

@zygoloid, this addresses http://lists.isocpp.org/ext/2022/06/19564.php
Note that the example believes that fn_m (module linkage) is ok, but [dcl.inline] p7 makes no distinction between external and module linkage (both fn_e and fn_m are attached to the named module "A", I believe):
> If an inline function or variable that is attached to a named module is declared in a definition domain, it shall be defined in that domain.

[module.private.frag] Remove misleading example and broaden note

---

source/memory.tex

`std::pmr::polymorphic_allocator<T>` meets the _Cpp17Allocator_ requirements only if `T` is a cv-unqualified object type.
Fixes #5468.

[mem.poly.allocator.class.general] Clarify `polymorphic_allocator<void>` etc.

---

source/ranges.tex

Unfortunately, this got lost in https://github.com/cplusplus/draft/pull/5647#discussion_r929145700 because I suggested to simplify it as `decltype(current_) along with the class synopsis at https://github.com/cplusplus/draft/pull/5647#discussion_r929132253.

[ranges.cartesian.iterator] Fix format of `decltype(current_)`

---

source/future.tex
source/meta.tex

This replaces #2354, in line with the editorial meeting decision.

Use "denotes a type" in utilities library clause

---

source/statements.tex

As noted [here](https://lists.isocpp.org/std-discussion/2022/07/1737.php), we talk about the substatements of `if consteval`, but those are currently defined just in terms of _statement_ whereas `if consteval` has a _compound-statement_.

Substatements of if consteval

---

source/basic.tex
source/classes.tex
source/expressions.tex
source/lib-intro.tex

The term "enumerated type" is defined in [enumerated.types]
for use in the standard library, and is not synonymous with
"enumeration type".
Fixes #3977

[core] Replace 'enumerated type' with 'enumeration'

---

source/exceptions.tex
source/statements.tex

The "shall not be used to" phrasing may be taken to refer only in cases
where the actual use occurs or is the primary intent. Instead, the
intended restriction can be written in terms of static properties of the
constructs so restricted in the style of [stmt.if].
A new term of art (control-flow-limited statement) is introduced in
[stmt.label] to express the restrictions. Both [stmt.if] and
[except.pre] are updated to use the new term.
Co-authored-by: Johel Ernesto Guerrero Peña <johelegp@gmail.com>

[except.pre] Reword "shall not be used to" avoiding question of actual "use"

---

source/lex.tex

In P2071R2 and NameAliases.txt, 0+008E is named SINGLE-SHIFT-2, but it went
into the draft as "single shift-2", losing the hyphen between the words.

[lex.charset] Add missing hyphens

---

source/ranges.tex

The original wording seems to have been a copy-paste error.
Fixes #5735.

[range.cartesian.view] Fix definition of cartesian-product-is-common

---

source/utilities.tex

While implementing new features introduced by P2286R8 Formatting Ranges
I noticed some issues in the examples. These issues are in the paper
too.
For s3 the alternative would be to adjust the output instead of the
input.

[format.string.escaped] Fix invalid examples

---

source/ranges.tex

Note that I also removed the "`<V>`" part in "Class template `chunk_view<V>​::​iterator` for forward ranges" to be consistent with other sections.

[range.chunk] Add the class template description for `chunk_view`

---

source/expressions.tex

The misspelling was a misapplication of the motion paper P2579R0.
Also harmonize the local use of whitespace.

[expr.prim.id.unqual] Fix parameter name in example ("y", not "z")

---

source/containers.tex

After the addition of the formatting-related specialization, the
original subclause contained several class template synopses without
any intervening separation. The header synopsis is rearranged to
follow the document order.
Fixes #5719.

[vector.syn, vector.bool] Add subclause structure.

---

source/ranges.tex

```cpp
namespace std::ranges {
template<class F, class Tuple>
constexpr auto tuple_transform(F&& f, Tuple&& tuple) { // \expos
return apply([&]<class... Ts>(Ts&&... elements) {
return tuple<invoke_result_t<F&, Ts>...>(invoke(f, std::forward<Ts>(elements))...);
}, std::forward<Tuple>(tuple));
}
}
```
`error: 'tuple' does not name a template but is followed by template arguments; did you mean '::std::tuple'?`

[range.adaptor.tuple] Fix annoying tuple naming conflict

---

source/memory.tex

"_Mandates_:" is misused, as "`n > 0` is `true`" can't be checked at compilation-time. And the condition is in "_Preconditions_:" according to [P2590R2](https://wg21.link/p2590r2).

[obj.lifetime] Fix preconditions for `start_lifetime_as_array`

---

source/containers.tex

All other containers and container adapters use the member size_type,
and the flat maps already did so in the item specification, but not in
the synopsis.
The current wording follows the approved proposals, but this change
seems like an improvement.
Suggested by CD review.

[flat.*.{syn,erasure}] Change return type of erase_if to member size_type

---

source/compatibility.tex

For C++ differences, examples are always preceded by the phrase "For
example:", do not use the usual [Example n: ... -- end example] style,
and always appear in the "Effects on original feature" paragraph.
For differences with C, a different set of styles is used (examples
being part of paragraphs such as "Change" and "Rationale"), and that
subclause remains unchanged by this commit.
Suggested by CD review.
I will update the wiki accordingly.

[diff] Uniform style for examples

---

source/memory.tex

The comment was supposed to be added by P1642R11, but was accidentally
omitted.
Fixes #5731.

[memory.syn] Add missing "// freestanding" comment to "destroy"

---

source/utilities.tex

Moves the wording describing the zero-padding before the description of
the width; matching the order of the fields in the std-format-spec.
The swapped order was introduced in the initial <format> paper
P0645R10 Text formatting
Since both fields had one paragraph description it wasn't too noticeable.
P1868R2 🦄 width: clarifying units of width and precision in std::format
expanded the wording of the width. Now it's not so easy to find the
description of the zero-padding field.

Fix order of std-format-spec field descriptions.

---

source/ranges.tex

The first fix in 8275c19b3fa9e7cb09f84049ebd6207aceb7ca80 was incorrect. Only Const and the extraneous angle bracket needed to be dropped (which was an errorin the paper), but ignoring Vs... is intentional.
Fixes #5768.

[range.cartesian.view] Further fixing of cartesian-product-is-common

---

source/ranges.tex
source/threads.tex

Fix placement of namespace-scope declarations

---

source/ranges.tex

Elsewhere it is simple enough since there is no fold expression and `Base` is defined, and I think this improves readability.

[range.zip, ranges.cartesian.iterator] Simplify `maybe-const<Const, Views>` into `const Views`

---

source/utilities.tex

1. Change `typename` to `class` to be consistent with the standard library.
2. Remove the space between `template` and `<`.

[tuple.syn, tuple.like] Standardized template format

---

source/ranges.tex

[range.zip.overview] Use tuple in example, not pair

---

source/ranges.tex

1. Remove the space between `(void)` and `F`, which is consistent with the zip family overview.
2. Formatted unformatted `((void)F, decay-copy(E))` in [[range.drop.overview-2.4.2]](https://eel.is/c++draft/ranges#range.drop.overview-2.4.2).
3. Extended question: Is it correct to use `auto(E)` in these contexts?

[range.drop.overview, range.take.overview] Fixed unformatted `(void)F, decay-copy(E)`

---

source/utilities.tex

since we are not under the `ranges `namespace.

[format.range.fmtstr] Add ranges namespace qualifier for range concepts

---

tools/check-source.sh

Previously, the pattern required 'class' after '<' to fire.
This prevents the need for future piecemeal fixes such as 356fb7ff88b63d956b1109c72c5e3bf424f6ba29 or eca39f43798d7a58fdd482232c60b6db428b656f.
Tested with the state before 356fb7ff88b63d956b1109c72c5e3bf424f6ba29, which was successfully flagged.

[check] Flag any space between 'template' and '<'

---

source/ranges.tex

1. Use `views::istream` instead of `ranges::istream_view` (consistent with #4659).
2. Remove unnecessary `std::` qualification.

[ranges] Improve examples

---

source/containers.tex
source/ranges.tex
tools/check-output.sh

complain about undefined concepts
and about concepts in codeblocks not decorated with \libconcept
(we had quite a few late-ish fixes for the latter in the CD cycle)

Improve automatic LaTeX checking of concept names

---

source/basic.tex
source/compatibility.tex
source/exceptions.tex

These rewordings were proposed by @opensdh during earlier review. They are more extensive than local replacements of "might" or "could", and we should review them on their own merit, i.e. whether they are an improvement (or at least not making things worse), and we should also consider other (possible even wider-ranging) rewordings.

Rewordings to avoid "might" and "could"

---

source/expressions.tex

`\^` produces the circumflex accent `ˆ` instead of the ASCII character `^`.
The `\caret` command was added after #205 points out that `\^` produces a bad caret. PR #1902 fixed two uses of `\^` that were added after #205 got fixed. But another two uses of `\^` snuck in after that.
Given that `\^` keeps reoccuring, there's currently no use of the diacritic `ˆ` in this document, and there's precedent of redefining `\~` to mean something other than the diacritic, would it make sense to redefine `\^` to mean the ASCII letter, or else add a check to prohibit `\^`?

[expr] Replace `\^` with `\caret`

---

source/basic.tex

[basic.align] Fix cross-reference to meanwhile deprecated aligned_storage

---

source/modules.tex

I found this one when trying to implement [module.reach]. The problem here is that when the compiler see the module implementation unit declaration, the compiler would try to find the primary module interface. However, the primary module interface doesn't exist in the example.
Even we don't care the implementation details, it looks problematic from the perspective of language. According to [module.unit]p2 (https://eel.is/c++draft/module.unit#2):
> A module interface unit is a module unit whose module-declaration starts with export-keyword; any other module unit is a module implementation unit. A named module shall contain exactly one module interface unit with no module-partition, known as the primary module interface unit of the module; no diagnostic is required.
But the example doesn't …

[module.reach] Remove redundant module implementation unit declaration

---

source/containers.tex
source/numerics.tex

Rephrase "possibly const value" in terms of types

---

source/basic.tex

"Complete object" is a defined term (https://eel.is/c++draft/basic#def:complete_object). Putting const in the middle of that makes it unclear if we are referring to a const-qualified "complete object" or a complete const object with some other meaning of "complete" such as "with a complete type". Using the order "const complete object" avoids that ambiguity. It also matches the word order used in https://eel.is/c++draft/basic.life#10 to make it UB to create a new object on top of a "const complete object", unless it has dynamic storage duration.

[basic.life]/8.3 don't put const in the middle of "complete object" words of power

---

source/ranges.tex

These were moved to the synopsis after the P1642 changes to mark nearly everything in the synopsis freestanding, so they were not marked.
Fixes #5837

[ranges.syn] Make get overloads freestanding

---

source/utilities.tex

[format.string.std] Clarify location of 0x prefix for pointers

---

source/expressions.tex

[expr.prim.lambda.capture] Cross-reference [basic.def.odr] for 'odr-usable'

---

source/threads.tex

It refers to the member function that overrides `error_category::equivalent`.

[futures.errors] Add `\tcode` for `equivalent`

---

source/lib-intro.tex

[headers] Order `<type_traits>` before `<typeindex>` in the header table

---

source/numerics.tex

In [P1467R9](https://wg21.link/p1467r9) and the current synopsis of `<cmath>` ([cmath.syn]), the last parameter of 3-argument overloads of `std::hypot` is specified with _`floating-point-type`_, but it is specified with `double` in [c.math.hypot3].
This looks like an editorial mistake, and thus I think we should consistently use _`floating-point-type`_.

[c.math.hypot3] Fix the mis-specified `double` parameter of 3-argument `hypot`

---

source/lib-intro.tex
source/preprocessor.tex
source/support.tex
source/xrefdelta.tex

The new subclause contains both "integer types" (<cstdint>) and "extended floating-point types" (<stdfloat>).
Previously, the newly added <stdfloat> synopsis was somewhat disconnected and out of context.
Fixes #5714.

[support, etc.] New subclause "Arithmetic types".

---

source/containers.tex

There is a namespace-scope variable `dynamic_extent` defined in `<span>`, but this wording is clearly referring to the non-static data member _`dynamic-extents`_.

[mdspan.extents.cons] Correct spelling of "dynamic-extents"

---

source/containers.tex

This looks like neglect of the [P1206](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1206r7.pdf).  Is this an editorial?

[unord.general, container.adaptors.general] Complete the alias template that appears in the reduction guides

---

source/utilities.tex

Group shifts together and use same order for synopsis and detailed descriptions.
Also remove the unnecessary "for b[i];" comments explaining what operator[] does, and add a comment introducing the group containing count(), size() etc.

[template.bitset] reorder synopsis and member descriptions

---

source/lib-intro.tex

Lists providing the key for names used throughout a subclause are difficult to follow when buried as a single sentence in a paragraph.  This PR updates the key to tables 29-36 in [utility.arg.requirements] to a bullet list following the examples set elsewhere.
Each key is now consistently introduced with the word "denotes", following the precedent set by similar bullet lists.
It is not at all coincidental that this also resolves pagination issues at the end of the page, so that the floating tables to not float into the middle of a sentance in the following section.

[utility.arg.requirements] turn list of identifiers into a bullet list

---

source/iostreams.tex

We don't typically put empty lines before closing braces.

[ios.overview] Remove unconventional empty line

---

source/utilities.tex

Example 5 should only have one invalid code unit. The second code unit is a valid code point. This issue was already in the paper
P2286R8 Formatting Ranges

[format.string.escaped] Fix invalid example

---

source/intro.tex
source/lib-intro.tex
source/xrefprev

This address the US-2 NB comment as per the direction voted on by SG-16.
No use of "multibyte character" remains before [multibyte.strings] (we still cross reference "multibyte string" in [basic.start.main] but it's pre-existing (and otherwise correct).
@steve-downey @jensmaurer @tahonermann

[intro.defs] Move the definition of "multibyte character" to library

---

source/ranges.tex

Only in C is the term `tag` defined with respect to `struct`s. Replace the term "tag type" with simply "type" in [range.dangling].

[range.dangling] The `tag` of a `struct` is not a C++ term

---

source/containers.tex

For consistency with the other `set`, `unordered_set` containers. `key_type` is a synonym for `value_type`, and there's no reason the flat containers need to depart from existing practice here.

[flat.set] [flat.multiset] Use value_type, not key_type

---

source/time.tex

It doesn't mean anything to use `STATICALLY-WIDEN` withOUT a template argument list.

[time.clock.system.nonmembers], [time.zone.zonedtime.nonmembers] add <charT>

---

source/meta.tex

Changing the name of the bool parameter of enable_if_t and conditional_t from b to B. This increases the consistency of presentation and agrees with the names used in the specification of enable_if and conditional ([meta.trans.other]), as well as the definition of bool_constant.

[meta.type.synop] Make template parameter names start with capital

---

source/ranges.tex

The example in [range.drop.while.overview] is ill-formed. It attempts to use a `const char*` as a `range`, which isn't. The fix simply makes it a `const char (&)[N]`, which is a `range`

Ill-formed example in [range.drop.while.overview]

---

source/time.tex

This seems editorial, because if `charT` is not `char` then `os_str()` cannot be written to the output without widening it, so the current spec isn't implementable. The intention is to use a stringstream to build up the result then write it out, but there's no reason to do that as a narrow string then widen it, so clearly it should be a stringstream of the correct character type. This was confirmed by @vitaut on the LWG reflector, and matches what all implementations do.
The hyphenation hint is needed to fix an overfull hbox.

[time.format] use basic_ostringstream<charT> instead of ostringstream

---

source/lex.tex

The notion of a basic _source_ character set has been eliminated by the work on a better specification for translating source. Remove the last definition to it in the index, that points to a definition that no longer exists.

[index] Remove undefined term

---

source/containers.tex

Currently most of exposition-only names in [containers] are formatted with \exposid, and its absence is already addressed by several PRs. I think `span`'s _`data_`_ and _`size_`_ should also be so formatted for consistency.

[views.span] Add \exposid for `span`'s `data_` and `size_`

---

source/meta.tex

Resolves #5879.
Before and after:
Is it OK to only use math font on the relevant subexpressions?

[ratio.ratio] Use defined function for sign

---

source/declarations.tex

[dcl.link]/1:
> All functions and variables **whose names have external linkage** and all function types have a language linkage.

[dcl.link] Fix the wording of the application of the specified language linkage

---

source/templates.tex

As directed by CWG 2022-11-09.

[temp.deduct.conv] Remove misleading paragraph break

---

source/containers.tex

In library function declarations, the `constexpr` specifier always precedes the `explicit` specifier per our standing style guide.

[mdspan.extents.cons] "constexpr" should precede "explicit"

---

source/containers.tex
tools/check-source.sh

Per our style guide, `constexpr` should precede `explicit` in declarations. Nevertheless, the persnickety `explicit constexpr` seems to frequently sneak into the library wording.

[check] Add check for "explicit constexpr" in the library

---

source/back.tex
source/basic.tex
source/classes.tex
source/compatibility.tex
source/containers.tex
source/ranges.tex
source/utilities.tex

Fixes cplusplus/nbballot#418
Fixes cplusplus/nbballot#424
Fixes cplusplus/nbballot#434
Fixes cplusplus/nbballot#436
Fixes cplusplus/nbballot#478
Fixes cplusplus/nbballot#517
Fixes cplusplus/nbballot#532
Fixes cplusplus/nbballot#533
Also fixes #5894.

Editorial NB comments

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/exceptions.tex
source/expressions.tex
source/lex.tex
source/limits.tex
source/statements.tex
source/templates.tex

Fixes #5956.
Also fixes #5634.

[Motions 2022 11 cwg 1] P2709R0 ready issues except 2635 and 2602

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/expressions.tex
source/overloading.tex
source/support.tex
source/templates.tex
source/uax31.tex

Fixes #5958.
Fixes cplusplus/nbballot#542
Fixes cplusplus/nbballot#482
Fixes cplusplus/nbballot#484
Fixes cplusplus/nbballot#487
Fixes cplusplus/nbballot#492
Fixes cplusplus/nbballot#489
Fixes cplusplus/nbballot#465
Fixes cplusplus/nbballot#464
Fixes cplusplus/nbballot#500
Fixes cplusplus/nbballot#501
Fixes cplusplus/nbballot#477
Fixes cplusplus/nbballot#461
Fixes cplusplus/nbballot#421

2022-11 CWG Motion 3

---

source/declarations.tex
source/lex.tex
source/preprocessor.tex

Fixes #5959.
Fixes #5715.
Fixes cplusplus/nbballot#441
Fixes cplusplus/nbballot#475
Fixes cplusplus/nbballot#473
Fixes cplusplus/nbballot#503
Fixes cplusplus/nbballot#451

[Motions 2022 11 cwg 4] Issues 2615, 2639, 2640, 2652, and 2653 from P2710R0 

---

source/declarations.tex

Fixes #5961.
Fixes cplusplus/nbballot#430

[Motions 2022 11 cwg 6] Issue 2538 (Can standard attributes be syntactically ignored?) from P2710R0

---

source/expressions.tex
source/preprocessor.tex

P2647R1 Permitting static constexpr variables in constexpr functions
Fixes #5963.
Fixes cplusplus/nbballot#443
Fixes cplusplus/papers#1318

2022-11 CWG Motion 8

---

source/classes.tex
source/declarations.tex

P2706R0 Redundant specification for defaulted functions
Fixes #5965.
Fixes cplusplus/nbballot#498

2022-11 CWG Motion 10

---

source/basic.tex
source/declarations.tex
source/modules.tex
source/templates.tex

P2615R1 Meaningful exports
Fixes #5966.
Fixes cplusplus/nbballot#431
Fixes cplusplus/nbballot#428
Fixes cplusplus/papers#1236

2022-11 CWG Motion 11

---

source/concepts.tex
source/iterators.tex
source/lib-intro.tex
source/ranges.tex
source/support.tex

P2602R2 Poison Pills are Too Toxic
Fixes #5970.
Also fixes https://github.com/cplusplus/papers/issues/1266.
Also fixes https://github.com/cplusplus/nbballot/issues/526.
Also: Following discussion with @brevzin and @tkoeppe, added an extra note explaining why `swap` poison pill is still needed.

Motions 2022 11 lwg 9

---

source/iostreams.tex

P2539R4 Should the output of std::print to a terminal be synchronized with the underlying stream?
Fixes #5972.
Fixes https://github.com/cplusplus/papers/issues/1219.
Fixes https://github.com/cplusplus/nbballot/issues/537.
Fixes https://github.com/cplusplus/nbballot/issues/536.
Fixes https://github.com/cplusplus/nbballot/issues/535.

2022-11 LWG Motion 11

---

source/containers.tex
source/iterators.tex
source/lib-intro.tex
source/support.tex
source/time.tex
source/utilities.tex

P2696R0 Introduce Cpp17Swappable as additional convenience requirements
Fixes #5975.
Also fixes #5627.
Also fixes https://github.com/cplusplus/draft/issues/5628.

2022-11 LWG Motion 14

---

source/expressions.tex

We are currently using the term "unary complement" to refer to the "~" operator without ever giving it that name.
This change removes unnecessary uses of the terms "unary" and "complement", but adds notes that make referenes to "ones'/two's complement".

[expr.unary.op] Cleanup of {ones',two's} complement, and of "operator"

---

source/back.tex
source/compatibility.tex
source/intro.tex
source/lex.tex
source/macros.tex
source/uax31.tex
source/utilities.tex

The "hash"/"number" sign is reduced in size and placed on the baseline. This seems to look less distracting and disruptive.
We also use the usual small-caps presentation for universal character names.

[uaxid, macros, etc.] Smaller capital-style glyphs

---

source/future.tex

There are several typedef names defined precisely in the deprecated convenience conversion interface classes that are redundantly respecified in text.  Nowhere else in the library does this; any specified typedef names are _see below_ definitions, not repeats of the class definition.  Needless redundancy is always a risk of divergance, however small, so remove the respecification in text form.

[depr.conversions.string] remove redundent respecification

---

source/concepts.tex

[concepts.object]Replacing the term "built-in type" with "fundamental type"
Fixes cplusplus/CWG#192

[concepts.object] Changed built-in types to fundamental types

---

source/time.tex

This note about leap seconds is still true, but should be updated to be more precise. Saying something about 2019 in C++23 seems odd, and will lead readers to wonder if a negative leap seconds was inserted in 2020.
There has been no leap second inserted since 2016, and none will be inserted before 2023-06-28 at the earliest.
https://en.wikipedia.org/wiki/Leap_second

[time.zone.leap.members] update note about leap seconds

---

source/time.tex

This makes the parameters in the synopsis match the detailed descriptions.

[time.zone.zonedtime.overview] Rename parameters to match [time.zone.zonedtime.ctor]

---

source/ranges.tex

The synopsis and definition of the respective `yield_value` overload are inconsistent. Given that the first tparam of generator is `Ref` it makes sense to switch from `T2` to `R2` consistently whilst fixing the issue,

[coro.generator.promise] Fix tparams for generator::promise_type::yield_value

---

source/expressions.tex

Do paragraphs 7-10 need similar fix or we fine with «the type of the result is `X`» when it means the type of the resulting prvalue?

[expr.unary.op] Fix usage of "result"

---

source/containers.tex

to make it consistent with the declaration.

[mdspan.mdspan.overview] Add default template parameters for mdspan

---

source/ranges.tex

Currently, the first template parameter of `repeat_view` is called `W`, which is consistent with `iota_view`.
However, such consistency makes wrong suggestions, because two `W`'s have totally different constraints. Presumably `W` comes from `weakly_incrementable`, which is not related to the first template parameter of `repeat_view`.
This PR changes `W` to `T`, because `T` is a general name for type template parameters, and the constraints of `move_constructible` are relatively loose. And it also changes `WArgs` to `TArgs` for mirroring `BoundArgs`. I'm not sure whether the plain `Args` would be better.
Fixes #5902.

[range.repeat] Change template parameter name `W` to `T`

---

source/concepts.tex

A small rewrite avoids the phrase "possibly \tcode{const}", which we would like to remove entirely in favour of just "possibly const".
Partially addresses #117.

[concept.copyconstructible] Avoid "possibly \tcode{const}"

---

source/algorithms.tex
source/iostreams.tex
source/lib-intro.tex
source/numerics.tex
source/utilities.tex

The "const" here is not syntax, but just normal text. This is similar to "inline" and "public", which have previously been cleaned up similarly.
Fixes #117.

Replace "possibly \tcode{const}" with "possibly const"

---

source/iterators.tex

Add following definitions from the iterators library to the library index:
- indirect_result_t
- iter_common_reference_t
- iter_const_reference_t 
- iter_reference_t
- iter_rvalue_reference_t
- make_const_iterator
- make_const_sentinel

[iterators] Add missing definitions from the iterators library to the library index

---

source/ranges.tex

Add `subrange_kind` and its enumerators `unsized` and `sized` to the library index.

[ranges] Add subrange_kind to the library index

---

source/lex.tex

[lex.ccon] Add xref to lex.charset, where encodings are defined

---

source/utilities.tex

[format.string.std] Fixing grammar error (#5912)

---

source/overloading.tex

P0847R7 (Deducing this) was approved at the October, 2021 meeting and applied with commit ee5117e100bbe9b7adb3510b2d7bb6d4d150f810, missing this change.

[over.over] Missed edit for P0847R7

---

source/iterators.tex

I don't know what explicit refers to here, it seems to be more appropriate to remove. People who disagree with me are also welcome.

[reverse.iter.conv] Remove unclear explicit comments

---

source/support.tex

Paper P2417R2 was approved in July 2022, but commit 75518ffdc476cbc239918466588d963fc97a8013 did not set the feature-test to the approriate value.
Fixes #6065

[version.syn] Fix value of __cpp_lib_constexpr_bitset

---

source/utilities.tex

I don't see where this `T` is defined, so let me assume this might be a typo (or I'm dazzled).

[format.range.fmtmap] Fix undefined type name

---

source/utilities.tex

N is not a C++ entity, it refers to the N suffix of tN, and the equality is mathematical not a C++ operator.
If this was an actual C++ expression using a variable `N` we would need to say "`N == 1` is `true`" and that would be much worse :sweat_smile:

[func.require] Use math font for non-code conditions

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/expressions.tex
source/intro.tex
source/modules.tex
source/overloading.tex
source/preprocessor.tex
source/templates.tex

Fixes #6083.
Partially addresses cplusplus/papers#1480
Fixes cplusplus/nbballot#479
Fixes #6112

[CWG 1] P2796R0 except issues 2518, 2521, 2659, 2674, 2678, and 2691 

---

source/declarations.tex
source/intro.tex
source/lex.tex
source/templates.tex

Fixes #6085.
Fixes cplusplus/papers#1366

[CWG 3] P2796R0 CWG2518 Conformance requirements and #error/#warning

---

source/future.tex
source/lex.tex
source/lib-intro.tex
source/overloading.tex

[lex.name] Attempt to fix wording; identifiers (plural) can't appear as a single token, and there's no "pp-token"
Fixes #6086.
Fixes cplusplus/papers#1367

[CWG 4] P2796R0 CWG2521 User-defined literals and reserved identifiers

---

source/basic.tex

Fixes #6087.
Fixes cplusplus/papers#1416

[CWG 5] P2796R0 CWG2678 std::source_location::current is unimplementable

---

source/back.tex
source/future.tex
source/intro.tex
source/iostreams.tex
source/lex.tex
source/preprocessor.tex
source/utilities.tex

Fixes #6089
Fixes cplusplus/papers#1429
Fixes cplusplus/nbballot#412
Fixes cplusplus/nbballot#423

[CWG 8] P2736R2 Referencing The Unicode Standard

---

source/algorithms.tex
source/compatibility.tex
source/containers.tex
source/diagnostics.tex
source/future.tex
source/iostreams.tex
source/iterators.tex
source/lib-intro.tex
source/memory.tex
source/ranges.tex
source/strings.tex
source/support.tex
source/utilities.tex

Fixes #6093.
Fixes cplusplus/papers#1479
Fixes cplusplus/nbballot#463
Fixes cplusplus/nbballot#454
Fixes cplusplus/nbballot#453
Fixes cplusplus/nbballot#452
Fixes cplusplus/nbballot#447
Fixes cplusplus/nbballot#444
LWG3631: Were both declarations of handle in [format.arg] intended to be changed?

[LWG 3] P2790R0 Immediate issues except 3441

---

source/iterators.tex
source/lib-intro.tex
source/utilities.tex

[LWG 4] LWG3441 Misleading note about calls to customization points

---

source/ranges.tex

Fixes #6097.
Fixes cplusplus/papers#1360

[LWG 7] P2711R1 Making multi-param constructors of views explicit

---

source/utilities.tex

Fixes NB US 38-098, FR 5-134 (C++23 CD).
Fixes #6099.
Fixes cplusplus/papers#1418
Fixes cplusplus/nbballot#515
Fixes cplusplus/nbballot#408
So I couldn't get the s8 example to build - maybe I don't have the right setup? Can someone else take this and see if they can get the s8 example to build for them?

[LWG 9] P2713R1 Escaping improvements in std::format

---

source/utilities.tex

Fixes #6101.
Note: Could not complete edits due to invalid ucn chars.  Feel free to use my edits as a base and complete this if you can.

[LWG 11] P2572R1 std::format fill character allowances

---

source/diagnostics.tex
source/macros.tex
source/support.tex
source/threads.tex
source/utilities.tex

[thread.thread.id] Follow expressions with "is true".
Fixes #6102.
Fixes cplusplus/papers#1358
Fixes cplusplus/nbballot#410
Fixes cplusplus/nbballot#414
Please see FIXMEs in code - how to resolve?

[LWG 12] P2693R1 Formatting thread::id and stacktrace

---

source/memory.tex

Fixes #6103.
Fixes cplusplus/nbballot#459.
Fixes cplusplus/nbballot#508.
Fixes cplusplus/papers#1345.

[Motions 2023 02 lwg 13] P2679R2 Fixing std::start_lifetime_as and std::start_lifetime_as_array

---

source/meta.tex
source/support.tex

Fixes NB GB 089 (C++23 CD).
Fixes #6104.
Fixes cplusplus/papers#1340
Fixes cplusplus/nbballot#457

[LWG 14] P2674R1 A trait for implicit lifetime types

---

source/compatibility.tex
source/lib-intro.tex
source/memory.tex

- Adjust the changes reflecting LWG3775
Fixes #6106
Fixes cplusplus/papers#1320
Fixes cplusplus/nbballot#505

[LWG 16] P2652R2 Disallow User Specialization of allocator_traits

---

source/future.tex
source/support.tex
source/xrefdelta.tex

Fixes #6108 
Fixes cplusplus/papers#1278
Fixes cplusplus/nbballot#506

P2614R2 Deprecate numeric_limits::has_denorm

---

source/strings.tex

While we aren't entirely clear when to use maths variables and when to use code placeholders, in the present case math mode is not good for multi-character symbols (since $ab$ really means $a$ times $b$ etc.), and we have precendent for using placeholder-code for "expression aliases".

[string.capacity] Use \tcode+\placeholder for placeholder

---

source/declarations.tex

This change was missed from the application of CWG2518.
Also fixes the indexing of "static_assert" (which is a keyword, not a grammar production).

[dcl.pre] Add missing markup that makes "fails" a definition.

---

source/utilities.tex

There's no `T1` in sight; the relevant template parameter of `expected` is `T`.

[expected.object.eq] Fix typo

---

source/preprocessor.tex

This fix is editorial as it corrects a mis-application of the original paper, https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2334r1.pdf.
Note that the corresponding use of this grammar in [cpp.cond]p13 assumes the correct grammar, making the intent equally clear.

[cpp.pre] Fix grammar for #elifdef

---

source/expressions.tex

[The example for compound requirement](http://eel.is/c++draft/expr.prim#req.compound-example-1) is currently attached to the inner bullet point, but should be attached to the outer one.

[expr.prim.req.compound] Move compound requirement example from inner to outer bullet

---

source/algorithms.tex

Fixes #6143. As discussed in the issue, the note is probably wrong in some cases and we should strike it.

[specialized.algorithms.general] Strike the possibly wrong note

---

source/basic.tex
source/containers.tex
source/declarations.tex
source/expressions.tex
source/styles.tex
source/support.tex
source/tables.tex
source/templates.tex
source/time.tex

I believe LaTeX assumes that a full stop after a lower case letter ends a sentence, so it inserts slightly more space than between other words. I think this is the only occurrence of "etc." that does not end a sentence.
Before:
After:

[temp.expl.spec] Use normal spacing after "etc." within a sentence

---

source/future.tex

This subclause doesn't mention `is_literal_type`. I believe the index entry is a historical artifact from when the trait was deprecated; it should have been removed when the trait was removed.

[depr.meta.types] Remove is_literal_type index entry

---

source/time.tex

Only `operator<<` uses `ymwdi` instead of `ymwd` in the synopsis. [time.cal.ymwd.nonmembers]/11 also uses `ymwd` for `operator<<`.

[time.syn] Fixes ymwd abbreviation consistency.

---

source/regex.tex

The type of most container iterators is records in the index of implementation defined types, but somehow the `match_results` iterator in the <regex> clause was missed.
After applying this patch, I grepped for any other occurrences of "\\impdef}" and the only remaining (and intentional) match is the definition of this macro in macros.tex, so there should be no more latent cases to find.

[re.results.general] Add type of `match_results::const_iterator` to index of imp def behaviour

---

source/future.tex

Add a cross reference to the core language paragraph that contains the deprecation notice, [temp.names] (p6).

[depr.template.template] Add cross-ref to core language

---

source/ranges.tex

This makes it consistent with other [range.xxx.overview].

[range.take.overview, range.drop.overview] Remove redundant ranges:: qualifier

---

source/containers.tex

The current cross-reference is to [containers.requirements], which is the whole containers requirements clause, including not just general containers, but also allocator-aware, reversible, sequence, associative, and unodered associative containers.  It seems very unlikely that the cross-reference expects to be the intersection of all of those.
Rather, the reference seems to intend just the [containers.reqmts] subclause, which adds just two useful constraints: random access iterators should support the 3-way comparison operator, and the interoperabiity of container iterators and const_iterators.
As a drive-by, fixed the \indexlibrarymember macro by ordering the type, span, before the member, iterator, as is the convention. This has no impact on the index, as entries in both directions are …

[span.iterators] Fix cross-reference to container iterators

---

source/containers.tex
source/strings.tex

This edit deserves describing in detail, to establish that it is purely editorial.
As part of the mission to clean up tables in the standard, the general container requirements were split into 5 more focused leaf nodes.  Due to its location in the original text, the definition for a contiguous container fell into the subclause for reversible containers, to which it is entirely unrelated.  There is no requirement that a contiguous container be reversible, only that it has the correct category for its iterators.
Meanwhile, all 3 of the existing cross-references point to the wrong leaf node, that simply provides a key to the identifiers used throughout the specification of this clause.
The fix has two parts.  First move the definition of contiguous container, and a container with special …

[container.reqmts] Fix cross-references to contiguous container

---

source/ranges.tex

Running `git grep -C 1 'present only' *` in `sources` shows:
```
declarations.tex-\grammarterm{init-declarator} or \grammarterm{member-declarator}
declarations.tex:shall be present only if the declarator declares a
declarations.tex-templated function\iref{dcl.fct}.
--
iterators.tex-    using iterator_type = I;
iterators.tex:    using value_type = iter_value_t<I>;                         // present only
iterators.tex-                        // if \tcode{I} models \libconcept{indirectly_readable}
iterators.tex-    using difference_type = iter_difference_t<I>;
iterators.tex:    using iterator_concept = typename I::iterator_concept;      // present only
iterators.tex-                        // if the \grammarterm{qualified-id} \tcode{I::iterator_concept} is valid and denotes a type …
```

[range.subrange.general,range.adaptors] Use present only if condition is `true`

---

.github/workflows/check.yml
source/styles.tex

@jensmaurer We need to allow listings 1.9 for MacOS. Is there any point in having the version check at all?

Mac modernization: allow listings 1.9, and don't allow errors in a pipe

---

source/containers.tex

The exposition-only concept _container-compatible-range_ is defined in the subclause for allocator-aware containers, that does not actually use it.  This requirement is used throughout the subclause for a variety of containers, so relocate the definition into the leading subclause that provides a key to definitions used throughout the containers subclauses.

[container.requirements.general] Move exposition-only concept

---

source/support.tex

This is requested for the Tentatively Ready LWG issue 3887.
Fixes #6202

[version.syn] bump value of __cpp_lib_allocate_at_least

---

source/ranges.tex

Alias `all_t` needs `views::` qualifier.
Fixes #6198

[range.cartesian.view] Add missing `views::` qualifier in deduction guide

---

source/overloading.tex

The core conention is to retain deprecated wording in the core clauses, but always make a forward link to Annex D where a feature, or parts of a feature, are deprecated.

[over.literal] Cross-reference deprecated grammar

---

source/containers.tex

As part of rewriting the container requirements tables as text, several paragraphs of general container requirements were buried in the new subsection for more specific requirements such as reversible containers or allocator-aware containers.  This seems to have happened when general container requirements followed one of the container requirements tables that are noe expressed as text.
This PR carefully restores text to the general container requirements clause, in the original order they appeared in C++20, and audits that there are no further paragraphs to move that do not have outstanding pull requests.

[container.reqmts] Relocate more container requirements

---

source/declarations.tex

"templated function" is defined in [temp.pre], but avoid having two cross-references to the same place in the same paragraph by dropping the cross-reference for the definition of the grammar non-terminal "requires-clause".
Partially addresses llvm/llvm-project#61748

[dcl.decl.general] Fix cross-references

---

source/future.tex

There is no such thing as an "atomic specialization", so the only valid reading of this text is that "atomic" refers to the class template `atomic`.
This PR makes the intent clear with code font and a cross reference, and I believe is editorial.  However, the LWG chair might want to confirm whether the change of font counts as a normative change that deserves LWG review.

[depr.atomics.volatile] Use tcode to call out template name

---

source/algorithms.tex

I could have sworn there was an aspell dictionary or something checked in that would prevent such misspellings; if such a dictionary exists, I guess "namepace" should be added to it. :)

[alg.unique] namepace -> namespace

---

source/lib-intro.tex

The new name "Common definitions" for the entry of section 17.2 in Table headers.cpp.fs
is already used as name for the entry of section 17.2 in Table support.summary
and is also used as the name in section 17.2 (support.types)
There is still a difference for cstdlib (17.2.2: cstdlib.syn):
Table "support.summary" lists cstdlib for entry 17.2 and entry 17.5, but 
Table "headers.cpp.fs" lists cstdlib only for entry 17.5.
According to the Text in 17.2.2, cstdlib has 2 freestanding entries related to section 17.2
and 5 freestanding entries related to section 17.5.
cstdlib has references to a lot more sections, which are not listed in Table "support.summary",
but adding every reference from cstdlib to Table "support.summary" makes the Table very ugly.
--
Regards ... Detlef Riekenberg

Fix Subclause name for cstddef in headers.cpp.fs

---

source/iterators.tex

It should be clear what an implentation-defined term defines when reading just the index of implementation defined behavior. The current impldef text of integer-class types is so short as to be cryptic.

[iterator.concept.winc] Improve implementation-defined text

---

source/back.tex
source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/expressions.tex
source/iostreams.tex
source/macros.tex
source/meta.tex
source/templates.tex

* "cross-reference": [dictionary](https://www.thefreedictionary.com/cross-reference), [repo](https://github.com/cplusplus/draft/search?l=TeX&q=%22cross+references%22), [ngrams](https://books.google.com/ngrams/graph?content=cross+reference%2C%5Bcross+-+reference%5D&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3&case_insensitive=true)
* "multidimensional": [dictionary](https://www.thefreedictionary.com/multidimensional), [repo](https://github.com/cplusplus/draft/search?l=TeX&q=%22multidimensional%22%2C%22multi-dimensional%22), [ngrams](https://books.google.com/ngrams/graph?content=multidimensional%2C%5Bmulti+-+dimensional%5D&year_start=1800&year_end=2019&case_insensitive=on&corpus=en-2019&smoothing=3)
* "well-formed": [dictionary](https://www.thefreedictionary.com/well-formed), …

Fix inconsistencies with hyphens

---

source/declarations.tex
source/expressions.tex
source/lex.tex

Microtype's character protrusion is not desired in the presentation of certain grammar productions, and strict alignment is better.
Fixes #6239.

[lex, expr, dcl.dcl] Disable character protrusion from BNF lines.

---

source/classes.tex
source/time.tex
source/utilities.tex

As of CWG2602 (https://github.com/tkoeppe/draft/commit/ce7d8b0360e1509de6f7fd073d0a091238b1326f), the term "constexpr-suitable" replaces the previous phrase "satisfy the requirements for a constexpr function".

Use new term "constexpr-suitable"

---

source/support.tex

In [N4944](https://wg21.link/n4944), there's one occurence of `F` in [cmp.alg]/4 that is not properly formatted.
Also reflected in https://eel.is/c++draft/cmp.alg#4.

[cmp.alg] Add missing formatting for `F`

---

source/containers.tex

This was incorrectly changed from a \mandates to an \expects when 93ff092d1cd2b335f372b9546365b3d495caf2d8 replaced the requirements tables.
https://github.com/cplusplus/draft/commit/93ff092d1cd2b335f372b9546365b3d495caf2d8#diff-3b5851f7056b7c68cb3ba2ab51cf0b75a780c6a11e5e181770067700454ace7bL734 (click on "Load diff") shows the previous state, with `\mandates`, and https://github.com/cplusplus/draft/commit/93ff092d1cd2b335f372b9546365b3d495caf2d8#diff-3b5851f7056b7c68cb3ba2ab51cf0b75a780c6a11e5e181770067700454ace7bR1005 shows the new state, with `\expects`. That change was supposed to be editorial, but this is a normative change.

[container.alloc.reqmts] Fix incorrect change of \mandates to \expects

---

source/containers.tex

Restore consistency with [[flat.map.modifiers]/13](https://eel.is/c++draft/flat.map.modifiers#13), which already uses `ranges::distance(rg)`.
However, @jwakely can I also get some LWG guidance here?  Right now, there is no `insert_range` in [flat.multiset.modifiers](https://eel.is/c++draft/flat.multiset.modifiers), and there is no [flat.multimap.modifiers](https://eel.is/c++draft/flat.multimap.modifiers) at all. My intuition is that this `insert_range` wording should appear in both places.
I'm planning P2767R0 "flat_foo omnibus" for Varna. Should I submit a pull-request _before_ Varna to add a section named [flat.multimap.modifiers], with contents similar to [flat.map.modifiers]? Should I just make P2767 introduce all of [flat.multimap.modifiers]? Or does LWG think it's "obvious" what …

[flat.set.modifiers] `(first, last)` should be `rg`

---

source/macros.tex
source/ranges.tex
source/std.tex

Due to `nofrenchspacing`, a space after `.`, `:`, `?` are rendered as two spaces in monospaced fonts if these punctuations are preceded by non-capital characters. For example, `\tcode{a ? b : c}` is rendered as `a ?  b :  c`, and
```
\tcode{template <class... A> void f(A...) noexcept}
```
is rendered as
```
template <class...  A> void f(A...)  noexcept;
```
Currently, there are tens of these double spacings in the Standard.
This PR prevents them by adding `\frenchspacing` to `CodeStylex`.

Prevent double spacing in tcode

---

source/basic.tex

`S` does not have a default constructor.

[intro.execution] Fix bad function call in example

---

source/classes.tex

[class.base.init] use defnadj to introduce delegating and target constructor

---

source/expressions.tex

The use of comma is generally recommended after a conditional phrase or introductory phrase, such as `if something, ...` or `for something, ...`.

[expr.mul] Add missing commas after conditional and introductory phrases

---

source/iostreams.tex

This typo has been present since C++98.

[filebuf.virtuals] fix "if width if less than zero" typo

---

source/time.tex

[time.duration.cons] Fix redeclaration error in example

---

source/lex.tex

Fixes #6278
Fixes cplusplus/papers#608

P1854R4 Making non-encodable string literals ill-formed

---

source/lex.tex

Fixes #6280
Fixes cplusplus/papers#1220

P2558R2 Add @, $, and ` to the basic character set

---

source/declarations.tex
source/statements.tex

Fixes #6282.
Notes:
* The wording for this paper is problematic, both for type-id and for declaration (e.g. trying to redefine grammar production rules). I did my best to improve it editorially with the changes you see, and inserted FIXMEs to point out the remaining badness.

[Motion cwg 7] P2915R0 (Proposed resolution for CWG1223)

---

source/declarations.tex
source/preprocessor.tex

Fixes #6283
Fixes cplusplus/papers#1212

P2552R3 On the ignorability of standard attributes

---

source/compatibility.tex
source/declarations.tex
source/macros.tex

Fixes #6284
Fixes cplusplus/papers#1442

P2752R3 Static storage for braced initializers

---

source/declarations.tex
source/preprocessor.tex

Fixes #6285
Fixes cplusplus/papers#1434

P2741R3 User-generated static_assert messages

---

source/basic.tex
source/declarations.tex
source/preprocessor.tex

Fixes #6286
Fixes cplusplus/papers#878

P2169R4 A nice placeholder with no name

---

source/containers.tex
source/lib-intro.tex
source/numerics.tex
source/ranges.tex
source/strings.tex
source/threads.tex
source/utilities.tex

Fixes #6287.
Note: LWG3887 skipped - already fixed.

[Motion lwg 1] P2910R0 C++ Standard Library Issues

---

source/support.tex
source/time.tex

Editorial: Added \ref from synopsis to [time.hash]
Fixes #6289
Fixes https://github.com/cplusplus/papers/issues/1250

P2592R3 Hashing support for std::chrono value classes

---

source/lib-intro.tex
source/support.tex
source/threads.tex

Fixes #6292
Fixes cplusplus/papers#1206

P2545R4 Read-Copy Update (RCU)

---

source/limits.tex
source/support.tex
source/threads.tex

Fixes #6293
Fixes cplusplus/papers#1194
~NOTE: This is based on LWG motion 6 and needs a rebase onto "main" during merging.~

P2530R3 Hazard Pointers for C++26

---

source/iterators.tex

Fixes #6294
Fixes cplusplus/papers#1201

P2538R1 ADL-proof std::projected

---

source/support.tex
source/utilities.tex

Fixes #6296 
Fixes cplusplus/papers#1165

P2510R3 Formatting pointers

---

source/diagnostics.tex
source/lib-intro.tex
source/numerics.tex
source/strings.tex
source/support.tex
source/utilities.tex

- sort table [tab:headers.cpp.fs] by section number
Fixes #6298
Fixes cplusplus/papers#1017

P2338R4 Freestanding Library: Character primitives and the C library

---

source/support.tex

Fixes #6300 
Fixes cplusplus/papers#749

P2013R5 Freestanding Language: Optional ::operator new

---

source/back.tex
source/lib-intro.tex
source/locales.tex
source/support.tex

[text.*] Minor changes were made for consistency with existing text.
Fixes #6303.
Fixes cplusplus/papers#634
Edit notes: 
* How to specify the references in the Bibliography?

[LWG motion 17] P1885R12 Naming Text Encodings to Demystify Them

---

source/support.tex
source/utilities.tex

[LWG motion 18] P0792R14 function_ref: a type-erased callable reference

---

source/future.tex
source/xrefdelta.tex

Applies all changes to replace 'requires' clauses in Annex D with more modern wording, per LWG Poll 19 at Varna 2023 meeting, paper P2874R2.
Fixes #6305
Fixes cplusplus/papers#1557

P2874R2 Mandating Annex D

---

source/support.tex
source/utilities.tex

[LWG motion 20] P2757R3 Type checking format args

---

source/meta.tex
source/support.tex

[LWG motion 22] P2641R4 Checking if a union alternative is active

---

source/iostreams.tex
source/support.tex

[LWG motion 23] P1759R6 Native handles and file streams

---

source/support.tex
source/utilities.tex

Fixes #6310.
Fixes cplusplus/papers#1387

[LWG motion 24] P2697R1 Interfacing bitset with string_view

---

source/support.tex
source/utilities.tex

Fixes #6314.
Fixes cplusplus/papers#1419

[LWG motion 28] P2714R1 Bind front and back to NTTP callables

---

source/ranges.tex

- When "_Effects_: Equivalent to" is followed by a " ", the subsequent expression ends with a ".";
- When "_Effects_: Equivalent to" is followed by a ":", the subsequent expression ends with a ";".

[ranges] Make the "Effects: Equivalent to" format consistent

---

source/utilities.tex

We don't need to repeat the declarations of the incomplete primary template, they are already present in the `<functional>` synopsis.

[func.wrap.func.general], [func.wrap.move.class] Remove redundant declaration

---

source/basic.tex

Factor out a name for the "unless" condition to avoid the double-negative.

[basic.scope.scope] Avoid hard-to-read except...unless construction.

---

source/declarations.tex

Example 4 contains two instances where there are two spaces between the parameter list and the function body.
This code style is inconsistent with what is normally found in the standard.

[dcl.enum] Fix double spaces in Example 4

---

source/declarations.tex

[dcl.ambig.res] fix double declaration of 'y' in example

---

source/containers.tex

There is a typo where it says: LayoutStrideMapping, instead of StridedLayoutMapping. No other use of LayoutStrideMapping exists in the document.
This is in the constructor of `layout_stride::mapping` which takes a constrained other mapping and has remarks for the explicit condition:
```c++
template<class StridedLayoutMapping>
explicit(see below)
constexpr mapping(const StridedLayoutMapping& other) noexcept;
```
*Remarks:* The expression inside `explicit` is equivalent to:
```c++
!(is_convertible_v<typename StridedLayoutMapping::extents_type, extents_type> && (
is-mapping-of<layout_left, LayoutStrideMapping> || 
is-mapping-of<layout_right, LayoutStrideMapping> ||
is-mapping-of<layout_stride, LayoutStrideMapping>))
```
This needs to be:
```c++
!(is_convertible_v<typename …
```

mdspan/layout_stride: fix missed rename in use of template argument name

---

source/overloading.tex

The example is currently formatted as if `c` and `d` were free functions, not member functions of the surrounding `struct`.
Furthermore, the PR adds one space in `c()&` -> `c() &`. It is highly unusual to not separate cv-qualifiers or ref-qualifiers from the parameter list, and is a style that goes against almost every reference page. The example later uses `() const`, suggesting that this is merely a typo from the author, and not their preferred style.

[over.call.func] Example 1 - Fix misleading indentation

---

README.rst

See <https://archlinux.org/news/tex-live-package-reorganization/>.
`make` was also missing.

[README] Update Arch Linux instructions

---

source/basic.tex

As per https://github.com/cplusplus/draft/pull/6174#discussion_r1192795712.

[basic.stc.dynamic.allocation] Remove redundant 'address of'

---

source/containers.tex

We don't want programmers doing CTAD on `ranges::zip_view(args...)`, so we shouldn't put it in the as-if-by code either. What we expect people to do (and what we intend vendors to do here) is `views::zip`.

[flat.map.cons] etc.: zip_view should be views::zip

---

source/iostreams.tex

This is the follow-up of #6254.
Not sure if this is 100% spec-compliant, corrections are welcome.

[input.output] Fix non-compliance Effects: Equivalent to format

---

source/classes.tex

[class.copy.assign] Remove note obsoleted by CWG2586

---

source/basic.tex

* Remove reference to [[allocator.traits.members]](https://eel.is/c++draft/allocator.traits.members)
* Add reference to [[mem.res.public]](https://eel.is/c++draft/mem.res.public#2)
* Reorder references to [[bit.cast]](https://eel.is/c++draft/bit.cast) and [[cstring.syn]](https://eel.is/c++draft/cstring.syn) to match subclause order

[intro.object] Fix cross-references for implicit object creation in the library

---

source/containers.tex
source/regex.tex
source/strings.tex
source/xrefdelta.tex

Related to #6184
I missed the [re.results.general] one in #6253 because I searched for `{container.requirements.general}`. The [string.cons] one is to the top-level of container requirements, but should be to the sequence requirements.
After fixing those, we can retitle/relabel some of the container requirements subclauses, as discussed in #6184

Fix remaining references to container requirements, and adjust subclause naming

---

source/basic.tex

Per https://github.com/cplusplus/CWG/issues/365#issuecomment-1637162904

[basic.fundamental] Clarify that table of minimum integral type widths applies only to standard integral types

---

source/declarations.tex

There is a typo in the word appertain in [dcl.attr.grammar]p5 (in note 3).

typo fix appeartain -> appertain

---

source/basic.tex
source/future.tex

There is no back-link from the Annex D wording to the  feature that is deprecated.  The deprecation is mentioned in two places, so this PR links to both of them, and adds the corresponding missing link to the list item in [basic.def]

[depr.static.constexpr] Cross-reference core clauses 

---

source/classes.tex

[class.mem.general] Clarify ambiguous 'and'

---

source/memory.tex
source/ranges.tex

See LWG3753. Also makes definition of `allocator_arg_t` shown in one line, like `from_range_t`.
Fixes #5723.

[memory.syn][ranges.syn] Remove redundant `// freestanding` marks for freestanding class members

---

source/containers.tex
source/locales.tex
source/ranges.tex
tools/check-source.sh

[lib] Avoid redundant \tcode{\exposid{...}} and add a check

---

source/templates.tex

This PR aims to improve readability of p1, and to make it possible to separately cite the bullets. In my opinion, the introduction of bullets make the structure of this paragraph more obvious.

[temp.over] Itemize p1

---

source/exceptions.tex

There is a missing comma after the conditional clause *"In some situations,"*.

[except.terminate] Fix missing introductory comma

---

source/expressions.tex

(Member) pointer equality is specified in [[expr.eq]](https://eel.is/c++draft/expr.eq).

[conv.ptr], [conv.mem] Remove redundant text on null pointer comparisons

---

source/containers.tex
source/iostreams.tex
source/iterators.tex
source/macros.tex
source/ranges.tex
source/strings.tex

I plan to use this in my own documentation, so I hope to get feedback if this is desirable in the WD.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/21071787/142661043-2f2f8247-1c53-421d-9b49-5a1f3077cd4b.png"></td>
<td><img src="https://user-images.githubusercontent.com/21071787/142661047-40e68060-8ec1-40eb-b8fd-d5aca7a2bc3d.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/21071787/142661088-b4ca244d-0eca-4b34-80ba-9ba430a055bf.png"></td>
<td><img src="https://user-images.githubusercontent.com/21071787/142661089-af3d0513-1584-4e82-a75a-4bb838c3e34a.png"><img src="https://user-images.githubusercontent.com/21071787/142661092-60489c7e-f482-45b1-9bf8-0345a4b99494.png"></td>
</tr>
<tr>
<td><img …

[std] Index specializations of range variable templates

---

source/algorithms.tex

The example currently in paragraph 3 has its own list, whole numbering extends that of the normative list preceding it.  This can be confusing at first sight, with a one-line defintion apparently inserted into the middle of the list.  By adding a new pnum for the example, the list numbering in the example restarts at 4.1, reducing confusion.

[algorithms.parallel.defns] Insert new paragraph number for example

---

source/diagnostics.tex

[diagnostics] Exposition-only formatting for `val_`, `cat_`, and `frames_`

---

source/support.tex

I've noticed that for some reason, the typedefs in this header aren't indexed. By comparison, `std::int8_t` etc. are indexed here:
https://github.com/cplusplus/draft/blob/be07cd4e87c693fb9749c1e5e7c07ee0cf9e0084/source/support.tex#L1820-L1824
I've added the floating point typedefs to the index in the same style.

[stdfloat.syn] Add typedefs to library index

---

source/utilities.tex

Fixes https://github.com/cplusplus/draft/issues/6020.
First suggested here https://github.com/cplusplus/draft/pull/5978#discussion_r1044446006.

[tuple.swap] change weird 'call x with y' wording

---

tools/check-source.sh

POSIX only defines grep, not fgrep and egrep (the latter two were already marked as LEGACY in SUSv2 in 1997, and are not present in POSIX-2001 or any later POSIX standards). Recent versions of GNU grep warn when fgrep and egrep are used: https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html

tools: Use grep -F instead of fgrep

---

tools/check-source.sh

This fixes a warning when running the checks:
`grep: warning: stray \ before e`

[check] Use single quotes for grep argument

---

source/containers.tex

As far as I know, it is not enough to say
> For a non-empty array, [C++ boolean expression]
It is not obvious that this should be automatically interpreted as [C++ boolean expression] is `true` in all cases.
This edit fixes it by explicitly saying that the expression is `true`, which looks to be the intention here.

[vector.data],[array.members] Clarify C++ boolean expression

---

source/expressions.tex

This paragraph is reaching ahead quite a bit; talking about scoped enumerations, eligible special member functions, non-trivial special member functions, etc.
This edit adds the relevant forward references. What originally motivated me is that the current wording contains `non-trivial destructor\iref{special}`, which looked like a mistake. This forward reference is intended to apply to `eligible`.

[expr.call] Add further forward references

---

source/utilities.tex

Fixes #6474.
@timsong-cpp, @tahonermann FYI

[format.string.std] Fix example

---

source/basic.tex

Fixes cplusplus/CWG#379.
The example seemingly assumes that the implementation-defined properties on common platforms (e.g., `sizeof(int)` is `4`) hold. I guess we can keep such assumptions implicit and avoid pedantically writing `sizeof(int)`.

[intro.object] Make the storage in the example for storage providing properly aligned

---

source/expressions.tex

Since `sizeof...` is literally applied to an *identifier* in the grammar, (see https://eel.is/c++draft/expr.unary.general#nt:unary-expression), and p1 talks about `sizeof` *type-id*, where *type-id* is also a grammar term, it feels more appropriate to format *identifier* as such too.

[expr.sizeof] Turn identifier into a grammarterm

---

source/classes.tex

The [[class.access]](https://eel.is/c++draft/class.access) section generally only uses `private` or `public` when talking about the access specifiers in the language syntax.
The use of `\keyword{private}` is inconsistent with the rest of the subclause, and even with the rest of the paragraph.

[class.access.general] Fix improper `\keyword{private}`

---

source/lex.tex

This paragraph is obviously defining a term, but the definition is not formatted as such, contrary to definitions in [table 12](https://eel.is/c++draft/lex.string#tab:lex.string.literal).

[lex.string] Format narrow string literals as definition

---

source/templates.tex

Firstly, the leading space in the parameter list of `g1`, `g2`, and `g3` is obviously unintentional. This style isn't followed anywhere else in the example, and would be extremely unusual if intended.
Secondly, the spacing in `f` is quite excessive, and internally inconsistent with the remainder of the example. Just a few lines down, the example continues with:
```cpp
template<bool E> void f1(void (*)() noexcept(E));
template<bool> struct A { };
template<bool B> void f2(void (*)(A<B>) noexcept(B));
```
So everywhere but `f`, the author has no problem using a very conservative amount of spacing for function pointers.
This inconsistency tells me that the current declaration of `f` is some in-dev version which only made it into the standard by accident.

[temp.deduct.type] Remove excessive spacing in example

---

source/classes.tex

I personally find the absence of a comma quite annoying in this sentence, and it made me read the sentence twice.
Usually there should be a comma after an introductory clause, especially one as long as this.

[class.local] Add comma after introductory clause

---

source/basic.tex

Three of the 5 sentences in this paragraph correctly use the Oxford comma, so apply to the other two lists for consistency within the same paragraph.

[basic.types.general] Apply Oxford comma consistently

---

source/lib-intro.tex

The third column had one more entry than any other, while the fourth column was conincidentally one entry short.

[tab:headers.cpp] Rebalance table columns

---

source/preprocessor.tex
source/support.tex

I always find it difficult to locate these tables. Having an index entry will help a lot.

[preprocessor] [version.syn] Add index entries for "feature-test macro" in the two places they're defined

---

source/containers.tex

The Library spec uses `requires(` (no space before `(`) to introduce *requires-expression*s, and inserts a space to visually distinguish *requires-clause*s.

[mdspan.mdspan.overview] Don't use "requires(" for non-requires-expressions

---

source/containers.tex

The text says that "`StridedLayoutMapping` meets the layout mapping requirements" but the cross-reference is to the layout mapping _policy_ requirements.

[mdspan.layout.stride.cons] Fix cross-reference

---

source/containers.tex

"nonnegative" is meaningless for a value of some arbitrary type which we've only required to be convertible to the integral type `index_type`, so this wording clearly intends to constrain the result of the conversion.

[mdspan] require conversion results to be nonnegative

---

source/iterators.tex

[common.iter.const] Add missing periods for Returns

---

source/ranges.tex

We currently fail to say what happens if the first bullet is true, but then none of its sub-bullets is true.

[range.utility.conv.to] Add terminating condition for first bullet

---

source/time.tex

Fixes ISO/CS 003 (C++23 DIS).
Fixes cplusplus/nbballot#545

[time.format] Make reference to ISO 8601 more precise

---

source/expressions.tex

Paragraph 2 does two things.  The part before the note specifies the scope where the closure type is defined.  The part after the note places constraints on how the closure type can be implemented.  Adding a paragraph number after the note seems to be more readable, and referencable in the future.

[expr.prim.lambda.closure] insert an extra pnum

---

source/memory.tex
source/numerics.tex

Trivially copyable is (almost) never hyphenated, so remove the hyphens from the two extant cases.  Add one cross-reference
to the term for good measure.

Dehyphenate trivially-copyable

---

source/lex.tex

Fixes ISO/CS 008 (C++23 DIS).
Fixes cplusplus/nbballot#550
Note: The first commit (adding another reference to the Unicode Standard) is probably not strictly necessary.
The second commit puts a "shall" near the reference, which is the suitable trigger word here.

[lex.charset] Clarify normative reference to Unicode for UTF-x

---

source/intro.tex

Also change "argument" to "parameter" in the note.
Fixes ISO/CS 015 (C++23 DIS).
Fixes https://github.com/cplusplus/nbballot/issues/557

[defns.{impl.limits,iostream.templates}] Use singular

---

source/basic.tex
source/intro.tex
source/lib-intro.tex
source/macros.tex
source/support.tex

Fixes ISO/CS 035 (C++23 DIS).
Partially addresses https://github.com/cplusplus/nbballot/issues/544.
Fixes https://github.com/cplusplus/nbballot/issues/577.

Replace "C Standard" with "ISO/IEC 9899:2018" and define "C standard library"

---

source/declarations.tex
source/intro.tex
source/xrefdelta.tex

Partially fixes ISO/CS-11 (C++23 DIS).

[intro.defs, dcl.init.list] Move definition of direct-non-list-init

---

source/containers.tex

`std::span` has a member function `data`, which shadows `std::data`.
It is especially awkward that in `data() == data(arr)`, the first `data` refers to the member, while the second refers to `std::data`. The addition of `std::` helps to clarify that these two `data` belong to different scopes.

[span.cons] Add `std::` for `data(arr)`

---

source/utilities.tex

The example code refers to `std::string` directly so it should `#include<string>`.

[format.formatter.spec] Add missing include to example

---

source/classes.tex
source/declarations.tex
source/overloading.tex
source/templates.tex

Outside of the grammar term and first paragraph of [dcl.stc], "storage class" has no meaning in C++, and has no need to be defined. This replaces mentions of "storage class" with *storage-class-specifier*, "storage duration" and "linkage" where appropriate.

Strike surviving mentions of "storage class" (outside of stable names and grammar)

---

source/classes.tex

There is no such thing as a _ref-qualifier-seq_. The fix here is obvious.

[class.conv.fct] Fix reference to 'ref-qualifier-seq'

---

source/containers.tex

Currently it is a bit unclear in which headers these specializations are provided.
I'm trying to make clarification editorially since @Dani-Hub told me that the changes seemed almost editorial to him.

[stack.syn, queue.syn] Show `formatter` specializations in the synopses

---

source/basic.tex
source/classes.tex
source/statements.tex

[std] Use more \defnadj

---

source/classes.tex

Alternatively we could have added the word "non-object"; or changed it to say "An overloaded assignment operator must be a member function"; but it doesn't seem like it needs to be here at all.
(Clang, EDG, MSVC all agree that `B& operator=(this B, int);` is legal C++23.)

[class.copy.assign] Remove a superfluous note.

---

source/containers.tex

I have been requested to make this a direct request rather than putting it in P0447.
Despite the cute poem, section 2 should be removed because the note is misleading and over-simplified. The section conflates time complexity and performance, and oddly recommends vector as a default without mentioning its time complexity, unlike the other containers. Time complexity's relevance to both performance and latency is subject to architectural differences. If the committee chose to re-include such a note, it should simply describe time complexity as below (being removed may be better as it creates less confusion):
[Note 1: The sequence containers offer the programmer different complexity trade-offs. vector has amortized constant time complexity for insertions at the end of the sequence, and …

Remove section 2 from [sequence.reqmts]

---

source/classes.tex

The term "exception handler" isn't defined anywhere, so it is a mistake to refer to it.
Just a few bullets up, the wording refers to the term in the grammar, making the subsequent bullet inconsistent
https://github.com/cplusplus/draft/blob/1339fdd98ed04a5077e7dad9ed356eb0302be8aa/source/classes.tex#L6213-L6216
Also, `except.handle` is a more accurate reference than `except.pre`.

[class.copy.elision] Improve reference and replace informal term

---

source/memory.tex

Fixes https://github.com/cplusplus/draft/issues/5544 (in part)

[mem.res.pool.options] Replace `field` with `member`

---

source/support.tex

[P1383R2](https://wg21.link/P1383R2) "More `constexpr` for `<cmath>` and `<complex>`" modifies two headers. 8571e9454c7651995d72df8c3002bd97137304c6 updated `__cpp_lib_constexpr_cmath`, but I believe that `__cpp_lib_constexpr_complex` should also be updated.
SD6 already lists this new value. See https://wg21.link/sd6#__cpp_lib_constexpr_complex.

 [version.syn] Bump value of __cpp_lib_constexpr_complex

---

source/declarations.tex

I might just be missing something obvious here, but the current wording of [dcl.enum/2](https://eel.is/c++draft/enum#dcl.enum-2.sentence-8) seems to use the grammar production _initializer_ when it means _constant-expression_. The grammar production [_initializer_](https://eel.is/c++draft/dcl.init.general#nt:initializer) is defined as
initializer:
brace-or-equal-initializer
'(' expression-list ')'
I could have just replaced "an _initializer_" with "a _constant-expression_". But, looking at the preceding sentence, I think "with `=`" and "without `=`" are the perfect way to describe what we're talking about here. So this change is bigger (but still, IMHO, editorial).

[dcl.enum] Enumerators don't have "initializers"

---

source/iostreams.tex

[streambuf.general] Strike "abstract" from "basic_streambuf serves as an abstract base class"

---

source/expressions.tex

This paragraph should not be normative. It's essentially a "see also" paragraph.

[basic.lval] Turn reference paragraph into note

---

source/containers.tex
source/expressions.tex
source/templates.tex
source/utilities.tex

The current cross-references to [temp.param] appear confusing, as the structural type definition is buried a couple of pages below.  Also, this change looks clearer in the source.

[temp.param] Introduce term to xref structural type

---

source/basic.tex
source/memory.tex
source/meta.tex

All the other terms defined in this paragraph have a term.xxx.type name.  An iref using the term name, rather than the section name, will create a hyperlink to the specific paragraph, rather than the top of the clause.

[basic.types.general] Create a term for implicit-lifetime type

---

source/classes.tex

https://github.com/cplusplus/draft/blob/1c22d62180901069128b21daa2773d40566bd983/source/classes.tex#L2357-L2369
The author follows the ` = ` style in the rest of the example, so it is obvious that the missing space here is not intentional, but a typo.

[class.conv.ctor] Fix missing space

---

source/basic.tex

[intro.abstract]/3:
> Certain other aspects and operations of the abstract machine are described in this document as **unspecified**... These define the nondeterministic aspects of the abstract machine[.](http://eel.is/c++draft/intro.abstract#3.sentence-3) An instance of the abstract machine can thus have more than one possible execution for a given program and a given input[.](http://eel.is/c++draft/intro.abstract#3.sentence-4)
Without «unspecified» in [intro.race]/14
> The value of an atomic object M, as determined by evaluation B, shall be the value stored by some side effect A that modifies M, where B does not happen before A[.](http://eel.is/c++draft/intro.races#14.sentence-1)
reading atomic objects is not nondeterministic

[intro.races] Make reading atomic objects nondeterministic

---

source/basic.tex

This PR currently removes all occurences of "shall" in [intro.races], except for the explicitly stated use in "implementation shall".
Fixes cplusplus/CWG#373.

[intro.races] Remove unclear uses of "shall"

---

source/numerics.tex

`fma` and `lerp` have multi-line parameter lists which are not vertically aligned like `hypot`.
This looks goofy, and the edit fixes these issues.

[cmath.syn] Fix misaligned parameter lists

---

source/containers.tex

All of the standard containers are 3-way comparable, but the specification is provided under optional container requirements so does not show up in the index.
Adding these links shows just how poorly indexed the members of the 'flat_*' container adapters are, but that is properly the business on a separate PR.

[container.opt.reqmts] Index 3-way compare for containers

---

source/time.tex

`leap_seconds` can only be compared with `sys_time<Duration>`, so we are in nondeduced context here? 
Correct me if I'm wrong.

[time.zone.leap.overview] Fix example

---

source/expressions.tex

Fixes #6055.
The old example is made well-formed by CWG2392. And it's doubtful whether it was definitely correct before CWG2392, as an implementation may allow a large object type `T` such that `(int)sizeof(T)` is equal to `0`.
The expression `new decltype((void)T{})` used by this PR is guaranteed to be ill-formed and thus makes the program IFNDR - either `T{}` is ill-formed, or the expression is equivalent to `new void` which is ill-formed.

[expr.prim.req.general] Correct the IFNDR example

---

source/utilities.tex

I have visually checked with [eel](http://eel.is/c++draft/execpol#unseq) and fixed the inconsistencies in the code, but have not built and checked.

[execpol.unseq] Fix inconsistent indent

---

source/utilities.tex

Apply a consistent pattern to how we specify assigning members in assignment operators.
It looks like we have old wording on one overload, that causes an unnecessary line-wrap, so propose this editorial cleanup, that happens to bring consistency to the phrasing of all of the overloads.

[pairs.pair] Consistent wording for assignment

---

source/classes.tex

In both cases, I'm not sure introducing `V` helps much - just requires name lookup for `V`. If we just say "the return value" in every case, I think that's clearer.

[class.compare] Don't introduce `V` for the return value

---

source/basic.tex
source/support.tex

Since ISO/IEC/IEEE 60559:2008 the word „mantissa“ has been superseded by „significand“.

Change floating point wording from mantissa to significand

---

source/macros.tex
source/styles.tex

Fixes https://github.com/cplusplus/draft/issues/6510 .

Add \hypertarget to enable url links into xrefs

---

source/lib-intro.tex

It would be more appropriate in American English to use a comma in this place.
Without the comma, the sentence reads as:
> [...] depends on the name of at least one program-defined type and [on something else]
With the comma, the sentence reads as:
> [...] depends on the name of at least one program-defined type, and [there is another requirement]
The second reading is correct here, given the rest of the sentence.

[namespace.std] Convert unconventional (a) and (b) notation to items

---

source/threads.tex

Fixes #6376.
p11 should have been a recommended practice paragraph, and the current phrasing is slightly unclear on whether demands are made only towards atomic stores, or towards both loads and stores.
The proposed wording is a combination of my initial disambiguation, incorporating ideas from @jensmaurer.

[atomics.order] p11 - Make it recommended practice and rephrase

---

source/meta.tex

Not sure why runtime `assert` was used on [meta] in the first place.

[meta.unary.prop.query, meta.trans.arr] Use `static_assert` instead of `assert` in example

---

source/expressions.tex

Using `constexpr` in this context is how users would implement the trait typically, in modern C++.
This also improves the example because it demonstrates that `sizeof...` is a constant expression, which `const` in itself doesn't.

[expr.sizeof] Use constexpr member in example

---

source/strings.tex

It's very confusing to talk about `reserve()` when describing a call to `reserve(size_type)`, given that the overload `reserve()` also exists.

[string.capacity] Remove parentheses from "reserve()"

---

source/declarations.tex

A [*declarator-id*](https://eel.is/c++draft/dcl.decl.general#nt:declarator-id) is not necessarily a [name](https://eel.is/c++draft/basic.pre#def:name).

[dcl.meaning.general] Use 'declarator-id' instead of 'name'

---

source/modules.tex

* Simplify the wording of [[module.global.frag]/3.5.2](https://eel.is/c++draft/module.global.frag#3.5.2)
* Make the phrasing of 'one of *D* and *M*' consistent across following bullets

[module.global.frag] Simplify wording

---

source/declarations.tex

"Related type" is not a term, and it might be clearer to use "reference-related type".
Should close cplusplus/CWG#461, which is not a defect IMO. Towards #6651.

[dcl.init.ref] Clarify "related type"

---

source/intro.tex
source/macros.tex

[intro.defs, macros] Add cross-references among definitions

---

source/lib-intro.tex

Add missing ellipsis, changing to `a.construct(c, args...)`.
Hopefully this fix can be made editorially.
CC: @jwakely

Fix typo in [allocator.requirements.general] wording for `a.construct(c, args)`

---

source/intro.tex
source/time.tex

As requested by ISO/CS for C++23 DIS.

[std] Update references from ISO 8601:2004 to ISO 8601-1:2019

---

source/classes.tex

Everywhere else has "friend declaration" without monospace.
Sidebar: Actually, I fail to find any definition of the term "friend declaration"; it clearly means "any kind of declaration involving the `friend` keyword," but I don't see that spelled out. The logical place for such a definition might be [[dcl.friend]](https://eel.is/c++draft/dcl.spec#dcl.friend).

[class.friend] Fix a mistakenly monospaced "`friend` declaration"

---

source/preface.tex

This clause explains our conventions regarding stable labels and choice of fonts.
It is based on a similar, minimal Introduction used by the Library Fundamentals TS for similar purposes.
This is the initial contribution to #6271, and for C++26 we should expand this material considerably.

[introduction] A minimal "Introduction" clause

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/expressions.tex
source/preprocessor.tex
source/templates.tex

Fixes #6657
Fixes cplusplus/papers#1329
NOTE:
- The paper renames class-or-decltpye to class-or-computed-type-specifier
in the grammar, but nowhere else.  There are references to class-or-decltype
in the narrative accompanying the grammar, those references are now pointing
to nowhere.
It is editorially-unclear whether the other mentions of class-or-decltype
should be bluntly replaced, or whether some of them shouldn't (maybe
because of special cases).
- In expr.prim.id.qual, an "or" was struck, but nothing was added.
The only effect is to destroy the grammar of the sentence.
This can be editorially reverted, I think.

[Motions 2023 11 cwg 3] P2662R3 Pack Indexing

---

source/containers.tex
source/future.tex
source/iostreams.tex
source/iterators.tex
source/locales.tex
source/memory.tex
source/numerics.tex
source/ranges.tex
source/strings.tex
source/threads.tex
source/utilities.tex

Fixes #6659.
Notes:
* LWG3965 skipped; I don't know how to apply this change.

[Motions 2023 11 lwg 1] P3040R0 C++ Standard Library Issues

---

source/algorithms.tex
source/lib-intro.tex
source/support.tex

- Removed trailing 's' from subsection names to match parent.
- Modified punctuation for clarity.
Fixes #6660.
Fixes cplusplus/papers#1218

[LWG motion 2] P0543R3 Saturation arithmetic

---

source/algorithms.tex
source/containers.tex
source/lib-intro.tex
source/strings.tex
source/support.tex
source/utilities.tex

Fixes #6661 
Fixes cplusplus/papers#1077

[LWG 3] P2407R5 Freestanding Library: Partial Classes

---

source/support.tex
source/utilities.tex

Fixes #6665.
Fixes cplusplus/papers#1621

[LWG 7] P2909R4 Fix formatting of code units as integers (Dude, where’s my char?)

---

source/compatibility.tex
source/containers.tex
source/support.tex

Fixes #6667.
Fixes cplusplus/papers#1118

[LWG 9] P2447R6 std::span over an initializer list

---

source/compatibility.tex
source/future.tex
source/xrefdelta.tex

Fixes #6669
Fixes cplusplus/papers#1524

[LWG 11] P2868 Remove deprecated typedef from std::allocator

---

source/compatibility.tex
source/future.tex
source/xrefdelta.tex

Fixes #6670 
Fixes cplusplus/papers#1526

[LWG 12] P2870R3 Remove deprecated basic_string::reserve() with no parameters

---

source/numerics.tex
source/support.tex
source/utilities.tex

Fixes #6672.
Fixes cplusplus/papers#1500

[LWG 14] P2819R2 Add tuple protocol to complex

---

source/strings.tex
source/support.tex

Fixes #6673.
Fixes cplusplus/papers#1605

[LWG 15] P2937R0 Freestanding: Remove strtok

---

source/containers.tex
source/lib-intro.tex
source/memory.tex
source/support.tex
source/utilities.tex

Partially fixes #6674.
Note:
* See #6692 for change to [views.span] after [P2821] "span.at()" merged:  "append a // freestanding-deleted comment to every overload of at". I only saw one such "overload" - should there be more?

[LWG 16] P2833R2 Freestanding Library: inout expected span

---

source/iterators.tex
source/support.tex

Fixes #6675
Fixes cplusplus/papers#1509

P2836R1 std::basic_const_iterator should follow its underlying type's convertibility

---

source/diagnostics.tex

Fixes #6676.
Fixes cplusplus/papers#957
Question: Was the red wording in [cassert.syn] intended to be deleted?
- Update: Thomas says no; added back and force-pushed.

[LWG 18] P2264R7 Make assert() macro user friendly for C and C++

---

source/support.tex

This macro indicates that freestanding support for "saturation arithmetic" is available, which was added in motion LWG-2 (via P0543R3). This reverts the previous change
148e03a16d53ff8cffd219384df37efad5fd386d, which I had made subsequent to motion LWG-3 (P2407R5), on advice of LWG. A separate macro is preferable to mixing both headers under "algorithm".

[version.syn] New feature test macro __cpp_lib_freestanding_numeric

---

source/ranges.tex

Elsewhere we say "the header" or "any of the headers", e.g. [meta.trans.other], [tuple.helper], etc.

[range.access.general] Use consistent "In addition to being available" form

---

source/utilities.tex

[expected.general] Fix description of expected<T, E> (issue #6714.)

---

source/classes.tex

The last sentence of [class.eq]p3 says the opposite after the refactor done in #6035.

[class.eq] Fix the return value of a defaulted == operator function

---

source/statements.tex

In this paragraph, *expression* literally refers to when the *expresssion* grammar term is missing in the syntax (included in the same paragraph):
> *expression*<sub>opt</sub>`;`
It feels more appropriate to style it as a `grammarterm` due to this strong connection, instead of simple prose.

[stmt.expr] use grammarterm for expression

---

source/basic.tex
source/classes.tex
source/containers.tex
source/declarations.tex
source/expressions.tex
source/iostreams.tex
source/lex.tex
source/lib-intro.tex
source/numerics.tex
source/overloading.tex
source/support.tex
source/templates.tex
source/threads.tex
source/time.tex
source/utilities.tex

Only specific phrases involving the word "required" are problematic, namely when they appear to establish a normative requirement. They have been reworded, often by replacing "is required" with "needs", sometimes with slightly larger edits.
Also reword "necessary", "permitted", "allowed" in notes, so that they do not (inappropriately) state requirements or
permissions.
On request of ISO.

[std] Remove problematic phrases from notes

---

source/locales.tex

[text.encoding.cmp] calls these parameters `a` and `b` so the synopsis should either not name them, or use the same names.
https://github.com/cplusplus/draft/blob/74433025763f83bbccfb001dab8aa084647ffb2f/source/locales.tex#L5021-L5033
Partially addresses #3255

[text.encoding.overview] Use same parameter names as detailed description

---

source/support.tex

We recently added `bad_expected_access<void>` to the Standard Library, which derives from `exception`, but does not have "the following publicly accessible member functions, each of them having a non-throwing exception specification." For clarity, we should point out that this provision is not universal.

[exception] Paragraph two is no longer universally true

---

source/utilities.tex

[tuple.helper] p1 defines a general requirement that all specializations of `tuple_size` shall meet the *Cpp17UnaryTypeTrait* requirements but p4 actually defines a special situation where this requirement is not met ("Otherwise, it has no member value"). We have the same seemingly contradiction in [depr.tuple] p2. For clarity, we should point out that this provision is not universal.

[tuple.helper] paragraph one not universally true

---

source/utilities.tex

Consistent with '2' on line 1977 above.
https://github.com/cplusplus/draft/blob/4fe9190fa05c4fb4e83c1a1ba68aa12aa49542e9/source/utilities.tex#L1977

[tuple.cnstr] Do not use code font for cardinal number 1

---

source/numerics.tex

This error was present in the incoming [P1719R2](https://wg21.link/p1719r2) paper (Mandating the Standard Library: Clause 26 - Numerics Library), but is obviously bogus. There is no UnaryOperation type in that constructor. The correct requirement is taken from the corresponding constructor in [rand.dist.samp.pconst].

[rand.dist.samp.plinear] Fix copy & paste error in Mandates

---

source/strings.tex

[string.view.synop] 23.3.2 // 23.3.7, suffix for basic_string_view literals
[string.syn] 23.4.2 // 23.4.7, suffix for basic_string literals

[string.view.synop,string.syn] Fix indentation

---

source/memory.tex
source/regex.tex

[mem.res.private, mem.res.monotonic.buffer.mem, re.traits] Use `*this` instead of improper `this` in the library wording

---

source/threads.tex

`INVOKE` is not a function, it's a magic expression rewriter. So we don't "call" `INVOKE`, we evaluate the rewritten expression.

[thread.once.callonce] INVOKE is evaluated, not called

---

source/templates.tex

Gramatically, there should be a comma here. Sentences such as
> In case X, Y happens.
... read very strangely when removing the comma:
> In case X Y happens.
[temp.pre] p5 suffers.

[temp.pre] Add comma after introductory clause

---

source/utilities.tex

Fixes #6801.
I have had great difficulty reading paragraph 14 prior to this edit. There are multiple reasons for that:
1. It was 1AM when I've opened the issue.
2. I was unfamiliar with the wording "Call expressions". "Calls to this function" is commonly found in the standard and it's much more obvious that it refers to *this* function, not some call expressions in general.
3. The old wording is a huge grammatical sandwich of the form "Call expressions where ... are not core constant expressions.". The sentence goes on for quite a while and connecting the beginning to the end is mentally challenging.
4. The whole sentence is a double negation of the form "Call expressions where ... **is not** one of the types ... **are not** ...". This double negation makes it hard to comprehend what the …

[format.parse.ctx] improve readability of paragraphs 12 and 14

---

source/utilities.tex

It is more correct to write a comma here. The current wording suggests that
> An instance of `basic_fomat_parse_context` holds the one format string parsing state (of many parsing states) which happens to consist of ...
What the sentence is actually trying to express is
> An instance of `basic_format_parse_context` holds the the format string parsing state; this state consists of ...

[format.parse.ctx] add comma before consisting

---

source/utilities.tex

Normally, you would write a comma here.
Saying
> `indexing == manual` is `true` which
suggests that `index == manual` is the `true` which ...
This wouldn't make sense since there is only one `true`, which makes it more correct to write a comma here. Of course, the sentence is unambiguous one way or the other; this is purely a readability improvement.

[format.parse.ctx] add comma before 'which'

---

source/statements.tex

The current wording is:
> In the `...` statement the substatement is executed repeatedly
It would be more correct to have a comma after the introductory phrase, i.e. prior to "the".
While we're at it, I'd also like to draw some attention to https://github.com/cplusplus/draft/issues/6492.

[stmt.while], [stmt.do] Add commas after introductory phrases

---

source/statements.tex

The other day, a few other C++ users and myself were trying to find the rules which forbid `goto` from crossing non-vacuous initialization.
To our surprise, neither [[stmt.jump]](https://eel.is/c++draft/stmt.jump) nor [[stmt.goto]](https://eel.is/c++draft/stmt.goto) describe these rules; they are found in [[stmt.dcl]](https://eel.is/c++draft/stmt.dcl).
It would make the rules easier to find if we had an `\iref{stmt.dcl}` here.

[stmt.jump] Add reference to [stmt.dcl]

---

source/expressions.tex

There is a conditional clause in this wording:
> ... and if only one object of type `C` is derived from the subobject pointed (referred) to by `v` the result ...
There should be a comma prior to "the".
There are further issues with [expr.dynamic.cast] as brought up in https://github.com/cplusplus/draft/issues/6799, though this PR is orthogonal.

[expr.dynamic.cast] Add comma after conditional clause

---

source/compatibility.tex
source/time.tex

[time.parse], [diff.cpp17.temp] Hyphenate argument-dependent lookup

---

source/lib-intro.tex

Fixes #6789.
Furthermore, this paragraph has no normative effect and can be turned into a note. It's merely a *"this other section specifies ..."* paragraph.

[headers] Strike 'C standard library headers' and turn paragraph into note

---

source/lib-intro.tex

This is the first mention of "data race" or "synchronize with" in Clause [library], so adding an `\iref{intro.races}` seems helpful and appropriate here.

[handler.functions] Add reference to [intro.races]

---

source/basic.tex
source/classes.tex
source/declarations.tex
source/exceptions.tex
source/expressions.tex
source/intro.tex
source/lex.tex
source/overloading.tex
source/preprocessor.tex
source/statements.tex
source/templates.tex

Fixes #6863.
Fixes cplusplus/CWG#84
Fixes cplusplus/CWG#85
Fixes cplusplus/CWG#80
Fixes cplusplus/CWG#172
Fixes cplusplus/CWG#146
Fixes cplusplus/CWG#195
Fixes cplusplus/CWG#193
Fixes cplusplus/CWG#223
Fixes cplusplus/CWG#234
Fixes cplusplus/CWG#290
Fixes cplusplus/CWG#339
Fixes cplusplus/CWG#366
Fixes cplusplus/CWG#331
Fixes cplusplus/CWG#332
Fixes cplusplus/CWG#374
Fixes cplusplus/CWG#434
Fixes cplusplus/CWG#428
Fixes cplusplus/CWG#422
Fixes cplusplus/CWG#411
Fixes cplusplus/CWG#40
Fixes cplusplus/CWG#457
Fixes cplusplus/CWG#458
Fixes cplusplus/CWG#459
Fixes cplusplus/CWG#493
Fixes cplusplus/CWG#489
Fixes cplusplus/CWG#490
Fixes cplusplus/CWG#456
Fixes cplusplus/CWG#495
Fixes cplusplus/CWG#492
Fixes cplusplus/CWG#479
Fixes cplusplus/CWG#486
Also fixes cplusplus/papers#1582
Also fixes …

[Motions 2024 03 cwg 1] P3196R0 (Core Language Working Group "ready" Issues)

---

source/basic.tex
source/statements.tex

Fixes #6864 
Fixes cplusplus/papers#1439

CWG motion 2: P2748R5 Disallow Binding a Returned Glvalue to a Temporary

---

source/declarations.tex

Fixes #6866 
Fixes cplusplus/papers#1770

P3106R1 Clarifying rules for brace elision in aggregate initialization

---

source/declarations.tex
source/preprocessor.tex
source/statements.tex

Fixes #6865
Fixes cplusplus/papers#1233

P0609R3 Attributes for Structured Bindings

---

source/preprocessor.tex

Fixes #6867 
Fixes cplusplus/papers#1696

P3034R1 Module Declarations Shouldn’t be Macros

---

source/basic.tex
source/statements.tex

Fixes #6868
Fixes cplusplus/papers#1496

P2809R3 Trivial infinite loops are not Undefined Behavior

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/expressions.tex
source/intro.tex
source/lib-intro.tex
source/threads.tex
source/utilities.tex

Fixes #6869 
Fixes cplusplus/papers#1460

P2795R5 Erroneous behaviour for uninitialized reads

---

source/declarations.tex
source/preprocessor.tex

Fixes #6870 
Fixes cplusplus/papers#1229

P2573R2 = delete("should have a reason");

---

source/classes.tex
source/declarations.tex
source/preprocessor.tex
source/templates.tex

Fixes #6871 
Fixes cplusplus/papers#1567

P2893R3 Variadic friends

---

source/algorithms.tex
source/containers.tex
source/future.tex
source/iostreams.tex
source/locales.tex
source/ranges.tex
source/strings.tex
source/utilities.tex

Fixes #6872.
Also fixes #6765
Also fixes #6270 
Edit notes:
* LWG4016 [range.utility.conv.general]p5 Template parameters are reversed from what the paper has; resolution applied to body but not to remove Ref.

[LWG motion 1] P3180R0 C++ Standard Library Issues to be moved in Tokyo, Mar. 2024

---

source/future.tex
source/memory.tex
source/xrefdelta.tex

Fixes https://github.com/cplusplus/draft/issues/6873
Fixes https://github.com/cplusplus/papers/issues/1530

P2875R4 Undeprecate polymorphic_allocator::destroy

---

source/iostreams.tex
source/support.tex
source/utilities.tex

Fixes #6877.
Fixes cplusplus/papers#1771

[LWG motion 6] P3107R5 Permit an efficient implementation of std::print

---

source/iostreams.tex
source/support.tex

* Used oxford commas, and added commas to help the parsing of longer sentences.
* Named the sections "formatter support" for consistency.
* Used "fmtr" instead of "fmt" in section names to avoid confusion with existing section names.
* Moved the grammar for path-format-spec into the "general" section.
Fixes #6879.
Fixes cplusplus/papers#1516

[LWG motion 8] P2845R8 Formatting of std::filesystem::path

---

source/support.tex
source/threads.tex

Fixes https://github.com/cplusplus/draft/issues/6880
Fixes https://github.com/cplusplus/papers/issues/866
Applied value 202403L to feature macro
Added freestanding to feature macro
Used _intergral-type_ rather than `integer` when naming generic template parameters Removed a couple of existing commas where new preceding commas were introduced

P0493R5 Atomic minimum/maximum

---

source/algorithms.tex
source/containers.tex
source/iterators.tex
source/strings.tex
source/support.tex

- Omitted redundant 'typename' for default template arguments
- TODO: shorten name of feature-test macro
Fixes #6883
Fixes cplusplus/papers#944

P2248R8 Enabling list-initialization for algorithms

---

source/lib-intro.tex
source/support.tex
source/utilities.tex

- Reduce presentation in [replacement.functions] to signatures
Fixes #6884
Fixes cplusplus/papers#1487

P2810R4 is_debugger_present is_replaceable

---

source/algorithms.tex
source/numerics.tex
source/support.tex

- adjust subclause labels
- adjust subclause heading to fit the surroundings
Fixes #6885 
Fixes cplusplus/papers#409

P1068R11 Vector API for random number generation

---

source/containers.tex

Fixes #6888.
Fixes cplusplus/papers#1710

[LWG motion 18] P3029R1 Better mdspan's CTAD

---

source/lib-intro.tex

..Also fixed an issue where the first exposition-only comment wasn't quite aligned.

[expos.only.entity] Add missing \expos for two exposition-only names

---

source/declarations.tex

Currently looks like this: https://eel.is/c++draft/dcl.type.elab#4
I *think* the note "obviously" belongs to the previous paragraph.
Possible alternative solution: move Note 2 to the bottom of paragraph 5 instead.

[dcl.type.elab] Don't start a paragraph with a note

---

source/expressions.tex

https://github.com/cplusplus/draft/blob/8c8e05d7ff6cda6329ca898e7a270547a85675d7/source/expressions.tex#L4598-L4606
The paragraph above already states that *all* unary operators yield a prvalue. We can remove this redundant wording from the `&` operator.

[expr.unary.op] remove redundant value category wording

---

source/declarations.tex
source/overloading.tex

Fixes cplusplus/CWG#469.
Note that we can simplify the wording in [[over.ics.ref] p3](https://eel.is/c++draft/over.ics.ref#3) by the fact that an lvalue is of either an object type or a function type.

[dcl.init.ref, over.ics.ref, over.ics.rank] Avoid saying function lvalue

---

source/lib-intro.tex

The term "exception handler" isn't formally defined anywhere. It would be better to use the grammatical term *handler*, which is defined.

[res.on.exception.handling] Use `\grammarterm` instead of informal term

---

source/basic.tex

p8 is difficult to read as it defines transparently replaceable only after it has made all use of it.  The edit pulls the definition of transparently replaceable into its own preceding paragraph, and then simplifies the sentence that uses this term.

[basic.life] Reflow text defining transparently replaceable

---

source/lib-intro.tex

Fixes #6898
As the list of zombie names has grown so long, it is hard to check without scrolling.  Rendering as a table makes it easier to read in one place, as well as saving on our page count!
Pre-emptively turned all the other zombie name lists into tables too, for consistency.  We have precedent for such short tables with the table of contextual keywords.

[zombie.names] Turn lists of zombie names into tables

---

source/utilities.tex

The current wording in [[charconv.syn]](https://eel.is/c++draft/charconv.syn) is confusing at a surface level, but this is purely an editorial problem:
> ... the implementation provides overloads for all cv-unqualified signed and unsigned integer types and `char` in lieu of *integer-types*
Firstly, the reader may ask whether this means:
- (signed and unsigned integer types) and `char`, or
- (signed and unsigned) (integer types and `char`)
In other words, does this include `signed char` and `unsigned char`, or does it include `char`? However, `signed char` and `unsigned char` are already signed/unsigned integer types, so mentioning `char` separately here would be totally redundant. Only the former interpretation is plausible to me.
Secondly, the reader may ask whether "cv-unqualified" …

[charconv.syn] Clarify what types match integer-type

---

source/algorithms.tex

https://cplusplus.github.io/LWG/issue3031 proposed approved wording that includes:
> (possibly `const`)
However, all of these occurrences were formatted as plain "(possibly const)".
On top of being an editorial mistake, it's also somewhat misleading, as this shifts the intuition of the reader towards "const objects", and away from "`const` on `T`". It's clear from the surrounding wording that this `const` refers to types, but it's still easier to understand the wording with intended formatting in my opinion.

LWG3031 Fix missing code-formatting of const

---

source/ranges.tex

This appears to be a mistake when applying [LWG 4016](https://cplusplus.github.io/LWG/issue4016).

[range.utility.conv.general] Fix typo

---

source/lib-intro.tex
source/threads.tex
source/time.tex

I have audited the library and believe I have caught all the missing _Cpp17Requirements_ for the index, but have not done a further search for named requirements that do not have the Cpp17 prefix, i.e., _oldnewconcept_.

[index] Add missing entries for Cpp17 _oldconcepts_

---

source/basic.tex

For readability, there should be a comma after the conditional clause
> When a call to a library I/O function returns or an access through a volatile glvalue is evaluated
(https://eel.is/c++draft/intro.execution#7.sentence-3)

[intro.execution] Add comma after conditional clause

---

source/ranges.tex

since those 'equivalent to' s seems superfluous.

[range.reverse.overview] Replace 'equivalent to' with 'then'

---

source/classes.tex

P2662R3 contained a rename of the grammar production "class-or-decltype" to "class-or-computed-type-specifier".  That was editorially reverted with commit c831ec0b8aac369aa61ce392783865ff04b84b19, but that commit also accidentally reverted the change from "decltype-specifier" to "computed-type-specifier" as one of the options for "class-or-decltype".
This commit restores the latter change, as intended by P2662R3.

[class.derived.general] Restore accidental reversal of P2662R3 change

---

source/utilities.tex

`isdigit()` is not a `contexpr` function so it cannot be used in `parse()`, and the alignment seems to be in the wrong direction.
Demo of the original example: https://godbolt.org/z/qbs6dvq9q
fixed: https://godbolt.org/z/sjWdxxzWc

[format.context] Fix incorrect example

---

source/std.tex
source/styles.tex

[styles] Redesign Annex titles per Rice Model Standard

---

source/algorithms.tex

We don't want programmers doing CTAD on `ranges::drop_view(args...)`, so we shouldn't put it in the as-if-by code either. What we expect people to do (and what we intend vendors to do here) is `views::drop`.
(Compare #6373. I'm also pinging the LWG reflector for an opinion on whether this is handleable without an LWG issue.)

[alg.ends.with]: drop_view should be views::drop

---

source/declarations.tex

This and #6257 are the only instance of this solecism.

[dcl.init.list] Eliminate a case of "specialization of X<Y>"

---

source/support.tex

This note is talking about the class type, not the grammatical construct, so it should say `initializer_list`.

[support.initlist] Teletype font for `initializer_list`

---

source/memory.tex

The notes may want to warn the users with the phrase" will eventually result in undefined behavior," but the saying is inaccurate.
Closes: cplusplus/draft#7035

[util.smartptr.shared.cast] Properly describe a bad outcome in notes

---

source/iostreams.tex

Several of the synopses are not adjacent to the types they declare. Adding cross-references makes it easier to find the relevant definitions of classes and class templates.
Also make the title of [ostream.manip] more specific to its content.

[input.output] Add cross-references to header synopses

---

source/basic.tex
source/intro.tex

[defns.erroneous], [basic.indet] Index 'erroneous behavior' and 'erroneous value'

---

source/containers.tex

LWG reviewed this wording in Varna, approved it as suitably editorial ([poll 7–0–1](https://wiki.edg.com/bin/view/Wg21varna/P2767-20230616-LM)), and we agreed that I should now submit it as a PR for @jwakely to look at.
This PR right now is structured as eight commits: two commits per container adaptor. For each adaptor, the first commit is literally the wording published in [P2767R0 §3](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2767r0.html#editorial-cons-alloc) and reviewed live in Varna. The second commit is amendments requested by LWG, to put the constructor overload sets in the traditional order (e.g. default constructor at the top). These second commits are editorial, and they're improvements over the status quo, and they were explicitly requested by LWG, but they …

P2767R0 §3 as seen by LWG in Varna

---

source/lib-intro.tex

Not much to say here ... I personally find it helpful to have a link that takes you straight to the definition of "non-throwing exception specification" here so you can double check what it means.

[res.on.exception.handling] Add cross-reference to [except.spec]

---

source/containers.tex

In introduction in the same file there's a `\tcode{b} and \tcode{c} denote values of type (possibly const) \tcode{X},`, so this looks like a typo

Fix typo in containers.tex

---

source/utilities.tex

In paragraph [func.require#1](https://eel.is/c++draft/func.require#1), all variables use subscripted indices in text that is formatted as code, except in two cases. These look like an unintended omission. Adjust them to subscripts.

[func.require] Add missing formatting of variable index

---

source/compatibility.tex

[diff] Mark examples as such

---

source/future.tex

This should have been applied as part of LWG4036.

[depr.c.macros] Fix "macro" singular when referring to two macros

---

source/support.tex

This clause is already "Header \<version\> synopsis", no need to say "also in \<version\>" for any feature-test macro.

[version.syn] Remove redundant <version> in __cpp_lib_ranges_enumerate

---

source/ranges.tex

..which is already used in [range.cartesian.view].

[range.concat.view] Use \exposid for `is-const`

---

source/basic.tex
source/lex.tex
source/locales.tex

Fix table formatting

---

source/back.tex
source/support.tex

[numeric.limits.members,bibliography] Remove LIA-1 abbreviation for ISO 10967

---

source/basic.tex
source/lex.tex

[intro.memory] Move footnote about Unicode trademark to [lex.phases]

---

source/back.tex
source/compatibility.tex

[diff,bibliography] Move details of old C++ standards to the bibliography

---

source/containers.tex
source/declarations.tex
source/iterators.tex
source/memory.tex
source/meta.tex
source/numerics.tex
source/threads.tex
source/time.tex
source/utilities.tex

[std] Rename 'In general' headings to 'General' for consistency

---

source/classes.tex

[class.copy.ctor] Remove reference to non-existing example

---

source/preprocessor.tex
source/support.tex

[cpp.predefined,namespace.future,version.syn] Replace 'C++' with 'this document'

---

source/threads.tex

[futures.state] Turn note into example

---

source/basic.tex
source/support.tex

Fixes ISO/CS comment (C++23)
Partially addresses #7011 
@tkoeppe , this feels like an improvement to me also for the Working Draft (since we talk about specific section numbers, and "see also" already has the format we end up with here)

[basic.fundamental,cstdarg.syn] Use full reference for ISO C sections

---

source/utilities.tex

[execpol.general] Use 'this document', not 'this standard'

---

source/utilities.tex

[format.string.std] Add (R) symbol after Windows

---

source/numerics.tex

[rand.req] Replace 'that Table' with a precise reference

---

source/compatibility.tex
source/future.tex
source/utilities.tex

This seems good to apply to the WD as well.

[std] Replace 'this standard' with 'this document'

---

source/time.tex

[time.format,time.parse] Fix references to ISO week calendar

---

source/expressions.tex
source/iostreams.tex
source/iterators.tex
source/locales.tex
source/support.tex

[std] Avoid hanging paragraphs by introducing "General" subclauses

---

source/algorithms.tex
source/compatibility.tex
source/expressions.tex
source/iostreams.tex
source/lex.tex
source/lib-intro.tex
source/locales.tex
source/support.tex

(Based on pull request #7012.)
Fixes #7011 
ISO/CS wants to have a full "ISO/IEC 9899:2018" where we mention "ISO C".  That seems a bit over-the-top, and [intro.scope] p2 already explains what we mean with "C", so let's just use "C" (and drop the ISO prefix in front of it).

[std] Remove ISO from any mention of 'C'

---

source/concepts.tex
source/containers.tex
source/expressions.tex
source/iostreams.tex
source/lib-intro.tex
source/locales.tex
source/memory.tex
source/numerics.tex
source/preface.tex
source/ranges.tex
source/strings.tex
source/support.tex
source/threads.tex
source/utilities.tex

[std] Remove mid-sentence 'subclause' introducer

---

source/classes.tex

Also addresses an ISO comment about not having "For example," as the last part of the normal sentence.

[classes] Turn ad-hoc examples into proper examples

---

source/expressions.tex
source/lex.tex

[lex.ccon,expr.prim.lambda.capture] Excise 'ISO' prefix

---

source/iostreams.tex

[fs.class.path.general] Defuse cross-reference to POSIX

---

source/meta.tex
source/utilities.tex

[lib] Excise Note A, Note B, etc. designations

---

source/macros.tex
source/numerics.tex
tools/check-output.sh

[macros,numerics] Add and use numbered 'formula' environment

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/expressions.tex
source/intro.tex
source/lex.tex
source/limits.tex
source/overloading.tex
source/templates.tex

Fixes #7078.
Notes:  CWG2144 is fixed by CWG2876, to be added in CWG motion 2.

[CWG motion 1 2024-06] P3345R0 all issues except 2819, 2858, and 2876

---

source/basic.tex
source/expressions.tex
source/preprocessor.tex
source/support.tex

Fixes https://github.com/cplusplus/draft/issues/7080
Fixes https://github.com/cplusplus/papers/issues/1438

P2747R2 constexpr placement new

---

source/compatibility.tex
source/expressions.tex

Applies P3144, adopted at the St Louis meeting.
Fixes #7081
Fixes https://github.com/cplusplus/papers/issues/1796

2024-06 CWG-5 P3144 Deleting a pointer to incomplete type is illformed

---

source/compatibility.tex
source/templates.tex

Fixes #7082
Also fixes cplusplus/papers#1638

[CWG Motion 6 2024-06] P2963R3 Ordering of constraints involving fold expressions

---

source/declarations.tex
source/statements.tex

Fixes #7083 
Fixes cplusplus/papers#1617

[CWG motion 7 2024-06] P0963R3 Structured binding declaration as a condition

---

source/algorithms.tex
source/containers.tex
source/ranges.tex
source/support.tex
source/utilities.tex

[LWG motion 1 2024-06] Ready and Tentatively Ready issues in P3341R0 (C++ Standard Library Ready Issues)

---

source/support.tex
source/utilities.tex

Fixes #7087
Fixes cplusplus/papers#1831

[LWG motion 4 2024-06] P3168R2 Give std::optional Range Support

---

source/algorithms.tex

Fixes #7088
Fixes cplusplus/papers#1866

[LWG motion 5 2024-06] P3217R0 Adjoints to "Enabling list-initialization for algorithms": find_last

---

source/meta.tex
source/support.tex

Fixes #7089
Fixes cplusplus/papers#1659

[LWG motion 6 2024-06] P2985R0 A type trait for detecting virtual base classes

---

source/compatibility.tex
source/containers.tex
source/iterators.tex
source/lib-intro.tex
source/support.tex

Editor notes:
* Unable to apply change to Complexity for "a.swap(b)" in section [container.reqmts]; only such \itemdecl is in [container.alloc.reqmts] with different wording. UPDATE: found and fixed
* Unable to apply change to note in "sequence.reqmts.2" - wording does not appear to exist. UPDATE: wording was removed
* Sections named [containers.sequences.inplace.vector.\*] renamed to [inplace.vector.\*].
* [inplace.vector.modifiers] Add commas for clarity.
* [inplace.vector] Minor editorial fixes (e.g. add missing "the").
Fixes #7090
Fixes cplusplus/papers#114
Notes/questions on paper:
* Paper wants [inplace_vector] after [vector], but wouldn't it make more sense to put it after [vector.bool]? UPDATE: We probably do want [inplace_vector] after [vector.bool] - should add as a separate …

[LWG 7 2024-06] P0843R14 inplace_vector

---

source/iostreams.tex
source/support.tex
source/time.tex
source/utilities.tex

Fixes #7091
Fixes cplusplus/papers#1906

[LWG motion 8 2024-06] P3235R3 std::print more types faster with less memory

---

source/utilities.tex

Fixes #7092
Fixes cplusplus/papers#1640

[LWG motion 9 2024-06] P2968R2 Make std::ignore a first-class object

---

source/basic.tex
source/containers.tex
source/diagnostics.tex
source/iostreams.tex
source/iterators.tex
source/memory.tex
source/ranges.tex
source/regex.tex
source/strings.tex
source/support.tex
source/threads.tex
source/utilities.tex

Fixes #7094
Fixes cplusplus/papers#1744
Notes:
* [allocator.traits.other] No such declaration for allocation_result - change not applied. 
* Second edit for [set.overview] assumed to be intended for [multiset.overview].

[LWG motion 11 2024-06] P2422R1 Remove nodiscard annotations from the standard library specification

---

source/config.tex
source/exceptions.tex
source/exec.tex
source/lib-intro.tex
source/std.tex
source/support.tex
source/threads.tex
source/utilities.tex
source/xrefdelta.tex

Fixes #7095
Fixes cplusplus/papers#1054

 [LWG motion 12 2024-06] P2300R10 std::execution

---

source/lib-intro.tex

Not all of [containers] is meant to be freestanding.
The original instructions came from https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p0843r14.html#libraryrequirementsorganizationheaders.

[tab:headers.cpp.fs] Use a more appropriate subclause for inplace_vector

---

source/future.tex

Add cross-references to the corresponding C headers now that they are an adopted part of the standard library.

[depr.c.macros] Cross-reference the C headers for deprecated macros

---

source/iterators.tex

..as it is not under [[iterator.concepts]](https://eel.is/c++draft/iterator.concepts), which is difficult to find where it is defined.

[iterator.synopsis] Add \ref for `indirect-value-t`

---

source/containers.tex

The default template argument is already in [inplace.vector.erasure]. Fixes #7149.

[inplace.vector.syn] Add missing default template argument for `erase`

---

source/locales.tex

Use the macro libheaderref to add a direct cross reference to a couple of referenced headers.

[locale.ctype.general] Better cross-ref standard headers

---

source/utilities.tex

[variant.visit] Add `constexpr` to `as-variant`

---

source/iostreams.tex

The changes seem missed in #6908.

[print.syn] Show `locking` functions in the synopsis of `<print>`

---

source/memory.tex

Using the trick from https://github.com/cplusplus/draft/blob/decb06cd28ca5187444092ddebbb6845cae878c6/source/memory.tex#L5221-L5224

[out.ptr.t] Fix bullet placement for item that starts with codeblock.

---

source/iostreams.tex

#6971 added missing function declarations to the synopsis, but the function names were changed later by P3235R3.

[print.syn] Update `locking` to `buffered`

---

source/time.tex

(I threw in a little drive-by indentation fix.)

[time.duration.nonmember] Fix operator index entries.

---

source/threads.tex

For stoptoken::stop-state, the default-initialized value is already correct, and no further "{}" initializer is needed.
For stopsource::stop-state, the DMI "{}" is never used, since the constructor is explicitly specified and not defaulted.

[stoptoken.general, stopsource.general] Remove DMI from stop-state member

---

source/containers.tex

This PR fixes the following issues:
- *"The conditions for an aggregate shall be met."* does not specify that `array` meets those requirements, and usually we say this explicitly instead of letting the reader figure it out based on the subclause the wording is in. If we reworded this sentence to say *"An `array` is an aggregate"* (or something similar), this would just be repeating [[array.overview] p2](https://eel.is/c++draft/array.overview#2), and we don't need the same normative wording copied and pasted multiple times. **Therefore, the first sentence is deleted.**
- "Class `array`" is wrong. `array` is a class template, not a class. In the rest of [array], we say "an `array`" which is not wrong at least; it can be seen as a shorthand for "a specialization of the `array` class …

[array.cons] Fix various wording issues

---

source/expressions.tex

This is meant to improve readability of an otherwise overly long block of text.

[expr.cond] Itemize p4

---

source/ranges.tex

[coro.generator] Rename the `generator`'s template parameter `V` to `Val`

---

source/lib-intro.tex

The text "... the expression is an lvalue if the type is an lvalue reference type, an xvalue if the type is an rvalue reference type, and a prvalue otherwise" clearly indicates that a Result element describes the type and value category of an expression, yet we summarize it as only "a description of the type of the expression".

[structure.specifications] clarify description of Results element

---

source/algorithms.tex

Removes wrongly added default template arguments that are not present in that paper. Fixes #6949.

[alg.replace] Fix misapplication of P2248R8 to `std::replace_copy`

---

source/containers.tex

Introduce each header in its appropriate [*.general] clause with the appropriate libheaderref macro for that header.
Note that libheaderrefx must be used for header with underscores, as they would not match their computed stable label.  Similarly, plain `<map>` and `<set>` get an extra "associative." prepended to their stable label.

[containers] Consistently xref header synopses from General clauses

---

source/expressions.tex

[expr.call] Say "implicit object parameter" instead of "`this` parameter"

---

source/ranges.tex

There is no such thing as a `bidirectional_iterator_category`.

[range.join.with.iterator] Fix typo

---

source/exec.tex

`nothrow-callable` defines in [[functional.syn]](https://eel.is/c++draft/functional.syn#concept:callable), which is a concept.

[exec.snd.expos] Replace \exposconcept for nothrow-callable

---

source/exec.tex

The word _copyable_ here should be a concept. The [original paper](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2300r10.html) also confirms this.

[exec.split] Add \libconcept for copyable

---

source/basic.tex

…eference
[basic.scope.scope] Replaced the term top-level reference with just reference in light of [this issue](https://github.com/cplusplus/CWG/issues/569)
Fixes cplusplus/CWG#569

[basic.scope.scope] Replaced the term top-level reference with just reference

---

source/lex.tex

There are three cases here all doing the same thing.  Two refer to preprocessing a directive, while the first refers to processing without the pre.

[lex.pptoken] Consistent use of preprocessing vs processing

---

source/iostreams.tex

@jwakely LGTY, right? https://eel.is/c++draft/fpos exists.

[ios.syn] Fix typo'd xref to [fpos] introduced in 4b3f32ae

---

source/compatibility.tex
source/macros.tex

[macros,diff] Rework header indexing to avoid hyphenation hints

---

source/templates.tex

Fixes #https://github.com/cplusplus/draft/issues/5997.

[temp.over.link] Reword to clarify that declarations correspond

---

source/exec.tex

Change `o1` -> `o2` to reference the expression declared as part of the definition of `SCHED-ENV`.

[snd.expos] Fix typo in definition of SCHED-ENV exposition-only helper

---

source/declarations.tex

[dcl.fct] Fix obsolete phrasing when defining 'function type'

---

source/containers.tex

There is exactly one place in containers.tex where we have "If X, *then* there are no effects." But the "X" in that case is very convoluted, so I think the "then" is kind of helpful.
Notice the several novel instances of "there are no effects *on `*this`*" in [inplace.vector]. I want to fix those too, for consistency with [vector] and [list]; but I think that probably requires a formal LWG issue.

[list] [vector] [inplace.vector] Consistent comma in "If X, there are no effects"

---

source/exec.tex

Fixes one use of the exposition-only member _sync-wait-state::error_ in the wording of [exec.sync.wait] p9 where the identifier was not marked as exposition-only.

Correctly mark state.error as an exposition-only identifier in [exec.sync.wait] p9

---

source/exec.tex

The [original paper](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2300r10.html) confirms this.

[exec.recv.concepts] Add \libconcept for receiver

---

source/meta.tex

As I was implementing `std::is_within_lifetime` I tried to compile the example and fixed its problem.

[meta.const.eval] make the example compilable

---

source/expressions.tex

It would be quite strange if captures starting with `&` would suddenly be captured by copy because of presence of ellipsis.

[expr.prim.lambda.capture] Incorporate ellipsis into "captured by copy" definition

---

source/declarations.tex

There is full stop after the reference.

[dcl.type.elab] Remove redundant full stop

---

source/numerics.tex

In three places, correct typo Bessell -> Bessel

[numerics] correct typo Bessell -> Bessel

---

source/exec.tex
source/time.tex
source/utilities.tex

Removes extraneous `inline` from the definitions of variable templates in [format.syn], [format.tuple], [time.format], [execution.syn], and [exec.util.cmplsig].

(library-wide) Remove `inline` from variable templates

---

source/containers.tex
source/iostreams.tex
source/utilities.tex

Remove `friend class` from the library wording

---

source/iostreams.tex

It is a bit tautological to say "unneeded call" in a note, because implementations should always prevent unneeded calls.

[fs.class.directory.entry.general] Remove unneeded "unneeded"

---

source/basic.tex

The note is saying that declarations of qualified names do not bind names, but this is not supported by normative wording in [dcl.meaning]. @opensdh suggested that this is a leftover from P1787R4 (R6 is what was voted in).
This was discussed in Mattermost (https://chat.isocpp.org/general/pl/1rjh7gn95ifg9kx11kgibcg1fw) and on the Core reflector (https://lists.isocpp.org/core/2024/08/16249.php).
CC @jensmaurer

[basic.scope.scope] Fix a note about declarations that do not bind names

---

source/utilities.tex

The `@\seebelow@` has been present since a307ec1e76cbe1c4f76f25fab3371177154f64be, but it's unclear to me why it was preferred. Perhaps it would be an improvement to make the return type clearer in the synopsis.

[optional.syn] Use `decay_t<T>` directly instead of "see below"

---

source/containers.tex

Both paragraphs incorrectly point to [container.reqmts] instead of [container.alloc.reqmts] for "the requirements of an allocator-aware container".
Both paragraphs state "the requirements placed on `value_type` in [container.alloc.reqmts] apply instead to `key_type` and `mapped_type`" for `map`, `multimap`, `set`, and `multiset`. This would be nonsense, since those containers never allocate or (or allocator-construct) `key_type` or `map_type` objects: _do_ allocator-construct `value_type` objects. The examples in each paragraph also make the error obvious: there are no `CopyAssignable` requirements in [container.alloc.reqmts].
I suspect these pairs of xrefs in each paragraph were transposed sometime in the past and we just haven't noticed.

[associative.reqmts.general],[unord.req.general] Fix cross-references to [container.alloc.reqmts] and [container.reqmts]

---

source/expressions.tex

Not sure how this got there ...

[expr.delete] Remove stray "the" between words

---

source/utilities.tex

Use an itemize list for the constraints on template<class U = T> constexpr optional<T>& operator=(U&& v);
No change to the constraints, just editorial parallelism.

Use itemize list for optional<T>& operator=(U&& v) constraints

---

source/declarations.tex

[dcl.spec.general,dcl.fct.spec] Clarify duplication of decl-specifiers

---

source/iostreams.tex

Towards #5940 and #4702.
Renaming:
- `init_buf_ptrs` to _`init-buf-ptrs`_,
- `emit_on_sync` to _`emit-on-sync`_,
- `pathobject` to _`path-object`_.
`init_cnt` is not changed because it should be removed.

[input.output] Use `\exposid` for exposition-only names

---

source/lex.tex
source/regex.tex

[tab:lex.charset.literal] Shorten table heading

---

source/iostreams.tex

The text that made use of this variable was removed by LWG1123 and has not been present in the WP since N3090. The effects of `Init` construction and destruction are specified entirely without the use of this variable, so it serves no purpose now.
LWG1123 even noted that this variable could be dropped, stating "Some editorial changes are expected (in addition to the proposed wording) to remove `init_cnt` from `Init`." Let's do that. Better late than never.

[ios.init] Remove unused Init::init_cnt static member

---

source/std.tex

See ISO/IEC Directives, Part 2, section 6.5 Supplementary content

[std] Format URLs in blue regular font

---

source/macros.tex
source/styles.tex

This restores the C++20 status of the formatting.

[styles] Format title of \codeblocktu using 'caption' package

---

source/containers.tex

So we don't need this `from_range_t` constructor (and only this constructor) to tell us that the `inplace_vector` it constructs happens to be an object. I should also point out that this is inconsistent with the other constructors which simply say "constructs an `inplace_vector` with [properties]".

[inplace.vector.cons] "Constructs an object" is redundant

---

source/iostreams.tex

This is more compact, keeps the whole template-id on a single line, and avoids some awkward page breaks.

[ostream.inserters.arithmetic] Put use_facet use on fewer lines

---

source/future.tex

P2361R6 introduced the notion of unevaluated strings, and updated the grammar for literal operator function accodingly. Unfortunely, the corresponding grammar reference that was deprecated was not similarly updated.

[depr.lit] Fix grammar according to P2361R6

---

source/containers.tex

This is consistent with p2 and p8 which also value-initialize it.

[priqueue.cons.alloc] Add missing initialization for comp

---

source/containers.tex

It's confusing that these `to_array` overloads require `T` to be constructible from various types, when they actually construct `remove_cv_t<T>` objects. We experts know that initialization doesn't depend on the cv-qualification of the target type ([dcl.init.general]/16) but there's no need to make readers jump through hoops to understand the spec.

[array.creation] Clarify Mandates for `to_array` overloads

---

source/exec.tex

The wording for [exec.split] and [exec.when.all] refers to an alias template `stop_callback_of_t` which is not defined anywhere.
There is, however, a `stop_callback_for_t` alias template defined in [thread.stoptoken.syn] which has the desired shape and semantics.

[exec.split], [exec.when.all] Fix typo stop_callback_of_t -> stop_callback_for_t

---

source/exec.tex

The `\exposid{product-type}` needed some extra `@` symbols surrounding so that the subsequent curly-braces for the constructor call are treated as literal text.

Fix markup of product-type constructor call in [exec.just]

---

source/containers.tex

Add the missing containers to index the operations defined by the container requirements clauses.

[container.requirements] Index missing members of flat containers

---

source/containers.tex
source/threads.tex

In [mdspan.mdspan.overview], the `.`in `@\exposid{map_.}@is_strided()` was misplaced. It should be `@\exposid{map_}@.is_strided()`.
In [mutex.syn], add a comma after `\ref{thread.timedmutex.class}` for consistency.

[mdspan.mdspan.overview, mutex.syn] Mini fixes for synopses

---

source/threads.tex

The `stoppable_token<Token>` concept requires both `copyable<Token>` to be satisfied and `swappable<Token>` to be satisfied.
However, the `copyable<Token>` requirement already subsumes `movable<Token>`, which subsumes `swappable<Token>`.
Therefore the requirement for `swappable<Token>` can be removed from the `stoppable_token` concept definition with no semantic change.

[stoptoken.concepts] Remove redundant 'swappable<Token>' clause from 'stoppable_token' concept

---

source/exceptions.tex

The purpose of this subclause is to define stack unwinding, which in specified in terms of the lifetime of objects, not just class types.  Hence, while much of the text is addressing interactions with contructors and destructors (the original subclause title) it does more than just that.

[except.ctor] Retitle subclause as 'stack unwinding'

---

source/exec.tex

The initialization of the exposition-only `recv` and `state`
data-members in the `basic-state` constructor should have marked-up
the member identifiers using \exposid.
Also, the `recv` argument passed to `get-state` was supposed to be
referring to the exposition-only data-member rather than the parameter
of the same name as otherwise it would be referring to a moved-from
object.
So markup the `recv` argument to `get-state` using \exposid as well
to make this (slightly) clearer.

[exec.snd.expos] Fix markup of exposition-only identifiers in `basic-state` constructor

---

source/preprocessor.tex

The term 'preprocessing translation unit' is defined in [lex.separate] while the term 'preprocessing file' is never defined, and is not used anywhere else in the standard.  Prefer to use the specified term, as it reasonably covers this case.

[cpp.subst] proprocessing file -> translation unit

---

source/preprocessor.tex

The term 'active macro directive' is defined in p6, but never used. Meanwhile, there are multiple uses of 'active macro definition' but that term is never defined, including in the very sentence following the definition of the unused term, and in other clauses that cross-reference to this clause for their definition.
This seems clear enough to be an editorial fix, rather than a Core issue, but I defer to the CWG chair to make that call.

[cpp.import] Active macro directive -> definition

---

source/overloading.tex

The term "basic type" is used twice in this note but it's never defined anywhere. It's not used anywhere else either.
---
A similar fix was done in https://github.com/cplusplus/draft/pull/6012, so I was thinking we could do the same here. Alternatively, we could use "arithmetic types" instead of "fundamental types".

[over.oper.general]: Avoid use of the term "basic type"

---

source/locales.tex

Make it explicit that `copyable` is intended, rather than `semiregular`, and that the return types of `begin()` and `end()` can differ.
Also remove a FIXME comment for something that doesn't need fixing. These requirements on a type are specified in our usual form, it would be wrong to use _Remarks_: or _Requires_: here.

[text.encoding.aliases] Add note about what isn't required

---

source/lex.tex

The grammar for universal-character-name is oddly sandwiched into the middle of the subcluase talking about the different character sets used by the standard.  To improve the flow, extract that grammar into its own subclause.
In the extraction, I make two other clarifying changes.  First, describe this new subclause as 'a way to name any element of the of the tranlation character set using just the basic character set' rather than simply 'a way to name other characters'.  Secondly, remove the 'one of' in the grammar where there is only one option to choose.

[lex.charset] Extract universal-character-name grammar to new subclause

---

source/numerics.tex

The associated Laguerre/Legendre functions build on the Laguerre/Legendre functions, which are defined in different equations. Point to them from the associated functions.
Also use the correct \ell as used in the formula.

[sf.cmath.assoc.laguerre,sf.cmath.assoc.legendre] Add reference to eq

---

source/containers.tex
source/utilities.tex

After extensive discussion about [[nodiscard]] policy in LEWG, it was agreed that [[nodiscard]] should not appear in the library wording (see [SD-9](https://isocpp.org/std/standing-documents/sd-9-library-evolution-policies)). However, the wording removal paper, P2422R1 (approved in St. Louis, #7110), does not seem to remove all occurrences of [[nodiscard]] in the library clauses due to some recently added [[nodiscard]] annotation (such as those on flat containers’ `empty()`) being missed.
Therefore, this PR removes all occurrences of [[nodiscard]] in N4988. Those are:
- 22.2.1 [utility.syn]
- 24.6.9.2 [flat.map.defn]
- 24.6.10.2 [flat.multimap.defn]
- 24.6.11.2 [flat.set.defn]
- 24.6.12.2 [flat.multiset.defn]
- 24.7.3.6.1 [mdspan.mdspan.overview] and 24.7.3.6.3 [mdspan.mdspan.members] …

[utility.syn, flat.map.defn] Remove all [[nodiscard]] from library wording

---

source/expressions.tex

Someone has told me that they've been reading [[expr.new] p6](http://eel.is/c++draft/expr.new#6) wrong; namely in a way that implies `new int[0]` is ill-formed.
It's not immediately obvious that it is okay even though the wording says that something shall not be zero.

[expr.new] Extend example for new-expressions with zero size arrays

---

source/strings.tex

Add a few cross-references for headers used in the char_traits clauses.

[char.traits] Better cross-reference several headers

---

source/expressions.tex
source/templates.tex

Pointer values are not addresses ([[basic.compound]/3](https://wg21.link/basic.compound#3.sentence-8)), this updates some of the old text to use proper terminology. The intent of the wording is clear, and this PR does not change its normative meaning.
I'm not sure if changing 'address of' to 'pointer representing the address of' is an improvement, so the following are left untouched:
* [[basic.stc.dynamic.allocation]/2](https://wg21.link/basic.stc.dynamic.allocation#2.sentence-2)
* [[expr.delete]/11](https://wg21.link/expr.delete#11.sentence-4)
* [[dcl.fct.def.coroutine]/12](https://wg21.link/dcl.fct.def.coroutine#12.sentence-6)
Also, in [[temp.arg.nontype]/3](https://wg21.link/temp.arg.nontype#3), the text should probably also include past-the-end pointers, but that's not editorial.

Bring pointer terminology up to date

---

source/exceptions.tex

This commit moves all of the paragraphs involved in the search for a handler for an exception into a single logical sequence.
After this change, [except.spec] deals only with specifying the `noexcept` function decorator and its interaction with the `noexcept` operator, and contains no text regarding exceptions themselves.  It might be appropriate to move that subclause into the [dcl] structure at a future date.

[except.handle] group all paragraphs on searching for a handler

---

source/lex.tex

Comments should fit betweem character sets (to define the basic source character set) and preprocessor tokens, that must already understand comments in order to treat them as whitespace.

[lex.comment] Move the subclause earlier, to where it better fits

---

source/future.tex

Reorders the deprecated features annex to follow the order of the main clauses that the deprecates feature refers to. Where multiple clauses are references, use the one named by the [depr.XXX] stable label.

[depr] Reorder clauses by origin of deprecation

---

source/ranges.tex

..which was already there when it was declared.

[range.concat.iterator] Remove redundant \expos

---

source/lex.tex

This PR purely moves existing words around, and does not create any new content.
The proposed subclause ordering is now:
* 5 Lexical convensions
- 5.1 Separate translation
- 5.2 Phases of translation
- 5.3 Characters
- 5.3.1 Character sets
- 5.3.2 Universal character names
- 5.4 Comments
- 5.5 Preprocessing tokens
- 5.6 Header names
- 5.7 Preprocessing numbers
- 5.8 Operators and punctuators
- 5.9 Alternative tokens
- 5.10 Tokens
- 5.11 Identifiers
- 5.12 Keywords
- 5.13 Literals
- 5.13.1 Kinds of literals
- 5.13.2 ...

[lex] Reorder subclauses to better follow phases of translation

---

source/lex.tex

There exist 16 "a #include" in the draft, but only this one "an #include".

[lex.pptoken] Fix indefinitive article for consistency

---

source/algorithms.tex

The original note was incorrect and removed by #6157. But it turns out that _some_ note would still be helpful. This PR tries to find the right way to describe storage reusing and potential subsequent undefined behavior.
Fixes #6143.

[specialized.algorithms.general] Restore the note for potentially-overlapping objects and undefined behavior

---

source/lex.tex

The phases of translation use forward references to the rest of the standard well, but phases 3 and 4 almost entirely lack such crossreferences, despite doing significant work in the process of translating a file.

[lex.phases] Add crossreferences from phases 3 and 4

---

source/lib-intro.tex

In the Cpp17Allocator requirements, all identifiers name specific types, even if they are template instantiations.  Hence, all use of `typename`, `.template`, and `::template` is redundant.  Not in the sense of we are awaiting LWG to review P2150 for policy, but in the sense these have been redundant since C++11, and were outright ill-formed prior to that.
The majority of the wording throughout this subclause already (correctly) avoids use of these redundant keywords.  This PR brings the title rows into agreement with the body text, and fixes one outstanding redundant use of `::template`.

[allocator.requirements.general] Remove redundant template syntax

---

source/basic.tex

[intro.races] Clarify conflicts for the case where no bits are changed

---

source/basic.tex

This old paragraph defines two terms which aren't used anywhere else in the document. Maybe they have been used historically and someone forgot to remove them, or maybe they haven't ever been used.
On a personal note, I also have to say that I have never heard someone say *high-order bit* or *low-order bit*. The terminology *least significant* and *most significant* is much more popular in my experience, self-explanatory, and used in other places in the C++ standard.

[intro.memory] Remove stray bit definitions

---

source/basic.tex
source/xrefdelta.tex

The whole subclause [basic.stc.inherit] is a single sentence that belongs adjacent to the material in [basic.std.general] that specifies how entities acquire a storage duration, wheras all the remaining subclauses below [basic.stc] describe specific storage durations.  Folding that sentence directly into the general clause is even clearer.

[basic.stc.inherit] Dissolve paragraph into [basic.stc.general]

---

source/basic.tex

The lack of commas in [[basic.link] p4](https://eel.is/c++draft/basic.link#4) really had me stumped for a few minutes because I thought it should be read as:
```
The name of an entity that belongs to a
namespace scope that has not been given internal linkage above
and that is the name of ...
```
... when the intended reading is
```
The name of an entity
- that belongs to a namespace scope,
- that has not been given internal linkage above, and
- that is the name of ...
```
This PR adds an Oxford comma to make it immediately obvious which reading is intended.

[basic.link] Add oxford comma

---

source/utilities.tex

There exist 579 "behavior" in the draft, but only this one "behaviour".

[bit.cast] Rename "behaviour" to "behavior" for consistency

---

source/expressions.tex
source/iostreams.tex

In three places in the standard, we have the term "automatic variable".
This term is never defined and unconventional, but most likely means
> variable with automatic storage duration

[expr.prim.lambda.capture], [expr.const], [ostream.formatted.print] Clarify automatic variable

---

source/memory.tex

[ptr.align] Use math-font 'X' for the object

---

source/lex.tex
source/text.tex

"Derived Extracted Property" refers to the fact that the data for the `East_Asian_Width` property are extracted into the file [`DerivedEastAsianWidth.txt`]. It is not really a terminology.
[`DerivedEastAsianWidth.txt`]: https://www.unicode.org/Public/UCD/latest/ucd/extracted/DerivedEastAsianWidth.txt
[`EastAsianWidth.txt`]: https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt

[format.string.std] Replace "Derived Extracted Property" with simply "property"

---

source/numerics.tex

Fix for this bug: https://github.com/cplusplus/draft/issues/7371
redundant parenthesis in `MDS2::static_extent(r2));`
name mismatch in `in1_mat` -> `in_mat1`

[linalg.helpers.mandates] fix typos in linalg mandates section

---

source/threads.tex

This space is inconsistent with library style, and with the redeclaration of this member in [thread.lock.unique.obs].

[thread.lock.unique.general] Remove extraneous space in `operator bool ()`

---

source/iostreams.tex

To avoid confusion as in microsoft/STL#5088.

[fs.op.remove] clarify Returns element

---

source/overloading.tex

This currently renders as '*cv*`T`' (no space).

[over.ics.ref] Fix formatting of 'cv `T`'

---

source/exceptions.tex

While `std:terminate` was originally conceived as the way to report failures in the exception handling machinery, it has evolved to become a more general tool for reporting unrecoverable failures in the C++ runtime.  This rewording attempts to address that evolving design, and in doing so addresses the outstanding %FIXME% that the current text is not adequately descriptive in the first place.

[except.terminate] Better describe the  function `terminate`

---

source/config.tex
source/expressions.tex
source/intro.tex

This PR should show no difference in the rendered document, but will make it much easier to refactor the Core clauses in the future --- just as we can refactor Library clauses today.

[config.tex] Create and apply macros denoting first and last core chapters

---

source/declarations.tex

[dcl.link] p10 says: 
>Linkage from C++ to objects defined in other languages and to objects defined in C++ from other languages is implementation-defined and language-dependent[.](https://eel.is/c++draft/dcl.link#10.sentence-1)
Only where the object layout strategies of two language implementations are similar enough can such linkage be achieved[.](https://eel.is/c++draft/dcl.link#10.sentence-2)
The objects should be changed to entities, which includes both objects and functions for which the linkage is applied.
> Linkage from C++ to entities defined in other languages and to entities defined in C++ from other languages is implementation-defined and language-dependent.

[dcl.link] p10 objects vs. entities

---

source/numerics.tex
source/strings.tex

Related to https://github.com/cplusplus/draft/issues/5641.
In short, the C++ standard doesn't have a clearly-defined notion of "compile-time" or "run-time".
Instead of specifying that these type aliases have "compile-time complexity" (whatever that's supposed to mean) we can just leave the cell empty. No evaluation takes place here, so it's meaningless to talk about complexity.

[rand.req.seedeq], [rand.req.dist], [char.traits.require] Eliminate "compile-time" complexity

---

source/templates.tex

https://eel.is/c++draft/temp.pre#7 was normative wording that was converted into a note by [P1787R6](https://wg21.link/p1787r6). The first half of it reads:
> A template cannot have the same name as any other name bound in the same scope ([[basic.scope.scope]](https://eel.is/c++draft/basic.scope.scope)), except that a function template can share a name with non-template functions ([[dcl.fct]](https://eel.is/c++draft/dcl.fct)) and/or function templates ([[temp.over]](https://eel.is/c++draft/temp.over))[.](https://eel.is/c++draft/temp.pre#7.sentence-1)
I think it refers to wording about which declarations correspond (and consequently might conflict, rendering the program ill-formed), but it only reflects [[basic.scope.scope]/4.3](https://eel.is/c++draft/basic.scope#scope-4.3). The problem …

[temp.pre] Fix note about uniqueness of a template name in a scope

---

source/lex.tex

The footnote better belongs in the main text as a regular note.                 
To make the notes flow consistently, switch the order of the                    
note and normative text in the first paragraph to lead with the                  
normative text.

[lex.header] Modernize text around header names

---

source/exceptions.tex
source/lex.tex

There are two grammar entries that end with a trailing `\br` in their specification.  This trailing linebreak does not seem to be intended, showing up only as a wider spacing between adjecent grammars --- most notably in Annex A where otherwise non-adject grammars pick up neighbours.

[lex.ccon][except.spec] Remove trailing linebreak from grammar

---

source/declarations.tex

This PR is related to the **Issue** #7453 proposing multiple changes to clarify the text in [dcl.spec.auto.general]
However, a PR has been created for each specific change.
In **[dcl.spec.auto.general]-p2**, the verbal form
_The type of a parameter-declaration of a function declaration, lambda-expression, or template-
parameter ..._
may be ambiguous in the sense that it may be interpreted both as the type of any of three things (incorrect) or the type of a parameter of any of three things (correct).
In a discussion on _std-discussion_, it was highlighted that the former interpretation does not make sense as a lambda expression has never an explicit type, however it was still agreed that the verbal syntax should be improved (https://lists.isocpp.org/std-discussion/2024/11/2724.php).

Avoid incorrect sentence parsing option on types

---

source/ranges.tex

This is consistent with "`range` type" elsewhere.

[range.sized] Add \libconcept for range

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/expressions.tex
source/intro.tex
source/lex.tex
source/modules.tex
source/overloading.tex
source/preprocessor.tex
source/templates.tex

Fixes #7405.
Notes:
* CWG1965: fixed by CWG2879
* CWG2933: change to [basic.fundamental] applied instead to [basic.compound]
Fixes cplusplus/CWG#621
Fixes cplusplus/CWG#526
Fixes cplusplus/CWG#342
Fixes cplusplus/CWG#232
Fixes cplusplus/CWG#536
Fixes cplusplus/CWG#548
Fixes cplusplus/CWG#554
Fixes cplusplus/CWG#550
Fixes cplusplus/CWG#215
Fixes cplusplus/CWG#561
Fixes cplusplus/CWG#562
Fixes cplusplus/CWG#576
Fixes cplusplus/CWG#578
Fixes cplusplus/CWG#595
Fixes cplusplus/CWG#600
Fixes cplusplus/CWG#615
Fixes cplusplus/CWG#617
Fixes cplusplus/CWG#626
Fixes #7051

[2024-11 CWG 1] P3524R0 Core "ready" Issues

---

source/basic.tex
source/declarations.tex
source/expressions.tex
source/templates.tex

- Merge the change to [temp.arg.nontype] with existing text.
Fixes #7407 
Fixes cplusplus/papers#1351

P2686R5 constexpr structured bindings and references to constexpr variables

---

source/basic.tex
source/classes.tex
source/containers.tex
source/future.tex
source/meta.tex
source/strings.tex
source/support.tex

Fixes #7409
Fixes cplusplus/papers#1889

P3247R2 Deprecate the notion of trivial types

---

source/compatibility.tex
source/expressions.tex
source/future.tex
source/xrefdelta.tex

P2865R6 Remove Deprecated Array Comparisons from C++26
Fixes #7410
Fixes cplusplus/papers#1555

P2865R6 Remove Deprecated Array Comparisons from C++26

---

source/declarations.tex
source/expressions.tex
source/preprocessor.tex
source/templates.tex

- Replace digits with numeral words in comment in example.
Fixes #7411 
Also fixes cplusplus/papers#294

P1061R10 Structured Bindings can introduce a Pack

---

source/declarations.tex
source/future.tex

Fixes https://github.com/cplusplus/draft/issues/7412
Fixes https://github.com/cplusplus/papers/issues/1839

[2024-11 CWG Motion 8] P3176R1 The Oxford variadic comma

---

source/algorithms.tex
source/containers.tex
source/iostreams.tex
source/iterators.tex
source/memory.tex
source/meta.tex
source/numerics.tex
source/ranges.tex
source/strings.tex
source/support.tex
source/text.tex
source/threads.tex
source/time.tex
source/utilities.tex

Fixes #7413.
Notes: I assumed the Tentatively Ready issues were to be applied also.
Also fixes cplusplus/papers#1983

[LWG 1] P3504R0 C++ Standard Library Ready Issues

---

source/algorithms.tex
source/iterators.tex
source/lib-intro.tex

- Renamed [niebloid] section label [alg.func.obj].
Fixes #7414 
Also fixes cplusplus/papers#1790

P3136R1 Retiring niebloids

---

source/ranges.tex
source/support.tex

Fixes #7415 
Also fixes cplusplus/papers#1792

P3138R5 views::cache_latest

---

source/support.tex
source/utilities.tex

Fixes #7416 
Also fixes cplusplus/papers#2036

P3379R0 Constrain std::expected equality operators

---

source/text.tex

Fixes #7418 
Also fixes cplusplus/papers#1521

P2862R1 text_encoding::name() should never return null values

---

source/containers.tex
source/memory.tex
source/support.tex

Fixes #7419 
Also fixes cplusplus/papers#1568

P2897R7 aligned_accessor: An mdspan accessor expressing pointer over-alignment

---

source/containers.tex
source/support.tex

Fixes https://github.com/cplusplus/papers/issues/2011.
Fixes #7420.

P3355R1 Fix submdspan for C++26

---

source/numerics.tex
source/support.tex

Fixes https://github.com/cplusplus/papers/issues/1870.
Fixes #7421.

P3222R0 Fix C++26 by adding transposed special cases for P2642 layouts

---

source/numerics.tex
source/support.tex

Fixes https://github.com/cplusplus/papers/issues/1719.
Fixes #7422.

P3050R2 Fix C++26 by optimizing linalg::conjugated for noncomplex value types

---

source/exec.tex

- Replace 'one of' with 'either'.
- Replace 'Where' with more appropriate phrasing.
Fixes #7423 
Also fixes cplusplus/papers#2048

P3396R1 std::execution wording fixes

---

source/algorithms.tex
source/memory.tex
source/support.tex

Fixes #7426 
Also fixes cplusplus/papers#2026
Also fixes cplusplus/papers#2141

P3508R0 and P3369R0 constexpr for specialized memory algorithms

---

source/lib-intro.tex
source/numerics.tex
source/support.tex
source/utilities.tex

Fixes #7427
Also fixes cplusplus/papers#2027

P3370R1 Add new library headers from C23

---

source/support.tex
source/threads.tex

Note: Based on the changes for motion 13 to avoid copious not-quite-conflicts.  Please rebase before applying!
Fixes #7428 
Also fixes cplusplus/papers#1960

P3309R3 constexpr atomic<T> and atomic_ref<T>

---

source/compatibility.tex
source/lib-intro.tex
source/numerics.tex
source/support.tex

* Add closing parenthesis in [simd.reductions] p3.
* Add namespace std to `simd_flags`, `basic_simd`, and `basic_simd_mask`
* Add comma after 'e.g.'
* Add `\rSec3[simd.expos.defn]{Exposition-only helpers}` (missing sibling)
* Remove `\iref` from simd.expos.abi] (5.3), already in (5.2)
Fixes #7430
Fixes cplusplus/papers#670

[2024-11 LWG Motion 18] P1928R15 std::simd — merge data-parallel types from the Parallelism TS 2

---

source/exec.tex

Fixes #7431 
Also fixes cplusplus/papers#1986

P3325R5 A Utility for Creating Execution Environments

---

source/text.tex

This sentence comes from [LWG 379](https://cplusplus.github.io/LWG/issue379), but it seems that there's a mistake when applying the proposed resolution to the draft standard: the proposed resolution says "For any named ctype category with a ctype&lt;char> facet ctc", but the draft standard says "For any named ctype category with a ctype<char<ins>***T***</ins>> facet ctc".

[locale.ctype.virtuals] Fix a decade-old typo

---

source/exceptions.tex

[except.spec] Remove misleading restriction in list of examples

---

source/lex.tex

As suggested by Jens Maurer.  The first sentence refers to "tokens" that do not exist until after the second sentence.  Rather than change normaitve meaning by referring to the extant "preprocessing tokens" is seems best to preserve the clear intent, and simply reverse their order.

[lex.phases] Reorder the first two sentences of phase 7

---

source/classes.tex

Paragraph 1 already states:
https://github.com/cplusplus/draft/blob/1c22d62180901069128b21daa2773d40566bd983/source/classes.tex#L2347-L2353
The reader has no reason to believe that a copy/move constructor is excluded from the rule, and it certainly doesn't need to be stated in normative wording. The whole paragraph can and should be a note.

[class.conv.ctor] Turn last paragraph into a note

---

source/containers.tex

Also changes `key_equiv` to _`key-equiv`_.
I think it's OK to keep the member `comp` of `key_equiv` not marked `\exposid`, since the identifier `comp` is already reserved by `priority_queue::comp`. Implementations can use the name `comp` as-is or use another name.
`key_equiv` and `value_compare`'s exposition-only constructors are less than ideal to me. But I think they should be handled in an LWG issue because additional copy of comparator seems to be observable. Edit: now this is LWG3959.
Follows up #5914. Fixes #5812. Fixes #7380.

[flat.map, flat.multimap, flat.set, flat.multiset] Exposition-only formatting for `c`, `comp`, `compare`, and `key-equiv`

---

source/preprocessor.tex

Most references to tokens in [cpp] correctly refer to preprocessing tokens that a materially different thng to a regular token.  This commit addresses the last few places referring to a plain token where they should instead be referring to a preprocessing token. The remining usage of plain token where evaludating the predicate to  directives is intentional, and trying to change to a preproccessing token would be an actual error.

[cpp] Correctly identify preprocessor tokens vs, tokens

---

source/basic.tex

This PR cleans up a few wording discrepancies in the introduction to compound types:
1. We don't like to say that "functions return references". Any such case would mean that the function is declared with reference return type, but the reference would be transformed into an lvalue or xvalue designating the object upon the call. If we just say "a result", we keep it vague and correct.
2. The list of what classes contain tries to be exhaustive without much benefit. We can just say that classes contain class members, which does not miss many things not listed here, such as `static_assert`, `template`, etc.

[basic.compound] Update introduction

---

source/numerics.tex

This avoids reusing `T` which is also used for the type of the subexpression E.
Fixes #7494

[linalg.helpers] Rename template parameter for poison pills

---

source/containers.tex

Naming `from_range_t` is a bit weird, we should use the `from_range` variable directly. This is consistent with other parts of the standard.

[flat.map.defn, flat.set.defn] Avoid naming the `from_range_t` tag

---

source/back.tex

Fix spelling and formatting in bibliography.
These fixes were separated from PR #7504 per [reviewer request](https://github.com/cplusplus/draft/pull/7504#discussion_r1892801089).

Bibliography formatting fixes

---

source/back.tex
source/numerics.tex

Add SIMD acronym explanation and bibliography entry

---

source/compatibility.tex

- Correct \effect to \change.
- Add period at end.
- Add \tcode for swap.

[diff.cpp03.library] Correct \effect to \change

---

source/compatibility.tex
source/future.tex
source/numerics.tex
source/utilities.tex
tools/check-output.sh

Also add a check to prevent future oversights.

[stdckdint.h.syn,stdbit.h.syn] Add proper indexing for header definition

---

source/iostreams.tex

There exist 3 (exceptions() & badbit) in this draft, but only this one (exceptions()&badbit).

[ostream.formatted.reqmts] Insert space around & for consistency

---

source/support.tex

As far as I can tell, these are the last macro definitions that are missing from the index of library names.

[cstdint.syn] Index <cstdint> macros

---

source/utilities.tex

This fixes obviously invalid syntax in the definition of `bad_expected_access<void>` class specialization
```c++
bad_expected_access& operator=(const bad_expected_access& noexcept);
```

[expected.bad.void] Editorial fix - syntax error in `bad_expected_access<void>`

---

source/future.tex
source/support.tex

The \indexhdr macro is subsumed by more appropriate macros in the same area.  These are the last two uses of the \indexhdr macro that have not been similarly subsumed.

[stdbool.h.syn][depr.c.macros] Remove redundant macros

---

source/expressions.tex

P2686R5 (applied by commit e220906b71df01f09fe60921e8fac39b80558f78) accidentally reverted a change considering erroneous values made by P2795R5.
Fixes cplusplus/CWG#662

[expr.const] Properly merge P2686R5

---

source/utilities.tex

tuple_size is defined as a struct, so defaults to public inheritance.  Every similar type trait leans into this implicit default-to-public, and tuple_size is the only outlier.

[tuple.helper] Remove redundant public before base class

---

source/exec.tex

the definitions of `valid-completions-for` and `has-completions` should be marked as exposition-only.

[editorial]: in [exec.recv.concepts] mark exposition-only concepts as such

---

source/exec.tex

`apply_sender` is the name of a customization point object. it should appear in code font.

[editorial]: put `apply_sender` in code font in [exec.sync.wait]

---

source/exec.tex

wrap `transformed-sndr` in `\exposid{...}`.

[editorial]: in [exec.snd.transform] put exposition-only `transformed-sndr` in italics

---

source/future.tex
source/lex.tex

[lex.icon,depr.locale.category] Remove duplicate 'table' in front of table references

---

source/text.tex

C99 defines two modifiers for `strftime`, namely `'E'` and `'O'`.

[locale.time.put.members] Remove outdated footnote

---

source/exec.tex

this makes the id link to the concept definition

change \exposid to \exposconcept for the concept valid-specializations

---

source/exec.tex

SCHED-ENV is an exposition-only pseudo-macro

Make SCHED-ENV an exposid in [exec.let]

---

source/support.tex

The standard is not a tutorial.

[type.info] Remove comments explaining deleted members

---

source/expressions.tex

#7468 accidently reverted the resolution of CWG2909 (applied in commit 317160060b890edeaeb931366f5ae04680c87084). I think we should editorially re-apply it.
Fixes #7581.

[expr.const] Re-apply CWG2909

---

source/compatibility.tex
source/lex.tex

Since C++23 we no longer have physical source files, but rather input files.  Update the two implementation-defined references to the mapping from input file to translation character set using the same phrasing so that they provide the same entry in the index of implementation-defined behavior, just as they did in C++20, before getting out of sync when the terminology changed.

[lex.phases] Update implementation defined text

---

source/numerics.tex

This was the wording requested by LWG and approved in P3050R3, but I mistakenly put P3050R2 in the straw polls.

[linalg.conj.conjugated] Rearrange to match P3050R3

---

source/templates.tex

Modify LaTeX code from `\terminal{\opt{...}}` form into standard `\opt{\terminal{...}}`
This is the only occurrence of the unusual ordering in the repository

[temp.res.general] Clean up LaTeX

---

source/ranges.tex

replaces incorrect uses of "which" with "that" in the specification of `enable_view`. it should be possible to drop a phrase introduced with "which" without changing the meaning of the sentence. if the phrase is essential to the point, "that" is more correct.
(this is a pet peeve of mine.)

[editorial] ranges "which" hunt

---

source/iostreams.tex

Apparently I added this in f325daf919ffebf58fb9b133db79f4c60ce64034 - maybe because the original HTML source of the TS had separate `<code>` tags here and I scripted the conversion. There doesn't seem to be any reason for it to be this way.

[fs.rec.dir.itr.members] Merge adjacent \tcode commands

---

source/templates.tex

The example is inconsistent with [[temp.inst] p3](https://wg21.link/temp.spec#temp.inst-3), which states the following: 
> The implicit instantiation of a class template specialization causes
> - the implicit instantiation of the declarations, but not of the definitions, of [...] scoped member enumerations [...]; and
> - the implicit instantiation of the definitions of [...] unscoped member enumerations [...]
Hence, the example can be fixed by either (1) omitting the instantiation or (2) by replacing the unscoped with a scoped enumeration. Since the implicit instantiation does not contribute to the point of [[temp.mem.enum]](https://wg21.link/temp.mem.enum), the inconsistency can be solved most easily with alternative (1).
The example was taken exactly as is from …

[temp.mem.enum] Fix consistency of example with [temp.inst] (editorial)

---

source/lex.tex

Prior to converting preprocessing tokens to tokens in phase 7, all tokens are strictly preprocessing tokens.  Add the missing qualification is appropriate through the phases of translation up to that point of conversion.

[lex.phases] Use preprocessing token consistently

---

source/basic.tex
source/compatibility.tex
source/declarations.tex
source/expressions.tex
source/lex.tex
source/meta.tex
source/numerics.tex
source/overloading.tex
source/templates.tex

As previously discussed by CWG.
The aim is to editorially adopt some of the wording changes made in P2841R5 to ease its review in core.
Note that not all-instance of non-type have been
mechanically replaced as [dcl] and [diff] use
the term to refer to anything that is not a type
in the context of lookup

Rename non-type template parameter/argument to "constant"

---

source/numerics.tex

There is no ordering dependency between the two typedefs in namespace std, the macros that follow, and teh next opening of namespace std, so move the two typedefs to avoid repeatedly opening an closing the namespace.
Note that we could have done this without moving
the typedefs as macros are not bound by namespaces, but our convention very sensibly avoids confusing
readers by keeping macro definitions outside of
namespaces.

[cmath.syn] Consolidate std namespaces

---

source/threads.tex

By using more conventional "value-initializes".
Fixes #7522.

[util.smartptr.atomic.{shared,weak}] Fix wording for initialization

---

source/iostreams.tex

As per the Specification Style Guidelines.
https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines#describing-function-calls

[fs.op.funcs] Remove empty parens when referring to functions by name

---

source/exceptions.tex
source/support.tex
source/xrefdelta.tex

Several concurrent fixes.  First include the normative wording that 'uncaught_exceptions' returns the number of uncaught exceptions *on the current thread*.  This wording is present in the core language.
Then move the core wording for when an exception is uncaught directly into the text that talks about caught and uncaught exceptions.  In the process, turn the reference to into a note, so that there is only one normative specification.
Finally, remove [except.uncaught] as it is now empty, and add the missing descriptive sentence to the intro paragraph of [except.special.general].  This happens to produce quite a pleasing page-break, but that is just luck, not design.

[except.uncaught] Tidy the specification for uncaught exceptions

---

source/xrefdelta.tex

Several entries in the restored larger delta referred to stable labels that has since moved again, or been removed.  This commit updates their cross-reference accordingly, or marks them as removed if appropriate.
The new cross-reference, or removal, was performed by confirming the difference against the C++17 standard, rather than assuming each forwarding link was still valid.

[xrefdelta] Consolidate restored entries

---

source/classes.tex
source/overloading.tex

Fixes #7652
Also fixes cplusplus/papers#2179

[2025-02 CWG Motion 2] P3542R0 Abolish the term "converting constructor"

---

.github/workflows/check.yml

The MacOS runner (in all versions, 13, 14, 15) is currently broken, and we need to investigate. The various errors don't look familiar, but _could_ be related to the bad `extract` package.
(Insights from anyone with a Mac would be welcome!)

Update Ubuntu version, disable MacOS runner

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/diagnostics.tex
source/exceptions.tex
source/expressions.tex
source/intro.tex
source/lex.tex
source/lib-intro.tex
source/macros.tex
source/overloading.tex
source/preprocessor.tex
source/statements.tex
source/support.tex
source/templates.tex

Fixes: https://github.com/cplusplus/draft/issues/7655
Also Fixes: https://github.com/cplusplus/papers/issues/1648
I have put comments in starting with JMB (my initials) where an editorial change was made due to minor mistakes in P2900 (missing comma, rebasing, etc.)   as well as some places where I think we should have additional xrefs.
This is also based on the changes for P1494 (https://github.com/cplusplus/draft/pull/7681)  as we modify a paragraph added there.  That should certainly merge first, and I will keep this PR rebased on it.

[2025-02 CWG Motion 5] P2900R14 - Contracts for C++

---

source/basic.tex
source/compatibility.tex
source/declarations.tex
source/future.tex
source/preprocessor.tex
source/threads.tex
source/xrefdelta.tex

Fixes #7656 
Also fixes cplusplus/papers#2129

[2025-02 CWG Motion 6] P3475R2 Defang and deprecate memory_order::consume

---

source/basic.tex
source/declarations.tex
source/preprocessor.tex
source/templates.tex

[temp.param], [temp.arg.type] Some instructions do not apply due to more recent changes in the wording.
[temp.param] Added a reference for concept-dependent to where it's defined. [temp.constr.concept] Replace "may" with "might" inside note.
Fixes #7657.
Also fixes cplusplus/papers#1546
Notes:
* I had several issues with some of the wording - see embedded FIXMEs.
* It wasn't clear whether \tcode or math font should be used when formatting some of the invented variables as both appear to be used inconsistently.

P2841R7 Concept and variable-template template-parameters

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/expressions.tex
source/lex.tex
source/lib-intro.tex
source/memory.tex
source/meta.tex
source/preprocessor.tex
source/support.tex

Fixes https://github.com/cplusplus/draft/issues/7658.
Also fixes https://github.com/cplusplus/papers/issues/1463
Added freestanding to the lib feature-test macro, as all new parts are marked as freestanding.
Picked the most appropriate location within the type traits spec for each of the three new traits.

[2025-02 CWG Motion 8] P2786R13 Trivial Relocation

---

source/preprocessor.tex

Fixes https://github.com/cplusplus/draft/issues/7659.
Also fixes https://github.com/cplusplus/papers/issues/700.
Redistributed grammar around the preamble to better maintain a locality and flow.  More redistrubution expected in a follow-up commit.
Minor grammar tweak: "other than a" -> "except:"
following the model of such specifications in
basic-s-char and elsewhere.
Attempted to describe all implementation-defined
topics for the index, but will need review.

[2025-02 CWG Motion 9] P1967R14 `#embed`

---

source/algorithms.tex
source/containers.tex
source/exec.tex
source/lib-intro.tex
source/numerics.tex
source/ranges.tex
source/support.tex
source/text.tex
source/threads.tex

[2025-02 LWG 1] P3615R0 C++ Standard Library Ready Issues

---

source/ranges.tex
source/support.tex

Fixes #7662
Also fixes cplusplus/papers#1791

[2025-02 LWG Motion 3] P3137R3 views::to_input

---

source/iterators.tex

Fixes #7664.
Also fixes cplusplus/papers#2067

P3349R1 Converting contiguous iterators to pointers

---

source/containers.tex
source/support.tex

- Also apply "constexpr" to list::emplace in [list.overview]
- Fix bad placement of 'constexpr' before template-head in [stack.cons]
Fixes #7665
Also fixes cplusplus/papers#2029

P3372R3 constexpr containers and adaptors

---

source/diagnostics.tex
source/support.tex
source/text.tex
source/utilities.tex

Fixes https://github.com/cplusplus/draft/issues/7666.
Fixes https://github.com/cplusplus/papers/issues/2071.

P3378R2 constexpr exception types

---

source/numerics.tex

Fixes #7667 
Also fixes https://github.com/cplusplus/papers/issues/2105

[2025-02 LWG Motion 8] P3441R2 Rename simd_split to simd_chunk

---

source/numerics.tex
source/support.tex

Fixes #7672
Also fixes https://github.com/cplusplus/papers/issues/1622

[2025-02 LWG Motion 13] P2933R4 Extend <bit> header function with overloads for std::simd

---

source/numerics.tex

Fixes #7668
Also fixes https://github.com/cplusplus/papers/issues/1940

[2025-02 LWG Motion 9] P3287R3 Exploration of namespaces for std::simd

---

source/algorithms.tex
source/exec.tex
source/lib-intro.tex
source/memory.tex
source/numerics.tex
source/support.tex

Fixes https://github.com/cplusplus/draft/issues/7669.
Fixes https://github.com/cplusplus/papers/issues/1644.

P2976R1 Freestanding Library: algorithm, numeric, and random

---

source/numerics.tex

Fixes #7670
Also fixes https://github.com/cplusplus/papers/issues/2097

[2025-02 LWG Motion 11] P3430R3 simd issues: explicit, unsequenced, identity-element position, and members of disabled simd

---

source/containers.tex
source/ranges.tex
source/support.tex

[2025-02 LWG 14] P2846R6 reserve_hint: Eagerly reserving memory for not-quite-sized lazy ranges

---

source/containers.tex
source/intro.tex
source/lib-intro.tex
source/macros.tex
source/numerics.tex
source/strings.tex
source/support.tex
source/utilities.tex

Fixes https://github.com/cplusplus/draft/issues/7674.
Fixes https://github.com/cplusplus/papers/issues/2125.

P3471R4 Standard library hardening

---

source/compatibility.tex
source/containers.tex
source/lib-intro.tex
source/support.tex

Fixes #7675
Also fixes cplusplus/papers#328

[2025-02 LWG Motion 16] P0447R28 Introduction of std::hive to the standard library

---

source/memory.tex
source/support.tex

[indirect][polymorphic] Fixed minor inconsistencies and obvious errors. 
[indirect.hash] Remove awkward "then".
Fixes #7676.
Had some issues with the wording - see embedded FIXMEs.

P3019R14 indirect and polymorphic: Vocabulary Types for Composite Class Design

---

source/basic.tex

The definition of literal type is the only place where "non-static non-variant data member" is used as opposed to "non-variant non-static data member".
Change to use the canonical ordering.

[basic.types.general] Change ordering to "non-variant non-static"

---

source/support.tex

The cross-reference to [class.mem] was referring to a hanging paragraph that was fixed by 2850139be6285ba10a64fb718125a80ca967c631 so we should be referring to [class.mem.general] now.

[support.srcloc.cons] Update xref to [class.mem.general]

---

source/expressions.tex

Fixes #5422.
The remain issue (modulo CWG2558) is that we shouldn't imply a prvalue is an object, which is not true since C++17.

[expr.const] Check the result object of a prvalue

---

source/lex.tex

[lex.string] Clarify size of string-literal

---

source/diagnostics.tex

Follow-up to https://github.com/cplusplus/draft/pull/6681 (P2546R5) from thread beginning with edit/2023/11/0870.
- The notes in the paper make statements of fact about behaviour that, normatively, is implementation-defined. These should instead be statements of intent.
- The description of `breakpoint` assumes that a debugger is present (and should instead cover both cases).
- The odd restriction on how the debugger resumes execution of the program needs elaboration.
- The description of the implementation strategy of `is_debugger_present` for POSIX makes assumptions that are more appropriate for the LSB.
- The terminology used in the LSB is "tracing process", not "tracer parent process".
- The note in `is_debugger_present` implies the wrong trade-off when it is unknown whether a …

Follow-up to P2546, "Debugging Support"

---

source/iostreams.tex

`@` should be in blocks but not [ifstream.members]/1. Fixes a mis-addition in #7208.

[ifstream.members] Remove mistakenly added `@`

---

source/utilities.tex

Replace its usages with `is_invocable_r_v` and remove an unnecessary index. Fixes #6582.

[func.wrap.func] Drop Lvalue-Callable

---

source/algorithms.tex
source/containers.tex
source/strings.tex
source/text.tex

Currently, there are several cases where `\tcode{[i, j)}` is used for specifying left-closed right-open intervals, where `\range{i}{j}` is proper.

[containers, strings, algorithms, re] Use `\range` where appropriate

---

source/expressions.tex

`\cv \tcode{std::nullptr_t}` produces roughly "*cv*`std::nullptr_t`" with no space in-between. This PR adds a non-breaking space.

[expr.const] Add non-breaking space after `\cv`

---

source/lex.tex

It is better to specify them in this order so that the alternative representation is directly underneath the primary representation.
Currently, `<:` is underneath `{` and `<%` is underneath `[`, which is "the wrong way around".

[lex.digraph] Swap alternative token representations in table

---

source/preprocessor.tex

“Implementation-resource-width” should be a regular term like “ implementation-resource-count”.

[cpp.embed.gen] “Implementation-resource-width” should not be a grammar term

---

source/threads.tex

These were removed in error in the application of P2300R10.

[stopsource.general] Restore accidentally deleted members in class definition

---

source/algorithms.tex

This makes them consistent with all other parallel algorithms.

[alg.copy], [alg.move] Rename ExecutionPolicy parameters

---

source/iostreams.tex

These blocks are used for showing of directory hierarchy but not code, so we should use `outputblock`.

[fs.op.copy] Replace non-`codeblock`s with `outputblock`s

---

source/expressions.tex

This change is in part by P3421R1 discussion in CWG at Hagenberg.
If accepted, "constexpr destructor" and "`constexpr` destructor" no longer mean the same, and referencing the formal term may be helpful.

[expr.const] Forward-reference [dcl.constexpr] for "constexpr destructor"

---

source/ranges.tex

This is an unfortunate application of P2846R6.
Fixes #7769

[range.approximately.sized] Move to before [range.sized]

---

source/preprocessor.tex

The incoming paper did not explicitly specify their placement, but they are clearly meant to be defined unconditionally.

[cpp.predefined] Place the __STDC_EMBED macros in the unconditionally defined paragraph

---

source/templates.tex

This part of the wording is redundant with the first bullet of this list.
There's still an outstanding issue here that the *concept-tt-parameter* production lacks a *template-head*.

[temp.over.link] Remove redundant wording

---

source/containers.tex

The code is too long and has been truncated, so it would be better to put it on its own line.

[list.erasure, list.erasure] Separate code into another line for better formatting

---

source/memory.tex

[PR#7708](https://github.com/cplusplus/draft/pull/7708) used `\oldconceptname` for the old requirements, `\oldconcept` should be used instead.

[mem.composite.types] Replace \oldconceptname with \oldconcept

---

source/memory.tex

[polymorphic.general] paragraph 3 has a broken expression `allocator_traits<Allocator>::cop, args...)`. It should be the same expression used in [indirect.general].

[polymorphic.general] Fix paragraph 3

---

source/memory.tex

[polymorphic.asgn] p5 says:
> _Mandates:_ If `allocator_traits<Allocator>::is_always_equal::value>` is `false`, `T` is a complete type.
There is a superfluous greater-than sign following `value`.

[polymorphic.asgn] Remove a superfluous greater-than sign

---

source/containers.tex

Function declarations have noexcept, so this should be a typo.

[mdspan.layout.left.obs] Add missing noexcept

---

source/containers.tex

[vector.modifiers] p3 says:
> For the declarations taking a pair of `InputIterator`, performs at most one reallocation if `InputIterator` models _Cpp17ForwardIterator_.
“Model” should not be used on old _Cpp17XXX_ concepts, “meet the requirements of” should be used instead.
[vector.cons] p10 is also updated for consistency.

[vector.modifiers] Old concepts cannot be “modeled”

---

source/iterators.tex

P2538R1 made `projected` an alias template and removed the `incrementable_traits<projected>` partial specialization, so the synopsis should be correspondingly updated.
Fixes #7837.

[iterator.synopsis] Apply changes of P2538R1 to the synopsis of `<iterator>`

---

source/utilities.tex

`ignore-type`'s `operator=` is currently specified as
```cpp
constexpr const ignore-type operator=(const auto &) const noexcept { return *this; }
```
this should instead return `const ignore-type&`. 
@Eisenwave noted [P2968R2](https://wg21.link/p2968r2) specifies `ignore-type` as
```diff
+// ignore
+struct ignore-type { // exposition only
+  constexpr const ignore-type&
+    operator=(const auto &) const noexcept
+      { return *this; }
+};
+inline constexpr ignore-type ignore;
// 22.4.5, tuple creation functions
-inline constexpr unspecified ignore;
```
however, https://github.com/cplusplus/draft/pull/7109 drops the reference qualification on `ignore-type::operator=`'s return type. Therefore I believe this is an editorial issue.

[tuple.syn] fix ignore-type::operator= return type

---

source/classes.tex
source/ub.tex

This references undefined behavior specified elsewhere; it does not specify additional undefined behavior.

Remove incorrect class.union.assignment.not.start.lifetime

---

source/containers.tex

[container.adaptors] Avoid naming `sorted_{equivalent,unique}_t` tag parameters

---

source/containers.tex

Associative containers possibly containing multiple elements for each key are said to support “equivalent keys”, but there is one place in [containers] that uses the term “multiple keys”. We should eliminate that.

 [associative.reqmts.general] Eliminate the final usage of “multiple keys”

---

source/containers.tex

The missing `constexpr` looks like a typo, because it's present in the overview; and every other method is constexpr.

[mdspan.layout.right.obs] Add missing constexpr to required_span_size.

---

source/algorithms.tex

Adds missed corresponding editorial changes in [algorithm.syn] for P3217R0 (which updated `ranges::find_last`).
Fixes #7802.

[algorithm.syn] Fix-up synopsis for `ranges::find_last`

---

source/iostreams.tex

In #4335 this change was done for [stringbuf.cons] but these cases were missed.

[stringbuf.members], [ostringstream.cons], [stringstream.cons] spaces

---

source/text.tex

There's nothing named `loc` in this context. Apparently `fill` should be passed instead.

[locale.money.put.members] Fix typo

---

source/numerics.tex

This PR simply adds some commas after conditional phrases/clauses.
As a drive-by fix, the semantic line breaks are also improved a little bit.

[simd.creation] Add commas

---

source/iterators.tex

Looks like that P2538R1 forgot changing the description.

[projected] `projected` is now an alias template

---

source/lib-intro.tex

#7706 mistakenly listed the header for `is_execution_policy(_v)` as `<execpol>`. The correct header is `<execution>`.

[tab:headers.cpp.fs] Fix header name for `is_execution_policy(_v)`

---

source/containers.tex

[container.requirements] Simplify Returns specification for try_emplace

---

source/memory.tex

[indirect.asgn] p4 says:
> If an exception is thrown during the call to `T`’s copy assignment, the state of its **contained value** is as defined by the exception safety guarantee of `T`’s copy assignment.
The wording is copied from the description of the copy assignment operator of `std::optional`, which has a contained value (defined in [optional.optional.general] p1). For `std::indirect`, there is no “contained value”, “owned object” should be used instead.

 [indirect.asgn] std::indirect does not have a “contained value”

---

source/strings.tex

Makes exposition-only data members _`data_`_ and _`size_`_ of `basic_string_view` shown in italic style.

[string.view] Exposition-only formatting for `data_` and `size_`

---

source/time.tex

The resolution of [LWG 4124](https://open-std.org/jtc1/sc22/wg21/docs/papers/2024/p3504r0.html#4124) added an exception rule for “omitting _chrono-specs_”, therefore [time.format] p7 should begin with “unless otherwise specified” to avoid conflicts.
This PR also added two missing commas in [time.format].

[time.format] A minor update for LWG 4124

---

tools/check-output.sh

Setting `LC_ALL` propagates locale settings on MacOS, whereas `LANG` does not.

[check] Set locale properly

---

source/intro.tex

and
- don't say the static type of a pointer, because the difference between static and dynamic types is only present for glvalues of class types;
- say that the `B*` pointer is pointing to a `B` base class subobject, which avoids involving problematic cases of `reinterpret_cast` or `static_cast` from _cv_ `void*` (see [[expr.static.cast]/14](https://eel.is/c++draft/expr.static.cast#14)).
Fixes #5762.
Fixes cplusplus/CWG#257.

[defns.dynamic.type] Say "most derived object" in the example

---

source/numerics.tex

The difference between between "the `complex` template" and "the template named `complex`" (which including program-defined specializations) is obscure. It seems better to cleary say that [complex.numbers.general] only covers the primary template.
Fixes #7270.

[complex.numbers.general] Clarify that the template is primary

---

source/algorithms.tex

In order to make `is_execution_policy` satisfity the requirements, an implementation should determine the base class (which is either `true_type` or `false_type`) for each specialization, but not add things into the `{}`.
This PR makes the intent clearer.

[execpol.type] Drop "see below" from `is_execution_policy`

---

source/containers.tex

> In the synopsis [inplace.vector.overview], reserve() and shrink_to_fit() are under size/capacity, but their actual descriptions are in [inplace.vector.modifiers], not [inplace.vector.capacity].
And the English title of [inplace.vector.capacity] doesn't quite match [vector.capacity], either. I think this is editorial and easy to patch.

[inplace.vector] Move reserve+shrink_to_fit from #modifiers to #capacity

---

source/compatibility.tex

The 'Strings' clause was moved before the new 'Text processing' clause, so it's now after the 'Containers' clause. The order of the [diff.cpp23] subclauses should reflect that.

[diff.cpp23.strings] Move Clause 27 changes after Clause 23 changes

---

source/basic.tex
source/classes.tex
source/expressions.tex
source/ub.tex

This PR breaks up some `\ubdef` entries in the UB annex into multiple, more granular entries, for those cases of UB where there is value in distinguishing them. This PR makes the list of UB in the `ub-ifndr` branch identical to the list of UB provided in Appendix A of [P3100R2](https://wg21.link/p3100r2).

[ub] a few more fixes

---

source/algorithms.tex
source/exec.tex
source/meta.tex
source/utilities.tex

And `\vdots` in [[exec.snd.expos]](https://eel.is/c++draft/exec.snd.expos#17).
A `\linebreak` was added in [[numerics.defns]](https://eel.is/c++draft/numerics.defns#2) to avoid an overfull `\hbox`.

Use `\dotsc` in more places

---

source/expressions.tex
source/lex.tex
source/overloading.tex
source/preprocessor.tex
source/statements.tex
source/templates.tex

My impression is that keywords should be `\keyword{<string>}` usually, no surrounding command, except in `one of`  grammar definitions, where they should be wrapped in a `\terminal{...}`
Didn't do this on a couple occurences in preprocessor.tex (`if` and `else` are in `\terminal{}` args):
```
\begin{bnf}\obeyspaces
\nontermdef{else-group}\br
\terminal{\# else   } new-line \opt{group}
\end{bnf}
```
```
\begin{ncsimplebnf}\obeyspaces
\indextext{\idxcode{\#if}}%
\terminal{\# if     } constant-expression new-line \opt{group}\br
\indextext{\idxcode{\#elif}}%
\terminal{\# elif   } constant-expression new-line \opt{group}
\end{ncsimplebnf}
```
```
\begin{bnf}\obeyspaces
\nontermdef{if-group}\br
\terminal{\# if     } constant-expression new-line \opt{group}\br
\terminal{\# ifdef  } identifier …
```

Wrap keywords that were \terminal{} with \keyword{} instead

---

source/intro.tex
source/layout.tex

ISO House Style requires a special header on page 1; the two-ruled format follows the rice model (and is what I'm doing for the LFTS).
The published wording will say "INTERNATIONAL STANDARD" etc.

[intro, front] Special page header before Clause 1

---

source/declarations.tex

The rules for decl-specifiers do not allow `auto` to appear more than once in the declared type of a variable, so the plural "occurrences" in this paragraph is potentially misleading.
This wording originates from [N1984](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n1984.pdf). In the paper, "occurrence" is singular, but in [N2009](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n2009.pdf) it somehow gained an "s".

[dcl.type.auto.deduct] Change plural "occurrences" to singular

---

source/threads.tex

Paper P3323R1 cv-qualified types in atomic and atomic_ref was incompletely applied in commit cd4dbcf2aa6df895a25dbf8c0773dd0fa67ef45d.

[atomics.ref.float] Apply missing changes from P3323R1

---

.gitignore
source/Makefile
tools/gitconfig.sh

I tend to forget running `check-source.sh` before pushing. This might help.

Add check target and provide pre-commit hook for 'make check'

---

source/containers.tex

Use "for exposition only" for consistency with usage elsewhere in the spec, and for the clarity/grammatical correctness of this sentence.

[container.insert.return] Fix description of insert-return-type

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/containers.tex
source/exec.tex
source/expressions.tex
source/intro.tex
source/preprocessor.tex
source/templates.tex
source/threads.tex
tools/check-source.sh

Improve automated checks

---

source/declarations.tex
source/expressions.tex
source/intro.tex
source/lex.tex
source/overloading.tex
source/preprocessor.tex
source/templates.tex
source/uax31.tex
source/xrefdelta.tex
source/xrefprev

[2025-06 CWG Motion 1] Core Language Working Group "ready" Issues for the June, 2025 meeting

---

source/preprocessor.tex

Fixes #7927.
Also fixes #7784.
Also fixes cplusplus/CWG#695

[2025-06 CWG Motion 2] Core Language Working Group "ready" Issues for the June, 2025 meeting

---

source/basic.tex
source/classes.tex
source/compatibility.tex
source/declarations.tex
source/expressions.tex
source/lex.tex
source/lib-intro.tex
source/macros.tex
source/meta.tex
source/modules.tex
source/overloading.tex
source/preprocessor.tex
source/support.tex
source/tables.tex
source/templates.tex
source/utilities.tex
tools/check-source.sh

Feel free to cherry-pick into #8004 once @Eisenwave is done with the library part.

P2996R13 Reflection for C++26

---

source/basic.tex
source/declarations.tex
source/expressions.tex
source/meta.tex
source/templates.tex

Closes https://github.com/cplusplus/draft/issues/7931.
Also closes https://github.com/cplusplus/papers/issues/2074.

P3394R4 Annotations for Reflection

---

source/expressions.tex
source/meta.tex

Closes #7932.
Also closes https://github.com/cplusplus/papers/issues/1945.

P3293R3 Splicing a base class subobject

---

source/declarations.tex
source/preprocessor.tex

Fixes #7936
Fixes cplusplus/papers#2174

P3533R2 constexpr virtual inheritance

---

source/support.tex
source/utilities.tex

Fixes #7939
Fixes cplusplus/papers#1661
Note -- fixed a overfull hbox issue by forcing a break for the constraints at around 5469
is_reference_v<T>  ||
(is_move_constructible_v<T> && is_swappable_v<T>)
is true.

P2988R12 std::optional<T&>

---

source/memory.tex
source/support.tex
source/threads.tex

Fixes #7941
Fixes cplusplus/papers#1713
Did not apply `constexpr` to deleted functions. The application in the paper was inconsistent, and I deemed the active uses as errors.
Made minor whitespace and line-breaking adjustments to avoid line-wrapping and overfull hboxes.
Fixed odd use of return type on the same line as the template head for an `allocate_shared` overload, where it belonged on the same line as the function name, before applying the `constexpr` keyword.

P3037R6 constexpr std::shared_ptr and friends

---

source/exec.tex

Fixes #7942
Fixes cplusplus/papers#1938

P3284R4 write_env and unstoppable Sender Adaptors

---

source/numerics.tex
source/support.tex

Fixes https://github.com/cplusplus/draft/issues/7947.

LWG Motion 10

---

source/numerics.tex

Fixes #7947
Fixes cplusplus/papers#1531
Fixes #7948
Fixes cplusplus/papers#2134
Fixes: #7949
Fixes: cplusplus/papers#1383
Fixes: #7950
Fixes: cplusplus/papers#2321

2025-06 LWG Motions 13  std::simd

---

source/containers.tex

Fixes #7951
Fixes cplusplus/papers#2040

P3383R3 mdspan.at()

---

source/support.tex

Fixes #7952
Fixes cplusplus/papers#1649

P2927R3 Inspecting exception_ptr

---

source/exec.tex

[2025-06 LWG 19] P3481R5 std::execution::bulk() issues

---

source/exec.tex

Fixes #7957
Fixes cplusplus/papers#2098

P3433R1 Allocator Support for Operation States

---

source/exec.tex

* [exec.util.cmplsig] Subclause (now without siblings) promoted to \rSec1 (replacing [exec.util]) and renamed to [exec.cmplsig] "Completion signatures".
* [exec.snd.expos]p24 Added missing \expos comments.
* FIXED: [exec.snd.expos]p39 Unable to find paragraph to replace. Referenced paragraph starts: "Let Sndr be a (possibly const-qualified) specialization basic-sender" Inserted changes as new text after [exec.snd.expos]p41 instead.
* FIXED: [exec.write.env] Unable to apply changes - section does not exist. Referenced paragraph starts: "write_env is a sender adaptor that accepts a sender and a queryable object"
Also fixes LWG4203.
Fixes #7961.

[2025-06-lwg-24] P3557R3 High-Quality Sender Diagnostics with Constexpr Exceptions

---

source/ranges.tex
source/support.tex

Fixed "if T models is-integer-like" which is a category error because that's a variable template not a concept.
Fixes #7966 7966

P3060R3 Add std::views::indices(n)

---

source/containers.tex
source/meta.tex
source/support.tex

Fixes #7969
Fixes cplusplus/papers#1458
Allowed paragraphs to number themselves correctly.
For consistency, did not use code font for constexpr in the phrase "constexpr function".

P2781R9 std::constant_wrapper

---

source/diagnostics.tex
source/iterators.tex
source/memory.tex
source/ranges.tex
source/support.tex

P3697R1 Minor additions to C++26 standard library hardening

---

source/meta.tex
source/support.tex
source/utilities.tex

P1317R2 Remove return type deduction in std::apply

---

source/algorithms.tex

When reviewing [P3179R9.html](https://wiki.edg.com/pub/Wg21sofia2025/StrawPolls/P3179R9.html), it was discovered that a note mentions a hallucinated `copy_assignable` concept.
https://lists.isocpp.org/lib/2025/07/32289.php reflector discussion here suggested to use `copyable`. This makes sense: `copy_constructible` and the hallucinated `copy_assignable` combined should be `copyable`.

[alg.partitions] Replace hallucinated "copy_assignable" concept with "copyable"

---

source/lex.tex

The term "instantiation unit" was removed by the application of P2996 for reflection, #7930.  This PR removes the last remaining reference from a note.

[lex.separate] No more instantiation units

---

source/lex.tex

Suggested by editorial review committee.

[lex.pptoken] Reoder list items to avoid "or" and "and" at same level

---

source/numerics.tex

Resolves the following markup issue:

[simd.mask.overview] Fix markup; add two missing closing @

---

source/xrefdelta.tex

The contents were moved to [intro.defs] but not [intro.refs] by #4288. But the PR mistakenly added the corresponding entry in xrefdelta.tex.
Fixes #8110.

Fix the entry for [re.def] in xrefdelta.tex

---

source/numerics.tex

One part of #7214.
As @mhoemmen explains:
> ## Fix return type of nested_accessor member function
> 
> The `nested_accessor` member function of `conjugated_accessor` (which is defined inline in the class' synopsis) currently returns `const Accessor&`. This is incorrect, because there is no `Accessor` type in scope.
> 
> The intent is for the function to return `const NestedAccessor&`. As main author of this proposal, this is the intent. At some point in revisions, the template parameter was renamed from `Accessor` to `NestedAccessor`. It's likely that we missed changing the return type of `nested_accessor`.
@jwakely does this need an LWG issue or can we "just fix this"?

[linalg.conj.conjugatedaccessor] Fix incorrect return type of `nested_accessor`

---

source/basic.tex

Given that the last option is "no linkage", the list is exhaustive and should not open readers to questioning what other options might be available if a name merely "can have" one of four categories of linkage that otherwise make no claim to be an exhaustive list.

[basic.link] All names have linkage

---

source/exec.tex

Cleans up multiple issues in p16:
* The name "alloc" was confusingly used both for an exposition-only member and for a locally defined variable. The latter is renamed to "alc".
* Locally defined variables are just typeset as normal code, not as placeholders.
* Some commas inserted to separate coordinate subclauses.
* Replaced "(if any)" with leading "Oherwise", which seems better in order to avoid seemingly providing two conflicting definitions of `alc`.
**Open question:** What is "`Allocator`"?

[task.promise] Clarifications and disambiguations

---

source/algorithms.tex

`iter_diffrence_t<I>` must be used instead of `iter_diffrence_t<T>` according to https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2025/p3179r9.html#modify_special_mem_concepts.

[specialized.algorithms] Fix a typo: T -> I

---

source/lex.tex

Change identifiers to names, so that we use a term with the specified linkage.
Since P2996 it is variables rather than objects that have names, so fix that up to in this informative note --- not normative text, so still editorial.

[lex.phases] Identifiers do not have linkage, names do

---

source/meta.tex

Bring the return type of type_of in line with the synopsis and with the intention of the function and with the wording in P2996R13 from where this wording originates.

[meta.reflection.queries]/1 Use info return type

---

source/containers.tex

The synopsis specifies noexcept for this constructor and the effects don't invoke behavior that could throw, so the missing noexcept looks like an oversight. However, the originating paper P0447R28 is also missing noexcept here.

[hive.cons]/15 Add noexcept to move constructor

---

source/expressions.tex

This is a back-reference, because [expr.splice] refers to here already.

[expr.const]/note-8 Add splice-specifier to list

---

source/basic.tex

The example in [basic.scope.class] is missing a `typename` for a dependent type.

Add missing 'typename' to [basic.scope.class] Example 1

---

source/utilities.tex

Constructor and assignment should be plural because there are multiple ones. 
Destructor should be singular because there is only one.

[func.wrap.move.class, func.wrap.copy.class] Fix singular and plural

---

source/containers.tex

The parameter list of one of the constructors has an redundant `)` at the end.

[map.overview] Fix typo of constructor of map

---

source/meta.tex

Fixes #8239.
This fixes a wording bug in P2996R13; `is_enumeration_type` is a hallucination.

[meta.reflection.define.aggregate] Replace "is_enumeration_type" with "is_enum_type"

---

source/containers.tex

The pack `Extents` must be a pack of `size_t` integers.

Fix typo in submdspan_extents.

---

source/numerics.tex

The _Returns_ says "A basic_mask object initialized with the results of applying op to `lhs` and `rhs` as a binary element-wise operation)", but there is no `lhs` and `rhs`.

[simd.mask.comparison] Add missing param name

---

source/numerics.tex

[simd.alg, simd.reductions] Use libconcept for `totally_ordered`

---

source/iostreams.tex

We say "Effects: Equivalent to: `rdbuf()->str(t);`" but there is no `t`.

[stringstream.members] Add missing param

---

source/meta.tex

Fixes NB US 96-206 (C++26 CD).
Fixes cplusplus/nbballot#775

[meta.reflection.queries] Fix typo in comment in example

---

source/meta.tex

Fixes NB US 103-164 (C++23 CD).
Fixes cplusplus/nbballot#744

[meta.reflection.member.queries] Remove superfluous 'of'

---

source/basic.tex

Fixes NB US 18-035 (C++26 CD).
Fixes cplusplus/nbballot#610

[basic.life] Remove spurious commas

---

source/meta.tex

Fixes NB US 123-187 (C++26 CD).
Fixes cplusplus/nbballot#756

[meta.reflection.define.aggregate] Fix declarations of name-type constructors

---

source/exec.tex

Fixes NB US 200-323 (C++26 CD).
Fixes cplusplus/nbballot#898

[execution.syn] Add comments to cross-references in synopsis

---

source/exec.tex

Fixes NB US 212-352 (C++26 CD).
Fixes cplusplus/nbballot#927

[exec.snd.expos] Move specification of default template argument for 'Data'

---

source/exec.tex

Fixes NB US 218-349 (C++26 CD).
Fixes cplusplus/nbballot#924

[exec.write.env] De-bulletize specification of check-types

---

source/exec.tex

Fixes NB US 262-394 (C++26 CD).
Fixes cplusplus/nbballot#969

[exec.par.scheduler] Use 'has the value' for an expression

---

source/threads.tex

A misapplication of paper P3323R1.
Fixes NB US 194-314 (C++26 CD).
Fixes cplusplus/nbballot#889

[atomics.syn,atomics.ref.pointer] Remove partial specialization atomic_ref<T*>

---

source/threads.tex

Fixes NB US 196-315 (C++26 CD).
Fixes cplusplus/nbballot#890

[atomics.types.int,atomics.types.float] Excise uses of undeclared 'T'

---

source/threads.tex

Fixes NB US 192-312 (C++26 CD).
Fixes cplusplus/nbballot#887

[atomics.ref.generic] Avoid use of undeclared 'T'

---

source/exec.tex

Fixes NB US 259-380 (C++26 CD).
Fixes cplusplus/nbballot#955

[task.promise] Remove trailing semicolons in comments in examples

---

source/meta.tex

A misapplication of P2996R13.
Fixes NB US 115-176 (C++26 CD).
Fixes cplusplus/nbballot#994

[meta.reflection.substitute] Add 'in order'

---

source/exec.tex

Drop unnecessary 'std::' prefix
Fixes NB FR-033-335 (C++26 CD).
Fixes cplusplus/nbballot#910

[exec.snd] Harmonize subclause titles

---

source/numerics.tex

The subclause applies to both vecs and masks.
Fixes NB US 177-284 (C++26 CD).
Fixes cplusplus/nbballot#859

[simd.traits] Rename subclause heading to 'Type traits'

---

source/numerics.tex

The complex accessors are member functions.
Fixes NB US 179-293 (C++26 CD).
Fixes cplusplus/nbballot#868

[simd.complex.access] Move into [simd.class]

---

source/numerics.tex

Fixes NB US 186-300 (C++26 CD).
Fixes cplusplus/nbballot#875

[simd.mask.nonmembers] Add 'basic_mask' to subclause heading

---

source/exec.tex

Fixes NB US 248-378 (C++26 CD).
Fixes cplusplus/nbballot#953

[task.state] Fix formatting of subclause heading
